### ISSUE TITLE
EPIC: Use a separate database and search index in h QA

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1002]
_Description added by @lyzadanger 2020/03/11_

Typically, a staging or QA server allows for the testing of new changes before they are deployed to production. Isolation of data is an important part of this equation, as problematic changes on QA could corrupt data. When QA shares the same database as production, this introduces a real risk that production (user) data could be affected by activities on QA.

As I understand the history of this, the shared database situation came about because of a desire to see production-like data in place on the QA/staging site. This is likely achievable by some sort of automated sync-from-production script.

**Comment by seanh** [comment]
h QA and prod currently share the same DB and search index.

Bouncer QA and prod also both use the one h search index, so Bouncer QA should also be changed to use the new QA search index.

LMS QA and prod already use separate DBs (and LMS doesn't have a search index).

Our other apps (Via and Via 3) don't use any DB or search index.

We would want to have realistic data in the QA DB and search index somehow. Perhaps a one-way sync of data from prod to QA?

**Comment by robertknight** [comment]
This is now done. The new staging environment uses a separate DB.
