### ISSUE TITLE
Investigate why h.views.api.groups:groups is slow (conditional_http_tween & query)

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1004]
This is relatively low priority from a customer perspective since ~.01% of requests are >.5s during a 7 day period. 
There appear to be a couple problems here:
1. The h.tweens:conditional_http_tween appears to be causing a massive slowdown on certain groups api requests.
![image](https://user-images.githubusercontent.com/30059933/56982947-4ebea100-6b37-11e9-835b-94949f62b97f.png)
[detailed trace in New Relic](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions?tw%5Bend%5D=1556646058&tw%5Bstart%5D=1556041258#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e67726f7570733a67726f757073222c22225d&app_trace_id=6d10e691-6b50-11e9-93d3-0242ac11000f_27608_30380)

2. The group scope query is slow.
![image](https://user-images.githubusercontent.com/30059933/56983497-a0b3f680-6b38-11e9-87d2-90dfa7f284c5.png)
![image](https://user-images.githubusercontent.com/30059933/56983546-bde8c500-6b38-11e9-99ed-6bacac00526f.png)

[detailed trace in New Relic](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions?tw%5Bend%5D=1556646058&tw%5Bstart%5D=1556041258#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e67726f7570733a67726f757073222c22225d&app_trace_id=d8a6fc36-6840-11e9-93d3-0242ac11000f_0_3092)

In the average case the tween takes up 8% of the total time and the group scope query takes up about 15% of the total time.
![image](https://user-images.githubusercontent.com/30059933/56983235-f9cf5a80-6b37-11e9-9871-8cd6d47b1ed9.png)

**Comment by lyzadanger** [comment]
I'm a novice with New Relic, but I'm not seeing the same kind of data at this time. I'm looking at a 7-day snapshot, and here's the performance I'm seeing for the `GET /api/groups` endpoint:

![image](https://user-images.githubusercontent.com/439947/58639049-2657cd00-82c4-11e9-8c43-e07622c4d77d.png)

True, that endpoint accounts for 6% of our time, but recall that gets hit (twice, I think?) every single time the client loads. The overall average is 28.8ms for the whole request. Seems...not problematic to me? Perhaps at the time you pulled this data initially, there were other factors in play impacting the performance? Or am I looking at this wrong?

**Comment by hmstepanek** [comment]
Hi @lyzadanger, the view you have captured here is the overall performance in New Relic and you are correct, the overall performance for this endpoint looks fine but what this issue is about are occasional corner-case slow downs. These will appear as detailed transaction traces at the bottom of [this page](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions?tw%5Bend%5D=1559235718&tw%5Bstart%5D=1558630918#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e67726f7570733a67726f757073222c22225d). If you click on one of the detailed traces it will show you a breakdown just for that particular transaction.
![image](https://user-images.githubusercontent.com/30059933/58649846-0e7f4980-82c2-11e9-8c41-beb68fa02869.png)

That being said, I just clicked on one of the most recent traces and it shows almost all of the time was spent in the tween so this does still appear to be a problem.

**Comment by hmstepanek** [comment]
See https://hypothes-is.slack.com/archives/CBN3DGW02/p1560354924051600 here on tween issue.
