### ISSUE TITLE
Change chrome extension icon to h logo.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1006]
### Problem you are trying to address with this feature

Our chrome extension icon is flawed in two key ways.  

1. It's hard to see.  Especially when using night mode or dark themed browser chromes.
2. No one knows what it's for or who it's from, unless they use us regularly.

Originally we were on this kick to avoid branding and be utilitarian, which is still a core part of our DNA.  But this is an icon for our chrome extension, not the main app-- so it's definitely already clear that it's Hypothesis.

### Your solution

Replace with our std monochrome h. logo.

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label.

**Comment by klemay** [comment]
Ok so it looks like we'll need to change out the icon here:

https://github.com/hypothesis/browser-extension/tree/master/src/chrome/images

And we need to replace the following files: 

- browser-icon-active.png
- browser-icon-inactive.png
- browser-icon-active@2x.png
- browser-icon-inactive@2x.png

...which leads me to believe the icon needs to be pre-sized to fit into the sidebar. Look at these files, it appears the desired dimensions are: 
- 1x: 19 x 19px
- 2x: 38 x 38px

Jared's gist containing the new icon, which works for light and dark mode users, is here: https://gist.github.com/jaredpdesigns/626aa057417f7c82bfe352557cc9c93a

One thing I'm not clear on - where we landed for inactive vs active states. I know we said the full-opacity version (the one in Jared's gist) would serve for the active state, but what do we want to do for inactive? Jared suggested a semi-transparent option for the inactive state, which I think makes sense. 

Logos are here: 
[hypothesis-brower-icons.zip](https://github.com/hypothesis/product-backlog/files/3272975/hypothesis-brower-icons.zip)

**Comment by klemay** [comment]
Looks like I never closed this one!
