### ISSUE TITLE
User-reported conflict between Via + blogdosakamoto.blogosfera.uol.com.br

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1007]
A user [reported on Twitter](https://twitter.com/_limamedeiros/status/1123940213305245696) that visiting pages on a certain website using Via causes highlights to duplicate.

### Steps to reproduce
1. Using any browser, go to https://via.hypothes.is/https://blogdosakamoto.blogosfera.uol.com.br/2019/05/02/no-dia-do-trabalhador-bolsonaro-afaga-empresarios-e-ignora-desempregados/
2. Select text and create a highlight
3. See your highlight reproduced multiple times in the client sidebar. (Note: you might need to create a second highlight to trigger this):
![screenshot-via hypothes is-2019 05 02-13-30-47](https://user-images.githubusercontent.com/12087705/57094517-ba8f3e00-6cde-11e9-96d6-3bff5e0e540e.png)

### Notes
Strangely, this doesn't happen with annotations— only for highlights. It also seems to be Via-only (doesn't happen with Chrome extension or Bookmarklet).

**Comment by robertknight** [comment]
I'm not able to reproduce.
