### ISSUE TITLE
Implement account menu using new dropdown menu

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#1011]
**Depends on https://github.com/hypothesis/product-backlog/issues/1010**

In order to make dropdown menus feel consistent across the app, we are going to change the account menus to match the style of the new groups menu. This will also enable fixing accessibility issues with the new menu.

**Done when**

The account dropdown menu has been re-implemented using the new menu component introduced in https://github.com/hypothesis/product-backlog/issues/1010

Modulo further design tweaks, it should look like this:

<img width="478" alt="screenshot_2019-04-26_15 43 42" src="https://user-images.githubusercontent.com/2458/57142901-8cc8f880-6db5-11e9-8b3a-65d987a82d5f.png">

**Comment by lyzadanger** [comment]
This work is nearly done and deploy is imminent; I want to document the before and after states of this menu and its allies so we can have a clear picture of what has changed and why!

### 1. Sidebar

#### Before

The only way to expand the menu is through the tiny caret at the top right; it's easy to accidentally click on "Log in" instead. The "Help" link is the only item in the menu, and it can be a little hard to find. The rollover/link target area of "Help" is small and easy to miss.

![before-logged-out-help-menu](https://user-images.githubusercontent.com/439947/59277293-f1d20280-8c2d-11e9-92ec-2fa51ff884ee.gif)

Once logged in, "Help" is now the only non-account-related task in the menu, so it feels a little out of place. The rollover/target areas don't extend the full width of the menu.

![before-user-menu-client](https://user-images.githubusercontent.com/439947/59277530-5db46b00-8c2e-11e9-86bd-c005ff3b7b3d.gif)

#### After

The help icon stays put and you don't have to search for it in the tiny menu. The user menu is not present until after login:

![after-logged-out](https://user-images.githubusercontent.com/439947/59277873-f0eda080-8c2e-11e9-93b2-1bd9538df55c.gif)

Menu item rollovers are clearer and tap targets extend to the full size of the menu item; logout task is clearly separated from other items:

![aftere-user-menu](https://user-images.githubusercontent.com/439947/59278011-35793c00-8c2f-11e9-96e2-284f37d15809.gif)

### 2. Single-annotation Variant

#### Before

Before these changes, the user-menu interaction in the single-annotation view was inconsistent with the sidebar variant. "Sign up" option was missing, as well. As with the client's "before" situation, when logged out, it's fairly hard to find the "help" option and the target is narrow:

![before-logged-out-help-menu](https://user-images.githubusercontent.com/439947/59278108-68233480-8c2f-11e9-8de6-cffca53338b1.gif)

When logged in, there was a slightly startling rollover effect and menu items were in a different order, and worded differently, than in the sidebar variant:

![before-logged-in-user-menu](https://user-images.githubusercontent.com/439947/59278168-838e3f80-8c2f-11e9-9723-563dfcfca250.gif)

#### After

The help icon is always present. "Sign Up" option available. User menu doesn't show up until a user is logged in. Menu items are worded and sorted the same as the sidebar variant:

![after-login-flow](https://user-images.githubusercontent.com/439947/59278299-bb958280-8c2f-11e9-88a7-59058a283a8e.gif)

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/client/pull/1154
