### ISSUE TITLE
When only TextQuoteSelector is used, anchoring should use suffix to differentiate when prefix and exact are the same

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#1022]
When the Hypothesis client creates two annotations, as shown here, http://jonudell.net/h/same-prefix-diff-suffix.html, both anchor, because the client uses the full complement of selectors.

But when Scibot creates the same two annotations, the anchors pile up on one occurrence of the `exact` like so:

```
<hypothesis-highlight class="annotator-hl">
   <hypothesis-highlight class="annotator-hl">WB-STRAIN</hypothesis-highlight>
</hypothesis-highlight>
```

Now, granted, Scibot would ideally post annotations using the full complement of selectors. It doesn't  operate in a DOM context, so would have a hard time figuring out RangeSelector. Scibot probably could and should at least figure out TextPositionSelector as well as TextQuoteSelector, which might be enough to differentiate. Still, one would expect that the anchoring system could handle annotations with TextQuoteSelectors that differ by `suffix` alone. Evidently we don't? 

/cc @tgbugs, see https://www.ncbi.nlm.nih.gov/pmc/articles/PMC6522220/

**Comment by judell** [comment]
Here's why this happens:

https://github.com/tilgovi/dom-anchor-text-quote/blob/master/src/index.js#L109

We only search for the suffix if the prefix isn't found. Which makes sense: always searching would be expensive. If we kept track of anchors where prefixes and exacts match, we could maybe search for the suffix in only those cases.

**Comment by robertknight** [comment]
Fixed by https://github.com/hypothesis/client/pull/2814. When there are multiple matches for a given `TextQuoteSelector` they are now ranked by a weighted score based on quote similarity, suffix similarity, prefix similarity and distance from expected text position.
