### ISSUE TITLE
Postgress backups "offsite"

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#1023]
This comes from infosec audit work. We should have a backup of our customer data somewhere "offline". We already have live database redundancy, this off-site backup would be more on the order of a daily snapshot for disaster recovery.

In order of durability, we could choose to store this backup:
0. Live replication within AWS (we already do this)
1. An S3 bucket different AWS region
2. An S3 bucket in a different AWS account and region
3. Stored in a different cloud location such as Azure or hosted backups
4. pulled down to a physical hard drive under our control which is not generally reachable from the public internet

My suggestion is to first run a postgress_dump tool to create the backup in an S3 bucket in a different region (option 1) and then ship it to a cloud provider off AWS (option 3). 

Option 4 gives us the most control of our customer data, and insulates it against certain kinds of malicious actions (like if some hacker got access to both AWS and the other backup service), but we aren't accustomed to managing any physical infrastructure and it's probably overkill at this time. Option 4 also exposes us to other infosec concerns around handling of customer data properly. And, once we have an s3 backup, we could choose to start pulling it to offline storage at any time in the future.

**Comment by dmfine** [comment]
Conversation with Sean, decided to just implement option 1 for now. Using old pw based auth.

**Comment by lyzadanger** [comment]
@dmfine Wanna close this one? I believe it is completed.

**Comment by dmfine** [comment]
They are being copied to an s3 bucket in us-east-1
