### ISSUE TITLE
Spike to investigate what is required to upgrade to Postgres 11

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#1026]
Belongs to epic: [Upgrade Postgres 9.4 -> 11](https://github.com/hypothesis/product-backlog/issues/1024)

Support for our current version of Postgres ends in December, and we should begin the work to upgrade it now a few months in advance. This spike is to identify what's going to be required to upgrade Postgres, and make a list of tasks. Things to consider:

* Run all of the h and lms tests (including functional tests for h) with the new version of Postgres
* Also do some basic manual testing of h and lms running against the new version of Postgres in a dev environment
* Read the Postgres changelog. Any breaking changes that might affect us?
* What about sqlalchemy? Do h and lms's current versions of sqlalchemy support the new version of postgres? Or will we need to upgrade sqlalchemy as well?
* What will be the process for deploying the Postgres upgrade to QA and production?

[]- Switch to pg11 in dev environment
[]- Run tests on sample data. Proactively look for errors
[]- Figure out what it would take to fix anything that's broken
[]- Create gDoc with upgrade steps and compatibility findings

**Comment by dmfine** [comment]
[] - Switch to pg11 in dev environment
[] - Run tests on sample data. Proactively look for errors
[] - Figure out what it would take to fix anything that's broken
[] - Create gDoc with upgrade steps and compatibility findings

**Comment by lyzadanger** [comment]
Is this complete?

**Comment by dmfine** [comment]
Documented the resulting plan here https://docs.google.com/document/d/1dbwSiONiuLQ8Bq31fEpAFtflBpalsIzp0_hF-iWlY1o/edit?usp=sharing
