### ISSUE TITLE
Convert and Improve the Client's Tutorial Feature

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1031]
### Problem you are trying to address with this feature

Improve our tutorial card that shows when a user first begins using the service.

We added the tutorial because we got feedback that people didn’t know "how to use thing”, and it didn't matter whether they were chrome extension users or they'd stumbled on the interface as embedded elsewhere.  This need still exists.  However, we’re still using the same rushed, “implemented in 15 minutes” tutorial that we cooked up nearly 5 years ago.  It’s terrible.

- People don’t know they can dismiss this tutorial.  We see support requests, tweets, and screen shots of our interface where people have never closed that panel.  Create a larger button, perhaps at the bottom that says “Close” or “Dismiss”
- There are no links to our kb, or to other tutorials that give deeper information about how to use our app.
- Consider an embedded video of 30-60 seconds that gives a very basic intro on how to use Hypothesis
- Prune and tighten up the list of options.
- Perhaps make a quick survey.  Where are other similar tutorials implemented, and how do others do this?

### Current Appearance

![image](https://user-images.githubusercontent.com/439947/60120994-1e1e7080-9750-11e9-8cdd-ecb5b5d4b03b.png)

**Comment by dwhly** [comment]
It was suggested that we consider merging the tutorial with the "help" function.  This seems like a good idea.  If people agree, this issue should serve as the combined ticket.

![Screen Shot 2019-07-08 at 6 25 25 PM](https://user-images.githubusercontent.com/1413074/60852723-c94a1380-a1ad-11e9-8947-000a4f6f4089.png)

Several improvements to help, or help-as-merged-with-tutorial include:
- A copy-to-clipboard function for the information panel.
- Line clamping for the URL (https://css-tricks.com/line-clampin/) (if it's really really long).  Though we could use a strategy of hiding the help info behind a dropdown or menu until it's needed instead.

**Comment by jaredpdesigns** [comment]
Here’s my first pass at a revised help menu:

- In lieu of verbose instructions on how to commonly use Hypothesis, a _Getting Started_ video can supplement that.
- Carried forward the same `close` button design from the revised share menu to make it clearer users can dismiss the help card.
- Two secondary actions appear at the bottom of the card “Common help topics” opens a new tab/window and takes users directly to the [Help docs](https://web.hypothes.is/help/) and “Create a support ticket” opens a new tab/window taking users to the [help request page](https://web.hypothes.is/get-help/).
- If a user chooses the support ticket option, the content of the card is replaced with what’s in the 2nd image (the current help card) with an option either to return to the overview or copy all the pertinent details to their clipboard for inclusion in their support ticket. 
- We may want to consider revising the help request page to include a field for copied content to make it clearer there is a place for it.
- Closing the card using the `close` button would reset the card to the overview state if a user chose to open it again.
- Ideally the help card could be “open” when a new user first uses the application to try and capture user-onboarding hiccups.

![help-menu-1-overview](https://user-images.githubusercontent.com/6108048/61328737-64974600-a7b7-11e9-861c-6c2920dbb501.jpg)

![help-menu-2-support-ticket](https://user-images.githubusercontent.com/6108048/61328738-652fdc80-a7b7-11e9-884a-6ec7e540e766.jpg)

**Comment by klemay** [comment]
This looks good to me! One thing to note:

> We may want to consider revising the help request page to include a field for copied content to make it clearer there is a place for it.

I'm not actually sure if that's possible. I've [created an issue](https://github.com/hypothesis/support/issues/63) to look into it. NinjaForms does have a prefill/auto-populate feature but I'm unsure how we'd dynamically pass the info from the sidebar to the form. 

If it's not possible to do this, perhaps I can alter the form in a way that reminds people to copy & paste that info manually. Not ideal, but still helpful.

**Comment by jaredpdesigns** [comment]
@klemay thanks for the feedback. I think it would be OK if we didn’t auto-fill this via some sort of URL query—but having an optional field in the form could be nice to expedite support requests.

**Comment by klemay** [comment]
In yesterday's design meeting, Dan asked me to have a think about what would be included if we decided to keep a task-list in the "Getting Started" view. I think I'd pare down our current options and include:

1. To create an annotation, select text and click the "Annotate" button.
2. To create a highlight ([visible only to you](https://web.hypothes.is/help/why-are-highlights-private-by-default/)), select text and click the "Highlight" button. 
3. To annotate in a private group, select the group from the groups dropdown. (Don't see your group? Ask the group creator to send a [join link](https://web.hypothes.is/help/how-to-join-a-private-group/)). 
4. To reply to an annotation, click the "Reply" button. 

Notes:

- I'm not married to any of this language (especially the wording for the 3rd item - anyone should feel free to propose changes).
- We should make it clear that highlights are visible only to the user who creates them - this is a constant source of confusion
- We constantly get tickets about people not knowing how to join or annotate in groups, but the group creation process seems to cause less trouble. I'd suggest swapping out "To create a private group..." with "To annotate in a private group..."

@dwhly thoughts on this?

**Comment by jaredpdesigns** [comment]
A new iteration on the Help card moving things around a bit. 

- Main overview area has re-arranged action buttons which both open new tabs when clicked.
- Users can access the “About this version” whenever the help card is active by following the link at the bottom of the card.
- 2nd iteration of the help card looks at the idea of a slideshow of common steps that map to the options outlined in the comment above by @klemay (thanks Katelyn). Each step has an embedded GIF of the common action as a cropped screenshot that loops and autoplays.
- If we wanted to go for something a little simpler we could use the “Getting started” slideshow element in a different location of the application as a separate card and just update the Help card with a cleaner design (last image). 

_Revised main overview with embedded video:_

![help-menu-1-overview](https://user-images.githubusercontent.com/6108048/61569654-0de27400-aa24-11e9-9109-eb2738684649.jpg)

_Revised “About this version”:_

![help-menu-2-about-this-version](https://user-images.githubusercontent.com/6108048/61569655-0de27400-aa24-11e9-959a-c87d130011b6.jpg)

_Alternate main overview with embedded GIFs that loop through common actions:_

![help-menu-1-overview-alt](https://user-images.githubusercontent.com/6108048/61569657-13d85500-aa24-11e9-8940-c02471d11545.jpg)

_GIF that would be embedded to show action of annotation:_

![annotate](https://user-images.githubusercontent.com/6108048/61569684-441ff380-aa24-11e9-9777-931710defc9d.gif)

_Alternative Help card with simplified options_
 
![help-menu-alt](https://user-images.githubusercontent.com/6108048/61570092-43885c80-aa26-11e9-9416-bc4c32f16368.jpg)

**Comment by klemay** [comment]
Since we're pursuing WCAG AA compliance, I should mention: [WCAG 2.0 Success Criterion 2.2.2](https://webaim.org/standards/wcag/checklist#sc2.2.2) requires that automatically moving, blinking, or scrolling content that lasts longer than 5 seconds can be paused, stopped, or hidden by the user.

And even though "5 seconds" is specified there, I recommend against following the letter but not the spirit of the rule.

That means if we're going to include gifs, there should be a way to hide them (without having to close the entire help panel, since users will still need access to that info). Or, we could consider showing static images for each of these items instead of gifs.

**Comment by klemay** [comment]
Soon it will be time to convert this component to Preact, so we should revisit this and agree on scope + the path forward. So far we've decided:

- Combine the tutorial and help cards into one component. It's shown by default for new users, can be dismissed with the [x Close], and can be revisited by clicking the ? in the toolbar. 
- There are 2 cards that make up this component: "Overview" and "About this version"
- The "Overview" will contain a revised task list - see [my comment upthread](https://github.com/hypothesis/product-backlog/issues/1031#issuecomment-513343796) for a proposed list. "About this version" will let users easily copy their environmental info. 

To move forward we need:

- [ ] A mockup of the Overview with a revised task list 
- [ ] Tweaking/approval of the task list (with mockup to reflect any changes)

...I'll coordinate with Design to get a new mockup!

**Comment by jaredpdesigns** [comment]
@klemay I think this is a summary of the changes we’d like to see to the mockup:

![help-menu-1](https://user-images.githubusercontent.com/6108048/66614857-4ea2e280-eb66-11e9-960c-43f0389c3e5e.jpg)

The first image is the “Getting started/Overview”  which presents the steps outlined in your [comment thread](https://github.com/hypothesis/product-backlog/issues/1031#issuecomment-513343796) (a side note, I kind of like the idea of spelling out what the iconography means with a label to reinforce understanding).

If a user clicks the “About this version” button at the bottom of this image the second image will become the contents of the panel.

![help-menu-2](https://user-images.githubusercontent.com/6108048/66614861-5498c380-eb66-11e9-8f5c-606694d0ed47.jpg)

A user has two options in this image: clicking the `left-arrow` to return to the overview panel or to `Copy version details`. 

Between both versions of the panel a user can click the `Help topics` or `New support ticket` buttons to open new tabs relevant to either action.

**Comment by klemay** [comment]
I also like the combo of iconography + label in the task list!
