### ISSUE TITLE
Add activation_date column to User table

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1033]
Part of https://github.com/hypothesis/product-backlog/issues/988; enables https://github.com/hypothesis/product-backlog/issues/1034. 

We need to store the date and time when a user activates their account. @lyzadanger suggested in https://github.com/hypothesis/product-backlog/issues/1027 that we should add an `activation_date` column to our `User` table so we can then surface that info on admin pages (and use it to investigate how long account activation takes)

**Comment by jon-betts** [comment]
There is now a column on this table.
