### ISSUE TITLE
Don't populate last_login_date until user logs in for the first time

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1035]
Part of https://github.com/hypothesis/product-backlog/issues/988, related to https://github.com/hypothesis/product-backlog/issues/1033 and https://github.com/hypothesis/product-backlog/issues/1034. 

Currently, `last_login_date` is populated when a user clicks the button to create an account, even though they've never actually logged in. So we can get accurate account data, we shouldn't populate this field until a user logs in for the first time. 

We discovered in https://github.com/hypothesis/product-backlog/issues/1027 that `last_login_date` has "NOT NULL" enforcement, so that will need to be changed.

**Comment by jon-betts** [comment]
This has been deployed now
