### ISSUE TITLE
Don't show flag icon unless user is logged in and has permission to flag annotations

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1037]
Currently the flag icon is visible (and clickable) on annotation cards even if someone isn't logged in:

<img width="464" alt="Screen Shot 2019-07-17 at 2 35 01 PM" src="https://user-images.githubusercontent.com/12087705/61401955-13af4c80-a8a0-11e9-8e55-df49bf250ef7.png">

If you try to flag an annotation while not logged in, you'll get an error message:
<img width="457" alt="Screen Shot 2019-07-17 at 2 39 35 PM" src="https://user-images.githubusercontent.com/12087705/61402274-c2538d00-a8a0-11e9-963e-f29df4e04adc.png">

 We don't show the flag icon when a logged-in user is viewing their own annotations:
<img width="472" alt="Screen Shot 2019-07-17 at 2 48 08 PM" src="https://user-images.githubusercontent.com/12087705/61402825-e9f72500-a8a1-11e9-807c-c25a87ad71b2.png">

...we might consider not showing the flag icon to users who aren't logged in and thus can't flag annotations.

**Comment by lyzadanger** [comment]
Note that the UI has changed since this issue was opened:

![image](https://user-images.githubusercontent.com/439947/102516547-f7977800-405c-11eb-8508-5be3efcdba77.png)

**Comment by esanzgar** [comment]
I wonder if an additional source of confusion could be that some people don't associate the flag icon to the 'report an annotation', but to a highlight action.

**Comment by klemay** [comment]
@esanzgar definitely - we know that our users accidentally flag annotations all the time because they don't know what the flag icon does. We have plans to [bring moderation to the LMS app](https://github.com/hypothesis/lms/issues/1388), which will bring improvements to moderation in the client overall.
