### ISSUE TITLE
Problem: How can Hypothesis know who is installing the LMS app so it can provide support and information?

### ISSUE THREAD

**Issue by xolotl** [hypothesis/product-backlog#1040]
# User Story
As a Hypothesis team member, I want to know who has installed the LMS app so I can make sure they get support and information to help make annotation a success at their institution. Installers need to supply some technical information in order for Hypothesis to provide them with the credentials needed to install the app in their LMS. In order to provide installers with appropriate support and information, I need to know more information about who they are and what their goals are.

# Background
Hypothesis makes it possible for anyone to install the LMS app, but to install in their LMS, they need credentials which are currently supplied via [a form](https://lms.hypothes.is/welcome). See the process in #306 that resulted in the form.

Currently installers supply their email and the domain of their LMS, and if their LMS is Canvas, a Canvas developer ID and key. Installers are then returned a Hypothesis LMS app key and secret to use during installation in their LMS.

# Goals
1. Installers should not feel that the process is burdensome, with easy-to-use, accessible, professional UX.
1. The process and information collected/supplied should meet Hypothesis privacy and security practices, including Hypothesis' compliance with regulations like GDPR.
1. It should be easy to change the information collected/supplied and design of the UX to meet changing needs.
1. Information collected should be readily available to the tools Hypothesis uses to communicate with, provide support to, and track users and institutions that have installed the LMS app.

# Possible Proposals

## A. Continue to manage the process as is
1. Adjust the existing form to include all necessary information and to supply that information back out to external communication and support tools.
1. Update the existing form over time as information/communication needs and external communication and support tools change.

## B. Supply credentials via API
1. Use external communication/support tools to collect necessary information from installers.
1. From such an external service, call a Hypothesis API to pass required information and generate credentials, which would then be communicated to the installer by the external service.

## Interim: Collect information externally and use existing form for credentials
Not optimal, but an early step could be to build and external form to collect information and on successful completion, send installers to the existing form to generate credentials.

**Comment by klemay** [comment]
After a call today with @xolotl, @ajpeddakotla, and Butch, we agreed on the following path forward:

- Adopt the interim solution outlined by Nate above
- From the form that Nate builds, we'll learn: (a) what info we need to collect; and (b) what format it will be in (i.e., text entry? drop-down fields? radio buttons?); and (c) what format will be most useful for the data (spreadsheet? direct entry into CRM?)

Also note that we are in the process of choosing a CRM. If this user info will feed directly into the CRM from the signup process, we'll need to know the following:
- Which CRM we're using
- How that CRM receives & updates information

At _that_ point, it will make sense to decide on a long-term implementation and schedule the work needed from the engineers.

**Comment by klemay** [comment]
The interim form is here: https://web.hypothes.is/education/lms/install/

As of 8 Aug 2019, the info we're collecting is:

FIrst Name 
Last Name 
Email 
Role 
Organization 
Primary LMS 
What are you looking to do with annotation?

**Comment by xolotl** [comment]
Note that the form as of today, 8 Aug 2019, also requires people to acknowledge some usage terms before they can submit.

We've already changed the form multiple times since it went live, so flexibility and speed to modify will likely continue to be key requirements.

The form is also embedded in a H. webpage, which enables us to surround it with other content and functionality.

**Comment by xolotl** [comment]
I continue to think something like B. Supply credentials via API above will be the shortest path to the best solution as then communication with the CRM is also offloaded from H. to the form.

**Comment by robertknight** [comment]
> Hypothesis makes it possible for anyone to install the LMS app, but to install in their LMS, they need credentials which are currently supplied via [a form](https://lms.hypothes.is/welcome).

This URL now directs to the "interim form" at https://web.hypothes.is/education/. As the saying goes, there is nothing so permanent as a temporary solution.
