### ISSUE TITLE
Move sentry helpers into a separate python package

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1041]
Currently we have duplicated code in h and lms repos for configuring sentry logging/filtering. 
Move this code into a separate repository that can be installed as an external python package in h and lms.

 - [x] Apply feedback from PR
 - [x] Get a suitable login for PyPI 
 - [ ] <del>... and put it in Passpack</del> https://github.com/hypothesis/playbook/issues/235
 - [x] Get the package setup for publishing (Author metadata etc) (ask in #lounge about this)
 - [x] Push a manual build to PyPI
 - [x] Alter 'h' to use the published module locally
 - [x] Move the code to a separate repo

Future things:

 - [x] Get some CI working for the new repo (separate ticket?)

**Comment by jon-betts** [comment]
Pull request for this in: https://github.com/hypothesis/h/pull/5742

**Comment by seanh** [comment]
Checklist:

- [ ] Foo
- [ ] Bar

**Comment by jon-betts** [comment]
An initial version of the module is available at: https://pypi.org/project/h-pyramid-sentry/

**Comment by jon-betts** [comment]
The code has been moved out into a separate repo at: https://github.com/hypothesis/h-pyramid-sentry

**Comment by seanh** [comment]
Extracted the PyPI part into a separate issue: https://github.com/hypothesis/playbook/issues/235

**Comment by seanh** [comment]
Achieved!
