### ISSUE TITLE
Improve support of using docker in dev

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1043]
Currently we have `make docker` and `make run-docker` commands in our repo make files. These in theory build and run the docker containers for each of the repos so that you can use docker in dev, however, in practice these do not work. Instead of building from the local code they build from git head which is not optimal when developing a new feature as you generally test your changes before you commit them. They do not enable rebuilds of the code without rebuilding the container which takes extra time. In some cases these commands are also missing environment/config settings without which the service does not actually run in dev.

Our current Python setup for dev requires a lot of commands in order to install tools such as pyenv, tox, docker and configure these tools correctly (compile flags etc). The more steps you have in a setup the more fragile it becomes as the more chances you have to do something wrong. Once these tools are installed/configured correctly then there are several more commands needed to run dev including; spinning up some services in docker, setting environment variables, spinning up the main service locally, and populating some of these services with data such as the databases. All of these steps lead to a fragile environment setup and the more tools we have that build on that environment (pyenv, tox, docker, environment variables, python package installs) the more difficult it becomes to identify what went wrong in the setup and ultimately debug and fix the issue. There are several layers of indirection in our current setup; was it an incorrect python version (pyenv), was it a caching problem (tox) was it an incorrect configuration setting (environment variable), was it a bad dependency install (tox.ini or requirements.txt), was it a population problem (database), was it a configuration difference between dev and prod (conf/*.ini file), is this a case where I have to use docker because dev doesn't run that service (nginx). With so many different ways to go wrong and not everyone on the team being a Python, pyenv, tox, docker expert or even fully understanding what services are required to run a particular service, this often leads to developers getting stuck and being blocked until the expert is online to help them. It also leads to developers not being able to gain understanding and not wanting to gain understanding of our backend because it is so complicated and fragile and instead treating the environment like a black box. 

IMO the best dev environments are environments where the user has a deep understanding of how it works, enough so that they are able to debug it, configure it, and expand upon it independently. It is both isolated, quick, simple, flexible, stable, and easy to understand. IMO our current dev environment does not meet these needs. I think using docker for every service in dev on the other hand, does meet these criteria very well.

Docker is isolated; once you have installed docker, you don't have to install anything else. It is stable; since it's an isolated environment it doesn't change depending on the os/local environment. It requires less commands to run and therefore is less fragile: docker-compose up and maybe a one time data-init is really all the user needs to run to have their dev environment up and running. It encourages sameness between production and dev (because we use docker in prod we can pretty much re-use that same dockerfile in dev with some tweaks that enable rebuilding code without rebuilding the docker container thus guaranteeing that prod and dev will behave the same). Since docker is isolated it is also secure; if you were testing a new version of a package that had for example malicious content it would not gain access to your local system environment. Docker is also nice because it is simple to spin up or spin down all of the services with one command (`docker ps -qa | xargs docker stop`) and they hold their state through all of it so it doesn't require reconfiguration/re-running of a series of commands. Since we deploy using docker this also means developers will have a better understanding of how to debug things and how things run on production if they ever need to.

The disadvantage of docker is that it can be a bit taxing on resources potentially taking over the CPU.

**Comment by seanh** [comment]
Hi Hannah,

I think there's a misunderstanding here. `make run-docker` isn't meant for using Docker to do development, and we don't support using Docker in dev (other than to run the services). `make run-docker` is a rarely used command for testing the production Docker image locally:

```
$ make help
...
make run-docker        Run the app's Docker image locally. 
                       This command exists for conveniently testing 
                       the Docker image locally in production mode. 
...
```

Please use `make dev` for development -- I don't want to have multiple competing ways of doing development, as that would undermine ongoing work on our development environment that's needed to meet upcoming requirements.

I'm going to close this issue for now, but let's discuss the other problems you raised in your text, and the roadmap for the Hypothesis development environment, tomorrow.
