### ISSUE TITLE
Create a staging environment for H

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#1049]
We ought to have an environment like QA but not in the build pipeline.

What we're trying to solve:
Sometimes you want to be able to test something in a real AWS environment. QA is not a good place for that because it can block production releases or result in bad code being deployed

Goals:
1. An AWS environment where a PR build can be deployed and tested for a longer period of time without touching the production pipeline

2. It can be pointed at the same backend db as QA (creating another DB is almost certainly not necessary)

Implementation:
A new Elastic-Beanstalk configuration. Add this new Staging environment to jenkins build pipeline as a destination to deploy PR builds.
Ideally this can be spun down when not in use to save costs.

**Comment by dwhly** [comment]
For a long time, I've wanted to bring back a capability that we used to have, which was the ability to quickly deploy branches in a way that others could interact with them-- mostly in the team.  It was phenomenally useful, obviously for non-devs, but also there was a simplicity that even the developers appreciated.  I keep forgetting the name of the open source project we used for this....

Perhaps this could provide similar functionality?

**Comment by dmfine** [comment]
I agree this should be a key design consideration

**Comment by judell** [comment]
http://dokku.viewdocs.io/dokku/

**Comment by seanh** [comment]
Long-lived QA servers are antithetical to our development processes. We've chosen to use feature flags instead to provide the same QA needs.
