### ISSUE TITLE
Do not page on call staff during failed prod deploy that is rolledback by AWS

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1050]
# Problem:
Currently the on call staff are paged 25 minutes before developers are alerted that a production deploy has failed and been rolled back to a previous working version. When a production deploy fails, AWS health checks fail and AWS automatically rollsback to the previous working deploy. This means the on call staff do not need to be notified as no human intervention is required.

# Desirable Solution:
If a deployment is in progress for a particular repo, disable pager duty alerts about that repo until that repo has been deployed. If the deploy fails AWS will roll it back to a previous working version, if it passes AWS will roll out the new version and pager duty alerts will be re-enabled.

**Comment by robertknight** [comment]
See comment in https://github.com/hypothesis/product-backlog/issues/1051#issuecomment-2003457880.
