### ISSUE TITLE
Alert devs if health checks fail after deploy

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#1051]
# Problem:
Currently it takes 20 minutes (from the time of first health check failure to the notification of the failing/rolled back build in slack) for developers to be notified of failing health checks due to a production release.

# Ideal Solution:
Monitoring should be improved such that when a deploy is in progress and health checks start failing an alert is sent to the monitoring slack channel right away (hopefully with an `@developers` mention) indicating a production release has resulted in degraded behavior. This will improve visibility into the deployment process for developers and intentionally alert them to the problem rather than hoping they notice the failed build message among all the other build messages in the prod-general channel.

**Comment by robertknight** [comment]
We've changed our infrastructure a lot since this issue was filed. I can't remember exactly the details of the problem that prompted this issue, but we've not seen related issues in recent times that I can recall.
