### ISSUE TITLE
Pass LMS authentication to embedded client

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1071]
_Note: I refer to JSTOR a lot in this issue, but it's just a shorthand for "whichever scholarly repository we decided to work with first"._

## User story:
As a teacher, I would like for my students to annotate articles hosted in a repository like JSTOR, which has embedded Hypothesis over its articles, using their LMS-provisioned accounts.

## Background
Repositories like JSTOR require login (or authentication via IP) in order for students to read content hosted there. This means that teachers can't find an article on JSTOR and create a Hypothesis assignment using a JSTOR link (the use of Via in our LMS app means students won't be able to authenticate). The current workaround we've seen teachers use is to download the article as a PDF, upload that PDF to the LMS or Google Drive, and create a Hypothesis assignment with the PDF. This is problematic for a few reasons, including:

- It's cumbersome for teachers who have to go through gymnastics to upload PDFs.
- Increasingly there are features in the online interactive version of a text that aren't in the PDF.
- Repositories like JSTOR want to discourage (and in fact, sometimes expressly forbid) this behavior
- School librarians and lawyers don't like it either— it presents a potential copyright liability or violation of terms/contracts with publishers.
- Down the road, we'd like for students to be able to take their notes with them, outside of the LMS; this user story is consistent with that in that in that if they can obtain access to the text again they'll be able to resync their annotations.  At least with the authoritative copy there's a chance of that, whereas there is essentially zero chance they'll have permanent access to the downloaded PDF.

There are several moving pieces here, but a _very_ high-level account of how something like this would work:

1. JSTOR (or a similar repo) embeds Hypothesis over their documents
2. A teacher assigns an article hosted by JSTOR, and provides a link to the reading (i.e., https://www.jstor.org/[article_parameters])
3. Students are within the LMS-provisioned context when they click on the article link, and ... 
4. The link to the article either a) conveys the authenticated session (school, class, student, LMS) through the link (e.g. via custom query params), or b) the content is within a subframe where the H client embedded over the content can receive the authenticated context via frame to frame parameters.
5. Students follow the link and can view the content AND are also able to participate in LMS authenticated discussion and notetaking activities.

Ideally the way we approach solving this would be done in a way that is consistent with any existing technilcal approaches that have precedent in ed-tech and within existing LTI app launches.

**Comment by robertknight** [comment]
We implemented a specific JSTOR integration in the LMS app. Figuring out whether / how we can generalize this to support additional content sources requiring authentication is TBD for the future.
