### ISSUE TITLE
Add a "copy version details" function to the tutorial/help panel

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1075]
As part of the work for https://github.com/hypothesis/product-backlog/issues/1031, we initially proposed a "copy version details" button that would save the info in the tutorial/help panel to the clipboard so a user could easily paste into an email, Slack, or wherever they're going to get help. 

[As discussed in Slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1571406305018100?thread_ts=1570811559.001700&cid=C07NXBDNW), this is turning out to be more complicated than expected. It's still worth doing, but might need to be separated out from the Preact conversion work that's currently ongoing. 

In short, the copy-to-clipboard functionality we currently have for the client does not allow certain formatting, including line breaks (i.e. line breaks will be lost). This means that there is no straightforward way to make it possible to copy the version details in a readable way—they’ll all be crammed onto one line like so:

`fingerprint: N/A timestamp: Fri Oct 18 2019 09:37:14 GMT-0400 (Eastern Daylight Time) url: http://localhost:3000/ username: April Admin (admin) userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/77.0.3865.120 Safari/537.36 version: 1.0.0-dummy-version`

**Comment by dwhly** [comment]
> In short, the copy-to-clipboard functionality we currently have for the client does not allow > This means that there is no straightforward way to make it possible to copy the version details in a readable way—they’ll all be crammed onto one line

Still worth doing IMHO.
