### ISSUE TITLE
Make it easy for developers to use the matcher pattern in our python tests

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#1078]
Our tests often use a pattern of comparing concrete objects to 'matcher' objects which consider themselves equal under certain circumstances. Typically this is used to have more loose matching objects which will match a range of different things, where those differences don't matter for the test. For example:

```python
assert return_list == [AnyStringContaining('error'), AnyNumber()]
```

This is useful because:

 * It let's you concentrate on the features of the test that matters
 * Can create shorter more readable tests
 * Can make tests easier to write

Desired outcomes:

 * Prove that the cookiecutter template is versatile enough to work for more than one package
 * Prove we can use libraries from each other without issue
 * Provide a library for a common pattern we use, and reduce rework in future

Chosen solution:

 * Create a new python library containing re-usable matcher objects
 * Use it in `h-pyramid-sentry`

----

Acceptance criteria:

 - [x] We have a project which provides test matches as a python package
 - [x] The project uses the cookiecutter template: https://github.com/hypothesis/h-cookiecutter-pypackage
 - [x] We've met the standard requirements for lint, coverage etc.
 - [x] The package is deployed to PyPI
 - [x] `h-pyramid-sentry` uses the package
 - [x] Existing matcher objects in `h-pyramid-sentry` are removed
 - [x] No extra items which are not currently used in `h-pyramid-sentry` are created (no consumer, no code)

Possible future work:

 - Replace matchers in `h` or another package with this package (expanding capability as required)

**Comment by jon-betts** [comment]
Created a repo for this at:

 * https://github.com/hypothesis/h-matchers

**Comment by jon-betts** [comment]
This is now building out to:

 * https://pypi.org/project/h-matchers/

**Comment by jon-betts** [comment]
This is now used in h_pyramid_sentry in: https://github.com/hypothesis/h-pyramid-sentry/pull/9

**Comment by jon-betts** [comment]
We are all done and merged!
