### ISSUE TITLE
Allow users to opt in to receive comms on signup

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1086]
Writing a new issue in place of https://github.com/hypothesis/product-backlog/issues/431. The old issue has lots of outdated info & is a lot to read through.

## User story
- As a Hypothesis team member, I want to be able to email our users with news about Hypothesis and annotation
- I want to allow users to opt in to receiving these emails from us when they sign up for the service. 

## Current signup form
At https://hypothes.is/signup:

<img width="536" alt="Screen Shot 2019-12-18 at 2 13 11 PM" src="https://user-images.githubusercontent.com/12087705/71115709-8c446d00-21a0-11ea-953f-37d39f338fc0.png">

## Proposed change and scope
A second checkbox, under the privacy policy acknowledgement. 

- [x] The copy should read: I would like to receive news about annotation and Hypothesis
- [x] The checkbox should be un-checked by default
- [x] In our User data for each new signup, we should capture whether they opted in (checked the box) upon signup. So a simple "Yes/No" in the User table would be sufficient. For all previously created accounts, who did not have the option to check or un-check the box, it would be great if we could represent this in the User table (perhaps an "N/a" instead of a "No"?)

**Note that for this issue, we are just looking at capturing a date if/when someone checks this box upon signup.** Future iterations on this may include a toggle in the H account interface, auto-populating an email program, etc - but for now, we are just looking to get to a point where users can opt in upon signup and we can get the email addresses of users who have logged in.

## Outstanding questions:

Product will clarify these questions before engineering is expected to work on this: 

- [x] What should the checkbox statement say? The original copy proposed was "I agree to receive occasional communication for product and research purposes." This is a bit opaque. ** We got copy input from Marketing. See Proposed changes and scope section**
- [x] Our original issue, which predates GDPR, stipulates that the box be checked automatically. Now that we are GDPR-compliant, will this box have to be un-checked? ** Update: Yes, this will have to be un-checked **
- [x] Can we be GDPR-compliant if, upon first iteration, the only means of opting out is through our email service (i.e., there's an unsubscribe link in the emails we send out, but no toggle in the Hypothesis interface) ** it's fine to manage opt-out through our email service; but a next iteration of this where users can opt out through account settings would be nice **

**Comment by xolotl** [comment]
I would change the user story to be more specific as we already can and do email users about their accounts, for support, etc. How about something like:

> As a Hypothesis team member, I want to be able to email news about annotation and Hypothesis to our users

**Comment by xolotl** [comment]
For Q1: I think the copy would say something like:

> I would like to receive news about annotation and Hypothesis

**Comment by xolotl** [comment]
For Q2: Yes, as I understand it, to be GDPR-compliant, the box would have to be unchecked. People have to take an action to subscribe, like tick a box, just submitting a form with a box ticked by default is not considered an action.

**Comment by xolotl** [comment]
For Q3: I think it would be fine to have unsubscribe at first (or maybe always) via whatever system H. uses to send email news (formerly Mailchimp, now HubSpot). It might be nice if there were at least a link to go somewhere else to unsubscribe from a user's H. account settings (we could maybe set up https://web.hypothes.is/unsubscribe/ so we could redirect it at will to whatever system(s) were needed), but I don't think that's necessary for MVP. LMK if we do want to provide this.

**Comment by klemay** [comment]
Thanks Nate! 

I think https://web.hypothes.is/unsubscribe/ + a link from account settings would be a great next iteration - I will write up that issue and link it here as we get closer to completing the work for this issue.

**Comment by xolotl** [comment]
OK @klemay! I might set up https://web.hypothes.is/unsubscribe/ now anyways as it might be handy to have a human-friendly link for it. That way we will know if it's working out before we bake it in the product.

**Comment by klemay** [comment]
> That way we will know if it's working out before we bake it in the product.

Always a good move 😂

**Comment by xolotl** [comment]
Sorry for the delay in reviewing this. It all still looks good from my POV, with one added thing about how to handle the status of accounts that exist before this goes live. I think we need to differentiate between people that had the chance to opt in and didn't take it versus previously existing accounts that were never presented with the choice.

I think we will want to message all the  "legacy" accounts with an opportunity to opt in (that is a separate project), and so we will want to be able to identify them as different than accounts that had the chance to opt in and chose not to.

My suggestion is that:

1. Accounts that exist before this goes live have no value in the "opt in date" so that we can message them and ask them if they would like to opt in.
1. Accounts that opt in record the date of their action.
1. Accounts that choose not opt in record some value in the field so we know they have actively chosen not to opt in.

**Comment by klemay** [comment]
@xolotl agreed that we should specify who checked "No" vs who never had a chance to opt in. That's now reflected in the requirements. 

In terms of recording the date of opting in— wouldn't that be the same as the signup date/time? 

In the future when we create the ability to change one's designation via profile pages/account settings, it would certainly make sense to record the date of those changes - but for this iteration we are talking about one  value, set at signup.

**Comment by xolotl** [comment]
Oops, sorry, I misread that the opt in field would record a date. Yes, I agree yes/no/empty values would be fine until it becomes directly user configurable.

**Comment by jon-betts** [comment]
There are two PR's in to achieve this.

* For existing users the value is `NULL` (no value at all)
* For new users, it would be `True` or `False` depending on whether they check the box.

As of these changes:

 * Nothing happens to the value, it's just stored as `user.comms_opt_in` in the DB
 * There is no way to view, or opt in or out once this has been set on sign-up

**Comment by xolotl** [comment]
For everyone's information, https://web.hypothes.is/unsubscribe/ is in place and redirects to the current path to unsubscribe from HubSpot emails. If and when someone takes this path, we can thus make sure they don't receive any more marketing emails, but we don't yet have a pathway to flip their opt in value in the app. Would it be possible to either learn an API call to do this or include it in our admin capabilities at https://hypothes.is/admin?

**Comment by xolotl** [comment]
We might also identify all the email addresses currently unsubscribed to marketing emails in HubSpot and make sure their app opt in value is FALSE.

**Comment by klemay** [comment]
@xolotl it's possible to change the opt-in value in h, but outside the scope of this ticket as it would be a not-insignificant amount of work. I've written up https://github.com/hypothesis/product-backlog/issues/1129 to capture this - it'll be up for review at our next backlog meeting.

**Comment by seanh** [comment]
> The copy should read: I would like to receive news about annotation and Hypothesis

As I mentioned over in [the PR](https://github.com/hypothesis/h/pull/6136#discussion_r469097288) I think we should change this to:

> I would like to receive email about annotation and Hypothesis.

so that it's clear what they're consenting to (that we're going to email them).

It also doesn't say who they're consenting to receive email _from_, only what about. Are we going to give their email to third-parties who're going to email from about annotation? So maybe it could even be:

> I would like to receive product and research email from Hypothesis.

**Comment by seanh** [comment]
Just a note that when someone checks this box and submits the registration form **we have not verified that the email address belongs to them** and we shouldn't use it. We should only send marketing email to users who have activated their accounts

**Comment by jon-betts** [comment]
This is live now. The point about emailing people is valid and I'll add it to this: https://github.com/hypothesis/product-backlog/issues/1132.

This is live now.
