### ISSUE TITLE
Sidebar icons blank/missing on Great Courses website

### ISSUE THREAD

**Issue by xolotl** [hypothesis/product-backlog#1087]
### Steps to reproduce
1. Visit any page on the Great Courses site, like: [https://www.thegreatcoursesplus.com/films/title/finding-the-story](https://www.thegreatcoursesplus.com/films/title/finding-the-story)
2. Note that the Hypothesis sidebar icons are missing/blank (their src seems to be "unknown").
3. Annotation capabilities otherwise seem to be functional.

### Expected behaviour
Sidebar icons should appear normally.

### Actual behaviour
Sidebar icons are missing/blank.

### Browser/system information
timestamp: Mon Dec 30 2019 10:47:57 GMT-0800 (Pacific Standard Time)
userAgent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_14_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/79.0.3945.88 Safari/537.36
version: 1.261.0

### Additional details
Reported by user via support.

**Comment by robertknight** [comment]
Issue appears to have been resolved. Possibly by more extensive use of Shadow DOM in the client to protect our UI elements from those in the parent site, possibly by changes in the page itself.
