### ISSUE TITLE
Share link has some new formatting around it

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1088]
### Steps to reproduce
1. Grab the share link to an annotation, use the copy link icon
2. Paste it into a document, like an email message

### Expected behaviour
You should get a plain link, with no extra formatting.

### Actual behaviour
The link comes with some additional formatting, which has to be stripped out if desired.

### Browser/system information
Chrome

Here's what I expected:
![Screen Shot 2020-01-10 at 4 35 16 PM](https://user-images.githubusercontent.com/1413074/72195505-77d24980-33c7-11ea-9b3a-d7268780e638.png)

Here's what I got:
![Screen Shot 2020-01-10 at 4 35 45 PM](https://user-images.githubusercontent.com/1413074/72195478-5bcea800-33c7-11ea-98d1-ce97899e9352.png)

**Comment by lyzadanger** [comment]
Hi @dwhly I believe this has since been rectified in some manner or other. I'm not able to reproduce in my current set of browsers. Link is copying for me without any formatting. Please reopen if there are any further issues!
