### ISSUE TITLE
Improve account activation flow 

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1094]
### User Story
As a new Hypothesis user, I am directed to check my email and click a link to activate my account. When I click the activation link, I am redirected to https://web.hypothes.is/ with no confirmation that my account was activated, or that I can log in and start annotating. 

### Notes
As @seanh [points out in Slack](https://hypothes-is.slack.com/archives/C2C2U40LW/p1583418847014300), I would expect clicking that activation link to do some combination of: 

* Log me in
* Tell me that my account has been successfully activated
* Tell me that I now can (and must) log in with my email and password
* Send me to the login page

### Next steps
- [x] agree on what the experience should be when a user clicks the activation link
- [x] implement new workflow

**Comment by seanh** [comment]
I suggest we either:

* Redirect them to https://hypothes.is/login with a flash message at the top of the page saying your account has been successfully activated and you can now log in with your username and password (we might also pre-fill the username field for them)

* Or we log them in automatically and redirect them to their profile page, with a flash message at the top of the page saying your account has been successfully activated and you're now logged in. This is better but might be harder to implement
