### ISSUE TITLE
SPIKE: Video annotation via YouTube, Vimeo, etc.

### ISSUE THREAD

**Issue by bobheadxi** [hypothesis/product-backlog#1098]
### Problem you are trying to address with this feature

Annotation of videos from providers like youtube.com, vimeo.com, etc. - useful for online lectures, video essays, and more.

### Your solution

Most video providers like YouTube offer timestamping capabilities:

```diff
- https://www.youtube.com/watch?v=QCkm0lL-6lc
+ https://www.youtube.com/watch?v=QCkm0lL-6lc&t=34
```

It would be great if adding an annotation would automatically attach to the current timestamp. Currently, `hyp.is` doesn't work with YouTube links at all (#626), but it seems page annotations can still be added via bookmarklets without imposing a resource hog (if a bit inconsistently - additional parameters in the YouTube URL, like the above timestamps or even the `&feature=youtu.be` generated from short URL redirects seem to cause the same video to be identified as distinct)

This would require some site-aware functionality which I'm not sure is part of hypothesis's goal, but this would be a very nice feature

(with some pointers on where to start I would also be interested in partaking in the implementation of this)

**Comment by Faris999** [comment]
I would also like to have this feature.

**Comment by klemay** [comment]
an experimental tool that allows for annotating YouTube video transcripts: https://docdrop.org/

**Comment by klemay** [comment]
Related: https://github.com/hypothesis/product-backlog/issues/1142

**Comment by robertknight** [comment]
You can now annotate the transcripts of YouTube videos by going to https://via.hypothes.is and pasting the URL of the video in the input field. This will serve the embedded YouTube video alongside a transcript, which you can annotate. Support for other video providers will come in future.
