### ISSUE TITLE
"Cookies required" pages when viewing journal articles in via

### ISSUE THREAD

**Issue by hubgit** [hypothesis/product-backlog#1113]
### Steps to reproduce
1. Open https://via.hypothes.is/https://linkinghub.elsevier.com/retrieve/pii/S0720-048X(20)30250-3
2. Observe redirection to a page with message "This site requires Cookies to be enabled to function".

### Expected behaviour
I'd like to be able to view pages that require cookies to be enabled.

### Actual behaviour
It's not possible to view pages that require cookies to be enabled.

### Browser/system information
Chrome v81, macOS 10.15

### Additional details

Another example:

* https://via.hypothes.is/https://doi.org/10.1111/dth.13677

I found some related discussion in https://github.com/hypothesis/via/pull/89

**Comment by robertknight** [comment]
Hello @hubgit 👋 

Thanks for the report. Via currently blocks cookies to prevent them from being shared between different sites proxied through via.hypothes.is. This is important from a security perspective and we'd need to resolve that before we could consider enabling cookies at all.

**Comment by hubgit** [comment]
Thanks @robertknight, that's reasonable. 

If there are only a few sites that suffer from this problem maybe it's better that they support reading without cookies enabled.
