### ISSUE TITLE
Sidebar magnified on docdrop

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1124]
### Steps to reproduce
1. Go here: https://docdrop.org/pdf/1Vsd26C0KuMw4Mj1WEBjBz1T8G75vIhWx-gaQEE.pdf/
2. Open sidebar

### Expected behaviour
Sidebar should be normal size

### Actual behaviour
Sidebar is magnified.  Why?

**Comment by robertknight** [comment]
Hi @dwhly - Can you post a screenshot of what you are seeing? Nothing jumped out at me as unusual when I had a quick look in Chrome and Safari just now.

**Comment by klemay** [comment]
@dwhly can we close this issue? the original link you provided no longer works, but I tried a few different PDFs in Chrome, Safari, and FF, and I am not seeing the sidebar magnified. 

Chrome: 
<img width="1460" alt="chrome-docdrop-pdf" src="https://user-images.githubusercontent.com/12087705/107538539-15cbb100-6b92-11eb-83ec-e794e644709e.png">

Safari:
<img width="1430" alt="safari-dropdoc-pdf" src="https://user-images.githubusercontent.com/12087705/107538552-18c6a180-6b92-11eb-84d6-65c7fc104418.png">

Firefox:
<img width="1262" alt="firefox-docdrop-pdf" src="https://user-images.githubusercontent.com/12087705/107538575-1ebc8280-6b92-11eb-8633-8a98e2bf9f10.png">

**Comment by dwhly** [comment]
Yes, most def!
