### ISSUE TITLE
Remove flag icon from annotation cards for LMS users

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1126]
As part of our Sections work, we needed to temporarily remove moderation capabilities for LMS users. We removed the functionality but did not actually remove the icon. Now we have a flag icon that doesn't do anything, which is confusing for students and faculty:

<img width="1368" alt="Screen Shot 2020-07-22 at 2 03 26 PM" src="https://user-images.githubusercontent.com/12087705/88212533-6941d600-cc25-11ea-849f-59b9b2450e2b.png">

We should remove the flag icon until we are ready to tackle https://github.com/hypothesis/lms/issues/1388

**Comment by mattdricker** [comment]
Confusion from an LMS user about flagging: https://app.hubspot.com/contacts/6291320/ticket/284962510/

**Comment by robertknight** [comment]
What I would suggest doing for the implementation is to follow the example of the `allowLeavingGroups` option in the service configuration. See https://github.com/hypothesis/client/blob/8dacfeadbe916e7fcea9deb62246eff4460db8f7/src/types/config.js#L18 and `AnnotationActionBar` in the client and https://github.com/hypothesis/lms/blob/a795659f22ff554e4c4039228741f613b08f0039/lms/resources/_js_config.py#L476 in the lms app.

**Comment by esanzgar** [comment]
Thanks @robertknight  for the hint.
