### ISSUE TITLE
Support sites which do client-side navigation (SPA, PJAX etc.)

### ISSUE THREAD

**Issue by sean-roberts** [hypothesis/product-backlog#1135]
The client does not update the current document URL / metadata in the sidebar when a client-side navigation occurs (eg. using the HTML `window.history.pushState` API). This affects sites which are client rendered (eg. SPAs) as well as those which use PJAX / turbolinks-style techniques to optimize navigations after the initial page load. As a result the client does not update after a client-side navigation to unload annotations for the old URL and load annotations for the new URL. It does however always fetch/use the current document URL and metadata when a new annotation is created.

Some challenges that we need to deal with to resolve this:

1. We need to detect when a client-side navigation has occurred. Historically the History API did not have an event for this. The new [Navigation API](https://wicg.github.io/navigation-api/), which as of 2022-06-14 is only implemented in Chrome, does. For browsers that don't implement the Navigation API we might need to monkey-patch the history API or find a polyfill for the navigation API.
2. We have seen that some pages fail to update some `<head>` metadata fields after a client-side navigation. This can result in annotations created after the navigation mixing old and new document metadata. This is an existing issue though, so it shouldn't block an initial solution.

**Comment by robertknight** [comment]
I revised the description of the issue to make it easier to find and clarify the general problem and current status. A relevant recent development is that there is a new [Navigation API](https://wicg.github.io/navigation-api/) in browsers which we can use to detect client-side navigations without having to eg. monkey-patch the history API.

**Comment by robertknight** [comment]
Initial support for handling client-side navigation has landed. There a handful of notable websites (YouTube, Reddit) where this doesn't work because the site doesn't update its canonical URL after a navigation. This has been deferred to a separate issue: https://github.com/hypothesis/product-backlog/issues/1288.

**Comment by kael** [comment]
I've just come across the same issue while bookmarking a GitHub discussion forum page after I had read another one before.

See [this annotation](https://hypothes.is/api/annotations/IFsMJLzQEe270if2Dm2ahw) where the title is incorrect and reflects a lack of title update during client-side navigation:

```json
{
  "document": {
    "title": [
      "How to add cloudflare to existing project? · remix-run/remix · Discussion #5684"
    ]
  }
}
```

whereas the title of the page is _[Allow head and body to be hydrated separately #5244](https://github.com/remix-run/remix/discussions/5244)_.
