### ISSUE TITLE
In the LMS app in Moodle, once the Sidebar is fill, new annotations go past the bottom of the Sidebar and can not be reached by scrolling

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1157]
**Describe the bug**
In Moodle and in the LMS app, once the Sidebar has more annotations than can be shown on the screen, new annotations that appear last in the Sidebar will have the bottom of the annotation Card hanging below the edge of the screen, and the scroll bar doesn't update to allow further scrolling down. This means that  you could not, for example, delete the bottommost annotation.

The problem persists even if you re-load the assignment, and occurs when Hypothesis is embedded in a Moodle page **and** when Hypothesis opens in a new window. It occurs in both PDF and URL assignments.

**To Reproduce**
1. Log into our Moodle environment
2. Create a new Hypothesis assignment (PDF or URL, embedded window or new window)
3. Create and post enough annotations that the Sidebar fills up.
4. Create and post an additional annotation.
5. Attempt to scroll to the bottom of the annotation.

**Expected behavior**
At this point you would expect to be able to continue scrolling to get to the new bottom of the Sidebar. 

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/95751523-bd7cb500-0c6c-11eb-8c8a-fa2a44287a84.png)

**Desktop (please complete the following information):**
 - OS: Mac Mojave v 10.14.6
 - Firefox 81

**Additional context**
https://hypothesis.zendesk.com/agent/tickets/14334

**Comment by robertknight** [comment]
This issue should have been resolved in https://github.com/hypothesis/lms/pull/2210. I think it would be a good idea for @mkdir-washington-edu or someone else on the support team to re-test in case they can find any related issues.

**Comment by klemay** [comment]
We can no longer reproduce this issue after a fix put forward by Rob. The user who reported it has not gotten back to us, but we have no other reports of users running into the problem. Closing as fixed.
