### ISSUE TITLE
Layout problems when threaded discussions are 3 levels deep

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1163]
One of the most crucial features for our users is the ability to have threaded discussions. [A user pointed out to us on Twitter](https://twitter.com/thecorkboard/status/1337446123787718656) that once a discussion gets to be 3 levels deep, the interface gets crowded:

![ezgif-7-c6b258259516](https://user-images.githubusercontent.com/12087705/101993915-2f34a780-3c8c-11eb-924c-69d28e799b90.gif)

On desktop, you can resize the Hypothesis sidebar to create more room:
![ezgif-7-4378058adfd0](https://user-images.githubusercontent.com/12087705/101993967-a407e180-3c8c-11eb-9e04-85d1fd6bc9d0.gif)

However, on smaller screens, especially mobile devices, there is only so much horizontal room to work with. Our users also don't seem to realize this is an option— we often have to point it out to them

In [this discussion on Slack](https://hypothes-is.slack.com/archives/C07NXBDNW/p1607711470133200) the team discussed an old prototype for auto-collapsing of threads along with some other potential solutions. 

**The desired outcome here would be that no matter your screen size, the UI does not get cut off when the Hypothesis sidebar is at the default width.**

**Comment by lyzadanger** [comment]
While I don't want to assert that we've solved or nailed this UI, the problems reported in this issue have been mitigated, in two ways:

* The amount of horizontal room required per nesting level has been greatly diminished. Even at six levels deep, you don't have to "resize the sidebar" on the desktop to have enough room:


<img width="455" alt="image" src="https://user-images.githubusercontent.com/439947/204870661-f52d276b-d0e3-404e-9640-ab2740a3c9d2.png">

<img width="470" alt="image" src="https://user-images.githubusercontent.com/439947/204870811-bd9495af-ec2b-496f-9c33-32db83acbfd2.png">

* This interface should not "break out" of its container when it's wide
