### ISSUE TITLE
Unintuitive "Show all" UX

### ISSUE THREAD

**Issue by nicolae-stroncea** [hypothesis/product-backlog#1167]
### Steps to reproduce
1. Annotate multiple examples
2. Click on one
3. Output in the sidebar:
![image](https://user-images.githubusercontent.com/39338488/100553673-188a5b80-325d-11eb-8216-b895b6d5f4fe.png)

This is unintuitive, and more than once I clicked on an annotation and was not sure how to get back to viewing all annotations. The wording of *X | Show all (2)* is contradictory: the X implies you are already showing all examples and you can cancel that by clicking the X. In reality, the button does the opposite.

### Desired behaviour

1. Get rid of "Show all()" and instead add the X button around the text on the left: *X | Showing **1 annotation***. This now implies that when you click X it will stop showing only 1 annotation, which is exactly the desired effect.
2. Get rid of the X and just have *Show allI()* as a button, though personally the first approach is more clear to me

**Comment by klemay** [comment]
Hi @nicolae-stroncea, thanks for this feedback! The screenshot you have shared is from a filtered view of the client: clicking on an annotation will show just that annotation and its replies. The [X Show all (2)] button is how you exit or "cancel" that filtered view and return to seeing all of the annotations, so the button describes the action that will be taken when you click it.
