### ISSUE TITLE
Top of superscript text overlaps with previous line in annotation cards

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#1171]
### Steps to reproduce
1. Create an annotation that contains superscript text (in Markdown, you can do this with `<sup></sup>` tags - so to write 2<sup>3</sup> you'd type `2<sup>3</sup>`)

### Expected behaviour
The superscript text properly renders.

### Actual behaviour
There is overlap between the superscript text and the previous line. If this happens in the first line of annotation text, the top of the superscript is cut off. If it happens later on in the annotation, the superscript text overlaps with the previous line:

<img width="414" alt="Screen Shot 2021-02-02 at 11 54 28 AM" src="https://user-images.githubusercontent.com/12087705/106634095-6f5a2d00-654d-11eb-991c-a32552f7e895.png">

([link to example shown in screenshot](https://hyp.is/j668MmV2EeuWraPoYmS40Q/en.wikipedia.org/wiki/Trypsinization))

### Browser/system information
Discovered in  Chrome/88.0.4324.96 for Mac & reproduced in latest versions of Safari and Firefox for Mac.

**Comment by lyzadanger** [comment]
The styled text from markdown/markup for annotation bodies has been re-implemented since this issue was opened. Superscript no longer gets cut off on top or other lines. yay!
