### ISSUE TITLE
Don't cache /_status endpoints (all apps)

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#1198]
All `/_status` endpoints should send a `Cache-Control: no-store` header to prevent responses from being cached (e.g. by Cloudflare). Otherwise alarms set on these endpoints (such as ones we have in New Relic) won't work.

See: https://hypothes-is.slack.com/archives/CR3E3S7K8/p1616760276070900?thread_ts=1616581242.031600&cid=CR3E3S7K8

For some reason h, bouncer, lms, and via's `/_status` responses are not being cached by Cloudflare but we don't know why. They look like they should be cached. Via 3 QA's responses definitely were being cached, and this did cause an alarm to fail to trigger, before we added a Cloudflare rule to disable the caching.

- [x] h - https://github.com/hypothesis/h/pull/6571
- [x] bouncer - https://github.com/hypothesis/bouncer/pull/410
- [x] lms - https://github.com/hypothesis/lms/pull/2542
- [x] via - https://github.com/hypothesis/legacyvia/pull/299

Others: 

- [x] checkmate - https://github.com/hypothesis/checkmate/pull/277
   * Checkmate's `/_status` endpoint responses currently contain a session cookie in a `Set-Cookie` header that I think might be preventing the responses from being cached. This is incidental though: Checkmate's authentication should not be adding session cookies to all non-session using requests. The `/_status` endpoint still needs a proper `Cache-Control` header.
- [x] via3 - https://github.com/hypothesis/via3/pull/430
 * We have added Cloudflare rules to disable Via 3 QA and prod `/_status` endpoint caching. Without these rules Via 3 QA's `/_status` responses _were_ being cached. But these rules shouldn't be necessary: the app should send headers to prevent caching.
- [x] viahtml - https://github.com/hypothesis/viahtml/pull/130
   * Currently sends `Cache-Control: no-cache` which I think is incorrect. I think this needs to be changed to `no-store`.

**Comment by jon-betts** [comment]
Done! Phew
