### ISSUE TITLE
Work out a mechanism to monitor Docker file updates (for Python at least)

### ISSUE THREAD

**Issue by jon-betts** [hypothesis/product-backlog#1209]
Dependabot doesn't do a good job of managing our docker file updates for a few reasons:

 * There are two version numbers going on at the same time, one for Alpine and one for Python
 * It doesn't work well with us wanting not to go to 3.9, but still wanting Python 3.8 versions
 * It's possible for upstream maintainers to change the dockerfile without changing the name - so we should be hash based or at least aware if possible (which does change)

Some ideas;

 * Is there anything we can do with Dependabot? Probably not
 * Can we add an `hdev` command and call it periodically from GHA or something?

Progress:

 * [x] `h-periodic` - https://github.com/hypothesis/h-periodic/pull/105
 * [x] `bouncer` - https://github.com/hypothesis/bouncer/pull/452
 * [x] `checkmate` - https://github.com/hypothesis/checkmate/pull/370
 * [x] `h` - https://github.com/hypothesis/h/pull/6746
 * [x] `lms` - https://github.com/hypothesis/lms/pull/2914
 * [x] `via`- https://github.com/hypothesis/via/pull/533
 * [x] `viahtml` - https://github.com/hypothesis/viahtml/pull/208

Dependabot PRs:

 * [x] https://github.com/hypothesis/checkmate/pull/371
 * [x] https://github.com/hypothesis/via/pull/534
 * [x] https://github.com/hypothesis/viahtml/pull/209
 * [x] https://github.com/hypothesis/bouncer/pull/453
 * [x] https://github.com/hypothesis/h-periodic/pull/107
 * [x] https://github.com/hypothesis/lms/pull/2915
 * [x] https://github.com/hypothesis/h/pull/6747

**Comment by ajpeddakotla** [comment]
removing this from the product/bug backlog as its a tech issue

**Comment by seanh** [comment]
Adding this to the [Engineering Backlog](https://github.com/orgs/hypothesis/projects/8).

I think Dependabot can handle this for us, see: https://hypothes-is.slack.com/archives/C1MA4E9B9/p1621938886140300

For clarification: there aren't actually two version numbers going on at the same time. It's a single semantic version number. For example  `python:3.8.9-alpine3.13` is a semantic version number with major version `3`, minor version `8` and patch version `9-alpine3.12`. The problem with Dependabot previously was that we only want it to send us patch version updates for Docker images but it wasn't capable of doing that, it would always send major and minor updates as well. But a new Dependabot feature (see Slack thread) means we can configure it to send patch versions only.

I'm not sure about the hash thing and whether Dependabot supports that, though. I think I remember reading that it does support it

**Comment by jon-betts** [comment]
Done!
