### ISSUE TITLE
Automatically fix course-copied Canvas Groups assignments whenever possible

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1219]
This seems to be the same issue as https://github.com/hypothesis/lms/issues/2764 

When we create a launch URL for a Groups assignment we include data about the Group Set the teacher chose (e.g. “group_set=135”). Like Files, Canvas seems to assignment a number to each Group Set across the whole Canvas instance, and a copied assignment has a launch URL that references a group set in the old course.

We should look for a way to make sure that copied Groups assignments can still work, and give useful error messages when we don’t. A major difference from the Canvas Files course copy solution is that as far as I can tell when you copy a Canvas course you do **not** copy over existing Group Sets or Groups. So any solution is likely to have work to do on the user's side, such as requiring that they build new Group Sets with the same names as the old Groups Sets.

To reproduce:
1. Create a Groups assignment in a Canvas course. Note the Group Set ID in the launch URL.
2. Copy the course and create new Group Sets.
3. Launch the copied assignment. Note that the Group Set ID has remained the same.
4. Create a new Groups assignment in the new course and note that the Group Set ID is different (even if the Group Set name, etc., is the same).

**Comment by marcospri** [comment]
We already try to fix this for BB and D2L.

Canvas was excluded of this because Canvas itself doesn't copy the groups on course copy but I don't see a reason not to also try to match group sets by name.

**Comment by mkdir-washington-edu** [comment]
Slack convo: https://hypothes-is.slack.com/archives/C2C2U40LW/p1711107060455979?thread_ts=1711020039.622829&cid=C2C2U40LW


**We expect instructors to only need to launch one Groups assignment to sync all of them**
We've seen behavior from Files course copy where, if the Files tool is hidden, the instructor need to launch every assignment, not just one assignment. Once this fix is implemented I think Support should test this same thing if the People tool is hidden from students.

**Students get the You're not in any of this assignment's groups  because we can't tell why we can't find the course**
That makes sense to me!

**I need help re-wording the error modal**
I think a lot of this can stay the same. Here's some writing suggestions. Note that I'm also adding suggestions to the parts that **aren't** effected by course copy. Implement or ignore them as you wish. **Most of this is the same.**


**Group set not found**
This Hypothesis assignment was set up to use Canvas' Group Sets, and we can no longer find the Group Set for this assignment. This could be because:
- The group set has been deleted from Canvas.
- This course was created by copying another course.

If the group set has been **deleted** from this course, an instructor needs to edit the assignment settings and select a group set.

If this is a **copied course** the instructor needs to create a new group set in this course that matches the name of the group set in the old course. The group set name in the old course was {{name}}.

**If you are a student copy this message and send it to your instructor.**

If the problem persists, etc.

**Comment by mkdir-washington-edu** [comment]
Tested and looking great! Thanks @marcospri !
