### ISSUE TITLE
VitalSource integration gives an error in non-Canvas LMSs

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1231]
### Steps to reproduce
1. Enter course https://aunltd-test.blackboard.com/ultra/courses/_38_1/cl/outline (use "professor" login)
2. Try to launch any "test VS" assignment
3. See error

In Firefox I get this error:
![image](https://user-images.githubusercontent.com/22603275/139097750-41ef33e0-0d02-4870-87d9-c7630cc3329e.png)

In Chrome I get a blank page.

### Expected behaviour
Blackboard and other LMSs should launch VitalSource just like Canvas does.

### Browser/system information
MacOS big sur 11.6
Chrome 95
Firefox 93

### Additional details
[Original Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1635347477018300)

## Feature Request Form

**Comment by marcospri** [comment]
This should work now, tested on blackboard. 

Created a  "Prod VitalSource assignment" assignment on the test course.
