### ISSUE TITLE
[PDF] Create a demo of VitalSource on PDF

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1233]
We'll be done when:

- The developer of the feature can complete the scenario laid out below
- A "laundry list" of next steps exists to capture the remaining tasks required to get PDF ready for launch.

#### Scenario / story

I'm the person who wrote the code. We're in a meeting giving VS the update that we're ready to roll this out in a limited pilot for the Spring. We've already learned from profs that having H will prompt them to force students to opt-in/buy the textbook via VS, so we're adding real value to their business.

To prove we can cover the entirety of their catalog (both EPUB and PDF) and motivate them to begin recruiting their own customers for use, we show them the work we've done to solve for their PDF reader:

##### Assuming that:

- I'm in Canvas
- I've logged into VS ahead of time to avoid any login interstitial
- I've picked a PDF book from VS I know I have access to
  - :information_source: _For the demo, we can pick the best book, but eventually this will need to work with **any** of a representative sample_
    - [ ] Get a representative sample from VS and include it here
- I've created a new Canvas assignment and select Hypothesis
- I do **not** make this a group assignment
- I opt to launch the app in a new tab

##### I can do the following demo:

- :bust_in_silhouette: I start as a teacher
- I launch the Hypothesis tool to set up the assignment
- I select the VitalSource source option
- I drop in a full VS bookshelf link
- The book loads with a thumbnail of the cover
- I select a chapter from the chapter menu to assign that chapter as the entry point
  - :information_source: _It does not need to keep users from going past the assigned chapter for the demo_
- :bust_in_silhouette: I switch to a student
- I launch the assignment, which kicks me into a new tab. The sidebar shows up on the right side of the viewer.
- When I highlight some text in the PDF and get the annotation pop-up
- When I hit Annotate, a draft annotation appears in the sidebar. I can save it like normal.
  - :information_source: _I've intentionally not mentioned page notes or highlights, in case it cuts scope :shrug: _
- When I drag or scroll the VS pager and the pages change but I stay in the same chapter, my annotations in the sidebar stay there
  - :information_source: _It's not an issue for the demo, but we should keep in mind that in the future, we may need to bucket posts by **assignment**, not chapter, and keep them from going past the assigned page range._
- When I switch to the next chapter using the table of contents or prior/next buttons, my annotations in the sidebar switch to display the annotations associated with the new chapter_

#### :heavy_plus_sign: For the future

- Adding an ISBN should also work (should already be true)
- The same flow works for highlights
- Page notes also work
- When I open Notebook. My new annotations show up next to my other posts from other assignments outside VitalSource, linking to the VitalSource book correctly

**Comment by robertknight** [comment]
There are some initial technical notes from me on how PDF-based books work in VitalSource here: https://hypothes-is.slack.com/archives/C1M8NH76X/p1633947326099500.

Quoting from that thread:

> The VitalSource PDF viewer presents each page of the PDF as a separate HTML document, consisting of one high-resolution image of the PDF, plus a bunch of data about the page and its text content in a <script> tag. Unlike PDF.js there is no transparent text layer for text selection. Instead they simulate the browser's normal text selection when you click and drag the pointer, using data rendered into the page about the locations of glyphs in the rendered page. This has the unfortunate side effect that standard browser shortcuts for copying text do not work. Instead you have to click the "Copy" button from a popup menu. Not great for accessibility. I think what we'll need to do is generate our own text layer from the data embedded in the page that is similar to the one PDF.js creates. The highlight rendering can then work similarly.

> The format of the embedded text data is an object containing:
> - A string containing the rendered text
> - An array of the same length as (1) containing the bounding box of each character in the text, expressed as a percentage offset from the corner of the page. I guess this representation was chosen because it can be very easily translated to CSS percentage coordinates for position: absolute elements.

**Comment by chrisshaw** [comment]
@robertknight are we keeping this around for something or should we consider this closed? I don't see a linked commit or PR but we did the demo so... :slightly_smiling_face:

**Comment by chrisshaw** [comment]
Done
