### ISSUE TITLE
Add feature flag for Blackboard Groups

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1241]
#### We'll be done when

- [ ] We can hide the new Blackboard Groups feature during and after implementation
- [ ] We can turn on the new Blackboard Groups feature for an individual user
  - :information_source: _The existing feature flag infrastructure may suffice for this, assuming we are walking a test user through it. A problem this won't solve, however, is the ability_
- [ ] We can turn off the new Blackboard Groups feature for after installation, if we learn it isn't ready after launch
  - [ ] :information_source: :question: _I'm less sure the existing feature flag infrastructure would allow this, however we can stick to reverting current practices if not_

**Comment by marcospri** [comment]
This has been done as other setting as setting per "ApplicationInstance" so it's possible to enable/disable it by installation but not individual users.
