### ISSUE TITLE
[EPUB] Expand and contract reader view in EPUBs (instead of overlaying it)

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1248]
**As an assignment user, I want to read the text and the discussion side by side in VitalSource, so annotating doesn't get in the way of my reading and my experience mirrors the one I get from VitalSource directly.**

## Flow

As a user

- I open the H+VS assignment
- When I land in the viewer, the sidebar is **open** and the VS reader is "squished" between the TOC and the sidebar.
- When I toggle the sidebar, the sidebar toggles open and closed
  - When I toggle it closed, the VS reader expands into the open area
  - When I toggle it open, the VS shrinks into the available area

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [View annotations side-by-side in VitalSource ebooks ](https://app.harvestr.io/components/0/list/ROQJT_zcS)

**Comment by chrisshaw** [comment]
I think this is done, per @lyzadanger [here](https://github.com/hypothesis/client/pull/4245#pullrequestreview-893612907):

> Based on [discussion in Slack](https://hypothes-is.slack.com/archives/C1M8NH76X/p1645778349057179) (private to Hypothesis team members), we feel that this is at a point that it's good to release, with some identified follow-up tasks.

**Comment by lyzadanger** [comment]
We tackled a few other items related to this feature this sprint, which are now deployed:

* https://github.com/hypothesis/client/issues/4300
* https://github.com/hypothesis/client/issues/4280

Those were the last items we wanted to address before calling this stage of work complete.
