### ISSUE TITLE
[VitalSource] Default the table of contents as closed

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1249]
Nick from VS has directly asked us to default this to close because it improves the user experience.

## Scenario

:bust_in_silhouette: As a Student

- logged into Canvas
- logged into VS

I can do the following:

- I launch a Hypothesis Vitalsource assignment
- When I land on the vitalsource reader, the TOC is closed
- Everything else **still works**
  - When I hit the TOC menu, the TOC toggles open and closed
  - When I hit any TOC link item, the book navigates to the selected location

## Notes

- We need to get the API from VS 

## To do

- [x] Ask in Slack for the "public" API they talked about

**Comment by chrisshaw** [comment]
The team at VitalSource added support on their end to configure TOC starting state and then set ours to default off.

**Comment by robertknight** [comment]
I've confirmed this works as expected.

**Comment by robertknight** [comment]
A clarification for future readers. VitalSource assignments in the LMS use a Hypothesis "branded" version of the VitalSource book reader. The configuration to turn the TOC off by default is part of the configuration for our branded version.
