### ISSUE TITLE
[EPUB][Nav] Navigate to annotation in different EPUB segments

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1252]
We currently don't have a way to move throughout the book, if someone were to select a note on another "chapter". Based on conversations with Nick in the last meeting, there is a public API used for this, so this should be doable. This card is simply about the ability to navigate to that on selection--say, in Notebook, or perhaps if we showed them in the sidebar (because we may want to treat multiple pages as one there too).

Questions:

- [ ] What is the minimal experience we can enable here? Adding a dummy annotation to the sidebar and navigating to it? Using Notebook? How do we want to demo this? That could be our guide.

## Notes

- This same problem should show up within true chapters if publishers have chopped up their EPUBs into smaller documents. So I think we're not really so interested in whether we can navigate chapters as we are we can navigate "pages" as defined by VitalSource's viewer.
- See https://github.com/hypothesis/product-backlog/issues/1251. This story covers the same for PDFs.

**Comment by robertknight** [comment]
This has now been done as part of this project: https://github.com/orgs/hypothesis/projects/96
