### ISSUE TITLE
[Discovery] Show all annotations in an EPUB book

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1253]
**As a student, I want to view annotations outside of the current chapter, so I can view conversations that span multiple chapters, like personal notes and non-chapter assignments.**

Teachers and students expect Hypothesis to work like it does in other tools. That means we show all the annotations for the "document," in this case the book. We currently don't have a way to pull from notes across multiple "pages" in a PDF. This is a problem when we run into PDFs that have multiple pages for a single chapter.

**The output of this story is an internally demoable prototype.**

## Flow

- When I open the assignment, I see annotations for the entire book
- The annotations that _are_ located on the content work as expected

## Notes

- Inline notes at https://hyp.is/go?url=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fproduct-backlog%2Fissues%2F1253&group=1y5rJZVR

### Technical details

- What will happen to existing VitalSource annotations?
  - (Because we'll be adding new metadata) If we want to preserve them, we'll need to migrate the old cards.
    - @chrisshaw :  **We can let old annotations break**

**Comment by chrisshaw** [comment]
- [x] How would we adapt the UI for loading _so many_ annotations?
  - Now has draft issues
- [x] How do we incorporate logical location (and can we wait on that)?
  - Now has draft issues

Other notes

- We should handle performance later

- [x] @robertknight and @chrisshaw will talk about this early next week.

**Comment by robertknight** [comment]
> Inline notes at https://hyp.is/go?url=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fproduct-backlog%2Fissues%2F1253&group=1y5rJZVR

As an aside, the experience if you follow this link and are not already a member of the group is really bad. It just gives you a "couldn't fetch group" message with no indication as to how to join the group (or whether it can be joined).

**Comment by chrisshaw** [comment]
> > Inline notes at https://hyp.is/go?url=https%3A%2F%2Fgithub.com%2Fhypothesis%2Fproduct-backlog%2Fissues%2F1253&group=1y5rJZVR
> 
> As an aside, the experience if you follow this link and are not already a member of the group is really bad. It just gives you a "couldn't fetch group" message with no indication as to how to join the group (or whether it can be joined).

Agreed @robertknight, I ran into this too. I've captured it as another UX tweak we should make some day.

**Comment by robertknight** [comment]
This has now been done, as part of this project: https://github.com/orgs/hypothesis/projects/96
