### ISSUE TITLE
[VitalSource] Toggle on the VitalSource feature for a customer

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1255]
Give us internally the ability to switch VitalSource assignments on and off at the app instance level (like normal)

## Scenario

:bust_in_silhouette: As a H LMS admin

- On the admin page of the "school"

I can do the following:

- I see a flag for turning on and off VitalSource
- When I turn it on and save, the feature is enabled for users at that school
- When I turn it off and save, the feature turns off for users at that school

**Comment by chrisshaw** [comment]
@marcospri Flag works for turning on and off the option in assignments. :+1: 

It looks like previously created assignments are still available to students. Is that expected? (I'm thinking yes, otherwise there would have been work to gate assignments on launch.) If so, that's fine, just a gotcha I need to note down, and likely a separate ticket.

**Comment by marcospri** [comment]
Yes, it doesn't affect existing assignments by design (at the moment).

I think keeping existing assignments working is the rationale here but if we were to disable those we need to decide what happens then, we show some talk-to-your-admin type of modal?

**Comment by chrisshaw** [comment]
Thanks @marcospri. I was wrongly thinking about this from the perspective of being able to turn on features for customers as a pricing issue rather than as a set of toggles we would turn around and offer to LMS admins. Given we don't have different pricing plans and it's actually closer to the latter, this makes total sense.
