### ISSUE TITLE
[VitalSource] Discovery: Constrain annotation to assignment

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1256]
Restricting user access to the content is a common theme when talking with instructors. But this limits some of the potential engagement of the students. We'd like to thread the needle between those needs.

We also have multiple possible implementation ideas that have various trade-offs

- Allow the user to annotate the whole thing and do nothing
- Only show the content for the assignment
- Automatically submit users' assignments **later** when they are published, if they annotated outside an assignment
- "Turn off" the annotator when they go "out of bounds"
  - Optionally giving them shortcuts to navigate back in bounds
- (My preference) Automatically switch to a "social" or personal group, not the assigned group, when they go out of bounds
  - Optionally giving them messaging on what happened, options to change groups, and shortcuts to go out of bounds.
- Others to be discovered

Question:

- [ ] Are there any we could do incredibly cheaply (a couple days)? We can just learn from feedback then.

## What we should learn

- [ ] Which UX design accomplishes our desired goal of threading the needle best?
- [ ] What are the technical problems to solve for each UX design?
- [ ] Which UX design gives us the best bang for the buck (accomplished user goals / technical problems)?

## How we hope to learn it

- Show different options to our early testers, through guided user tests to see whether this solves their problems
- Run the different designs by VitalSource and get their preference. If they have strong preferences, limit it there
- Define technical problems needed to solve for frontrunners.

## Notes

- Need to know where an assignment starts and end
- Technical problems
- UI to configure it
- Save that configuration

**Comment by chrisshaw** [comment]
Candidate for Lyza

**Comment by dwhly** [comment]
A few potential issues w/ this:
1- It adds a UX complexity. Having to define an "assignment", from one place in a text to another.
2- It has the potential to create "hidden" and unexplained behaviors (why does the group control mysteriously change when I go from here to there.)
3- It removes agency from students.  For instance, why can I not ask a question of my peers in a different place in the text?  (Note that we're
4- It can be "solved" simply by adding instructions to assignments.  (You're expected to create X annotations and reply to Y others on Chapter 3).  If they do more than that or "work ahead" of where they're supposed to be, shouldn't that be ok?

Of course it may be useful for us to more precisely allow instructors to indicate the beginning of (and possibly the end) of an assignment (e.g. not just at the beginning of Chapter 3, but 5 pages in, on page 135.)   Possibly, one solution is (at some point in the future) to allow instructors to define these points, and provide visual clues for them, but not necessarily to constrain annotation functions around them.

**Comment by robertknight** [comment]
We've implemented a feature that addresses this. See https://github.com/hypothesis/lms/pull/6111 for a summary.
