### ISSUE TITLE
[PDF] Show all annotations in a PDF book chapter

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1264]
**As a student, I want to view the annotations for the chapter I'm working on, so I don't get confused and lose points because I respond to a post that wasn't part of the assignment outside the chapter.**

Assignments are sometimes a single chapter. VitalSource also will navigate by chapter in books that have them. As a proxy to an assigned area, we can limit the annotations to only that chapter.

## Flow

As a teacher or student in an assignment with a selected entry from the table of contents...

- When I set the entry at the book level, I always see all annotations in the sidebar for the whole book
  - _:information_source: This would be a way to maintian the functionality from https://github.com/hypothesis/product-backlog/issues/1253_
- When I am on a page that is outside of a chapter, I see annotations for the whole book
- When I'm in a chapter, I see annoations for all segments within it
- When I cross over to a new chapter, I see annotations for the next chapter

## Notes

- The flow is a proposal based on how a user expect these things to happen
- We probably don't get the **end** of a segment. We could treat the _next_ segment page number - 1 as the end.

## Questions

- I have yet to find a book without chapters. What happens when there are no chapters?

### Nested segments

Some segments I cross into are higher level or lower level than the one I started in. Let's say, for example, my book has sections, chapters, and segments, with a structure like:

```
-Book
  - Section
    - Chapter
      - Segment
```

VitalSource doesn't seem to care about these segments. To stay consisent with their navigation pager, I suggest neither do we.

The problem comes when books _aren't_ broken up this way. What do we do then?
  - We could simply limit annotations to whatever segment you're in, as defined by the file.
  - We could reconstruct the chapter. This is what VS seems to do.
  - Does VS treat sections and chapters as special from other segments in their TOC structure? If so, we could rely on this.

## Dependencies

Depends on https://github.com/hypothesis/product-backlog/issues/1253#issue-1058599223

**Comment by chrisshaw** [comment]
Instructor's experience grading is...

**Comment by robertknight** [comment]
This has been partially addressed by https://github.com/orgs/hypothesis/projects/96. The current status is that you can see activity from all across a book in an assignment. This solves the problem of users missing activity because it happened in a different sub-section or page of a book than it happened to be divided into. What is not yet solved is providing a way for users to easily filter annotations to either some level of granularity based on current location (eg. surrounding chapter) or based on instructor configuration for which pages are part of the current assignment.
