### ISSUE TITLE
Show instructors the TOC hierarchy when selecting an assignment

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1266]
As an instructor creating an assignment, I want to see the same table of contents hierarchy I see in VitalSource in Hypothesis, so I can more quickly find and select the exact book segment I want to use as my assignment.

## Why

The table of contents VitalSource provides nesting for publishers:

![image](https://user-images.githubusercontent.com/2966918/146059718-d89e0e41-bd61-4abd-b0d7-683d21529668.png)

Meanwhile, the current assignment entry point selector shows a flat list. This makes it hard for assignment creators to find the segment they're looking for.

## Flow

As an instructor...

- After I select a book, I view a table of contents selector that shows me the nested structure I see in VitalSource
- The top level section is the whole book. When I select the top level section, I start from the beginning.
- The book has sections, chapters, and segments. When I select a nested segment within a chapter, I start from the start of the segment (not the parent chapter or section).

## Questions

- Does VitalSource provide us the parent/child relationships?

**Comment by robertknight** [comment]
There is some missing context here on how the proposal relates to the current status. When a user configures a VitalSource assignment, we currently display a flat list of table-of-contents entries for them to choose from. This worked OK in our initial tests, but I guess there are books where not having the full hierarchical structure is a problem. See https://github.com/hypothesis/lms/pull/3098 for a screenshot / video clip of what the current UI looks like.

**Comment by robertknight** [comment]
This is now done in a minimal sense. See https://github.com/hypothesis/lms/issues/5821.
