### ISSUE TITLE
[EPUB] Show all annotations in an EPUB book chapter

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1267]
This is the same story as https://github.com/hypothesis/product-backlog/issues/1264 but for EPUBs. Treat https://github.com/hypothesis/product-backlog/issues/1264 as the source of truth for the customer experience. This is here to track the nuances of the implementation.

## Notes

- Unlike PDFs, we won't really have dependable page numbers.
  - We could rely solely on TOC.

---

### [Guidance from VitalSource](https://vitalsource.slack.com/archives/C01208U1A2F/p1643231943011600?thread_ts=1642647987.005800&cid=C01208U1A2F)

I think your best plan will be to use our table of contents API to bucket assignments/user annotations into logical sections of the book (likely chapters). I just confirmed that API endpoint works with your API key. the path is https://jigsaw.vitalsource.com/books/VBIDGOESHERE/toc do for example, `curl --request GET https://jigsaw.vitalsource.com/books/9781319367077/toc --header 'X-VitalSource-API-Key: YOURAPIKEYHERE'` would get the specific TOC for that book

each entry in that response looks like this:

```
{"title":"Chapter 1 Understanding Arguments and Reading Them Critically","path":"/OEBPS/xhtml/lun_9781319056261_ch01.xhtml#ch01_sec_1","level":2,"cfi":"/6/22[;vnd.vst.idref=ch01]!/4/2[ch01_sec_1]","kind":"document_container","page":"3","data":[]}
```

(note this is the exact data that powers the table of contents in Bookshelf, so you can open that up and probably see how the data maps)

the way I would use that data is something like this:

- retrieve the TOC via our API
- identify which level of the TOC you want to use for logical grouping, or which exact nodes you want to use. this may require manual work, or some fuzzy heuristics - every book’s TOC can be a little different. in the case of 9781319367077, grabbing the nodes with “Chapter” in the title is a nice simple option
- each TOC node includes an EPUB CFI, a data point that tells you the precise location in the book where that node (in this case, Chapter) starts. collect those (eg. `curl --request GET https://jigsaw.vitalsource.com/books/9781319367077/toc --header 'X-VitalSource-API-Key: YOURAPIKEYHERE' | jq -c ' map(select( .title | contains("Chapter ")))[] | {title,cfi}'`, which gives you data like
```
{"title":"Chapter 23 How Does Popular Culture Stereotype You?","cfi":"/6/236[;vnd.vst.idref=ch23]"}
{"title":"Chapter 24 How Does What We Eat Define Who We Are?","cfi":"/6/252[;vnd.vst.idref=ch24]"}
{"title":"Chapter 25 How Does Language Influence Our World?","cfi":"/6/266[;vnd.vst.idref=ch25]"}
{"title":"Chapter 26 Has the Internet Destroyed Privacy?","cfi":"/6/280[;vnd.vst.idref=ch26]"}
{"title":"Chapter 27 How Free Should Campus Speech Be?","cfi":"/6/296[;vnd.vst.idref=ch27]"}
```
- Based on those boundary points through the book, aggregate assignments / annotations into chapter-level buckets.
- Any time a student is on a page or triggers an event in Bookshelf, you can sniff the URL for the CFI, or it is passed on Javascript events you can listen to as well. You can then compare that CFI to the Chapter CFIs to determine which Chapter you currently inside of, even if the content is split up into many smaller HTML docs.

if CFIs are new to you all, they are part of the EPUB spec (http://idpf.org/epub/linking/cfi/) or the attached doc is a more approachable intro I wrote up a while back

[nbrown1-UnderstandingCFIs-260122-2103.pdf](https://github.com/hypothesis/product-backlog/files/7947115/nbrown1-UnderstandingCFIs-260122-2103.pdf)

**Comment by robertknight** [comment]
To add to the above, the TOC data is accessible to the client without making an API call, by using the `getTOC()` method of the `<mosaic-book>` element in the book's container frame.

**Comment by robertknight** [comment]
This has now been done, as part of this project: https://github.com/orgs/hypothesis/projects/96
