### ISSUE TITLE
Change default LMS app install configuration in Canvas to disable Sections integration

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1276]
This is a request to change the default install configuration for new Hypothesis LMS app installs in Canvas using a developer key to **not enable** Sections integration. Current behavior is to install with Section integration enabled by default.

Note that this change will be for new installs moving forward, not for any existing installs.

**Context**

Before Hypothesis integrated with Canvas Groups, Sections integration was the global feature in Canvas to enable instructors to split reading assignment into smaller student groups.

Now, however, instructors have much more control over how to create group assignments in Canvas, including easily matching Canvas Groups to existing sections. In many (if not most) cases, default Sections groups are not needed, and add a layer of confusion for instructors who are not aware of it.

I believe it would be better to leave the default install with Groups integration enabled only. Then we can manually enable Sections integration for schools that specifically request it after a conversation and understanding about how it will work.

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Fix how canvas sections works](https://app.harvestr.io/components/0/list/LAoRP9S--)
