### ISSUE TITLE
SPIKE: investigate feasibility of asking for a percentage in the grading bar and converting to the 0-10 scale LTI requires

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1279]
**Describe the bug**
We've had a few tickets ([see this issue](https://github.com/hypothesis/support/issues/187) for some of them) about instructor confusion with our grading bar. Since our grading bar declares that you're entering a "Grade (out of 10)" users will think their assignment is **worth** 10 points, even when they set it up to be worth a different amount of points, or when their LMS doesn't allow them to set their own points and chooses the points for them (as an example see here: https://github.com/hypothesis/lms/issues/1169#issuecomment-702828676).

![image](https://user-images.githubusercontent.com/22603275/134704603-4658bcdd-6cfd-4e8e-bd91-c9a55b16d0ac.png)

Rather than attempting to solve [this issue](https://github.com/hypothesis/lms/issues/1169) we could just tell users they're entering a percentage (0-100%) which makes it more obvious they're not assigning a point value. Past verbal feedback has indicated that the reason we chose to build an input out of 10 is because that is the range of values the LTI standard accepts, so this spike is to see if we can accept a different range of values and still send a value 0-10 through LTI.

**Comment by marcospri** [comment]
Done in https://github.com/hypothesis/lms/issues/5505
