### ISSUE TITLE
Bug - Canvas assignment Files is giving an API error

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1293]
**Describe the bug**
We've seen this intermittently. I'm not convinced this is the whole issue, but this is one reproducible issue. Perhaps investigating it will help us fine the other issues (see comment for other issues).

There is a PDF we put in the courses Support501 and Support501copied. Despite the name the PDF was uploaded separately in each course and the assignment was created separately in each course.

The instructor can access both assignments.

A student enrolled in both courses can access one assignment, but gets a "couldn't get the file from canvas" error in the other.

**To Reproduce**
1. In 1Password, in the LMS vault, get login information for "Canvas: Dean Moriarty (student 2)".
2. Open https://hypothesis.instructure.com/courses/276/assignments/2245
3. Open https://hypothesis.instructure.com/courses/258/assignments/2244
5. If you'd like to check instructor settings or the file in Canvas Files the instructor is in 1Password as "Canvas: Professor D"

**Expected behavior**
Being the same PDF and using the same Hypothesis install the assumption is that the files will work identically.

**Screenshots**
![image](https://user-images.githubusercontent.com/22603275/143278890-cf5902fe-9927-4df8-8aa5-4a6cc53d04d5.png)

![image](https://user-images.githubusercontent.com/22603275/143278910-b7c34db7-4801-44fc-be7c-e6c0043eea90.png)

**Desktop (please complete the following information):**
 - OS: macOS Big Sur 11.6
 - Browser: Chrome 96

**Additional context**
Original support ticket here: https://app.hubspot.com/contacts/6291320/ticket/672475811
The issue for this user was slightly different, but in trying to reproduce we discovered this issue

**Comment by chrisshaw** [comment]
@mattdricker @mkdir-washington-edu I'd like to get this fixed if we can figure out what the issue is. It seems like there's actually two issues mentioned: one where a student enrolled in two courses with the same file can't access one, and the other where groups is interfering somehow.

Which are we ultimately trying to fix? Did this issue go away on its own or is it still an outstanding issue for this student?

**Comment by mkdir-washington-edu** [comment]
@chrisshaw Coincidentally I think the school experiencing this issue wrote again at EOD today saying they're seeing it again.

I can try to divide this into two different repros, or even divide this into two issues if you prefer. I'll work on it tomorrow.

**Comment by mkdir-washington-edu** [comment]
@chrisshaw Ok, so there are two issues; the one the partner school is experiencing I haven't been able to reproduce. I can write it up in a different GH issue, but all I'll be able to do is articulate what the school is reporting to us.

The issue on this page **is** reproducible. I've spelled out the steps above and linked to assignments where you can see the error in action. It is still happening. My thought was that investigating this issue might also lead us to finding the partner school's problem as well.

Would you like me to write up a second issue for the school knowing I can't reproduce it?

**Comment by chrisshaw** [comment]
@mkdir-washington-edu thanks. I do think we should keep this focused. How about we move the unreproducible school issue to a Q&A Discussion with a bug label for now. That way we can use the voting to track incidents and collect additional data about it should it come up again. Then we can refer to that Discussion here in a comment. But otherwise let's keep this focused on solving the reproducible bug.

**Comment by mkdir-washington-edu** [comment]
1. Log in as jeremydean+teacher@hypothes.is
2. Go to course https://hypothesis.instructure.com/courses/258
3. Go to course files and click on Bradstreet_Verses upon the Burning of our House.pdf
4. Confirm this is file # 795 and that it is published. You can also see file at https://hypothesis.instructure.com/courses/258/files?preview=795
5. Create a new assignment using this file, note in the launch URL we are pointing at file 795
6. Log in as jeremydean+student2@hypothes.is
7. Access new assignment
8. See error.

@seanh

**Comment by mkdir-washington-edu** [comment]
This was bothering me and I wanted to look at it again. I can reliably reproduce it, but only in the linked course and only with that file.

It turns out that PDF, while set to Published in Canvas Files, is also referenced in an unpublished Module, which somehow then blocks us from using it (I'm like 99% sure). You can see it if you log in with the student account in step 6, and then view the file in Canvas files as that student. Even though the file is published you'll get a Canvas error message.

So I need to go back to the drawing board tomorrow, likely close this issue, and then go back to trying to replicate the original user issue. But I want to check it one more time tomorrow before doing so.

**Comment by chrisshaw** [comment]
@mkdir-washington-edu any news on this one?

**Comment by chrisshaw** [comment]
Can't reproduce. We'll close this until we encounter it again.
