### ISSUE TITLE
[Bug] Markdown table not rendered correctly

### ISSUE THREAD

**Issue by kael** [hypothesis/product-backlog#1295]
**Describe the bug**
Markdown tables are not rendered correctly on the website.

* On [web pages](https://hypothes.is/users/kael?q=https://github.com/ldodds/schema-icons), markdown tables are rendered as non-parsed HTML.
![Screenshot 2021-12-16 at 09-23-04 Hypothesis](https://user-images.githubusercontent.com/2463/146336220-e5f60f49-d3b2-4d2f-bdb3-677b3982aec5.png)

* On [annotation pages](https://hypothes.is/a/M-qHQl5EEey055Nz3Jc3Tg) and on [bookmarklet sidebar](https://hyp.is/M-qHQl5EEey055Nz3Jc3Tg/github.com/ldodds/schema-icons), markdown tables are rendered as non-parsed markdown. 
![Screenshot 2021-12-16 at 09-28-01 Annotation by kael hypothes is on GitHub - ldodds schema-icons Mapping schema org types t](https://user-images.githubusercontent.com/2463/146336250-8dfb2713-1877-4430-81a4-06ea1b685d3d.png)

**To Reproduce**
[Annotation Example](https://api.hypothes.is/api/annotations/M-qHQl5EEey055Nz3Jc3Tg)

**Comment by jon-betts** [comment]
We don't support tables at the moment, but we certainly shouldn't be mangling them or be inconsistent.

The mangled HTML is a consequence of the Markdown library we are using `mistune`. We are in the process of removing it, and when it's gone I don't think this is going to happen. The tables won't be rendered, but at least they will be somewhat readable unlike now, and should be the same in all places.

There's no automatic fix for users, but if they edit and re-save the annotation after we deploy the change it should update and fix it.

The relevant ticket is:

 * https://github.com/hypothesis/h/pull/7275

We can enable table rendering if we choose to in the backend, but there's not much point until the client supports it. When we do though it should be easy: https://python-markdown.github.io/extensions/tables/

**Comment by jon-betts** [comment]
The above replacement has gone through, so are rendering should at least be the same now. This should show the raw text for tables, as they aren't part of the core Markdown spec (they're an extension).

To "fix" the annotation you can edit and save it again. This will remove the encoded HTML from the presented string.
