### ISSUE TITLE
Certain YT videos are not working in the docdrop YT annotator

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1298]
### Steps to reproduce
1. Visit https://docdrop.org/
2. Paste https://www.youtube.com/watch?v=8rBfWe58zy8
3. See error.

From @bumper314:
> Hey Dan, thank you for http://docdrop.org, but for the past few days, I haven't been able to get it to work with YouTube videos anymore, even videos that  worked before.  It just says "Our video annotation capability works for public YouTube videos that have either human or machine-generated transcripts."  Example video https://www.youtube.com/watch?v=8rBfWe58zy8

### Expected behaviour
For embeddable videos (and others?) the video should appear in docdrop, with annotations enabled over the visible text.

### Additional details
Slack: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1642272492165400
Embedding is turned on for this video, though I note monetization is also on.

Also may be related to https://github.com/hypothesis/product-backlog/issues/1297

**Comment by robertknight** [comment]
Video transcript annotation has now been implemented in Via. The example video at https://www.youtube.com/watch?v=8rBfWe58zy8 works there: https://via.hypothes.is/https://www.youtube.com/watch?v=8rBfWe58zy8
