### ISSUE TITLE
Remove leading "www." from domain names shown on activity pages

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#130]
Suggestion from a user: when a domain name "www.youtube.com" is shown in the left-hand column on activity pages, just show "youtube.com" instead.

* Consistent with how we render domain names in some other places (apparently)
* Not repeating www. lots of times
* Save horizontal space for rest of domain name

https://hypothesis.zendesk.com/agent/tickets/849

![annotation_domain_name](https://cloud.githubusercontent.com/assets/22498/21856668/b2272332-d81a-11e6-8bcb-3cb60dc2e9d5.jpg)

**Comment by klemay** [comment]
I added the accessibility tag because this affects the experience of users who use screen readers.

**Comment by ajpeddakotla** [comment]
Closing this one in favor of https://github.com/hypothesis/product-backlog/issues/49. If we implement #49 we won't need to worry about this.
