### ISSUE TITLE
Enable Blackboard Groups for all application instances that have Blackboard Files enabled

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1300]
**As an admin, I don't want to have to reach out to support to get new features.**

Bulk turn on Blackboard Groups for all app instances that already have Blackboard Files on.

So far we've only had ~30 schools turn on Groups, with the largest group set being 10 groups. We've heard not complaints from users about errors from the feature. This makes sense as so few are using it. Given nothing has exploded, at this point, we should go ahead and turn it on for everyone who could use it (people who have already enabled Files). This will hopefully increase usage, and we shouldn't have that many more schools anyway (given BBG represents < 30% of all schools).

**Comment by seanh** [comment]
I think this probably doesn't require any code changes. It probably involves looking in the LMS production DB in Metabase to find all the application instances that have Blackboard Files enabled and then using the LMS app's admin pages to manually enabled Blackboard Groups for each one of these application instances.

**Comment by chrisshaw** [comment]
@seanh The idea was to avoid having to do this from the frontend given how tedious it is.

But there are only 33 of these schools by my query, so (assuming I'm right) I'll just do this as you said.

Check my query will you?

```
    select
        ai.tool_consumer_instance_name app_name
        , ai.id app_id
        , ai.consumer_key
        , ai.settings
        , ai.tool_consumer_instance_guid
        , ai.lms_url
        , ai.tool_consumer_info_version
        , ai.requesters_email
        , ai.tool_consumer_instance_contact_email
    from
        application_instances ai
    where
        ai.settings -> 'blackboard' ->> 'files_enabled' = 'true'
        and (
            ai.settings -> 'blackboard' ->> 'groups_enabled' is null
            or ai.settings -> 'blackboard' ->> 'groups_enabled' = 'false'
        )
```

**Comment by seanh** [comment]
Query looks good to me
