### ISSUE TITLE
Fix regression on hide/unhide moderation buttons

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1306]
### Steps to reproduce
1. As a group moderator, flag an annotation
2. See hide/unhide buttons

### Expected behaviour
Make them more [button-y](https://hypothes-is.slack.com/archives/C2BLQDKHA/p1643377103570649?thread_ts=1643376620.437289&cid=C2BLQDKHA).

### Actual behaviour
![image](https://user-images.githubusercontent.com/22603275/151558393-4f4e2ec2-0c98-44d5-b77b-b7dc770bd208.png)

**Comment by lyzadanger** [comment]
What do you think about updating the interface to look like this?

![image](https://user-images.githubusercontent.com/439947/151993364-32b9da81-846d-4bd6-87e5-701ed5abe901.png)

![image](https://user-images.githubusercontent.com/439947/151993408-2aadf316-c628-4649-8e30-9841c22233b6.png)

![image](https://user-images.githubusercontent.com/439947/151993477-5c969629-be8a-41dc-a3ce-bb4e9701047a.png)

![image](https://user-images.githubusercontent.com/439947/151993534-ce5980f8-3420-47ef-b704-a680331073dd.png)

A few words about this.

The `ModerationBanner` implementation has long been a thorn in our sides. It relies/relied on pixel-math complex absolute positioning and sizing and as you can see from the screenshot in the issue description, the math was already breaking down.  There are a lot more improvements we can make here and I don't want to portray the suggested changes here as a fix-all, but they will:

* Eliminate the fragility and dimensional brokenness of the interface
* Use more standard, cleaner component patterns without introducing too much newness
* Hopefully be clearer for users?

We could easily make an entire project out of just making this feature's UI better. I'm hoping I can position this change somewhere between the "fix the absolute minimum" and "go full-hog on re-doing this feature" spot such that it hits the sweet spot for the moment.

**Comment by chrisshaw** [comment]
@lyzadanger I appreciate the move to a cleaner (dare I say more modern) design language. A couple comments:

- I think my eyes are just playing tricks on me but: is there a border around that red block that's pushing it out of alignment with the edge of the annotation card?
- Is that an acceptably accessible contrast for those gray text, gray button, on the gray background buttons?

**Comment by lyzadanger** [comment]
@chrisshaw Thanks for the feedback!

* On contrast, we're good: 5.46:1 in that case.
* I see what's bugging you about that alignment. It's technically perfectly aligned but, zoomed in like we are in these screen grabs, it looks a little misaligned with the adjacent border. I'll see if there is a way to alleviate the optical oddity.
