### ISSUE TITLE
Markdown-styled scrollable code blocks do not render properly in annotation card

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1315]
## Bug report form
As reported by user: https://app.hubspot.com/contacts/6291320/ticket/766559332/
### Steps to reproduce
1. Select text to annotate
2. In editor, type 4 (or more) leading spaces before long-winded note
3. Click the Preview to see rendering

### Expected behaviour
Scrollable code block should render in a way that doesn't interfere with existing styling constraints. Note following example in GitHib, where the scrollable block is contained within the window, and a scrollbar is provided.
<img width="887" alt="Screen Shot 2022-02-07 at 12 13 30 PM" src="https://user-images.githubusercontent.com/71603629/152838141-3865105b-f724-45b9-b6ac-4b4c17c08138.png">

### Actual behaviour
Text that has 4 or more leading spaces in the Hypothesis editor renders spilling over the edge of the annotation card.

Example as typed in editor:
<img width="419" alt="Screen Shot 2022-02-07 at 10 11 18 AM" src="https://user-images.githubusercontent.com/71603629/152838824-dff8bc7e-9b06-4f5c-a3e6-b753f6fbead6.png">

Above example as rendered:
<img width="419" alt="Screen Shot 2022-02-07 at 10 11 30 AM" src="https://user-images.githubusercontent.com/71603629/152838926-9bb81818-efb3-40c2-b4ed-42de0fa185ff.png">

**Comment by chrisshaw** [comment]
We just closed a similar but not the same bug https://github.com/hypothesis/product-backlog/issues/1296
