### ISSUE TITLE
PDF.js changes affecting HTML page in Bookmarklet/Via

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1317]
See: https://github.com/hypothesis/product-backlog/issues/1270#issuecomment-1040000118

### Steps to reproduce
1. Visit https://musicbrainz.org/
2. enable bookmarklet
3. see font size increase

Also happens in Via.

Rob says:
>It looks like this relates to some PDF.js-specific changes that happen to be loaded in normal web pages as well. Two things we need to do here:
>
> 1. Not load the pdfjs-overrides.css file outside of PDF.js (see Only load PDF.js style overrides in PDF.js client#4224)
> 2. Continue looking for solutions to the adder REM-sizing issue that don't affect the host page.

### Additional details
Support ticket: https://app.hubspot.com/contacts/6291320/ticket/778913126/

**Comment by robertknight** [comment]
This was fixed by https://github.com/hypothesis/client/pull/4224. The second of the two solutions I mentioned above is something we still need to look into:

> Continue looking for solutions to the adder REM-sizing issue that don't affect the host page.
