### ISSUE TITLE
Let Canvas teachers grade faster with speedgrader

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1321]
**As a grader, I want Canvas Speedgrader to work like it does in other LMSs, without refreshing when I swtich students, so that I don't have to wait for it to load every time.**

Speedgrader reloads the document every time a grader switches students. Loading VitalSource is especially painful in Speedgrader because of how long it takes to load the reader every time. We've had both pilot teachers mention this. Beyond Speedgrader, we get comments like the following every so often: _"It's a little janky as a tool; it refreshes a lot making it hard for me to comment when grading."_

In other LMSs, where we use our homebrew grading bar, we don't do this. The goal is to replicate that behavior in Speedgrader.

## Flow

In Canvas

- I open Speedgrader for an assignment (let's say VitalSource) and wait for it to load. Then I submit a grade for one student
- I switch to the next student. **I don't have to wait for VitalSource to load.**
  - :construction:  If the new student annotations fails to load, handle it the same way it's handled in Blackboard
- I repeat the process with the next student

## Constraints

- I _think_ all other unhappy paths should stay the same. If not, handle errors the way we handle them now in Canvas.

**Comment by seanh** [comment]
Unfortunately the control for switching between users in SpeedGrader is part of Canvas, not part of Hypothesis, and it's Canvas not Hypothesis that does a full page reload of Hypothesis's iframe when you switch students. I'm not sure whether there's anything we can do about this one

**Comment by chrisshaw** [comment]
That does change things.

The alternative @robertknight brought up would be to give Canvas users access to our LMS grader as an alternative. This seems likely to send a bunch of users to support with a confusing user experience, as they're used to clicking on Speedgrader (unless we did something like a new placement with a grading "app" for teachers). But it's worth a user test.

To start with, I'll do some digging to see if others have complained about this, and then engage Canvas. You'd wonder why that doesn't send something like a "student changed" event. Surely other apps don't want to reload every time.

But there's no product work at this time here.

Before I close this for now, @seanh, what would it look like to, say, cache these launches? Or something else we could do? Most of the waiting for VitalSource is in loading the VS reader... I have no idea how we could hydrate that. But I wonder if there's any major benefits to be gained even for other assignment types?

**Comment by robertknight** [comment]
> Surely other apps don't want to reload every time.

Reloading is crude but has the benefit of being the easiest thing for Canvas and the LTI tool (eg. us) to implement. If the document viewer is simple and effective caching is used, it could be good enough.

For web pages and PDFs there probably are things we could to speed up repeated launches of the same content in the same browser. PDFs being easier and web pages being, probably, a lot more complicated. I think it would be difficult to come anywhere close to the experience in non-Canvas LMSes though as long as a full reload is happening. VitalSource, and other cases where a third party hosts the content, are unfortunately outside of our control.

Engaging Canvas seems like a good move here.
