### ISSUE TITLE
Glitches in Blackboard Learn while in "Student Preview" mode

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1331]
Reported by user: https://app.hubspot.com/contacts/6291320/ticket/800442012/

## To reproduce
The behavior can be reproduced logging on to Hypothesis' Blackboard SaaS instance as "professor" and opening the course: Hypothesis 501.

Confirmed in Chrome 98 and Firefox 97.0.1

## Behavior

In Blackboard Learn Original (not Ultra), when an instructor enter Student Preview mode:
<img width="318" alt="Screen Shot 2022-03-02 at 3 37 32 PM" src="https://user-images.githubusercontent.com/71603629/156446307-f632e993-2f7e-491a-9ad2-830f53d5a3af.png">

Bb puts a large banner across the top of the page a visual reminder. Typically, the course breadcrumb navigation is shown below the banner, allowing the user to navigate as normal.
<img width="1278" alt="Screen Shot 2022-03-02 at 12 43 25 PM" src="https://user-images.githubusercontent.com/71603629/156453602-879e8c9a-0209-432d-98a1-360c2852bf37.png">

However, when a Hypothesis assignment is opened in Student Preview mode the breadcrumb navigation is gone, and you can see that the Hypothesis frame has covered up a bottom portion of the banner itself.
<img width="1278" alt="Screen Shot 2022-03-02 at 12 42 55 PM" src="https://user-images.githubusercontent.com/71603629/156454284-591b9c84-01b5-4438-a4d9-b62cd9393731.png">

Furthermore, if the Settings or Exit Preview buttons are clicked, their respective modal windows are displayed severely cropped. One can close the modals, but that loads what appears to be a Bb 404 page in the banner frame. The same thing occurs in the Exit Preview modal, where you can scroll to find the Exit button, but clicking it does not end Preview Mode. Instead, the same 404 page is displayed.
<img width="1280" alt="Screen Shot 2022-03-02 at 3 48 54 PM" src="https://user-images.githubusercontent.com/71603629/156448211-c4c05acc-8c55-4c3e-bea5-4f3387edd146.png">

<img width="1280" alt="Screen Shot 2022-03-02 at 3 47 52 PM" src="https://user-images.githubusercontent.com/71603629/156447988-302b4ea4-084f-4944-a58a-6648206a6823.png">

In all cases, to navigate away from the Hypothesis assignment, the instructor must either click the blue 'x' icon at the upper left of the frame to exit out of the course altogether, or click the browser back button several times to return to an interior Bb course page.

**Comment by lyzadanger** [comment]
The styling and positioning of the student-preview banner and the (cut-off) modal dialog are within `iframe` elements that are outside of anything that we "touch". This interface, that is, lives fully outside of any Hypothesis integration/content.

That doesn't mean that _something_ we're doing isn't a catalyst here, but it leads me to cast a thoughtful eye. One thing that would be quite helpful:

Can anyone find an integration (i.e. non-Hypothesis) that _doesn't_ have a broken layout in student-preview mode? i.e. can someone find an example of an assignment in which this looks _correct_? That would help us track down if there's something we're potentially doing that would be causing this.

**Comment by chrisshaw** [comment]
This is not a problem with Hypothesis. It is a problem with Blackboard Learn's handling of LTI tools. I've tried with both the dummy LTI app and a third-party test app (Piazza) and both have the same problem.

https://user-images.githubusercontent.com/2966918/159750220-d96f948b-377c-480c-a04d-e9d6663ac09c.mp4


https://user-images.githubusercontent.com/2966918/159750222-f526c220-169d-400f-9b05-7195d766669e.mp4


I'll report this to Blackboard.
