### ISSUE TITLE
PDF ToC appears broken when Viewed in Safari (12-15 at least)

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1340]
### Steps to reproduce
1. In Safari, open https://arxiv.org/pdf/1606.02960.pdf
2. In Safari, open https://via.hypothes.is/https://arxiv.org/pdf/1606.02960.pdf (see error)
3. For comparison, do the same in other browsers.

### Expected behaviour
We would expect to see the PDF ToC look like it does in Chrome and FF when served up in Via:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1651096786442219?thread_ts=1651092919.551759&channel=C2BLQDKHA&message_ts=1651096786.442219

Instead of how it looks in Safari when served up in Via:
https://hypothes-is.slack.com/archives/C2BLQDKHA/p1651093201487409?thread_ts=1651092919.551759&channel=C2BLQDKHA&message_ts=1651093201.487409

### Actual behaviour
See Slack thread for pics: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1651092919551759

### Browser/system information
Safari 15

**Comment by robertknight** [comment]
Looks correct to me in Safari 15.4. Which Safari 15.x release were you testing in @mkdir-washington-edu?

**Comment by mkdir-washington-edu** [comment]
@robertknight I've checked again, using two different computers.
I can **not** replicate on:
- macOS Big Sur 11.6.5
- Safari 15.4

I **can** replicate on:
- mac OS Big Sur 11.6.3
- Safari 15.0

I don't see other obvious differences between the two (no extensions installed in either version of Safari, for example).

**Comment by chrisshaw** [comment]
The investigation seems to reveal this is a browser regression that they fix in later updates. I would recommend we tell this user to upgrade their Safari browser (or request and wait for the update, if this is controlled by their IT department). < 0.25% of users are on this browser.
