### ISSUE TITLE
[client] Accessibility: Announce the annotation I'm deleting

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1342]
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified of the steps as I delete an annotation, so that I can more quickly make and remove annotations as I engage in discussions.**

In an accessibility review, the reviewer considered it a critical defect that the user using JAWS did not know what annotation they were deleting or that they had deleted it. We also received similar feedback from our recent WCAG audit:

> To improve accessibility further, an aria-describedby attribute can be added to the edit, reply, and delete buttons and associate them with the annotation as well.

## Related

Related to #1341 

Related to #1343

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Know what annotation I'm deleting](https://app.harvestr.io/components/0/list/uqU1y0sSH)

**Comment by lyzadanger** [comment]
Reviewed: Sounds like we need to add `aria-` attributes as delineated here to action buttons in the `Annotation` card's footer.

**Comment by lyzadanger** [comment]
Oh, I don't think the dependency cited in the description is accurate.

**Comment by lyzadanger** [comment]
Please see https://github.com/hypothesis/product-backlog/issues/1344#issuecomment-1168694871 for recent contextual improvements to this area.
