### ISSUE TITLE
[client] Accessibility: Announce when I save an annotation

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1345]
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified when I save an annotation, so that I can move on confidently to engage in discussions more quickly.**

A reviewer in an accessibility review considered it a major defect that, upon saving an annotation, the user would not know anything actually happened:

> Did not hear a confirmation that the highlight or annotation was saved.
> 
> Provide a confirmation message.
> 
> Major

## Related

Related to https://github.com/hypothesis/product-backlog/issues/1344

Related to #1346

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Hear announcements when I save annotations](https://app.harvestr.io/components/0/list/9VBzYJ1OT)

**Comment by lyzadanger** [comment]
See proposed approach for #1343
