### ISSUE TITLE
[client] Accessibility: Announce when I save a highlight

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1346]
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified when I save a highlight, so I can move on confidently to engage in discussions more quickly.**

From our recent WCAG audit:

> The flow for creating annotations shifts focus into an annotation text input, and a button is pressed in order to create an annotation, setting up an expectation. In contrast, when text is highlighted, users who rely on a keyboard press a single character shortcut and the only feedback is the visual highlight of the text on the page. A status message that informs screen reader and braille display users that text has been highlighted would be beneficial.
> 
> ### Recommendation for announcing highlights
> Consider adding a status message (this could be for screen reader users only and may not be visible on the page) that confirms that text has been highlighted. If possible indicate which text has been highlighted, for example “ ‘The average life span of various Grimpoteuthis species is 3 to 5 years’ has been highlighted”

<details>
<summary>This also came up in a recent accessibility review</summary>

> H key to generate a highlight worked, but there was no spoken confirmation for the screen reader user.
> 
> Screen reader users should hear a confirmation that text has been highlighted.
> 
> Major

</details>

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Hear announcements when I save highlights](https://app.harvestr.io/components/0/list/iLPUZYpyL)

**Comment by lyzadanger** [comment]
I'd initially suggest trying the same approach proposed for #1343 (visually-hidden toast message using `aria-live`). If that is not successful, we can try something else.
