### ISSUE TITLE
[client] Accessibility: Announce the annotation I'm replying to

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1347]
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified of the annotation I'm replying to, so that I can add a reply more quickly while engaging in discussions.**

https://github.com/hypothesis/product-backlog/issues/1341, https://github.com/hypothesis/product-backlog/issues/1344, and #1351  recommend describing the content of the _document_ a user is commenting on, which makes sense for the editor of a root annotation.

For buttons, however, the most pertinent content is the annotation content.

> To improve accessibility further, an aria-describedby attribute can be added to the edit, reply, and delete buttons and associate them with the annotation as well.

**But,** when the editor opens, the content we're "annotating" is actually the **parent annotation.** So, for replies, we want to describe the annotation content of the parent, not the parent annotation's highlighted content.

## Related

Related to https://github.com/hypothesis/product-backlog/issues/1341

Related to https://github.com/hypothesis/product-backlog/issues/1344

Related to #1351

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Hear announcement when I save a reply](https://app.harvestr.io/components/0/list/F0PyPexGW)

**Comment by lyzadanger** [comment]
@chrisshaw Sorry, I don't understand this one. What does "I want to be notified of the comment I'm replying to" mean? When?

**Comment by chrisshaw** [comment]
@lyzadanger I tried updating the description to be a little more clear. I was trying to make a distinction between the flow for a root annotation and a reply. This boils down to:

- Make the button do what all the other action buttons do
- Unlike what happens with the edit button, rather than use the highlighted content in the editor, use the parent annotation content

**Comment by lyzadanger** [comment]
I grok the core gist of this now: content associated with a reply is the parent annotation's content, not the annotation target (highlighted/selected text). As with the "edit" variant of this, I'm a little uncertain of exactly what a user would want their screen reader to read for them: the entire associated content? That could be long...I'll have to look at this in more depth...

**Comment by chrisshaw** [comment]
I was thinking just straight dumb entire content, but yeah, I'm worried about the UX. My thought, though, was that users can cut that off themselves. Additionally, we could clean it up in a future iteration and meanwhile the full content would be "right" and better than what we give now. But open to ideas.

**Comment by lyzadanger** [comment]
Please see https://github.com/hypothesis/product-backlog/issues/1344#issuecomment-1168694871 for recent contextual improvements to this area.
