### ISSUE TITLE
[client] Accessibility: Announce the annotation I'm editing

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1351]
**As a user using assistive technologies like NVDA, JAWS, or VoiceOver, I want to be notified of the steps as I edit an annotation, so that I can more quickly make and remove annotations as I engage in discussions.**

In an accessibility review, the reviewer considered it a major defect that the user using JAWS did not know what annotation they were editing. We also received similar feedback from our recent WCAG audit:

> To improve accessibility further, an aria-describedby attribute can be added to the edit, reply, and delete buttons and associate them with the annotation as well.

After pressing the editor button and the opens, it should work the same was as described in https://github.com/hypothesis/product-backlog/issues/1344.

## Related

Related to #1341 

Related to #1343 

Related to #1344

**Comment by MercanAda** [comment]
I have a problem with all type accounts. Someone controlling all my mobile and pc accounts.

**Comment by chrisshaw** [comment]
**Issue was linked to Harvestr Discovery:**  [Know what annotation I'm editing](https://app.harvestr.io/components/0/list/ddEYBCOeN)

**Comment by lyzadanger** [comment]
Please see https://github.com/hypothesis/product-backlog/issues/1344#issuecomment-1168694871 for recent contextual improvements in this area.

**Comment by MercanAda** [comment]
Could you please block this client  migration or audit. And does it possible to choose to assignments for authorization?
