### ISSUE TITLE
Show JSTOR document metadata when teachers configure assignments

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1354]
We have new APIs from JSTOR. Let's use them now for creating assignments.

## Flow

As an instructor...

- I grab a stable URL and open the assignment creation form
- [x] When I submit the JSTOR url, I view the thumbnail
- [x] Instead of "a JSTOR article," I see the title, author, publication title, issue, and publisher. This is meant to align with the metadata that JSTOR shows.
  - _Update 2022-06-14_: Partially complete. We show the title but not other metadata_
  - _Update 2022-08-24_: This has been deferred. Since the ticket was originally specced we made some other design changes to the dialog (added terms and conditions, increased thumbnail size) which reduce the amount of space we have for other data.

 

## Constraints

- [x] Prior to building, we need to ensure the new metadata endpoint actually works, e.g.,
  - we get the expected response with the needed fields (e.g., thumbnail url, etc)
  - when we call for the thumbnail we get the image

## Related

- [x] We also need to handle when they don't have access to it (_Update 2022-06-14_: This is not applicable, the metadata endpoint doesn't tell us whether we have access or not)

**Comment by robertknight** [comment]
See links in https://hypothes-is.slack.com/archives/C02T75RKBTK/p1651073373706719 for details of API endpoints for metadata and thumbnails, including links to an API directory.

**Comment by robertknight** [comment]
The initial fetch and display of the title and thumbnail is done. Not all of the other information mentioned ("I see the title, author, publication title, issue, and publisher.") was available. We'll need to revisit this. See https://github.com/hypothesis/lms/issues/4049. 

There are some in-flight pull requests to deal with issues that were encountered along the way:

- https://github.com/hypothesis/lms/pull/4076
- https://github.com/hypothesis/lms/pull/4078
- https://github.com/hypothesis/lms/pull/4079

There is a minor cosmetic issue tracked with icon alignment tracked in https://github.com/hypothesis/lms/issues/4060.

Additionally there are issues with:

- A 500 error when fetching thumbnails for book chapters. See https://hypothes-is.slack.com/archives/C02T75RKBTK/p1655121850684739 and https://hypothes-is.slack.com/archives/C02T75RKBTK/p1655126622579989
- Resolving an issue where the metadata returned for some articles/book chapters does not have a title field but instead a `tb` (Title of Book?) field. Our code currently complains about the missing title and presents an "External request failed" error to the user

**Comment by robertknight** [comment]
The 500 errors in the previous comment have been fixed. The only remaining issue is to make a decision on whether to show fields other than the title in the picker. We may not want to do this because we are quite space constrained:

<img width="826" alt="Canvas JSTOR picker" src="https://user-images.githubusercontent.com/2458/182600219-4c60b351-cecc-4e0b-8cf8-4fbdafbcffc9.png">

The limited space here I believe is due to an unfortunate decision that was made a long time ago about the size hint we give to Canvas for this dialog. From what I can recall we could increase this for new installs, but it would remain in the configuration for existing installs.

**Comment by robertknight** [comment]
We're going to stick with just displaying the title for the time being, for the reasons mentioned in the previous comment. If we find situations where the current thumbnail + title combination is not enough to be useful, we might have to revisit this.
