### ISSUE TITLE
Via errors on previously working assignment URL

### ISSUE THREAD

**Issue by chrisshaw** [hypothesis/product-backlog#1362]
_Originally posted by @mkdir-washington-edu in https://github.com/hypothesis/product-backlog/issues/1270#issuecomment-1127747325_

URL: https://writingspaces.org/

The user reports that the URL worked as of April 4, but now (as of May 16) Via gives the following error:

> Via Error
> https://writingspaces.org/?via.client.ignoreOtherConfiguration=1&via.client.openSidebar=1&via.external_link_mode=new-tab
> 
> Error Details:
> 
> {'args': {'coll': 'proxy', 'type': 'replay', 'index': '$live', 'templates': {'banner': 'templates/banner.rewriter', 'error': 'templates/error.rewriter', 'head_insert': 'templates/head_insert.rewriter', 'index': 'template/index.html', 'search': 'template/search.html', 'query': 'template/query.html'}}, 'error': '{"message": "https://writingspaces.org/", "errors": {"LiveWebLoader": "https://writingspaces.org/"}}'}

![image](https://user-images.githubusercontent.com/2966918/168653710-778479f2-9ee1-4049-a74e-cdc99640ed37.png)

## Notes

This could be due to changes to the third party website but because we've made changes to Via since then it was worth an investigation.

## Related

(optional) Slack convo: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1652709309801049

Support ticket: https://app.hubspot.com/contacts/6291320/ticket/911404893/

**Comment by mkdir-washington-edu** [comment]
Note that the site works correctly in Via now. I'm wondering if the site made some changes to their code and then pulled those changes back.
