### ISSUE TITLE
Students no longer see a friendly error message when PDF is unaccessible in Canvas

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1368]
### Steps to reproduce
1. Create an assignment in Canvas using a PDF stored in Canvas Files.
2. Make that PDF unavailable, e.g. unpublish, set availability date to the past, etc. (Do not delete, that generates a different error.)
 * See: https://hypothesis.instructure.com/courses/125/assignments/1371
4. Log on a student and open the assignment.

### Expected behaviour
Student should receive the following error message written in friendly text:
```
Hypothesis couldn't get the assignment's file from Canvas.

You might not have permission to read the file in Canvas. This could be because:

* The file is marked as Unpublished in Canvas: an instructor needs to publish the file.
* This course was copied from another course: an instructor needs to edit this assignment and re-select the file.

If the problem persists, you can open a support ticket or visit our help documents.
```
![student-error-message](https://user-images.githubusercontent.com/71603629/174145304-24523800-3111-4a0e-a444-6ce013c571b5.png)

### Actual behaviour
Student instead receives the following, non-friendly error message:
```
Something went wrong

Calling the Canvas API failed.

If the problem persists, you can open a support ticket or visit our help documents.

Error Details
{
  "request": {
    "method": "GET",
    "url": "https://hypothesis.instructure.com/api/v1/files/1281/public_url"
  },
  "response": {
    "status_code": 403,
    "reason": "Forbidden"
  },
  "validation_errors": null
}
```
<img width="580" alt="Screen Shot 2022-06-16 at 2 50 10 PM" src="https://user-images.githubusercontent.com/71603629/174145404-aa12400e-04e9-4b50-abfc-c548e9411c95.png">

### Additional details
[This change on 06/13/2022](https://community.canvaslms.com/t5/Canvas-Change-Log/2022-API-Change-Log/ta-p/509738) in the Canvas API response code from 401 to 403 seems a likely culprit:

> An unauthorized response from the JSON API will return a 403 (Forbidden) instead of a 401 code, to be more in line with HTTP standards. Additionally, localization of the “status” field in unauthenticated or unauthorized JSON errors is deprecated; the status will always be given in English.

**Comment by mattdricker** [comment]
See also [this discussion about improving the text of the friendly message](https://github.com/hypothesis/product-backlog/discussions/1324).

**Comment by jon-betts** [comment]
The 401 to 403 change seems very likely. This would break this location:

 * https://github.com/hypothesis/lms/blob/main/lms/services/exceptions.py#L214
 
I'm not sure if there are other places. We might have to do some digging to make sure we don't enable this message when it's not appropriate.

**Comment by jon-betts** [comment]
I think this is done now
