### ISSUE TITLE
Automatically fix course-copied Blackboard Groups assignments whenever possible

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1390]
When we create a launch URL for a Blackboard Groups assignment we include data about the Group Set the teacher chose (e.g. “group_set=135”). Like Files, Blackboard seems to assignment a number to each Group Set across the whole Canvas instance, and a copied assignment has a launch URL that references a group set in the old course.

We should look for a way to make sure that copied Groups assignments can still work, and give useful error messages when we don’t. When you copy a Blackboard course you do not copy over existing Group Sets or Groups, so any solution is likely to have work to do on the user's side, such as requiring that they build new Group Sets with the same names as the old Groups Sets.

To reproduce:

1. Create a Groups assignment in a Blackboard course. Note the Group Set ID in the launch URL.
2. Copy the course and create new Group Sets.
3. Launch the copied assignment. Note that the Group Set ID has remained the same.
4. Create a new Groups assignment in the new course and note that the Group Set ID is different (even if the Group Set name, etc., is the same).

**Comment by marcospri** [comment]
This is now fixed.
