### ISSUE TITLE
LTI 1.3 LMS admin user unable to create new assignment

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1394]
## Bug report form
This was discovered during new customer LTI 1.3 installation https://app.hubspot.com/contacts/6291320/ticket/1141169715
### Steps to reproduce
1. Log on to an LMS with a global LMS admin account
2. Create a new course, or visit and existing course where the admin account is NOT enrolled as a teacher
3. Create a new LTI 1.3 Hypothesis assignment, and launch. You will be presented with the "You are not authorized to view this page" error message.<img width="805" alt="Screen Shot 2022-10-10 at 10 07 56 AM" src="https://user-images.githubusercontent.com/71603629/194887148-63166472-2a33-44ba-ab25-4ff0ec6c9018.png">
4. Now enroll the admin user in the course with the role of "Teacher" or "Instructor", and create a new assignment as above. This will now launch successfully
5. Unenroll admin user from course, and the error returns.

### Additional details
This behavior differs from LTI 1.1, where an LMS admin user CAN successfully create a new assignment without being enrolled with the instructor role.

**Comment by marcospri** [comment]
In canvas:

1.1 roles: 

```
urn:lti:instrole:ims/lis/Administrator
urn:lti:instrole:ims/lis/Instructor
urn:lti:instrole:ims/lis/Student
urn:lti:role:ims/lis/Instructor
urn:lti:sysrole:ims/lis/User
```

1.3 roles

```
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Administrator",
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Instructor",
"http://purl.imsglobal.org/vocab/lis/v2/institution/person#Student",
"http://purl.imsglobal.org/vocab/lis/v2/system/person#User"
```

This is likely a result of fixing https://github.com/hypothesis/lms/issues/4411 in 1.3 (so institutional roles don't interfere with course level ones) but admin should be special cased as is always a institutional one.

**Comment by chrisdaaz** [comment]
email the creator of this ticket once fixed: https://app.hubspot.com/contacts/6291320/ticket/1155111311

**Comment by mkdir-washington-edu** [comment]
new ticket: https://app.hubspot.com/contacts/6291320/ticket/1258803272

**Comment by marcospri** [comment]
Should be fixed now that https://github.com/hypothesis/lms/pull/4658 is deployed

**Comment by mattdricker** [comment]
Original user emailed: https://app.hubspot.com/contacts/6291320/ticket/1141169715

**Comment by chrisdaaz** [comment]
Another user interested in this bug has been emailed: https://app.hubspot.com/contacts/6291320/ticket/1155111311

**Comment by chrisdaaz** [comment]
Thank you!
