### ISSUE TITLE
Some Open Access JSTOR texts are not loading in the LMS app

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1397]
## Bug report form
Links that don't work in the LMS app:
- Open Access book chapter: https://www.jstor.org/stable/j.ctt24h9fn.14
- Open Access Serial: https://www.jstor.org/stable/community.28034010

Slack convo: https://hypothes-is.slack.com/archives/C02T75RKBTK/p1665682025299599

It's not clear if we think Serials and book chapters **should** work in the Hypothesis/JSTOR integration. For comparison, these Open Access links **do** work:
- Open access journal: https://www.jstor.org/stable/20027847
- Free journal: https://www.jstor.org/stable/44674956

### Steps to reproduce
1. Log into the account in JSTOR
2. Access either of the "links that don't work" above, confirm you have access
3. In the LMS app, in the JSTOR integration, use either of the "links that don't work" from above
4. See errors:
<img width="826" alt="image" src="https://user-images.githubusercontent.com/22603275/195672614-0404e5a2-945c-45b1-aca2-f43708bca2e7.png">

<img width="921" alt="image" src="https://user-images.githubusercontent.com/22603275/195672696-f62a6309-b843-4bd6-9159-af8acd2ca16a.png">

### Expected behaviour
If this behavior is expected it might be worth seeing if we can customize the error message in these situations to differentiate between a text your **institution** can't access vs a text we're not allowed to load regardless of institution access.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.

MacOS Big Sur 11.6.5
Chrome 106

**Comment by mkdir-washington-edu** [comment]
Ticket once this is resolved: https://app.hubspot.com/contacts/6291320/ticket/1148202006

**Comment by robertknight** [comment]
For the two cases in the description that don't work JSTOR `/metadata/{doi}` ([docs](https://labs.jstor.org/api/anno/docs#/default/metadata_metadata__doi__get)) is returning a response that contains:

```json
"requestor_access_level": "preview_access"
```

The LMS instance I am using for testing is associated with the JSTOR site code "hypothes.is".

I started a Slack thread with the JSTOR devs to discuss: https://hypothes-is.slack.com/archives/C02T75RKBTK/p1666105218319929

Other cases:

10.7249/mg876rc.10 (Book chapter)
10.7249/mg876rc (Book)
10.2307/community.22669911 (Primary source image)
10.2307/community.30528851 (Primary source book)

**Comment by robertknight** [comment]
This has been resolved on JSTOR's side. See https://hypothes-is.slack.com/archives/C02T75RKBTK/p1666113938922479?thread_ts=1666105218.319929&cid=C02T75RKBTK.
