### ISSUE TITLE
Error when using Canvas Speedgrader with JSTOR docs

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1408]
### Steps to reproduce
1. In Canvas, create a JSTOR assignment
   - Example assignment: https://hypothesis.instructure.com/courses/258/assignments/3847
3. Logged in (or masquerading) as a student, add at least one annotation
4. Back as the instructor, open the assignment in Speedgrader and attempt to filter on the student
    - Example: https://hypothesis.instructure.com/courses/258/gradebook/speed_grader?assignment_id=3847&student_id=947

### Expected behaviour
Speedgrader should open with JSTOR document loaded and the sidebar filtering on the selected student's annotations

### Actual behaviour
Via throws an error message trying to load the JSTOR doc:
`BadURL: No connection adapters were found for 'jstor://2140238'
URL: https://lms-via.hypothes.is/route?via.client.ignoreOtherConfiguration=1&via.client.openSidebar=1&via.external_link_mode=new-tab&via.client.requestConfigFromFrame.origin=https%3A%2F%2Flms.hypothes.is&via.client.requestConfigFromFrame.ancestorLevel=2&via.blocked_for=lms&url=jstor%253A%252F%252F2140238&via.sec=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJoIjoiSE1yS0k5Z051MXlVOUxyTm5pU0ciLCJleHAiOjE2Njk4MzQ4MDB9.OLeCcTBTXbJGIZsYBHS0IIrplnGdg-eNEjqwz2cc0Is
Third party URL: jstor://2140238`
<img width="1280" alt="Screen Shot 2022-11-30 at 1 11 49 PM" src="https://user-images.githubusercontent.com/71603629/204875833-03c0c6e9-867d-41f4-bb4d-6b98c9457ffd.png">

### Browser/system information
MacOS 12.6.1 Chrome 107

### Additional details
Tested with numerous JSTOR stable URLs. Assignment opens successfully for students and instructors outside of Speedgrader -- this appears to be a Speedgrader issue only.

No similar issues found in non-Canvas LMSes.

**Comment by jon-betts** [comment]
From what I can tell, this should be a "deep_linking" configured URL and pass through as `jstor://` here:

 * https://github.com/hypothesis/lms/blob/main/lms/services/document_url.py#L38
 
Which should result in a configured Launch here:

 * https://github.com/hypothesis/lms/blob/main/lms/views/lti/basic_launch.py#L61
 
Which ends up translating the URL here:

 * https://github.com/hypothesis/lms/blob/main/lms/resources/_js_config/__init__.py#L95
 
This depends on `jstor_service.enabled and document_url.startswith("jstor://"):`

 * The document does start with `jstor://`
 * The service is enabled if:
   * JSTOR enabled AI setting is checked - Seems to be: https://lms.hypothes.is/admin/instance/id/4817/
   * JSTOR site code AI setting is present - Seems to be: https://lms.hypothes.is/admin/instance/id/4817/
   * `api_url` from environment `JSTOR_API_URL` is present (it must be for it to work in other context)

So I can't see right now what's wrong.
