### ISSUE TITLE
Speedgrader fails to load PDF when Hypothesis cannot find the student's group

### ISSUE THREAD

**Issue by chrisdaaz** [hypothesis/product-backlog#1415]
## Bug report form

_Please help us debug the following issue_. 

We received a [support ticket](https://app.hubspot.com/contacts/6291320/ticket/1382548075/) where an instructor gets a Hypothesis error while attempting to grade an assignment using Canvas SpeedGrader. 

_We are not able to reproduce this error. We met with the instructor and were unable to find a resolution. We learned that the original assignment was modified after it was discovered that the original PDF was not OCR'd._

### Steps to reproduce

This is the order of events from the instructor's point of view:

1. The instructor has the Teacher Role in the course
2. Create a group set for all students
3. Created a group Hypothesis assignment in Canvas using a PDF from Canvas files
4. Students annotated the document
5. Instructor can view the assignment in Hypothesis and see student annotations
6. Instructor cannot use Speedgrader to grade the assignment because the PDF will not load; we see an error

### Expected behaviour

The PDF file should load in speedgrader. 

### Actual behaviour

Hypothesis displays "(LMS Error) A problem occurred while handling this request. Hypothesis has been notified" in place of where the PDF should be in Canvas Speedgrader.

This is happening in more than one assignment for the instructor.

### Browser/system information

Mac and Google Chrome (latest version)

### Additional details

We tried the following things to resolve the issue, but none of them fixed the problem:

- Cleared browser cache
- Updated Chrome to latest version
- Checked for multiple installs of Hypothesis
- Reauthorized Hypothesis
- Checked user roles for students and instructor
- Checked group membership for students

The user sent us the HAR file from their browser in case it contains helpful debugging information. Here's [the link](https://drive.google.com/file/d/1UqqhaHzt-KPK-lthbqfVQGTeMRnY-f7j/view?usp=sharing).

Sentry has [logged an error here](https://sentry.io/organizations/hypothesis/issues/3885445215/?project=259908&query=&referrer=issue-stream&sort=freq&statsPeriod=14d).

### To Do

_from [slack discussion](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1674483627757469?thread_ts=1674252306.041259&cid=C4K6M7P5E):_
- fall back to just showing all of the groups (in the assignment's group set) when this happens
- show an error message explaining that we couldn't find the learner's group so we're showing them all so that the instructor can find the learner's group manually and get the grading done

**Comment by chrisdaaz** [comment]
@mattdricker feel free to take a look at this whenever you get a chance

**Comment by chrisdaaz** [comment]
see discussion: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1674252306041259

**Comment by marcospri** [comment]
Related exception in sentry: https://sentry.io/organizations/hypothesis/issues/3885445215/?project=259908&query=&referrer=issue-stream&sort=freq&statsPeriod=14d

**Comment by chrisdaaz** [comment]
this has been fixed and the original customer has been updated. they confirmed all is working :)
