### ISSUE TITLE
trying to access a Canvas Files assignment after a Due Date displays the Hypothesis Files error

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1419]
### Steps to reproduce
1. Log into Canvas as a student (example jeremydean+student2@hypothes.is - https://my.1password.com/vaults/5go274a5lhckc6djpf5zmemxxu/allitems/quz3lys7q3et4w5jrmamhb27mq)
2. Visit an assignment using Canvas Files where the due date has past (example: https://hypothesis.instructure.com/courses/534/assignments/4674)
3. See error
![image](https://user-images.githubusercontent.com/22603275/220193285-9d381e74-8328-41cc-aa2d-a17d9cf089fe.png)

### Why is this an issue
Students **can** make late submissions, so they need to be able to access the assignment after the due date.

### Browser/system information
Chrome 110
MacOS Big Sure 11.6.5

**Comment by marcospri** [comment]
I'm not sure what's going on here.

- In another course tried the same thing, canvas file, due date in the past. The student can access the file just fine.

- In this particular course if I login as a student and I get this error launching I also get an error while trying to get to the file using the UI https://hypothesis.instructure.com/courses/534/files?preview=2118


- I can however access other files in the course: https://hypothesis.instructure.com/courses/534/files?preview=2115


- Both the file and the assignment seem to be published.

- Temporarily removed the due date on the assignment, nothing changed.

**Comment by mkdir-washington-edu** [comment]
Thanks for looking at this! I think the best next steps are to remove this from the Support project board, close this issue, and open one where, when we have time, we try to figure out why this PDF behaves the way it does, since our users might run into similar problems.

**Comment by mkdir-washington-edu** [comment]
Hmm. I don't think this is just the PDF, since I downloaded that PDF, uploaded it to another course, and can't reproduce the error: https://hypothesis.instructure.com/courses/258/assignments/4688

I don't know what next steps I can take to make this issue clearer: https://github.com/hypothesis/product-backlog/issues/1420
