### ISSUE TITLE
Embed Internet Archive clips [SPIKE]

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#142]
### Problem you are trying to address with this feature

Right now Hypothesis supports embedding youtube and vimeo clips in annotation bodies.  Another organization has a powerful corpus of video content, the Internet Archive.  Their TV News archive continuously records and indexes a global set of over 60 news channels.  You can point into that archive with a link, like this one:
https://archive.org/details/MSNBCW_20161230_230000_MSNBC_Live/start/35.1/end/101

Which if reformulated, points more directly to a video player, like this:
https://archive.org/embed/MSNBCW_20161230_230000_MSNBC_Live?start=35.1&end=101

So lets see what it would take to let people embed internet archive videos along with youtube and vimeo.  This would enable people to annotate by embedding a video that is queued up right to a specific 10 second clip of someone saying something that relates to the annotation's target.

We should keep in mind that the folks at the archive are friends and might potentially be able to make minor tweaks on their end if that was helpful to us-- so keep that in mind.

**Comment by klemay** [comment]
Closing - it's done!
