### ISSUE TITLE
Screen reader does not move to Help text when the Help button is expanded

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1421]
This feedback comes out of Accessibility Web Audit from UC Berkeley.

### Current behavior
When the Help "?" button is selected the screen reader only announces the button as "expanded". The next navigation item is the user icon.

### Expected behavior
After clicking the Help button, the screen reader user expects the text of the expanded section to be read.

This is the feedback from the review:

> Screen reader user was confused after expanding the Help. The next thing heard was the Account button. The screen reader user expected to hear the text that was expanded.
>
>When expand/collapse widget is used, people will expect the next thing heard is what was just expanded.
>
> Better to have the header showing so it was a card that could be expanded and collapsed rather than a button that hides or shows.
> 
> Note: aria-controls is not supported by VoiceOver or NVDA.

**Comment by lyzadanger** [comment]
`aria-controls is not supported by VoiceOver or NVDA` 😠 

Our job is hard 😉

**Comment by lyzadanger** [comment]
I believe we could approach this by executing on a small project we've had in the wings for a while: https://github.com/hypothesis/frontend-shared/issues/77

**Comment by acelaya** [comment]
@mattdricker we have just landed the fix for this, using the improvements that @lyzadanger implemented (see her previous comments).
