### ISSUE TITLE
Tabbing backward off a confirmation modal closes modal

### ISSUE THREAD

**Issue by mattdricker** [hypothesis/product-backlog#1424]
This feedback comes out of Accessibility Web Audit from UC Berkeley.

### Current behavior
When a confirmation modal is presented, such as the modal shown for deleting an annotation, user is able to tab forward outside of modal unto frame. Tabbing backward off the modal closes the modal entirely.

### Expected behavior
Modal stays present and focussed until the user explicitly closes or selects an action button.

This is the feedback from the review:

> Keyboard user tabbed forward off the confirmation modal into the document frame; tabbing backward off the modal closed the modal
>
> Constrain focus to within the modal; Control keyboard focus so that the same thing happens forwards and backwards.

**Comment by lyzadanger** [comment]
We know we need focus-trap in our modals, known issue, glad to have a clear reason to solve it! See https://github.com/hypothesis/frontend-shared/issues/77

**Comment by lyzadanger** [comment]
As of https://github.com/hypothesis/lms/issues/5293 completion, all modal dialogs in our apps have been updated in their behavior such that:

* Focus is trapped in the modal, and tab-key navigation cycles through navigable elements within the modal
* Modals no longer close if you click or focus outside of them, and it is not possible to "tab out of", and thus inadvertently close, a modal
