### ISSUE TITLE
D2L Assignment Creation

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/product-backlog#1471]
**Problem Statement**: D2L users get frustrated having to input the LTI URL every time they enable an individual assignment with H. 
**Rationale**: a pain point for all D2L users, especially those who have just converted from a different LMS. Stops them from using the tool altogether. 
**Impact**: All D2L clients
**Proposal**: Not having to input the LTI URL. Put the URL in LMS account settings etc; some sort of global set up.

Intel- [Playposit currently has the ability to bypass entering the URL ](https://knowledge.playposit.com/article/223-d2l#setup-d2l)(step 2  under “assign a bulb to learner” in this kb article)

![Image](https://user-images.githubusercontent.com/123364063/242525775-3343e6a2-55a7-4a8b-8acd-dd1f02852b90.png)

**Comment by nairiboo** [comment]
This issue is a factor in DeSales University's decision not to renew

**Comment by jeremydean** [comment]
To add to above, here's how DeSales describes the issue--though it's pretty well captured above:

> First is the integration with D2L. I feel that it’s awkward to require our faculty to remember the LTI information when following these steps - [https://web.hypothes.is/help/using-the-hypothesis-lms-app-for-d2l/](https://t.sidekickopen22.com/Ctc/T9+23284/cLZwY04/Jl22-6q7W7lCdLW6lZ3nGN4L3VxFSvb98VvVz7w3V6cYTW7RvqMW1fMT0yW2rVM0T3rl4rYW6cB9Rt98ZTmZW7Yg4RL6v0cwtW4-n01T3T_DHBW14TxH94hYRptN6GZC-PhmfvWVfRhcp9gHlC4W7kXH0Q60PHnyVPS4lQ3NYRxYVVTVS43qjJMRW7qwg9H8vdcDVW70gFY_1qFCs6W7GDNRC1sss99W23t1ZF89RPZ_N1_PzhS8L2KqW3Xb6_l2MVqCbW36tGXN82WMkLW34jvRl75qQq_W7qQdzj30D_j6N8n1HxHtSjY_W6kW0Dw5Fntr0f7K3yG204). If instructors could choose Hypothesis as an external learning tool without needing the LTI information that would help promote added use. If there is a way to add Hypothesis as an existing tool instead of a new LTI integration each time please let me know.

**Comment by jmferr0608** [comment]
Hi folks - was talking to Christie about this issue and did some digging into the Playposit Support Notes

https://knowledge.playposit.com/article/119-install-playposit-in-lms-admin#d2l-cim

This link talks about how they're integrating into LMS at D2L schools. Is this similar to our process, or do they do something differently?  

D2L is fastest growing LMS in North America, so positive UX is important to land new customers and keep existing ones.  Please let me know what I can do to support a fix.

**Comment by marcospri** [comment]
I've been taking a look at this and I have three very unsatisfying approaches:

## Use a shorter URL

Instructors will still need to type an URL but a shorter one.

Currently we use `https://lms.hypothes.is/lti_launches`. It's easy to think of any shorter alternative.

Changing this will need admin intervention in any school using the new one.


## Using Deeplinking

This works better from an UI perspective, the tool can be selected from the menu, no need to type any URLs, see:

https://github.com/hypothesis/product-backlog/assets/1433832/3b211309-ba87-4c6b-91ec-e63d07b4917b


Technically it has a few challenges:

- We rather use less deeplinking, no more. See recent conversations around its support in Canvas.
- We'd need to start asking for a title in the LTI content selection window.
- A few small differences we'd need to tackle in implementation vs Canvas one, [see PR](https://github.com/hypothesis/lms/pull/5472)

I haven't done a full on testing of every feature after using deeplinking but I'm not expecting mayor changes needed, we might be able to reuse most of the implementation we have for Canvas.

The main downside of this approach is having another thing to support on top of our existing D2L integration.

This will also need admin intervention in any school switching to this approach.


## Maybe not typing an URL is possible in D2L but we don't know how

I can't find a way to achieve it and seen other tools suggest a similar approach to ours (when not using deeplinking).


I tried a few things, for example: https://documentation.brightspace.com/EN/integrations/ipsis/LTI%20Advantage/lti_1.3_add_lti_link_navbar.htm

This seems to add a handy link to the navbar but then all launches have the same resource link id (meaning it will be equivalent of having just one assignment). Not useful.

Creating links and then selecting them in "Existing activities" doesn't use new resource link IDs per link, it's always the same one. Not useful either.

I'd ask D2L for guidance here:

```
Is it possible to add a LTI Link for a tool that doesn't use deeplinking without having to input the launch URL by hand?

In other worsd, can we point a link to that Target Link URI of the tool without having to write it for every link, basically a way to instead of writing the URL and then selecting the tool, select the tool and get the URL automatically.
```

I have a feeling this might not be possible.
