### ISSUE TITLE
YouTube transcripts in the Wild

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1481]
[PRD Link](https://docs.google.com/document/d/1MrU3b_uP6Uh-v2yryUlQitVhT9m83DCmld7YpCffBiY/edit)

**Comment by robertknight** [comment]
Annotating youtube.com videos is possible by pasting the video URL into the input box at https://via.hypothes.is. This provides the same experience as annotating YouTube videos in the LMS app. We had discussed at some point surfacing the availability of this feature when visiting youtube.com, but that is a separate issue.
