### ISSUE TITLE
Youtube URL BUG 

### ISSUE THREAD

**Issue by Facni** [hypothesis/product-backlog#1498]
### Steps to reproduce
1. Open a youtube video that you didn't annotate yet.
2. Try refreshing the page sometimes until the number of hypothesis extension or bookmarklet notifications be high
3. Annotate
4. Open your personal hypothesis page and see that the annotation is on Youtube.com/

### Expected behaviour
The link of the video should be there not the youtube home page.

### Browser/system information
Browser Firefox / Chrome **(I tried in both)** Windows 11
**Firefox:** _Bookmarklet and Unofficial Hypothesis extension_
**Chrome:** _Extension and bookmarklet_
Sorry for mi english, I am not native.

**Comment by robertknight** [comment]
> Try refreshing the page sometimes until the number of hypothesis extension or bookmarklet notifications be high

This is odd. The number shown on the Hypothesis extension icon depends only on the URL. Is the URL changing in any way when you refresh the page?

There *is* a [known issue](https://github.com/hypothesis/product-backlog/issues/1288) with YouTube where if you land on one page, and then navigate to another using links within the YouTube UI, it doesn't update some parts of the page and this confuses Hypothesis (specifically the `<link rel=canonical>` metadata).
