### ISSUE TITLE
Import / Export Backend Scoping

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1499]
Product Issue: [Export/Import Annotations](https://github.com/hypothesis/product-backlog/issues/1496)
[PRD: Link](https://docs.google.com/document/d/1urk_9I_bEdnnoenSreF05Qs9RH6knl1oyrH68PF9rn8/edit)
[DD: Import/Export Annotations](https://docs.google.com/document/d/12q6y5uu0bojEK-vuXYZrcTrhDfg4BPumnIYUCO9GGaE/edit)

**Comment by marcospri** [comment]
In summary, the backend work will include:

- Decide an API field/structure for the import-related data (original_id, etc)
- Design & implement a dashboard based on the metadata from the previous point to track usage and impact.
