### ISSUE TITLE
Export annotations: frontend scoping

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1500]
This issue pertains to scoping tasks for the export portion of the import/export annotations project.

Product Issue: [Export/Import Annotations](https://github.com/hypothesis/product-backlog/issues/1496)
[PRD: Link](https://docs.google.com/document/d/1urk_9I_bEdnnoenSreF05Qs9RH6knl1oyrH68PF9rn8/edit)
[DD: Import/Export Annotations](https://docs.google.com/document/d/12q6y5uu0bojEK-vuXYZrcTrhDfg4BPumnIYUCO9GGaE/edit)

**Comment by lyzadanger** [comment]
This task is complete.

See project board at https://github.com/orgs/hypothesis/projects/122/views/1
