### ISSUE TITLE
Image Annotations - PDF

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/product-backlog#1502]
HTML
IIIF
PDF
web clipping 
SVG

https://www.notion.so/Image-Annotations-c85f3755745c4603a78e5a0455382619

**Comment by nairiboo** [comment]
[PRD: PDF Image Annotation](https://docs.google.com/document/d/1Ov72o1pQGzZpxfy62ABw7MmIAETdiy84G2noujlviEo/edit)

**Comment by almereyda** [comment]
Should the OP now also include SVG in the list?

**Comment by MrCoder** [comment]
> HTML IIIF PDF web clipping SVG
> 
> https://www.notion.so/Image-Annotations-c85f3755745c4603a78e5a0455382619

This page is not public.

**Comment by robertknight** [comment]
I'm going to close this issue because there isn't useful information in it, but some form of image annotation is definitely planned. We haven't started any work on image annotation yet. When we do we'll create more helpful issues.
