### ISSUE TITLE
Delete Users (webapp)

### ISSUE THREAD

**Issue by nairiboo** [hypothesis/product-backlog#1516]
Linked to https://github.com/hypothesis/product-backlog/issues/1476

[PRD](https://docs.google.com/document/d/1V4MePLdH0UfNETD81U6SWNgMs_MbYnki4zaStTMOjAE/edit#heading=h.gjdgxs)

**Comment by seanh** [comment]
I'm gonna close this ticket as superseded.

We now have a new PRD, DD and project board for self-service user deletion:

https://github.com/orgs/hypothesis/projects/133
https://docs.google.com/document/d/1SdXBraDZpgUVCARLI5OelV3DcjahHJBvQ9tticEG1GY
https://docs.google.com/document/d/1czDOdzls7OqONxZgiHs39SyWSXnzqfERlDnF26MV-Fc
