### ISSUE TITLE
Support WebVTT web native video transcript annotations

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1518]
[VTT Spec](https://developer.mozilla.org/en-US/docs/Web/API/WebVTT_API)

[Slack conversation](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1690366354338489)

**Comment by robertknight** [comment]
To add some context - WebVTT is the native format for subtitles that is supported by the `<video>` API on the web platform.  The browser has built-in APIs for accessing them in JavaScript. Supporting transcripts in this format would enable video annotation for any content providers that make use of these standards.

Some examples of content using this standard:

- Apple (https://developer.apple.com/videos/play/wwdc2022/10077/)
- (More suggestions welcome)

**Comment by robertknight** [comment]
Implemented in https://github.com/hypothesis/via/pull/1294.
