### ISSUE TITLE
VitalSource Student Payment

### ISSUE THREAD

**Issue by leedenison** [hypothesis/product-backlog#1519]
[PRD](https://docs.google.com/document/d/1TX4MvBx_gehtzmnJndQCFlvDqKCBM2GhlCSfoM9kDHU/edit#heading=h.gjdgxs)

Targeting Spring '24 which means:
  - Instructors release Dec '23
  - Student release Jan '24

Waiting on updates regarding SKU related deadlines to decide whether to prioritise.

**Comment by marcospri** [comment]
This was done in early 2024
