### ISSUE TITLE
Youtube assignment metadata for metabase reports

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1521]
In metabase, we show the relative proportion of assignments across different types.... like so:

![Image](https://github.com/hypothesis/product-backlog/assets/1413074/e0310a27-2b6f-4d88-9e2c-41924972477a)

Now that we have Youtube as an assignment type, we need to add that.

**Comment by marcospri** [comment]
Youtube assignment types are now in metabase.

In the reports metabase will put it under "other" when the number is low but hovering over that will give you the actual number:

![Screenshot from 2023-08-17 08-47-43](https://github.com/hypothesis/product-backlog/assets/1433832/6a93092c-22e6-4e43-89e0-7a40ad05261c)
