### ISSUE TITLE
YouTube URL bug

### ISSUE THREAD

**Issue by LordMartron94** [hypothesis/product-backlog#1533]
### Steps to reproduce
1. Install Librewolf
2. Use the Hypothesis bookmarklet on YouTube
3. Annotate
4. You will see the source URL is Youtube.com and not the actual video you are watching. The href in the rel=canonical of the source code is updated correctly, so this is most likely not the issue.

### Expected behaviour
The source URL should be the actual video we are watching.

### Actual behaviour
The source URL is YouTube.com home page.

### Browser/system information
I am using the latest version of Librewolf currently available and Windows 11.

**Comment by LordMartron94** [comment]
Update: it happens on Chrome browser, too, now... Maybe it's a Windows 11 thing?

**Comment by robertknight** [comment]
I'm not able to reproduce in Chrome using the extension. Steps tested:

1. Go to a YouTube.com video URL directly (ie. don't first go to youtube.com and then navigate)
2. Activate the client, go to Help -> Version and see that the displayed URL is correct
3. Create an annotation. The source URI will match the payload.

Note that if you do go to the homepage first, and then navigate to a video, it won't work. This is because of the issue where the `link rel=canonical` is not updated on youtube.com when client-side navigations happen. That's a known issue and is tracked in https://github.com/hypothesis/product-backlog/issues/1288.

**Comment by LordMartron94** [comment]
Even after I refresh on the page, it still happens.

**Comment by robertknight** [comment]
Can you provide the exact URL of the page you are testing with. Also can you confirm whether the URL that shows up under Help -> Version in the client matches the page URL.

**Comment by LordMartron94** [comment]
![image](https://github.com/hypothesis/product-backlog/assets/85250199/43bb8783-181e-4126-bf67-e8c858ed2680)

Hmm, apparently if I copy the URL and paste it in a new tab it does work.

![image](https://github.com/hypothesis/product-backlog/assets/85250199/45886316-a72c-4f80-b355-f93d5bfcb1dd)

PS) thanks for the quick replies

**Comment by LordMartron94** [comment]
It is friction to copy/paste the URL each time, though... Since when is this necessary? When I used hypothes.is before, last in September 2023, this was not a thing.

**Comment by robertknight** [comment]
I can see from the screenshot that you're using an old version of the client, and it looks like it is not an official build. The current extension release is v1.1461.0. Before doing anything else, I would suggest updating to a current version.

> Hmm, apparently if I copy the URL and paste it in a new tab it does work.

This sounds as though whatever you are doing to "refresh the page" is not actually refreshing the page fully but perhaps using a cached version of it. Check the `link[rel=canonical]` value in the page by evaluating `document.querySelector('link[rel=canonical]').href` in devtools and see whether it aligns with the URL shown in the sidebar.

**Comment by LordMartron94** [comment]
Where can I update? I am on Librewolf, a fork of Firefox.

**Comment by LordMartron94** [comment]
Refresh appears to be working now. I will close the issue. Thanks for your help. :)
