### ISSUE TITLE
Finish investigating current canvas studio token limitations

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1537]
Lets complete investigation of current token limitations, with the goal of finding some way to allow our implementation of studio to be used as is within classrooms.

As we also simultaneously push for them to implement a proper solution, etc  as detailed in https://github.com/hypothesis/product-backlog/issues/1537

**Comment by robertknight** [comment]
We've resolved the issues we had with using admin users' API tokens in Canvas Studio, for now.
