### ISSUE TITLE
Outline possible extensions to Canvas Studio that address current limitations.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#1538]
Lets detail the possible changes in Canvas Studio that might address its current limitations, so that we can begin a dialog w/ their team.

**Comment by robertknight** [comment]
We didn't record the specifics of what this issue was about back in May. The main thing we'd like to fix in future would be to replace the current workaround where we use an admin user's auth for certain Canvas Studio API calls. I'm closing this for now until we're in a position to revisit this.
