### ISSUE TITLE
LMS admin usage report may be missing some courses

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1546]
University College London
ORG ID: us.lms.org.CROs5T7nS72IqISlCi0rEQ

Generating a usage report for the ORG for dates 2023-07-01 through today, and then counting unique users in a spreadsheet, gives 460 users. [See "MD work 3" tab in this Sheet](https://docs.google.com/spreadsheets/d/1_l6oXzoyBnK_KX7DnM4zWyAEKhU19PvdCHtNTYzR2UY/edit?usp=sharing).

But I noticed that, when looking at all of the application instances for this org, I got different sets of groups when looking on the grouping table vs the group_info table. See [MD work 1 tab](https://docs.google.com/spreadsheets/d/1_l6oXzoyBnK_KX7DnM4zWyAEKhU19PvdCHtNTYzR2UY/edit?gid=554029242#gid=554029242).

There are 35 total authority_provided_ids tied to the AIs associated with the ORG. 30 of them are on the group_info table. 27 of them are on the grouping table. Combining and de-duping the authority_provided_ids, and using those to get H groups with annotations made from 2023-07-01 through today, gives 1,487 users.

**Comment by mkdir-washington-edu** [comment]
This is a Moodle course. I wonder if they've been using the "course reset" option, which re-uses the same LMS course year after year and puts new students in it.

That itself might be the cause of these numbers.
***

In fact, some of the differences here do seem to be due to a student making new annotations in an old course. Assuming we don't count that old course, I think the current ORG reports make sense; it's probably a good thing they ignore the scenario where a lone student made new annotations in an old course with a high number of students in it.

See: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1719779730810179?thread_ts=1719509850.784029&cid=C2BLQDKHA

**Comment by marcospri** [comment]
Further digging:

- [Groups that are in group_info that are not part of grouping](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo3LCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgKiBmcm9tIGdyb3VwX2luZm8gd2hlcmUgYXV0aG9yaXR5X3Byb3ZpZGVkX2lkIGluIChcblxuc2VsZWN0IGRpc3RpbmN0IGF1dGhvcml0eV9wcm92aWRlZF9pZCBmcm9tIGdyb3VwX2luZm8gd2hlcmUgYXBwbGljYXRpb25faW5zdGFuY2VfaWQgaW5cbihcbiAgc2VsZWN0IGlkICBmcm9tIGFwcGxpY2F0aW9uX2luc3RhbmNlcyB3aGVyZSBvcmdhbml6YXRpb25faWQgPSA3MDJcbilcblxuXG5leGNlcHRcblxuc2VsZWN0IGRpc3RpbmN0IGF1dGhvcml0eV9wcm92aWRlZF9pZCBmcm9tIGdyb3VwaW5nIHdoZXJlIGFwcGxpY2F0aW9uX2luc3RhbmNlX2lkIGluXG4oXG4gIHNlbGVjdCBpZCAgZnJvbSBhcHBsaWNhdGlvbl9pbnN0YW5jZXMgd2hlcmUgb3JnYW5pemF0aW9uX2lkID0gNzAyXG4pXG4pXG5cblxuXG5cbiIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6eyJ0YWJsZS5jb2x1bW5fd2lkdGhzIjpbbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsbnVsbCxudWxsLG51bGwsNzgwXX19)


I think it should be safe to ignore "group_info" for dates after 2023.

- [Annotations made on those groups](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgKiBmcm9tIGFubm90YXRpb24gd2hlcmUgZ3JvdXBpZCBpbiAoXG5cbnNlbGVjdCBwdWJpZCBmcm9tIFwiZ3JvdXBcIiB3aGVyZSBhdXRob3JpdHlfcHJvdmlkZWRfaWQgaW4gKFxuJzNiY2I1MDRjYWE3ZjJiOGRmZjNiYjMyMzRmZDkwMzJkYjg2MDgxODQnLFxuJzQ3MGMzNzkxMmI5ZWI4ZmE1NzQzZWViZTMwYjYxYTlmZDViNmVhMTYnLFxuJzJmMDRjYTIzY2JkODU0OGE2YzBmMjA1M2ZkMzBiNTEwZTEzNzU4OGUnLFxuJzQxY2I2NDUyYWRjZDBmM2E1MjU2MjRmMzBjYTZjNDc4Y2Y3YjAyMzcnLFxuJzU3YTVkMzVkMTI2NzgwNDI5NGE3NDYxMWNhNzc2NTAzMjlkMmRkN2InLFxuJ2Y4MjJmMTNmMDc4YzUxNWZiNjZjNWQ5MDMxZjk4ZjYwZDI0YWQ1ZTQnLFxuJzhkZGYyYzhiNDJlMjUyN2UzYjVkODBlMTYyZjVhMmZmYmI3YzNmODYnLFxuJzg5MmViNGU5MDI3MjI2NzYzMTUzNzZiODdlMzIzYWQxMTdhMjNkNDQnXG4pXG4pIiwidGVtcGxhdGUtdGFncyI6e319LCJkYXRhYmFzZSI6NX0sImRpc3BsYXkiOiJ0YWJsZSIsInBhcmFtZXRlcnMiOltdLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=)

Those don't have any recent annotations.

- [For UCL, from 2023-07-01. I get 4 groups with annotations in the period](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJuYXRpdmUiOnsicXVlcnkiOiItLSBHcm91cHMgdGhhdCBoYXZlIGFubm9zIGluIHRoYXQgcmFuZ2VcbnNlbGVjdCBkaXN0aW5jdCBhdXRob3JpdHlfcHJvdmlkZWRfaWQgZnJvbSBcImdyb3VwXCIgd2hlcmUgcHViaWQgaW4gKFxuLS0gQW5ub3MgY3JlYXRlZCBpbiB0aGUgZGF0ZSByYW5nZVxuc2VsZWN0IGdyb3VwaWQgZnJvbSBhbm5vdGF0aW9uIHdoZXJlIGdyb3VwaWQgaW4gKFxuc2VsZWN0IHB1YmlkIGZyb20gXCJncm91cFwiIHdoZXJlIGF1dGhvcml0eV9wcm92aWRlZF9pZCBpbiAoXG4nMDJlNGY5OWQ1ZjgyMzQ2MjUxYmY0MDRhNGYzODBhMmQ2NjRjOWYyOScsXG4nMTI1YzMyMTkwNDg1NzQ2ZDRhZGI3Y2RhZjY4YWMwOTg1NWEwM2M4NScsXG4nMTQyNGViNTY0MjU0MGIzNzZiMWY0MWJmYzE4NGFjMDU5NjBmODRhNScsXG4nMTViMTNiNTA3YTg3NzZjNWU1MTM0NTQ4ZWE4ZTU1ZjgwNTdhZGI2ZCcsXG4nMTViNWViYzI1Zjg4OTBiMDFlZWU0NTJlODkwYTJkZThiNGNmYzk4ZCcsXG4nMjIzMThiYzgwZDE5NzQ3YWM5NjVjMjExNDA0NTY2ZGQ5YTM1OWY4NCcsXG4nMmUzMTQ4NDM5NDI5OTQwY2FiNDhkOTY2NjU1NzNjYzg1YjkzNzI0OCcsXG4nMmYwNGNhMjNjYmQ4NTQ4YTZjMGYyMDUzZmQzMGI1MTBlMTM3NTg4ZScsXG4nMzVjY2FmNTU0MDMxNGViYzBjNDZhMTJjYzRkNDAzZjJkZGJmOGZiOCcsXG4nM2I1OTIyY2I3MjU3M2UyMWUyYTJiNjJlMzkyODllOGVlNDFlNGE5NCcsXG4nM2JjYjUwNGNhYTdmMmI4ZGZmM2JiMzIzNGZkOTAzMmRiODYwODE4NCcsXG4nM2MxYjU3MmY5NzMwYjIyMzAwOTZjNDIyOWFlNzAzNGI0ZTA0MWMzMCcsXG4nNDFjYjY0NTJhZGNkMGYzYTUyNTYyNGYzMGNhNmM0NzhjZjdiMDIzNycsXG4nNDcwYzM3OTEyYjllYjhmYTU3NDNlZWJlMzBiNjFhOWZkNWI2ZWExNicsXG4nNDg1NTkxNjc5YWEyNDRkMGQ3MWJjMTU3YTliYjIyNGRjYWZhYjM5ZCcsXG4nNDg2MDE1YjJkNTU5YjBkOTdlOTMyZmY2Y2IyNmUzYzljNjZjY2RkNycsXG4nNTEwYTliMzkzMTdkODMwOTk3N2IwNjc4YTc0YTNhMjE4ZTMwYmVlZicsXG4nNTdhNWQzNWQxMjY3ODA0Mjk0YTc0NjExY2E3NzY1MDMyOWQyZGQ3YicsXG4nNmRiNzdmZmE1MDFmN2YwNWE2NzkwY2U1ZTJlN2FmMTQ0MWEyNGJjOCcsXG4nNzgwYzIwYjk3MDg2YTYwZTQ1MjZjZjg3OTE3MzJiNzE1NjBlOWViZCcsXG4nN2NhZDg0ZWI5OTVmNjAwMGQzNTQwZGE0ZjNiZTA1ZTlmOTY5NTQ2YicsXG4nODkyZWI0ZTkwMjcyMjY3NjMxNTM3NmI4N2UzMjNhZDExN2EyM2Q0NCcsXG4nOGRkZjJjOGI0MmUyNTI3ZTNiNWQ4MGUxNjJmNWEyZmZiYjdjM2Y4NicsXG4nOGViMmM3MDdjNWM3NTg0ZmUwZWYwZDY0YjUyNGQ1Yzg4NGViZWEwMScsXG4nY2RhNDJjMTQwZTM2NmNmYzIwODIyMmJiYTE2Y2ZkOGUxNzhmODAxOCcsXG4nZDJiMzdhYWE4Zjk2NzcxOWZiMDU4MzQ4NmQ2YTUwMmNlNDNiZTRlNCcsXG4nZDc2NDVmODU3ZTFiMTdhNTIyZjhlNDdiMDkyZDU2ZjYyY2QyOGI2MCcsXG4nZDg3ZTUyZTlkZDg3OGVlM2MwNDY5ZGU4ZjBiMGEzODc0Njc0NGVhNycsXG4nZTg2YzMwNWFlOGExYjE5N2M1N2FiMTRjYjRkMWJmYzk2MGU3MDVlMCcsXG4nZjgyMmYxM2YwNzhjNTE1ZmI2NmM1ZDkwMzFmOThmNjBkMjRhZDVlNCdcbilcbilcbmFuZCBjcmVhdGVkID49ICcyMDIzLTA3LTAxJ1xuKSIsInRlbXBsYXRlLXRhZ3MiOnt9fSwidHlwZSI6Im5hdGl2ZSJ9LCJkaXNwbGF5IjoidGFibGUiLCJwYXJhbWV0ZXJzIjpbXSwidmlzdWFsaXphdGlvbl9zZXR0aW5ncyI6e319)


- [In those groups I count the people and get a roughly the same 460 number of unique users](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7InR5cGUiOiJuYXRpdmUiLCJuYXRpdmUiOnsicXVlcnkiOiJzZWxlY3QgZGlzdGluY3QgIGhfdXNlcmlkXG5mcm9tIFwiZ3JvdXBpbmdfbWVtYmVyc2hpcFwiXG5qb2luIFwiZ3JvdXBpbmdcIiBvbiBcImdyb3VwaW5nXCIuaWQgPSBncm91cGluZ19pZFxuam9pbiBcInVzZXJcIiBvbiBncm91cGluZ19tZW1iZXJzaGlwLnVzZXJfaWQgPSBcInVzZXJcIi5pZFxuXG53aGVyZSBhdXRob3JpdHlfcHJvdmlkZWRfaWQgaW4gKFxuJzM1Y2NhZjU1NDAzMTRlYmMwYzQ2YTEyY2M0ZDQwM2YyZGRiZjhmYjgnLFxuJzNiNTkyMmNiNzI1NzNlMjFlMmEyYjYyZTM5Mjg5ZThlZTQxZTRhOTQnLFxuJzUxMGE5YjM5MzE3ZDgzMDk5NzdiMDY3OGE3NGEzYTIxOGUzMGJlZWYnLFxuJzhlYjJjNzA3YzVjNzU4NGZlMGVmMGQ2NGI1MjRkNWM4ODRlYmVhMDEnXG4pXG4iLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sImRhdGFiYXNlIjo3fSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

- If I get one the groups missing from my number from @mkdir-washington-edu spreadsheet, for example:
`e86c305ae8a1b197c57ab14cb4d1bfc960e705e0`

[There doesn't seem to be any annotations made after march, so it shouldn't count for the 2023-07 report](https://metabase.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjpudWxsLCJuYXRpdmUiOnsicXVlcnkiOiIiLCJ0ZW1wbGF0ZS10YWdzIjp7fX0sInR5cGUiOiJuYXRpdmUifSwiZGlzcGxheSI6InRhYmxlIiwicGFyYW1ldGVycyI6W10sInZpc3VhbGl6YXRpb25fc2V0dGluZ3MiOnt9fQ==)

**Comment by marcospri** [comment]
## The main difference in unique user counts is the source of the users, H vs LMS.

In H we can see  'acct:002d464a2f9cb0058f0bf7c9eb334f@lms.hypothes.is' as a returned user for the count.

This user belong to `510a9b39317d8309977b0678a74a3a218e30beef` in H but we don't have any record of him in LMS. 

Not in the "user" table and of course not in grouping_membership or events.

Should this student be counted? I'd argue it shouldn't. 

`510a9b39317d8309977b0678a74a3a218e30beef` was created in the summer of 2021. Someone made an annotation there and we brought all the students the ever belonged to that course even before we did any user recording in LMS.

It would be tricky to present the information about this user in the LMS context, we won't display him in the dashboards, we can't track his launches... I reckon this type of user is the one more likely to cause questions about our numbers and ticker type to answer.

**Comment by mkdir-washington-edu** [comment]
Closing this issue as the problem is solved, and comparing/fixing the two different data systems is beyond the scope of this bug issue.
