### ISSUE TITLE
SPIKE Via efficiency / errors

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1557]
### Problem you are trying to address with this feature
This issue contains URLs are don't work correctly, or don't work consistently, in Via: https://github.com/hypothesis/product-backlog/issues/1270

Overall, we see these are the categories of these URLs:
    - Slow load - Slow load that eventually works
    - Partial load - Some assets are never loaded
    - No load - Slow load that times out altogether
    - Captcha fail - Site doesn’t like proxies
    - Browser version fail - Site doesn’t like our via browser?

The purpose of the SPIKE is to figure out what we can do to solve many, most, or all of these issues in a reasonable amount of time.

**Comment by robertknight** [comment]
There are several different issues mentioned in the PR description. I suggest we disentangle them. The issues of slow page loads where largely due to https://github.com/hypothesis/viahtml/pull/716.
