### ISSUE TITLE
Change Assignment drop down filter during assignment selection so that very long assignment names don't make it hard to see the multi-select boxes

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1561]
Currently the drop down filter expands to fit the titles inside it when opened. Some assignment titles can be very long, and can make it so that the multi-select checkboxes need to be accessed by scrolling horizontally.

The checkboxes should always be available for the user without scrolling.

![Image](https://github.com/user-attachments/assets/4ae17a4e-c631-480b-9612-4e8e33f2f5f2)

**Comment by mkdir-washington-edu** [comment]
Similar: https://github.com/hypothesis/product-backlog/issues/1573

**Comment by acelaya** [comment]
This is now implemented.
