### ISSUE TITLE
For Hypothesis Staff - show which school (using ORG names) they're currently viewing

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1567]
When Hypothesis Staff view the Reporting Dashboards through the LMS admin portal they can see the ORG public ID in the URL bar, but have no other indication on the screen as to which organization they are viewing.

The Hierarchical links should show, in this instance, the Name property of the ORG they're currently viewing, as an aid in keeping track of what data they're viewing.

https://www.figma.com/design/ctCnzwkAyYArSNBYEshiCm/Hypothesis---LMS-Assignment-Grading?node-id=1615-28&node-type=canvas&t=NqEOLDwbHPCk533n-0

![Image](https://github.com/user-attachments/assets/87707596-5c37-4035-ace1-7d58a6625447)

**Comment by acelaya** [comment]
This is now implemented
