### ISSUE TITLE
The Student and Assignment drop down filters need a badge showing the count of students currently available based on other filters (or no filters)

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1570]
In the LMS Reporting Dashboards filters are response to other filters, and convey information to the user based on how the contents of a given filter change based on setting other filters. For example, the contents of the Student Filter change after selecting a single course in the Course Filter.

Conveying a count of the entities within a filter on the filter itself is also useful information, is readily available, and helps set some expectations about the filter contents.

https://www.figma.com/design/rugQ2tONStRF3RL9UXZaGW/Search-Explorations?node-id=1280-38&node-type=frame&t=h1xgWlh3WysCnVQy-0
![Image](https://github.com/user-attachments/assets/3be4d733-2336-471b-bbe0-b2b11292ceba)

**Comment by acelaya** [comment]
Just to clarify, the count badge should only be displayed in filters where there's no value selected at all, right?

**Comment by mkdir-washington-edu** [comment]
@acelaya That makes sense to me to avoid confusion with thinking you've inadvertently selected 99 items, etc.

**Comment by acelaya** [comment]
@dwhly @mkdir-washington-edu A question has popped-up when it comes to this feature.

I reckon we discussed displaying a badge in the lines of `99+` if we know there are multiple pages to load for a specific filter (in case you don't remember, we load only the first 100 items, and as the user scrolls, we continue loading more items).

Do we want the badge number to be updated while new results are loaded via scroll? `99+`, then `199+` then `299+`, until all pages have been loaded and we can display the actual value, let's say `351`.

Or do we want to display the exact value only as long as there's a single page (so, less than 100 items) and `99+` if there are more than 1 page, regardless the amount of pages?

**Comment by acelaya** [comment]
Related with the above, @dwhly and I also were discussing if, considering the page size is currently 100, should we display `99+` or `100+`?

`99+` seems like a common approach in other services, but if you think about it, it's actually a bit arbitrary. If the page size is different than 100, or changes in future, or we want the value to be updated as new pages are loaded, then displaying 1 less than the page size might look weird. `24+` for 25-item pages, `149+` for 150-item pages, etc.

**Comment by mkdir-washington-edu** [comment]
> Do we want the badge number to be updated while new results are loaded via scroll? 99+, then 199+ then 299+, until all pages have been loaded and we can display the actual value, let's say 351.

If there's not a big cost in the browser to doing so then yes please. I think ultimately getting the correct count with enough scrolling will be very helpful, especially to admin.

> 99+ seems like a common approach in other services, but if you think about it, it's actually a bit arbitrary. If the page size is different than 100, or changes in future, or we want the value to be updated as new pages are loaded, then displaying 1 less than the page size might look weird. 24+ for 25-item pages, 149+ for 150-item pages, etc.

IMO: If you scroll to the bottom and there's no more to load (e.g. it says 99+, but you scroll to the bottom of the list, get to 100, and the API comes back with no more items) then the display should change to 100.

I'm interested in what Dan has to say since I could also see the logic in showing 100+, then just dropping the + if you fail to load more, but I think that makes the initial load inaccurate (since it wasn't actually more than 100), where 99+ may be weird, but it's accurate.

**Comment by acelaya** [comment]
> > Do we want the badge number to be updated while new results are loaded via scroll? 99+, then 199+ then 299+, until all pages have been loaded and we can display the actual value, let's say 351.
> 
> If there's not a big cost in the browser to doing so then yes please. I think ultimately getting the correct count with enough scrolling will be very helpful, especially to admin.

It shouldn't be a problem

**Comment by acelaya** [comment]
> > 99+ seems like a common approach in other services, but if you think about it, it's actually a bit arbitrary. If the page size is different than 100, or changes in future, or we want the value to be updated as new pages are loaded, then displaying 1 less than the page size might look weird. 24+ for 25-item pages, 149+ for 150-item pages, etc.
> 
> IMO: If you scroll to the bottom and there's no more to load (e.g. it says 99+, but you scroll to the bottom of the list, get to 100, and the API comes back with no more items) then the display should change to 100.

We will always know ahead of time if there are more pages, so this shouldn't happen. If there's exactly 100 items, the API will tell us there's no more pages to load and we can display 100 from the beginning, the user won't see a change when scrolling down.

**Comment by acelaya** [comment]
We have decided we'll be updating the number displayed in the badge as  we load results from the API. However, when only the first page of results has been loaded (so we have 100 results) and we know there's more results, we'll display `99+` to reduce the space used by the badge as much as possible.

**Comment by acelaya** [comment]
This is now implemented and released.
