### ISSUE TITLE
Give "Super Admins" (users who are admins across their whole LMS instance) automatic access to LMS Dashboards without needing an email.

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1572]
Super admins in an LMS are admins who are admins across the whole LMS instance, not just a subaccount or similar.

Super admins can have the roles: 
urn:lti:sysrole:ims/lis/Administrator
http://purl.imsglobal.org/vocab/lis/v2/system/person#Administrator
urn:lti:sysrole:ims/lis/SysAdmin
http://purl.imsglobal.org/vocab/lis/v2/system/person#SysAdmin

See: https://hypothes-is.slack.com/archives/C2BLQDKHA/p1724958677399309?thread_ts=1724958633.931619&cid=C2BLQDKHA

Super admins can be presumed to always be allowed to access Hypothesis' data concerning students, and so we can allow them admin access to the Dashboards without needing to verify their email addresses.

**Comment by mkdir-washington-edu** [comment]
This should solve one use case for issues: https://github.com/hypothesis/product-backlog/issues/1552, https://github.com/hypothesis/product-backlog/issues/1560

**Comment by marcospri** [comment]
Done on https://github.com/hypothesis/lms/pull/6798
