### ISSUE TITLE
Add new group icons to Hypothesis Sidebar

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1597]
Icons from: https://www.figma.com/design/jon1U01LGSLcx7PWtZ9TPZ/Hypothesis---Group-Management?node-id=2677-127&node-type=canvas&t=zoIzfqEvL9mGUe2o-0

![Image](https://github.com/user-attachments/assets/f87f9ef9-4954-4c38-a238-6edde0b91a74)

As part of our rolling out of the new Managed Groups feature, we've created new group icons. These icons appear in the new group creation workflow, and will eventually appear in multiple places.

For now, we should implement the icons in the Sidebar group dropdown, using the same feature flag that's currently controlling access to the new group creation page.

**Comment by acelaya** [comment]
We have decided not to change the sidebar menu as much as in the designs, but only add the icons right before the chevrons (which are currently in the right side, not the left side).

**Comment by acelaya** [comment]
This is now implemented, looking like this:

![Image](https://github.com/user-attachments/assets/e7b4de1d-0a65-4e8d-9b8f-401395f5c85a)
