### ISSUE TITLE
Fix certificate for https://status.hypothes.is

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1598]
I'm getting "connection not private" when trying to get to https://status.hypothes.is/

Firefox: Error code: [SSL_ERROR_BAD_CERT_DOMAIN]
Chrome: net::ERR_CERT_COMMON_NAME_INVALID

**Comment by indigobravo** [comment]
This will work:
- https://web.hypothes.is/status/

And that is what we link to on [web.hypothes.is/status](https://web.hypothes.is/status/). 

I need to have a think about next steps. I am not sure going directly to https://status.hypothes.is/ has ever worked. Technically, this is not a Hypothesis problem, we are reliant on a Pingdom certificate which has a common name of: `secure-stats.pingdom.com`

![Image](https://github.com/user-attachments/assets/15f7b8f5-c70f-4573-bb2a-fa1ebd4ed99b)

**Comment by mkdir-washington-edu** [comment]
Based on Ian's comment I'm closing this issue.
