### ISSUE TITLE
Create a page that shows up when people uninstall the Chrome extension

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1599]
Generated from a meeting on [web app data needs](https://docs.google.com/document/d/1Xh7Cpfv_rcAe-EsD5s4HVQJIc2JUGzL8Sb2mGFGP9HU/edit?usp=sharing).

When users uninstall the Chrome extension we'd like to know why. If possible, directing them to a page with short survey, or otherwise displaying a survey, would allow us to better understand what users are looking for an not finding when they uninstall the extension.

**Comment by mkdir-washington-edu** [comment]
Google Form we can link to: https://docs.google.com/forms/d/1hxTpxcq07gl1Iz7SkfRR0_PmRQhS70FbucRaDHQbr5A/edit

An example of the form another app is using for this same purpose: https://docs.google.com/forms/d/e/1FAIpQLSdA3ovcFxS31XQRbGdTjWXr0y21Gv0ZgQk3D-frrfRddhhSEg/viewform

**Comment by mkdir-washington-edu** [comment]
Related: https://github.com/hypothesis/product-backlog/issues/1600

**Comment by mkdir-washington-edu** [comment]
Stable URL: 
https://docs.google.com/forms/d/e/1FAIpQLSd250Bi4xvxxvL-SgajHRmk8K1LMLZLGRoYkp6WSwT8PDTlLA/viewform?usp=sf_link

**Comment by robertknight** [comment]
@mkdir-washington-edu that link is going to break if the form gets recreated. I suggest we create a link on https://web.hypothes.is/ or a short-link service (if we have one that the team already use) that redirects to whatever the current form link is. It would be nice (but not essential) if that link had a meaningful URL.

**Comment by robertknight** [comment]
The Chrome API for setting a post-uninstall URL is [`chrome.runtime.setUninstallURL`](https://developer.chrome.com/docs/extensions/reference/api/runtime#method-setUninstallURL). Per the description:

> Sets the URL to be visited upon uninstallation. This may be used to clean up server-side data, do analytics, and implement surveys. Maximum 1023 characters.
