### ISSUE TITLE
Share links should differentiate between annotations on Youtube pages, and over Youtube transcripts

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1604]
**The problem**
The bouncer link https://hyp.is/id3fuqOCEe-R3BuKxZpTFw/www.youtube.com/watch?v=mBtsNNXjBPw, when opened in Chrome with the extension present, doesn't open the Via transcript view, and the annotation is orphaned.

Similarly, a page bouncer link would have the safe effect.

**Expected result**
When an annotation share link points to an annotation over a youtube transcript, bouncer should open the link in Via, even if the browser extension is available.  If a share link points to an annotation on that same page **not** on the transcript (say, over the title of the video) then bouncer should behave as it already does now.

When a page share link is created with the transcript visible, following that link should open the page in Via with the transcript visible. If the page share link is created without the transcript visible then bouncer should behave as it does now.

**Slack conversation:**
https://hypothes-is.slack.com/archives/C4K6M7P5E/p1731696793525149

**Comment by robertknight** [comment]
Bouncer could infer that the annotation was made on the transcript based on it having a `MediaTimeSelector` selector. In that case it could redirect the user to Via in the same way as if the Chrome extension was not present.

This will work for a _specific_ annotation. It won't work for Bouncer links which don't include an annotation, like those generated by the "Share" panel displayed via the Share icon in the client's top toolbar. For that we could add a parameter to the bouncer link to provide the context of which viewer app was being used.
