### ISSUE TITLE
The auto-grading "sync grades" button should not appear for Canvas Module items

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1608]
Slack conversation: https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1732217246293399

The issue:
Currently the auto-grading "sync grades" button appears even for Hypothesis readings that are set up for Canvas Module Items. Module items don't sync up the Canvas gradebook.

A solution
There may still be utility in allowing instructors to automatically count the number of annos and replies on readings set up for module items, so we should keep that option available during the assignment creation workflow.

But when there's no LMS gradebook sync available, or just specifically when a reading is made in a Canvas Module item (currently the only supported assignment creation workflow that doesn't sync to an LMS gradebook) we should suppress the "sync grades" button in the Dashboard assignment view.

**Comment by marcospri** [comment]
This also applies to non-Gradable assignments in other LMSes.
