### ISSUE TITLE
Align company data reporting with Sunday as the start of a week for weekly reports

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1612]
From the standup on 2024-12-04, we had discussed checking the various data reports that create weekly internal data reports and making sure they all align with Sunday as the start of the week (some or all may use Monday as the week start).

From the discussion, it sounds like this is split into:
- Checking the data views we have and aligning them on Sunday - probably not difficult
- Re-running our weekly reports to recalculate all of their data with the new weekly start date (potentially tricky since this runs in Prod)

**Comment by marcospri** [comment]
Fixed on:

- https://github.com/hypothesis/lms/pull/6910
- https://github.com/hypothesis/h/pull/9198
- https://github.com/hypothesis/report/pull/436

and run "create from scratch" on H, LMS and report today.
