### ISSUE TITLE
Add new doc types to list of document types ("File Types") in lms-us > report > Assignments

### ISSUE THREAD

**Issue by mkdir-washington-edu** [hypothesis/product-backlog#1613]
lms-us > report > Assignments can be found at https://report.hypothes.is/question#eyJkYXRhc2V0X3F1ZXJ5Ijp7ImRhdGFiYXNlIjo1LCJ0eXBlIjoicXVlcnkiLCJxdWVyeSI6eyJzb3VyY2UtdGFibGUiOjMwMX19LCJkaXNwbGF5IjoidGFibGUiLCJ2aXN1YWxpemF0aW9uX3NldHRpbmdzIjp7fX0=

We need to include:
1. Canvas Studio
2. Canvas Pages
3. Moodle Pages 
4. Moodle Files

...in this list

**Comment by marcospri** [comment]
Fixed on https://github.com/hypothesis/lms/pull/6909 and run "create from scratch" on H, LMS and report today.
