### ISSUE TITLE
prevent line overlap in headers

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#162]
https://hyp.is/s0TnNOvMEeax2F-uiYxKrg/www.twincities.com/2016/10/24/minnesota-insurance-increases-mnsure/#annotations:gaYiauvMEeaUdPsbnsCUCA

![image](https://cloud.githubusercontent.com/assets/46509/22628891/dee3b064-eb90-11e6-89cc-56a3418fecfd.png)

https://hypothes.is/users/hapgood?q=

![image](https://cloud.githubusercontent.com/assets/46509/22628899/fccb14fa-eb90-11e6-9cf7-02f4be58d810.png)

**Comment by klemay** [comment]
This was [brought up today](https://hypothesis.zendesk.com/agent/tickets/4240) by Europe PMC. Some of the annotations on their site contain h2 tags, which result in overlapping text. Example: https://hyp.is/dIePJH44EeiOlXM7IVNyXg/europepmc.org/abstract/MED/21334061

**Comment by robertknight** [comment]
The general problem here is that the client's stylesheets sets line heights to absolute pixel values in various places, but the markdown body styles do not reset the line height.

The minimal change to fix the problem will be to reset `line-height` in the markdown body. More generally it would probably be a good idea to go over the client's styles and replace pixel values with unitless lengths for line height.
