### ISSUE TITLE
Add metrics for OAuth token usage

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#170]
We would like to know how often the client (embedded in partner sites) is finding itself with an expired access token (e.g. because the user suspends their laptop for too long, and then tries to use the client without reloading the page, but the client has missed its chance to use its refresh token). If we have this data then we can know whether or not it's necessary to extend the lifetime of the OAuth refresh tokens (which would complicate the code somewhat, see Slack discussion: <https://hypothes-is.slack.com/archives/backend/p1486662430003559>).

Possible approaches:

1. Use the new client metrics stuff. @sean-roberts will this be easy to do? Have the client report when its access token expires, or when it tries to do some access token or refresh request and gets an error back from the server.

2. Do it server-side using statsd (as we already track various metrics server-side). This only works if the client tries to _use_ the expired access or refresh token with the server. It won't work if the client sees that the token is expired and knows to show an error to the user without even trying to use it with the server.

**Acceptance Criteria**

_(Updated during sprint planning 26/05/17)_

1. The client detects a failure to refresh an OAuth token and submits a Google Analytics event to record this.
2. If the client is offline at the time the event occurs, as detected using the [Online and offline](https://developer.mozilla.org/en/docs/Online_and_offline_events) events or other network status APIs, the client makes a _best effort_ attempt to queue up the events and submit them when the user regains a network connection.

**Comment by sean-roberts** [comment]
It is super cheap to do it via analytics on client side. I'd like to think it's cheap to do it on the server but I haven't used the server side stuff before.

**Comment by chdorner** [comment]
It depends on what you want to track. If we want to track how often our own client runs into an expired token, then we should do it client side. If we want to track how often API clients (our sidebar client, but in the future also other, potentially third party, OAuth clients) try to use the API with an expired token, then we should do it server side.

**Comment by sean-roberts** [comment]
yep. Ideally we could do both as it's interesting to know from both the user perspective, how often they are running into expired token issues, and from the api consumer perspective. They both are probably pretty cheap

**Comment by robertknight** [comment]
I think this is irrelevant now since we fixed the original issue (that access & refresh tokens have the same lifetime) that prompted this ticket. Technically the token could still expire after a week, but that's long enough that we can worry about that later.
