### ISSUE TITLE
wacky pdf scrolling

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#173]
In http://cdn.nmc.org/media/2017-nmc-horizon-report-he-EN.pdf, the New Media Consortium's Horizon Report, watch the scrollbar bounce up and down as I lean on PageDown:

http://jonudell.net/h/infinite-scroll.mp4

Version:
0.55.0
User agent:
Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/56.0.2924.87 Safari/537.36
URL:
http://cdn.nmc.org/media/2017-nmc-horizon-report-he-EN.pdf
PDF fingerprint:
e53aca2272be4a1f935b307adcb0c827
Username:
judell
Date:
15 Feb 2017 11:46:30 -0800

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/740, where PDF issues have been compiled.
