### ISSUE TITLE
Protect our users from malicious or injected content

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#176]
### Problem you are trying to address

We currently employ a number of tactics to try and protect users from the possibility that malicious content can be injected into the pages of the Hypothesis service. At the moment there are a number of limitations to what we do:

- users can include arbitrary off-domain images and videos in annotations, including from insecure (`http:`) addresses, leading to ["mixed content"](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content) warnings displayed by the browser -- leading to users learning to ignore these security warnings.
- we do not have any policy-based protections against script or other media injection attacks that would serve as a second line of defence against XSS attacks, thus protecting user privacy and account security.

### Your solution

1. Apply restrictions to valid sources from which content embedded in annotations can be served. This will probably require deploying something like [thumbor](https://github.com/thumbor/thumbor) or [camo](https://github.com/atmos/camo) to proxy image requests.
2. Apply a restrictive [`Content-Security-Policy`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) and appropriate [`X-XSS-Protection` headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) to pages served on the `https://hypothes.is` domain.

### References

- https://github.com/hypothesis/h/issues/1940

**Comment by robertknight** [comment]
> Apply a restrictive [Content-Security-Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy) and appropriate [X-XSS-Protection headers](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-XSS-Protection) to pages served on the https://hypothes.is domain.

This is now done. We have a strict `script-src` requirement on https://hypothes.is. There is a `style-src` but it has `unsafe-inline` because KaTeX requires this.

Browsers started auto-upgrading HTTP resources to HTTPS automatically, per https://chromium.googlesource.com/chromium/src/+/refs/heads/main/docs/security/autoupgrade-mixed.md, so that helps us with embedded resources.
