### ISSUE TITLE
Enable scholarly publishers to sync annotations among syndicated copies of articles

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#18]
_Problem Summary_

Consider http://jneurosci.org/content/34/17/6112

It has this DOI: 10.1523/JNEUROSCI.5212-13.2014 (which resolves to the above URL)

The article is also syndicated to:

Pub Med URL:  https://www.ncbi.nlm.nih.gov/pubmed/?term=PMID%3A+24760871
Pub Med Central (US) URL:  https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3996228/
Europe PMC URL:  http://europepmc.org/abstract/MED/24760871

Annotations made against any of these URLs should coalesce with annotations to any other. Instead here is the situation:

(annotation count, url)

(46, 'https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3996228/')
(46, 'doi:10.1523/JNEUROSCI.5212-13.2014')

(0, 'http://jneurosci.org/content/34/17/6112')
(0, 'https://www.ncbi.nlm.nih.gov/pubmed/?term=PMID%3A+24760871')
(0, 'http://europepmc.org/abstract/MED/24760871')

_Analysis of problem, diiscussion of possible solutions_

Please see https://docs.google.com/document/d/1Hmb_gfBVVLCQ1yI4l-rTtS2579x8Ug7J6FA0M4onrQU/edit#heading=h.tduqh0dlpo47

@ajpeddakotla this probably wants the label -- which I don't think I can create -- "needs discussion"

**Comment by klemay** [comment]
@judell and @dwhly is this issue still valid? 

Isn't it true that the DOI can be added in a common tag to the `<head>` of each syndicated version [as outlined in our KB article](https://web.hypothes.is/help/how-hypothesis-interacts-with-document-metadata/)?

**Comment by judell** [comment]
@klemay yeah this issue predates DOI support, please close.
