### ISSUE TITLE
Support bouncer/hyp.is links to URLs (with optional queries) rather than just annotations

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#194]
**Updated Description**

Bouncer (hyp.is) links can currently only direct the user to specific annotations, not all annotations on a specific URL or a subset of annotations matching some query on a specific URL.

We have several use cases for the latter:

- QDR want to be able to link to all annotations by a specific user on a page (nb. their use case would also be solved by public groups)
- Education users have often had problems with users annotating in the wrong group. One proposed solution is to make it possible to get `hyp.is` links that include a specific group to focus on.
- As a user I want to call attention to a specific subset of annotaitons (eg. by user, tag etc.) on a page

**Original Description**
We can't prevent people from using via instead of bouncer, but we can make it easier and more likely that they will.

Here's one thing that'll help. If you go to https://arxiv.org/abs/1606.02960 and run the arxiv bookmarklet (see http://jonudell.net/h/#bookmarklets) you'll notice that the PDF + 23 Annotations link it produces is https://hyp.is/s-FN-oEOEea3FAtZbNbKrg. The bookmarklet does this by fetching annotations for the page, sorting by location, taking the first id, and forming a hyp.is URL with that id.

Could https://hyp.is/https://arxiv.org/abs/1606.02960 function as an alternative to  https://via.hypothes.is/https://arxiv.org/abs/1606.02960, one that would find the first annotation and redirect to its direct link?

----

- [x] Support hyp.is links which direct to a URL rather than an annotation
- [x] Automatically activate extension when URL includes an annotation query fragment
- [x] Support filtering annotations by user & tag in the client on startup
- [ ] Support hyp.is links that trigger the client to select a specific group on startup
- [x] Update bouncer interstital page for redirects to URLs rather than annotations

**Comment by robertknight** [comment]
This is being actively worked on. The URL format is described at https://gist.github.com/robertknight/85c9dfc89910288e84588903ab1010a3 , in brief: `https://hyp.is/go?url={url}&q={query}` where the "q" parameter is optional.

This is now working when hyp.is redirects to Via. Support in the browser extension is being worked on: https://github.com/hypothesis/browser-extension/pull/45

**Comment by klemay** [comment]
All but one of the acceptance criteria have been met; there's a separate issue for that one: https://github.com/hypothesis/product-backlog/issues/713
