### ISSUE TITLE
Better moderation tools

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#197]
### Problem you are trying to address

As a publisher who embeds Hypothesis
I would like to be able to moderate annotations made on my site
So that I have some editorial control over what visitors to my site see
And so that I can quickly and easily suppress spam and/or abusive content

As someone trying to convince a site owner to embed Hypothesis
I would like to be able to tell people considering embedding Hypothesis that they can control what users see (by default)
So that they are less likely to perceive an embedded Hypothesis instance as a risk to the credibility and perception of their site.

### User requests

- https://hypothesis.zendesk.com/agent/tickets/68
- https://hypothesis.zendesk.com/agent/tickets/311
- https://hypothesis.zendesk.com/agent/tickets/437
- https://hypothesis.zendesk.com/agent/tickets/494
- https://hypothesis.zendesk.com/agent/tickets/692
- https://hypothesis.zendesk.com/agent/tickets/988

**Comment by robertknight** [comment]
We implemented a really basic moderation capability in Hypothesis v1.11 - v1.15 earlier this year. Anyone can flag an annotation and the creator of a group can see which annotations have been flagged and choose to hide them from non-moderators.

It ticks the boxes above but IMO there is still a lot to do to make it really convenient to use. We can track that work in separate issues.
