### ISSUE TITLE
On a URL query, time-bucketing groups the list of annotators unhelpfully

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#20]
The question answered by the list in other contexts, e.g. a tag or user query, is: “Who else annotated this doc.” And the answer comes back as a complete list:

![image](https://cloud.githubusercontent.com/assets/46509/19500221/17122f84-9550-11e6-993c-8ae992cffab6.png)

For the uri: query, though, the list may split across time buckets:

![image](https://cloud.githubusercontent.com/assets/46509/19500244/29f18ef6-9550-11e6-8a94-be60e322bd78.png)

@ajpeddakotla this might want a tag like "design"

**Comment by klemay** [comment]
We are working through many of these questions and problems as we build a capability for LMS users to see and filter annotations made in a course (See: https://github.com/hypothesis/product-backlog/issues/1161). 

The plan is to replace our activity pages with the work that comes out of the LMS project. I'm going to close this issue and propose that further discussion on how we display annotations happens as part of the iteration process for the new project.
