### ISSUE TITLE
"Only Me" in groups is a poor experience

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#200]
### Problem you are trying to address

The way we currently manage private annotations seems to be consistently at odds with the way users expect private annotations to work. The idea of annotating "privately, in a group" confuses people about what the purpose of a group is, and what "private" means.

As a user who primarily annotates for their own benefit
I want to quickly and easily see my own annotations (and no-one else's) on any page
So that I don't have to trawl through other contributions to find my own.

As a user who is new to Hypothesis, and who has been invited to annotate with a group
I want the simplest possible route to posting annotations in that group
So that there is little risk I get stuck and frustrated.

### Your solution

As discussed most recently in https://github.com/hypothesis/product-backlog/issues/191, but also elsewhere, it seems like moving from a model where annotations can be in:

```
Public
  shared
  only me
Group A
  shared
  only me
Group B
  shared
  only me
```

to one in which annotations are in one of:

```
Only me
Public
Group A
Group B
```

would be a useful simplification of our user interface and would solve this and related issues.

### User requests

- https://hypothesis.zendesk.com/agent/tickets/328
- https://hypothesis.zendesk.com/agent/tickets/836 (How to see only my annotations?)
- https://hypothesis.zendesk.com/agent/tickets/990 ('I had assumed that once I was logged in, “Private” would be an option in the drop down menu')
- https://hypothesis.zendesk.com/agent/tickets/995 ('...even my public annotation are marked with a small padlock that says that only I can see this annotation. What's the difference between these two options?')
- https://hypothesis.zendesk.com/agent/tickets/996 (Feature Request: a way to filter out public annotations)

**Comment by dwhly** [comment]
Note also: https://github.com/hypothesis/product-backlog/issues/528

**Comment by klemay** [comment]
Closing in favor of #528
