### ISSUE TITLE
Allow searching by domain/site/path

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#201]
### Problem you are trying to address

As the publisher of web content
I want to be able to search for annotations across my website
So that I can find and engage with annotations on my content.

As a researcher
I want to be able to search for annotations made on a domain
So that I can understand and compare annotation activity on a domain without needing to enumerate all the possible URLs on that site.

### Your solution

Make it possible to search annotations by `domain` (AKA `site`) rather than just by URL.

### User requests

- https://hypothesis.zendesk.com/agent/tickets/989 ("It would be good if a web page (such as [a] forum) which consists of many pages...displayed as a single tape.")
- https://groups.google.com/a/list.hypothes.is/forum/#!topic/dev/bzyngQF0oLM

**Comment by klemay** [comment]
As a solution: https://github.com/hypothesis/product-backlog/issues/30

**Comment by ajpeddakotla** [comment]
| Business Viability | User Engagement | Building Community | Level of Effort |
|---|---|---|---|
| 3 | 3 | 3 | 3 |

**Comment by ajpeddakotla** [comment]
Closing this as we have wildcard queries now. (See #30)
