### ISSUE TITLE
alert user when pdf is image-only

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#202]
### Steps to reproduce
1. Try to annotate an image PDF

### Expected behaviour
Alert user: "This is an image-only PDF, there is no text to annotate."

### Actual behaviour
User scratches head:  "Why can't I select any text to annotate?"

### Additional details

Ran into this today looking over the shoulder of an instructional designer at UC Berkeley. Even though I know this can happen, it puzzled me at first.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/740, where PDF issues have been compiled.
