### ISSUE TITLE
Browser extensions should ignore configuration from host page

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#209]
@seanh did an extensive write-up of how the client configures itself (see [Slack discussion](https://hypothes-is.slack.com/archives/frontend/p1488912816003926) and annotated [GitHub gist](https://gist.github.com/seanh/f2cf65bc70db0815da0582c7dbabdeb6#suggestions)).

One issue arising from that discussion which I think we've got consensus on is that the host page should not be able to influence the configuration of the client _when injected by the browser extension_. This is for reasons of meeting user expectations and security - when the user clicks the Hypothesis button in the toolbar, they should get a consistent behaviour.

As explained in [the Gist](https://gist.github.com/seanh/f2cf65bc70db0815da0582c7dbabdeb6#suggestions) the extension needs to be able to configure the client in several ways:

1. It needs to be able to specify the annotation ID to focus on initially
2. It needs to make the client load `app.html` and client assets from the extension _whose ID is not known at build time in development (though it _is known at build time for QA/prod_)_.
3. In future it may also need to communicate extension-specific preferences to the client

This means that:

1. The extension will need _some_ way of providing the configuration above but:
2. When the client is injected by the browser extension, it should otherwise ignore configuration on the host page.

**Comment by seanh** [comment]
I'm gonna be opening a couple follow-up issues from this...

**Comment by seanh** [comment]
First issue split out from this one: https://github.com/hypothesis/private-issues/issues/1

**Comment by seanh** [comment]
Second issue split out from this one: https://github.com/hypothesis/private-issues/issues/2
