### ISSUE TITLE
Write an ADR for what a clearer directory structure for the client would look like

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#216]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

One of the client technical debt issues identified was a lack of directory structure in the client code - it's too flat, making the code harder to navigate and comprehend and probably contributing to the spaghetti-like dependency graph.

**Comment by robertknight** [comment]
Implemented in https://github.com/hypothesis/client/pull/687
