### ISSUE TITLE
Rename all JavaScript entrypoints to index.js

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#218]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

It's a simple thing, so just do it - if the browserify / commonjs entrypoint file is always named `index.js` (as in conventional) then it will be easier to find than `app.js`, `main.js`, etc currently.

**Comment by robertknight** [comment]
This was done in https://github.com/hypothesis/client/pull/632
