### ISSUE TITLE
Enable Babel on all frontend repos

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#220]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

Enable Babel on all repos (especially the client repo) so we can use ES6 features, and have consistency between repos.

**Comment by robertknight** [comment]
This is now done for the client repo. Only the browser extension repo is left.

**Comment by robertknight** [comment]
Done for the browser extension repo too now in c3cf775abb4a828426e9ce1122877b1c03aa2cf6

**Comment by seanh** [comment]
Sweet! So I guess we can use ES6 everywhere now, which is awesome

**Comment by robertknight** [comment]
In the case of the browser extensions, all browsers we support now have pretty much full support for ES6 aside from ES6 modules, so we could actually get ES6+ support and consider skipping the transpilation step or using [babel-preset-env](https://github.com/babel/babel/tree/master/experimental/babel-preset-env) to transpile only stuff which is not natively supported.
