### ISSUE TITLE
Spike to investigate what to do about AnnotatorJS in the client

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#223]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

It was generally agreed that the presence of AnnotatorJS in the client _is_ a problem that should be fixed sooner rather than later. So what are we gonna do about it? @sean-roberts made a very convincing argument (perhaps it's in [Rob's notes](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md)). @robertknight also pointed out that this is likely to become a pressing issue when we get to the upcoming Epub integration work.

**Comment by robertknight** [comment]
The Evident Point developers have put up a PR to remove Annotator from the client, which looks easier than I was expecting: https://github.com/hypothesis/client/pull/380

**Comment by robertknight** [comment]
The above PR is now merged. At some point I think it would still be worth writing up an ADR that describes how we have / are going to evolve the "guest" and "host" code, where removing Annotator is one of the steps. For now though, I'm going to close this.
