### ISSUE TITLE
Create some retrospective ADRs about the client and AngularJS

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#224]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

People did not seem to think that we'd be moving the client away from AngularJS anytime soon or that there was a pressing need to do so. But there _is_ a need to document or somewhat custom approach to using AngularJS. For example [Rob has recently done an ADR about our decision to use a component-based architecture](https://github.com/hypothesis/client/pull/292). There are a few more high level facts about how we use AngularJS that will also be valuable to document in retrospective ADRs.

**Comment by robertknight** [comment]
These slides from the Brighton meetup in January 2019 provide an overview of the current situation and plans: https://docs.google.com/presentation/d/1U4-3ONkJREzNTAULPdNrc4238x2LyyjswAd6RTSO8oM/edit#slide=id.g4b02c14b59_0_5. I think I'm going to consider this done.
