### ISSUE TITLE
Write a retrospective ADR about our approach to state storage in the client

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#225]
This issues comes out of the [16th March 2017 client technical debt meeting](https://hypothes-is.slack.com/files/robertknight/F4JQGU7MX/-.md).

This is an architectural decision that was taken in the past and that is not typical for an Angular app and not consistently applied across our codebase either. So now that we have ADRs for the client it will be useful to write a retrospective ADR for it.

**Comment by robertknight** [comment]
In [the ADR](https://github.com/hypothesis/client/pull/687) which describes the current goal state for the client application, I included some historical footnotes about the rationale for adopting a state container in the first place which I believe covers this.
