### ISSUE TITLE
Make the client read the group leave URL from the API descriptor

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#230]
Make the client read the HTTP method (`POST`) and URL template (`/groups/:id/leave`) from the [hypothes.is/api](https://hypothes.is/api/) descriptor endpoint, instead of hardcoding the URL template in the client.

Depends on https://github.com/hypothesis/product-backlog/issues/229 to add this URL to the descriptor endpoint first.

**Comment by robertknight** [comment]
This was done a while back IIRC but is now obsolete as there is an API method to leave a group.
