### ISSUE TITLE
Show replies to hidden annotations

### ISSUE THREAD

**Issue by fatbusinessman** [hypothesis/product-backlog#231]
## User stories

As a reader, I should still see replies to annotations that have since been hidden, so that I can follow the conversation.

As an annotator who has replied to an annotation that has since been hidden from view, I should still see my own reply, so that I don’t get confused that my annotation has disappeared.

## Background

This is a part of the work required to make the NIPSA (“not in public site areas”) system fit for use as a moderation tool. It came from the spike on how we hide annotations (#184).

Currently, when a user is marked as NIPSA, all their annotations are hidden to everyone but them, effectively [shadow banning](https://en.wikipedia.org/wiki/Stealth_banning) them. However, due to the way we handle replies in our search engine (search for top-level annotations, search for replies to those annotations, stitch them back together in the client), any replies to those annotations are *only* shown to the NIPSA’d user.

## Acceptance criteria

- [ ] NIPSA’d users still see their own annotations, with no indication that they’ve been hidden
- [ ] When a hidden annotation has replies, other users see that the annotation exists, but the content is hidden
- [ ] When a hidden annotation has no replies, it is hidden entirely (as it works currently)

## Suggested implementation

- Add a field to annotations in the search index to indicate whether they have replies
- When a new reply is created, re-index its immediate parent to set this field to `true`
- Only exclude annotations with the `nipsa` flag set if they also have no replies
- Update the [search presentation logic](https://github.com/hypothesis/h/blob/master@%7B2017-03-21%7D/h/views/api.py#L313-L325) to strip out the content of an annotation when the requesting user should not be able to see it
- Add functionality in the client to be able to show a content-stripped annotation (see [latest design mock-up](https://docs.google.com/presentation/d/1XSQoSwfmuPjtPPW6mUeGo_4d1YnBB7ds1fpP939XqMg/edit#slide=id.g1c59f62733_0_0))

## Known considerations

- As [pointed out by @chdorner](https://hyp.is/PX5NWg1bEee7SFPI4vkV5g/github.com/hypothesis/product-backlog/issues/184), an annotation returned from the API without a `text` value gets treated as a highlight, so we need to make sure there’s a way to distinguish between an annotation with its content hidden and a highlight.
- The badge endpoint also uses the search engine, but doesn’t separate replies: we should make sure that we don’t break the count here.
- There is an edge case here where a NIPSA’d user replies to their own annotation (or that of another NIPSA’d user), in which case it will show up blanked out with no replies. This may well be something we choose to live with until it becomes an issue.

**Comment by seanh** [comment]
I believe this is done and on prod now? (Both frontend and backend)

**Comment by dhwthompson** [comment]
Almost. We still haven’t done a client release with the changes in https://github.com/hypothesis/client/pull/363, so the moderation banner is still showing up for hidden annotations that have replies:

<img width="461" alt="Errant moderation banner" src="https://cloud.githubusercontent.com/assets/32775/25775264/065a8d8c-3256-11e7-8539-3e65c19e1ae5.png">

**Comment by robertknight** [comment]
^ I have just done said client release.
