### ISSUE TITLE
Return flagged annotations for a group reader for a specific URI and group

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#243]
## User story

As a group reader, I want to be able to see the annotations that I've flagged for a specific group and URI, so that I know which annotations have been flagged when I load a page.

## Background

This is part of the work for group moderation, from the reader's perspective. This work is an extension of #207 which completes the BE API work, and details the FE component needed to show flagged annotations for the reader. 

## Acceptance criteria

- [ ] Any annotations that have been flagged by the user should show a red flag, indicating that the annotation was flagged. 
- [ ] The flag is only visible to the group member that flagged it (so that other group members can flag the annotation if needed). 

## Notes

This work is the final piece of flagging an annotation for a group member. 
This work is an extension of #207, and was broken down from this spike: #182
Also linking it to this work: #164, which echoes the need for the second acceptance criteria - that the red flag should only be visible to the group member that flagged it.

**Comment by chdorner** [comment]
Closing this, as it's done and out in production.
