### ISSUE TITLE
don't cover my pdf with your sidebar!

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#25]
A very simple CSS tweak will mostly solve the problem for our PDF viewer.

https://docs.google.com/document/d/1HR5h_AOj-LcjwYwqr-2Q62Yt9v1QALdmLtRlaA3RayI

This is deployed now for the instance of https://github.com/hypothesis/pdf.js-hypothes.is used in the Canvas app.

**Comment by klemay** [comment]
Related request, asking for sidebar on the left: https://hypothesis.zendesk.com/agent/tickets/2111

This user's needs would be met if the sidebar did not cover the window at all, but the option to anchor the sidebar on the left would also (I imagine) be useful for languages written/typed right-to-left.

**Comment by judell** [comment]
Closed by https://github.com/hypothesis/client/pull/2573.
