### ISSUE TITLE
Poor user experience when trying to flag an annotation when not logged in

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#261]
### Steps to reproduce
1. Log out (or don't login) to the client
2. Visit a publisher page that has the sidebar embedded and the moderation feature enabled
3. Click the flag button on one of the annotations

### Expected behaviour
 
Some sort of user friendly error message that explains:

1. What went wrong - flagging the annotation failed
2. What the user can do about it - login

It might be nice if the actual error message could contain a clickable login link / button?

### Actual behaviour

An unfriendly error message is shown:

> **Flagging annotation failed**
>
> 404 Not Found. Either the resource you requested doesn't exist, or you are not currently authorized to see it.

![peek 2017-04-06 10-38](https://cloud.githubusercontent.com/assets/22498/24748614/22281d00-1ab8-11e7-8816-9d7b8c0379b3.gif)

After a few seconds the error message disappears by itself. If you click on the error message it disappears immediately.

Problems with this error message:

* Contains technical jargon:

   * 404 Not Found is an HTTP response type
   * By "resource" it's referring to HTTP resources
   * "not currently authorized it" (instead of not logged in)

   All three should be removed from the user error message.

* It says that _either_ the resource doesn't exist or you're not authorized, but in fact we know the resource _does_ exist and the problem is definitely that the user isn't authorized (and also, both "the resource doesn't exist" and "you're not authorized" are meaningless jargon to the user).

* It doesn't tell the user what they can do about it.
### Your solution

Even though I think they're terrible, I'd suggest still using the floating-red-toaster-bubble-that-disappears approach to error messages (since that's not unique to this error message, it's the main way the client currently has for showing error messages, replacing that is a bigger job), and for now simply changing the error message. Maybe something like this:

> **Login to flag annotations**
>
> You must be logged in to flag annotations.

I said above that it'd be nice if the error message itself could contain a login button or link. Unfortunately I don't think these toaster bubble error messages can - clicking anywhere on the bubble causes the bubble to disappear.

### Additional details

* I think it's important to realise that this is related to <https://github.com/hypothesis/product-backlog/issues/169> (the client needs to handle OAuth-related errors in a user-friendly way) - when the user gets logged out of the client because their OAuth token expires then flagging will start producing the error message above.

   #169 runs into a similar problem - when the user has been logged out because the client was unable to refresh their OAuth access token (this will happen sometimes, unavoidably) we currently don't have a great way to display an error message to the user.

   So I think there is general issue here along the lines of _the client lacks good ways of showing error messages_.

   **But** importantly when the user has been logged out because the client was unable to refresh their OAuth access token (this will happen sometimes, unavoidably) they will **still be logged in to the eLife** website. So telling them that they need to "log in" doesn't really help - from the user's point of view they're already logged in. They need to reload the page. But one of the (many) things that will start going wrong when this happens if that flagging will show this "404 Not Found. Either the resource you requested doesn't exist, or you are not currently authorized to see it" which of course doesn't help the user (to know that they need to reload the page).

   **Suggestion**: When this OAuth logout has happened and the user needs to reload the page, I think we need to put the client into a "broken mode" where they can still read public annotations, but trying to _do_ anything (annotate, highlight, reply, flag...) shows a "You need to reload the page" error message. But this is for #169.

* This could be handled as a separate issue - if you click on the flag multiple times it creates multiple error messages:

   ![peek 2017-04-06 10-39](https://cloud.githubusercontent.com/assets/22498/24748702/6921f6b8-1ab8-11e7-9bb2-fdd87e36a95a.gif)

   If it's possible to implement easily (I'm not sure whether it is) it'd be better to:

   1. Not create multiple of the same error at once
   2. On subsequent clicks flash the existing error for attention
   3. Each subsequent click should reset the lifetime of the existing bubble (so it doesn't disappear while the user is reading it)

* Not really part of this issue, but maybe worth noting for information, what happens when you click on the other button on annotations when you're not logged in is completely different:

   ![peek 2017-04-06 10-45](https://cloud.githubusercontent.com/assets/22498/24748740/8e9f6114-1ab8-11e7-91bc-59fa9ae9dab6.gif)

   In a way this is actually better:

   * I think you _could_ put a log in button / link in this error message
   * The error message doesn't disappear by itself
   * Multiple clicks doesn't duplicate the error message (although they don't do anything to draw attention to the existing message either - user may think clicking is just doing nothing)

   On the other hand:

   * It says you must be logged in to create _annotations_ when the button the user clicked was _reply_
   * The error message is under a collapsible hide/show replies thing as if it is a reply

   Anyway, that's a separate issue. (And of course you can also try to create annotations or highlights when logged out, which produces another two different error message behaviors.)

**Comment by seanh** [comment]
Update: https://github.com/hypothesis/client/pull/374 and https://github.com/hypothesis/client/pull/375 are merged so the error message is not as bad any more, but we can still also make it hide the flag button when you're not logged in so that the error message doesn't show at all? Scored as 2.

Talking to @fatbusinessman about this a minute ago I think there's a good argument for hiding the flag button only when not logged in, but not necessarily hiding other buttons (reply, page note, annotate, highlight), because those buttons are more core to what the product offers so we may want users who don't have accounts to see that those actions are there, whereas flagging is probably not core.

Also hiding just the flag button is less work and I think probably less controversial.

So I think we have 3 options now:

1. Close this issue now - go with the improved error message that we now have
2. Hide just the flag button when logged out
3. Hide all the buttons that you can't use when logged out

@ajpeddakotla ?

**Comment by ajpeddakotla** [comment]
Agree w/ your assessment @seanh and @fatbusinessman - Let's close the issue - we're fine with the error message we have now.

**Comment by nickstenning** [comment]
Ok, closing and marking as done in the Not-Really-A-Sprint.
