### ISSUE TITLE
You shouldn't be able to flag your own annotations

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#262]
I think the client probably shouldn't show the flag button on the user's own annotations. At an API level, maybe the server shouldn't allow a user to flag their own annotation either.

![peek 2017-04-06 14-12](https://cloud.githubusercontent.com/assets/22498/24755738/3766f892-1ad3-11e7-964f-3b4d91a7a085.gif)

**Comment by nickstenning** [comment]
Let's just do this client-side. There's no harm in allowing users to flag their own annotations via the API, it's just a user experience problem IMO.
