### ISSUE TITLE
TASK: Use annotation formatters in websocket annotations

### ISSUE THREAD

**Issue by chdorner** [hypothesis/product-backlog#264]
### Context

We recently introduced annotation formatters in the API and added a bunch of them([`flagged`](https://github.com/hypothesis/h/blob/master/h/formatters/annotation_flag.py), [`hidden`](https://github.com/hypothesis/h/blob/master/h/formatters/annotation_hidden.py), [`moderation`](https://github.com/hypothesis/h/blob/master/h/formatters/annotation_moderation.py)).

But the realtime websockets code, still [only renders the annotation with the presenter, and not the formatters](https://github.com/hypothesis/h/blob/5140713ee900c9b5294dd0a37499699a524b2fb9/h/streamer/messages.py#L151).

In practice, this means that the JSON payload of an annotation transferred from the server to the client in the realtime websocket API does *not* have either of the `"flagged"`, `"hidden"`, or `"moderation"` keys.

Rendering an annotation object for a given user should result in the same output both for the API and the WebSocket, and more generally the view of a given annotation in a given format should be consistent across the external APIs of `h`.

### Task

Ensure that "rendered" annotations look the same whether returned from the HTTP API or from the WebSocket API.

### Discussion

The initial implementation of this may need to be pretty ugly. That's fine.

### Points

2017-04-20: 3

**Comment by lyzadanger** [comment]
Closing in favor of https://github.com/hypothesis/h/issues/5487 which includes this task.
