### ISSUE TITLE
Derive annotation location sort order at page load

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#266]
### Problem you are trying to address with this feature
Right now, our "location" sort order is derived from the sort order at the time that each annotation was created.  However, this means that for pages that change the location order will no longer be correct.  It's important to note that this isn't necessarily always because the related content was shuffled around-- it could be because different advertisements were in place, or page templates were adjusted, etc.

This has three implications:
- The cards in the sidebar are seemingly randomly organized.
- It appears our sort control is broken.  
- Projects like Climate Feedback that annotate the title in order to have key annotations stuck to the top of the sidebar have their summary annotations floating midway down the annotation stream.  (Like here: https://via.hypothes.is/https://www.bostonglobe.com/opinion/columns/2017/03/14/why-are-climate-change-models-flawed-because-climate-science-incomplete/hekwjPBTScRpFyXaXnrWhI/story.html) 

It turns out that in practice, many pages change-- particularly on news sites.  A casual examination of climate feedback's critiques shows that about 35% of them suffer from this.  http://climatefeedback.org/feedbacks/

### Your solution
Derive location sort at the time of reanchoring.

I completely understand that this might have performance indications.  So perhaps a spike is warranted here to first evaluate.

Previously filed as a bug: https://github.com/hypothesis/client/issues/174

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/client/issues/248
