### ISSUE TITLE
Distinguish between Hypothesis owned v. Hypothesis namespaced groups

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#269]
### User Story
As a Hypothesis user, I want to be able to distinguish between Hypothesis owned groups and groups where the group lives in the Hypothesis namespace, but is moderated and run by other entities (publishers, community experts, etc.)

### Background
We have, on our roadmap, instances where we will create groups for our users that will live in the Hypothesis namespace, but will ultimately be moderated and run by those communities. We need to have some way to distinguish these groups from Hypothesis controlled and moderated groups. 

### Acceptance Criteria
- There should be delineation between Hypothesis owned groups, and publisher/community owned groups that are in the Hypothesis name space
- Users should be able to see who moderates/ “owns” the group. 
- Users should have some way of knowing that if they post annotations in the group, those annotations will be moderated by the appropriate owner of the group. 

### Designs (TBD)

**Comment by seanh** [comment]
@ajpeddakotla Can we close this one? I think this is covered by user stories like <https://github.com/hypothesis/product-backlog/issues/418> and <https://github.com/hypothesis/product-backlog/issues/419>. (Although I think the way this one is written up is a really excellent user story, maybe we should copy-paste some of the text into <https://github.com/hypothesis/product-backlog/issues/418>)

**Comment by ajpeddakotla** [comment]
Closing this in favor of: https://github.com/hypothesis/product-backlog/issues/497
