### ISSUE TITLE
(SPIKE) add an identifying string to the user-agent header that via relays

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#27]
Atypon is a journal-hosting service that welcomes via but wants to be able to identify it, either by IP range or User-Agent string. 

Per this eng@ thread, https://groups.google.com/a/list.hypothes.is/forum/#!topic/eng/qC9Bckml5Xw, the latter seems like an easy and satisfactory solution for Atypon (and others), and Marty Picco (Atypon VP) confirms it'll work for them. 

When browser sends:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 afari/537.36

then via relays that unchanged.

Marty confirms that if via tacks on an identifier, e.g. Hypothesis-Via (or whatever we deem appropriate), like so:

Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/52.0.2743.82 afari/537.36 Hypothesis-Via

then Atypon can look for it and use it to classify via as an allowed crawler of their system.

**Comment by judell** [comment]
Follow-up with Marty:

Hi folks,

According to https://via.hypothes.is/https://httpbin.org/user-agent, the string "Hypothesis-Via" is included in the User-Agent header, as per https://github.com/hypothesis/via/commit/46e84af472249ca84e01f1fd09baa9a4c1e9e5fa#diff-d7a39c0d6fdaa37450167e35b2dbec97.

Note that we do not transmit cookies or auth headers, though: https://github.com/hypothesis/via/blob/81f950e04c2c787641b7141eaef0beb82937c093/via/security.py#L12-L17. I see that http://www.journals.uchicago.edu/doi/full/10.1086/692829, for example, which is openly available, leads to https://via.hypothes.is/http://www.journals.uchicago.edu/action/cookieAbsent when sent through via. 

Not sure what to do about "Cookies required" -- what do you think?

**Comment by chdorner** [comment]
We strip the `Cookie` header from the request to the origin, and then the `Set-Cookie` from the response back to the browser. This is done for security reasons, as the cookies would all be shared between the websites a user would visit through via.
I'm guessing that `journals.uchicago.edu` requires cookies for some reason? Unfortunately, I don't think there is much we can do about that.

**Comment by judell** [comment]
> I'm guessing that journals.uchicago.edu requires cookies for some reason?

They do. More from Marty today:

> Every article access requires a session, even from crawlers.  Session data includes (but might not be limited to) JSESSIONID cookie, which is used by our load balancer among other things.  No cookies -> no session -> "Cookies Required"

I guess we should just encourage them to embed H, eh?
