### ISSUE TITLE
If a moderator hides their own annotation it shows as unhidden after they reload the page

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#281]
As reported by @robertknight here <https://github.com/hypothesis/product-backlog/issues/262#issuecomment-292503040>:

> Related to this, a user can currently also _moderate_ their own annotations but because an annotation is never hidden from its author, this means that:
> 
> 1. User flags and hides their own annotation. Perhaps they are testing out the moderation tool. When the user clicks "Hide" the request currently succeeds.
> 2. When the same user reloads the page however, the annotation is shown as unhidden - because annotations are always unhidden to their authors. Other moderators in the group (when we support multiple moderators) will see that same annotation as hidden however.
> 
> We can avoid this by preventing users from moderating their own annotations as well.

Here's a video of the issue. In this video I'm logged in as a moderator, looking at my own annotation (which has already been flagged). When I click the _Hide_ button the annotation correctly shows as hidden, but then after I reload the page and open the sidebar again it incorrectly shows as unhidden. This only happens when a moderator is looking at their own unhidden annotation:

![peek 2017-04-26 11-51](https://cloud.githubusercontent.com/assets/22498/25431044/d6e84526-2a76-11e7-87b6-438126c6182a.gif)

**Comment by dhwthompson** [comment]
I’ve fixed this in https://github.com/hypothesis/h/pull/4550 by always showing moderators the true state of all annotations, including their own.
