### ISSUE TITLE
User reported bug - Adder not showing on LinkedIn Articles

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#283]
Hi. I've been using Hypothes.is while reading through LinkedIn articles. Unfortunately, there seems to be an odd page element that causes the 'Annotate | Highlight' pop up not to appear. The only time it appears is if you let go of your click at the sides of the page where the whitespace is.

I've attached a short video demonstrating the issue.
(See video linked on ticket here: https://hypothesis.zendesk.com/agent/tickets/1126)

**Comment by klemay** [comment]
This also happens with New York Times comments: https://github.com/hypothesis/product-backlog/issues/445 - could these be related?

**Comment by ajpeddakotla** [comment]
Closing this in favor of: https://github.com/hypothesis/client/issues/479
