### ISSUE TITLE
Allow publishers to customize user profile, Help and Log out links

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/product-backlog#284]
### Ability to add links to the user menu in configuration.
The best use case that I can think of is to add a Logout link which could trigger the logout on the publisher website
<img width="146" alt="screen shot 2017-05-06 at 13 55 00" src="https://cloud.githubusercontent.com/assets/383397/25775890/ba207f9e-3264-11e7-9e7d-e3c5825faa93.png">

### Your solution
```
window.hypothesisConfig = function () {
  return {
    "services": [{
      authority: 'publisher-group',
      onLoginRequest: function () {
        window.location.replace('/login');
      },
      // to add profile, help, logout
      onLogoutRequest: function () {
        window.location.replace('/logout');
      },
     onProfileRequest: function () {
        window.location.replace('/profile');
      },
     onHelpRequest: function () {
        window.location.replace('/help');
      },
    }]
  };
};
```

**Comment by robertknight** [comment]
One consideration if we were to implement something like the proposal is that the host page should only be allowed to supply `http` or `https` links. Otherwise I can see someone using this for good/evil to run script via `javascript:` URLs.

**Comment by ajpeddakotla** [comment]
We have initial designs for this as well - we just have to spec them out.

**Comment by sean-roberts** [comment]
add `onLogoutRequested` `onProfileRequested`

**Comment by nickstenning** [comment]
@sean-roberts to update with the scope within which this was pointed at 3 points -- basically to hack this in consistent with onLoginRequested etc.

**Comment by sean-roberts** [comment]
Rob confirmed with Nathan that they are wanting control over: profile, help, login/register/logout

**Comment by seanh** [comment]
I believe log in and sign up are already done, so I'm taking this issue to be for enabling overriding of the profile link (your username, **seanh** in the screenshot below), **Help** and **Log out** in the same way as we've already done for log in and sign up:

![screenshot from 2017-05-16 18-01-10](https://cloud.githubusercontent.com/assets/22498/26118408/b2328de0-3a61-11e7-83b1-49087fbffa28.png)

So my understanding is that we _won't_ be enabling overriding of the **Account settings** link in that same menu (at least not for this ticket).

**Comment by seanh** [comment]
Updated the title to reflect my understanding
