### ISSUE TITLE
In publisher groups allow the username to be a link

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/product-backlog#285]
### When using a publisher group the username links are not working.
It would be great if we could configure the client to convert the username to a profile page on the publisher site.

<img width="175" alt="screen shot 2017-05-06 at 14 15 00" src="https://cloud.githubusercontent.com/assets/383397/25775979/c36ae34e-3266-11e7-921d-56f8b0852032.png">

### Your solution
```
window.hypothesisConfig = function () {
  return {
    "services": [{
      authority: 'publisher-group',
      usernameLink: function (username) {
        window.location.replace('/user/' + username);
      }
    }]
  };
};
```

**Comment by robertknight** [comment]
This is closely related to https://github.com/hypothesis/product-backlog/issues/284

**Comment by ajpeddakotla** [comment]
This one needs some more thinking @nlisgo - we will have the ability in the future (after we ship this work on production) to point the user to their Hypothesis user profile at https://hypothes.is/users/artijwalker. 

One question we need to figure out is wether we want to direct users to an H profile page or an eLife one.....

**Comment by nlisgo** [comment]
@ajpeddakotla If there is a H profile page available then I don't mind if the default behaviour is to route users to that profile but we will want the ability to route users to a profile on our site.

**Comment by ajpeddakotla** [comment]
In conversations with Nathan, we've decided to have this link to the eLife user profile page.

**Comment by ajpeddakotla** [comment]
Closing this card out as it is part of the previous card of work: https://github.com/hypothesis/product-backlog/issues/350
