### ISSUE TITLE
Publish group grantToken expiring after 10 minutes

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/product-backlog#287]
### For publisher group sessions allow a new grantToken to be supplied without a page refresh
The grantToken will have a maximum life of [10 minutes](https://hyp.is/s42gGDKkEeeR67u9So3keQ/h.readthedocs.io/en/latest/publishers/authorization-grant-tokens/) but it could be sooner according to the grantToken `exp` value.

On the client we should be able to supply another grantToken before the previous one expires so that user can continue to annotate.

**Comment by nickstenning** [comment]
As discussed IRL, the lifetime of the grant token doesn't place a limit on the period during which the user can annotate on the page. The Hypothesis client will exchange the grant token for an API access token on startup and manage the refreshing of this access token without any further interaction.
