### ISSUE TITLE
More link font is not configurable

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/product-backlog#288]
### Steps to reproduce
1. Set the following configuration:
```
window.hypothesisConfig = function () {
  return {
    branding: {
      selectionFontFamily: 'Georgia, Times, serif'
    }
  };
};
```
2. Annotate enough text to trigger the display of the More link for the selected text

### Expected behaviour
The More link should use the font set in the config `selectionfontfamily`

See: http://h.readthedocs.io/projects/client/en/latest/publishers/config/?highlight=annotationFontFamily#cmdoption-arg-selectionfontfamily

### Actual behaviour
The More link has the font: `"Helvetica Neue", Helvetica, Arial, "Lucida Grande", sans-serif`

**Comment by robertknight** [comment]
This was fixed in https://github.com/hypothesis/client/commit/30215e8d882468559850760a08210f6779512e1e
