### ISSUE TITLE
Configure the client to only highlight annotated text when the client is open and hide the highlight feature when closed

### ISSUE THREAD

**Issue by nlisgo** [hypothesis/product-backlog#289]
### Allow text highlighting to be hidden by default
We would like the highlighted text on the page to only be visible when the hypothes.is client is open. Currently, the only way to hide the highlighted text is to click on the eye icon.

### Your solution

If we could give a name to the mode of behaviour that is described above then we could allow that mode to be employed by setting a configuration variable such as:

```
window.hypothesisConfig = function () {
  return {
    branding: {
      mode: 'toggle'
    }
  };
};
```

**Comment by ajpeddakotla** [comment]
@nlisgo we're working on this feature currently and tracking the work here: https://github.com/hypothesis/product-backlog/issues/273. Closing this as this is a dupe.
