### ISSUE TITLE
STORY: Upgrade `support` to Ubuntu 16.04

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#294]
## Context

Our `support` machine (on which we host https://jenkins.hypothes.is) runs Ubuntu 14.04 along with the rest of our infrastructure. At some point we want to upgrade all the machines to 16.04, the latest stable release of Ubuntu, supported until ~2021.

The fact that we're still running 14.04 caused us a problem this week when we went to perform a critical security upgrade to Jenkins. This upgrade was made problematic by the fact that Jenkins now requires Java 8, which is not easily available on 14.04.

## Story

Use `support` as a test-run for upgrading our managed infrastructure to 16.04.

## Discussion

I'd suggest that we ensure that as part this work we:

- make sure we can bring up a brand new `support` box on 16.04 using whatever changes we make to the infrastructure code, even if we choose not to migrate to a new machine
- if we do migrate to a new machine, ensure we carry across all jenkins configuration and state to the new machine before shutting the old one down

**Comment by seanh** [comment]
We probably want to go straight to 18.04 now?

**Comment by robertknight** [comment]
18.04 is an LTS release so yes, I think we should.

**Comment by seanh** [comment]
Closing in favour of https://github.com/hypothesis/product-backlog/issues/762
