### ISSUE TITLE
TASK: Provision necessary Elastic Beanstalk security groups

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#300]
## Context

In order to migrate to Elastic Beanstalk, we need to be able to bring up application instances in our `hop-prod` VPC which have permission to talk to required backing services (monitoring, RDS, etc.)

## Task

- [x] Create named security groups and update existing SG inbound rules so that:

     - all instances can send metrics to `mon`
     - `h` can talk to RDS

- [x] Update environment manifests in the deployment repository.

**Comment by chdorner** [comment]
hypothesis/playbook#132
hypothesis/deployment#1
