### ISSUE TITLE
TASK: Provision dedicated subnets for Elastic Beanstalk load balancers

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#301]
## Context

Elastic Beanstalk needs to provision load balancers in our VPC. For consistency with Skyliner we should bring these up in dedicated subnets.

## Task

- [x] Provision an "lb" subnet in `hop-prod` for each availability zone.
- [x] Update environment manifests in `deployment`

**Comment by nickstenning** [comment]
https://github.com/hypothesis/playbook/pull/131

**Comment by chdorner** [comment]
hypothesis/deployment#1
