### ISSUE TITLE
TASK: Report deployment status to Slack

### ISSUE THREAD

**Issue by nickstenning** [hypothesis/product-backlog#303]
## Context

In order to make it easier for developers to know when a deployment is happening, and whether it has succeeded or failed, we want to notify Slack with deployment status.

## Task

At a minimum, we want reports of:

- deployment of `$APP` to `$ENV` started
- deployment of `$APP` to `$ENV` completed successfully
- deployment of `$APP` to `$ENV` FAILED

## Discussion

There are many ways we could do this. One option is using something like the Jenkins [Slack Plugin](https://wiki.jenkins-ci.org/display/JENKINS/Slack+Plugin) including its support for Pipeline jobs (see the docs on the linked page).

**Comment by chdorner** [comment]
While we definitely need Slack notifications about failed build jobs (Jenkins, similar to Travis). We should investigate if it makes sense to send Elastic Beanstalk SNS notifications to Slack, this way we would possibly get additional events piped into Slack that are not based on a Jenkins deploy job (autoscaling events for example, or deploy notifications when we update the environment). People seem to be doing this with AWS Lambda functions: https://medium.com/cohealo-engineering/how-set-up-a-slack-channel-to-be-an-aws-sns-subscriber-63b4d57ad3ea

**Comment by chdorner** [comment]
I have enabled SNS email notifications to my email and it looks like we're only getting these types of notifications:

* Environment health has transitioned from Info to Ok.
* Environment health has transitioned from Ok to Info. 
* Environment health has transitioned from Warning to Ok.
* Environment health has transitioned from Warning to Info.
* Environment health has transitioned from Degraded to Warning.
* Environment health has transitioned from Info to Degraded.
* New application version was deployed to running EC2 instances.
* Failed to deploy application.
* Unsuccessful command execution on instance id(s) i-... _(Presumably this was when I tried deploying a non-existent Docker tag)_

None of them seems to be particularly interesting to get into Slack, other than the normal Jenkins deploy job started/succeeded/failed (which got merged in hypothesis/deployment#4)
