### ISSUE TITLE
TASK: Update docs and tools for SSH in Elastic Beanstalk

### ISSUE THREAD

**Issue by dhwthompson** [hypothesis/product-backlog#304]
# Context

So that developers can still get easy access to app servers for maintenance tasks (search reindexing, for instance), we want a documented way to get SSH access to an app server.

# Task

At a minimum, we need to update the [documentation in our playbook](https://github.com/hypothesis/playbook/tree/master/docs) so that it accurately reflects how we get SSH access to a server for a given app. If we can update the [`h-ssh`](https://github.com/hypothesis/playbook/blob/master@%7B2017-06-01%7D/tools/h-ssh) tool so that this works automatically, even better.

**Comment by nickstenning** [comment]
Docs and `h-ssh` updated.
