### ISSUE TITLE
Spike [???]: How can I authenticate into Hypothesis using my Canvas account? 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#308]
### Background
Currently, the biggest user problem faced by Canvas users is the inability to use their Canvas accounts to authenticate into Hypothesis, causing headaches for both the user and Jeremy, as he has to manually create accounts for all the students in the classroom. 

### User Story
As a student I would like to be able to authenticate into Hypothesis using my Canvas account, so that I do not have to create a separate account. 

### Questions
1. Can a student keep the access to their Hypothesis account after they have left the school (i.e. No longer have access to their Canvas credentials)? 
2. Will the student's annotation history be visible on the Activity Pages view? Currently, 3rd party users do not have access to their annotation history on activity pages. 

### Additional Info: 
Spec Sheet: https://docs.google.com/document/d/19dM-f4pScrhqmpHk6QHg36P3pVu6QTZ6wULmc_1ZTfM/edit#heading=h.penjuck3zeso - you can add more documentation to this or move it to this issue, if you like.

**Comment by jeremydean** [comment]
Ideally, I think the answer to both 1 and 2 should be yes. 

In terms of 2, it's pretty essential for the instructor if not for the student.

**Comment by ajpeddakotla** [comment]
@seanh @sheetaluk fyi from @judell He's included more background/expanded the discussion of authentication in Canvas in his doc here: https://docs.google.com/document/d/1iobDNeP9shOrnKX-oR9Yj9rLeozrHUlaB4BgdM0Ikyg/edit#heading=h.rj0h8gacbda7

**Comment by seanh** [comment]
Closing this spike as finished. I created four issues as a result of this spike:

1. https://github.com/hypothesis/product-backlog/issues/340
2. https://github.com/hypothesis/product-backlog/issues/339
3. https://github.com/hypothesis/product-backlog/issues/342
4. https://github.com/hypothesis/product-backlog/issues/341
