### ISSUE TITLE
Extend refresh token TTL for first party accounts

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#312]
In order to support the OAuth-based login flow described in the [design doc](https://docs.google.com/document/d/149Fntx5fQlrnjW5bgqC0booVlWOBZV4g1oFkpArh-QI/edit#) the service needs to support refresh tokens which have a TTL that is long enough that the user can remain logged into the client for a reasonable period of time while they are not using the client.

The current thinking is that this time will be kept in sync with the session TTL which is currently set at 7 days.

**Comment by seanh** [comment]
Closing this in favour of https://github.com/hypothesis/product-backlog/issues/329
