### ISSUE TITLE
Persist OAuth access & refresh tokens in client

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#315]
After completing the [authorization flow](https://github.com/hypothesis/product-backlog/issues/314) in the client, it should persist the access & refresh tokens for use when the client is next loaded. When the client next starts, it should load the persistent access & refresh tokens and use them instead of requiring the user to re-authorize the client.

The suggested implementation is that we'll persist this data to localStorage.

**Comment by seanh** [comment]
Backlog refinement says: we need to create a separate ticket for how login and logout will work when the user has both the Chrome extension and an embedded client. Does logging in to or out of one log you into / out of the other? If not what are the consequences of that (and are we happy with them)? If so, how does that work?

**Comment by seanh** [comment]
Closed in favour of https://github.com/hypothesis/product-backlog/issues/332
