### ISSUE TITLE
Problem: do we migrate existing cookie-based sessions to OAuth?

### ISSUE THREAD

**Issue by dhwthompson** [hypothesis/product-backlog#320]
Once we release OAuth login as a global feature, by default anyone who is logged into any Hypothesis client will need to re-authenticate (which, if they already have an active session on the hypothes.is domain, may not involve any action on their part beyond clicking “Login” in the client, depending on whether we streamline this process for our own clients). We need to decide whether we’re ok with this, or whether we want to do some extra work to transition these people onto new sessions more seamlessly.

**Comment by robertknight** [comment]
This should be solved by the seamless login proposal in https://github.com/hypothesis/product-backlog/issues/319 as cookie sessions will be automatically exchanged for OAuth tokens on first use of an OAuth-enabled first-party client. I am leaving this issue open to make sure we verify that it works as expected after implementing #319.

**Comment by robertknight** [comment]
There are basically only two solutions to this:

- We implement seamless login via cookies, in which case this is handled automatically.
- We do not implement seamless login, in which case users will be logged out in the first release after we enable OAuth and they will have to click "Log in" again

**Comment by robertknight** [comment]
The switch to OAuth was released long ago, and we decided not to migrate existing client sessions.
