### ISSUE TITLE
Provide ability to invalidate or work-around CDN cache after a client release

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#331]
The Hypothesis client is hosted at an entry point at https://cdn.hypothes.is/hypothesis . This script is cached by the CDN for a period of 30 mins, a time that is set by the [s3-npm-publish](https://github.com/nickstenning/s3-npm-publish) tool used to upload the client to the CDN. This means that immediately after doing a client release, the above URL continues to return the previous version of the client for up to 30 mins, which is a nuisance when testing.

**Constraints:**

1. The solution needs to work for both the `/embed.js` and `/app.html` routes which return references to the client's boot script.
2. This preferably should ideally be usable with both the bookmarklet and pages that embed the client directly, including Via.
3. We should be able to continue benefitting from the cache when not testing a new release.

**Some options:**

1. Add a feature flag to the service which causes the client URL to be returned with a cachebuster added for cohorts for whom it is enabled.
2. Support a query param on the `embed.js` route which causes a cache buster to be added to the client URL. An additional mechanism would then be needed to make sure that the client's app.html request included a cache buster.
3. Use CloudFlare APIs to invalidate the https://cdn.hypothes.is/hypothesis entry point when uploading a new release. Note that this only resolves the issue for the CDN cache. The browser may continue to return a cached copy of the boot script.

**Comment by seanh** [comment]
<https://github.com/hypothesis/h/pull/4582> (adds an `embed_cachebuster` feature flag that causes h to append a cache-buster query to the client URL) was merged. This solution should work. We said we'd leave this issue open in order to discuss alternative solutions but actually I think I'm just going to close this, lets see how using a feature flag works and if it turns out to be a problem we can revisit it.
