### ISSUE TITLE
Convert share links to use bouncer in sidebar/app

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#335]
### Problem you are trying to address with this feature

If a user shares an annotated document using the link generated by the client, it will always take the recipient to Via, even if they have one of our browser extensions installed.

### Your solution

Use https://hyp.is/go?url=$URL links instead which will take the user to the document using either via or directly if they have a suitable extension installed.

**Comment by dwhly** [comment]
Thanks for this.
