### ISSUE TITLE
https://github.com/hypothesis/h/pull/3970 did not completely fix the long-line-doesn't-wrap problem it addressed

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#343]
Example:

![image](https://user-images.githubusercontent.com/46509/28682985-c4d4ec74-72b3-11e7-8cb4-c1c525b332e2.png)

See https://hypothes.is/users/chunnan?q=uri%3Ahttps%3A%2F%2Fcommonfund.nih.gov%2Fsites%2Fdefault%2Ffiles%2FRM-17-026_CommonsPilotPhase.pdf. 

The problem is that the class attribute annotation-card__text, which has the overflow styling, is only applied to the first p element in the text.

**Comment by ajpeddakotla** [comment]
Closing this issue as it is being addressed here: https://github.com/hypothesis/h/issues/4727
