### ISSUE TITLE
Hide highlight visibility toggle when display mode set to "when sidebar is open"

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#346]
The client has an option to only show highlights [when the sidebar is open](https://h.readthedocs.io/projects/client/en/latest/publishers/config/#cmdoption-arg-showhighlights). In this mode, the behavior of the show/hide highlights toolbar button does not really make sense.

The solution @dawariley and I discussed yesterday and which I've run by eLife is to hide this toolbar button when the highlight display mode is set to "whenSidebarOpen".

**Comment by ajpeddakotla** [comment]
Closing this as we've completed the work.
