### ISSUE TITLE
<Final> eLife UI changes 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#350]
In talks with eLife there are some final UI changes that need to be made for launch. The changes are listed below and will be tracked in this one ticket. @dawariley will attach the final designs to this ticket. These changes will be made for eLife only

- [x] substituting the chevron for a close button (in the sidebar open/close toggle)
- [x] allowing re-positioning of the sidebar open/close toggle button
- [x] turning off the show/hide highlights button (when the client is configured to show highlights only when the sidebar is open)
- [x] dropping the drop shadow on annotation cards
- [x] moving the "Add Note" button from the toolbar into the sidebar
- [x] removing the bucket bar 
- [x] adding the divider lines between annotations/notes  (w:380px, h:1 px, #E1E1E1)
- [x] add a drop shadow along the left hand margin of the sidebar

**Comment by dawachan** [comment]
In response to your question @ajpeddakotla: "These changes will be made for eLife only (customized) with the exception of removing the drop shadow ( @dawariley is this still correct)"? The changes are part of moving our client towards being more universally customizable for publishers and our partners/clients. For now I think the best thing would be to push them out for eLife and then use this config as a springboard for future improvements to the UI/UX of our client, but to hold off on rolling it out globally until we have user tested designs.

**Comment by dawachan** [comment]
I've finally managed to see the current state of the eLife config (thanks to rob) - attaching a screenshot for reference. What this means is that we will need to make the following minor 3-4 additional configs in addition to those listed above, order for the design not to visually break and the UX to be poor.  These designs are proposed so that the sidebar remains unobstrusive for the brands and reflects well upon our brand. 

1. if we drop the drop shadow on the annotation boxes, we will need to add the divider lines.
2. we will need to make the bucket bar opaque and white to fit with the background.
3. we will need to line up the top bar to the current bucket bar, or just remove the bucket bar completely, and gain some pixel real estate on the page - this option is better and removes the need for #2.
4. in order to differentiate the siderbar from the white background, add a drop shadow along the left hand margin of the sidebar only.

Note that the new sidebar is narrower which gives more real estate back to the main view.

**Current config looks like this:**

![screen shot 2017-08-07 at 13 52 01](https://user-images.githubusercontent.com/5212631/29027502-cf4ce012-7b78-11e7-8ab1-efee1492fdd1.png)

**Comment by dawachan** [comment]
Revised UI which includes the 4 additional changes:

1. Annotations Tab selected
@ajpeddakotla @robertknight 

![elife annotations](https://user-images.githubusercontent.com/5212631/29182774-023389e6-7df8-11e7-9976-b82c37d9de69.png)

**Comment by dawariley** [comment]
![elife annotations](https://user-images.githubusercontent.com/5212631/29066335-d0320b20-7c26-11e7-96da-f6291a033e2f.png)

**Comment by dawachan** [comment]
2. Notes Tab selected


![elife notes](https://user-images.githubusercontent.com/5212631/29066358-e1a492ce-7c26-11e7-940c-9e5a8c7a75f2.png)

**Comment by dawachan** [comment]
@ajpeddakotla can you confirm the extra modifications are acceptable to you so they can be a) added to the checklist against this issue and b) I can share with Nick @ eLife.

**Comment by dawachan** [comment]
As requested by Rob - working on a mock of how the revised design looks with threaded conversations (ie. an annotation with replies visible).

**Comment by ajpeddakotla** [comment]
@dawariley these changes LGTM, and rolling them out for eLife makes sense, in terms of using this as a springboard for our design work. Thank you!

**Comment by dawachan** [comment]
I have reviewed the replies/threaded replies for the new eLife config and it looks identical to the current client - both on the same white background so no changes needed at present. We might want to optimize the icon size and check the grey colours for consistency with the rest of the UI. Will add a separate checklist for icon colours/size if needed. Any further design changes for annotation replies should be tackled in the future.

![screen shot 2017-08-08 at 12 06 29](https://user-images.githubusercontent.com/5212631/29115345-3ebb5358-7cef-11e7-94d6-3227109f7596.png)
[](url)

![screen shot 2017-08-08 at 12 10 37](https://user-images.githubusercontent.com/5212631/29115350-45d56cf0-7cef-11e7-9875-af15ccc05040.png)

**Comment by dawachan** [comment]
@ajpeddakotla added the 3 additional design fixes to the issue checklist above. thx

@robertknight you might want to review the checklist and confirm that it's an acceptable list. cheers!

**Comment by segdeha** [comment]
@dawariley Minor question: In the case where they substitute an `X` for the chevron, what does it look like when it's closed? Seems unintuitive to click an `X` to open the sidebar.

**Comment by dawachan** [comment]
@segdeha for the eLife implementation there won't be a minimized sidebar state - it's either fully open or closed, so the problem of what to display in the collapsed sidebar goes away.

**Comment by robertknight** [comment]
This list looks fine to me @dawariley . There are some implementation questions around whether we expose each of these changes as its own configuration option, or group multiple of these changes into one or more new config options or feature flags. We'll figure that out as we work on it.

**Comment by ajpeddakotla** [comment]
The email we're going to send to eLife. @dwhly please review. 

Hi Nick and Giuliano,
First of all thanks for bearing with us whilst we addressed your design/UX feedback. Below is the list of additional properties we have identified that we need to support on our side in order to get closer to the revised UI, and attached is a mockup of how the side bar will look once we allow for these custom configurations.

-  substituting the chevron for a close button
-  allowing re-positioning of the chevron
-  turning off the show/hide highlights button
-  dropping the drop shadow
-  moving the notes button to the notes tab
-  turning off annotation count markers in bucket bar
-  removing the bucket bar
-  adding the divider lines between annotations/notes
-  add a drop shadow along the left hand margin of the sidebar
I am attaching a screen grab of what the current config supports.

With regards to the tab redesign - it's something that we will approach in the future as part of a bigger redesign of our client, but I've included an additional design of how it might look when it's more minimal and paired back.

I'm attaching design explorations for improving the 'getting started' UX including:

A) an inline box to replace current version.
B) step-by-step walkthrough highlighting the key features in context - we could also stop at the light box step.
C) walkthrough of the key features - to be animated.

In terms of timeframes it seems better to focus on delivering approach A in the near term as we will be looking at revising the on boarding experience globally as well as running our own testing. 

I had a question about the happy path for eLife users as I'm not sure what the CTA for the action button to launch the sidebar is. I am under the impression it is via an "add comments" button - it would be helpful to see a design or screenshot.  The informational messaging inside the Getting Started box can be changed accordingly or by adding an additional bullet point. Also, I wasn't sure whether you are framing the annotation service more as a way for users to comment vs. annotate, so again the copy can be adjusted to match. e.g. instead of 'Start Annotating' it might be better to say 'Add a Comment' or 'Introducing Comments'.

**Comment by dwhly** [comment]
This sounds fine @ajpeddakotla.  Thank you.

By the way, I would prefer if at all possible that they use "Annotate" instead of "Comment".  Any chance of that?  A bit of branding in a way.

**Comment by dawachan** [comment]
Thanks for approving my email draft @dwhly. I'll send it out tomorrow first thing. I'm going to check with Nick how they're branding the feature in terms of their end-to-end user journey. It might be that users click on a comment CTA but I can word the email differently to recommend keeping consistency by using 'Annotate'. Will find out more and feedback.

**Comment by dawachan** [comment]
sketch file: https://drive.google.com/open?id=0Bww2MCTPhg08dkc0cTl1a3V2aEU

**Comment by dawachan** [comment]
@ajpeddakotla eLife is waiting for timelines on this SOW. placeholder reminder to follow up with @robertknight

**Comment by dawachan** [comment]
![elife notes](https://user-images.githubusercontent.com/5212631/30544939-0c93a23a-9c80-11e7-8785-b897cdea63fa.png)
 @sheetaluk - showing updated '+ New note' button

**Comment by dawachan** [comment]
![add_note](https://user-images.githubusercontent.com/5212631/30545080-81c97b42-9c80-11e7-818c-a20d16d6b41d.png)

**Comment by dawachan** [comment]
@sheetaluk Nick has confirmed that the position of the close button from the top should be set to **106px** which places it around **10px below the header**.

**Comment by ajpeddakotla** [comment]
@sheetaluk include the change to the username (allowing it to link to an eLife site) in this work as well please: https://github.com/hypothesis/product-backlog/issues/285

**Comment by ajpeddakotla** [comment]
Tagging this issue that we'll be addressing in this work as well: https://github.com/hypothesis/product-backlog/issues/346

**Comment by robertknight** [comment]
The work on this is substantially done modulo some follow-up bugs which have been opened and tagged with the eLife label.
