### ISSUE TITLE
Final onboarding/getting started 

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#351]
The need to address this was highlighted in Nick @ eLife's recent user study:

"All of our study participants after signing in were unsure what they should do next. We suggested a small visual cue to get started."

**Comment by dawachan** [comment]
**What we currently have:**

![getting started - getting started](https://user-images.githubusercontent.com/5212631/29356318-ca4a210c-826b-11e7-82e8-fd66e4759621.png)

**Comment by dawachan** [comment]
**Proposals for revised Getting Started:**

- Proposal A
![getting started - a](https://user-images.githubusercontent.com/5212631/29124759-bf9a6be0-7d11-11e7-8c3b-f4c4b26e30e7.png)

- Proposal B
![getting started - b](https://user-images.githubusercontent.com/5212631/29124765-c44b9c86-7d11-11e7-84b4-cd946d91d863.png)

![getting started - b1](https://user-images.githubusercontent.com/5212631/29124773-cc2226b4-7d11-11e7-822b-b6be757497fd.png)

![getting started - b2](https://user-images.githubusercontent.com/5212631/29124785-d14aad0a-7d11-11e7-8751-28bb9e7fa61c.png)


- Proposal C
![getting started - c](https://user-images.githubusercontent.com/5212631/29124791-d4d6d278-7d11-11e7-82bb-1cff7fe6f78b.png)

**Comment by dawachan** [comment]
As mentioned in our review meeting we need to define the rules around the display of the 'Getting Started' box. Proposal: It displays onLaunch of the sidebar for the first time and persists until a user makes their first annotation and then goes away. Users can also close it before they make their first annotation by manually clicking the 'x'. note: this doesn't affect the 'There are no annotations at this time' messaging - redesigning this isn't part of this phase of work.

**Comment by dawachan** [comment]
Based on review with Nick and iteration here's what I'm proposing to replace the current 'Getting Started' box. e-Life button and annotate icon would be blue accent colour, default for Hypothesis client would be grey. 

Configurable options:

- [ ] + Add note button colour
- [ ] Annotate icon colour

![getting started - revised](https://user-images.githubusercontent.com/5212631/30374915-7892b0e4-987e-11e7-85d3-9037b92fb2f4.png)

**Comment by robertknight** [comment]
@dawariley - Where is the "New note" button referenced in the onboarding card?

**Comment by dawachan** [comment]
It's not currently but we are adding a New note button to the client universally.

**Comment by dawachan** [comment]
eLife will only have the 'New note' button, H client will have the existing bucket bar button plus the additional 'New note' button. It was Dan's request to have them both present. We might also want to add the additional steps of Reply, Share and Groups (#4,5,6) to the 'Getting Started' box. eLife seem to want just the 3 steps, so it might be that the steps end up needing to configurable or at least show/hide steps depending on implementation of our client. I can create another mockup with #4,5,6. I was trying to make 'one size fits all' so I can pitch eLife on the 6 steps, although text for step 6 might need to be configurable as it will depend on the particular group implementation.

@robertknight can you confirm that the eLife groups implementation allows users to create private groups? I'm assuming yes since they use the H namespace.

**Comment by robertknight** [comment]
> @robertknight can you confirm that the eLife groups implementation allows users to create private groups? I'm assuming yes since they use the H namespace.

When the client is using a third party account, the functionality to create private groups is disabled.

eLife users do not use the H namespace. They use accounts created by eLife under an eLife namespace.

When the client is using a third party account, the user cannot currently use their normal H account (if they have one) on the same page. The plan is that will change in future, at which point users will be able to do everything they can normally do with H accounts.

**Comment by dawachan** [comment]
thanks

**Comment by dawachan** [comment]
Proposed design for 'Getting Started' H with additional Reply, Share, Groups onboarding info. 

![getting started - hypothesis](https://user-images.githubusercontent.com/5212631/30380936-dde1f392-9892-11e7-9a98-8f25a927a8a4.png)

**Comment by dwhly** [comment]
I'd like to request an "Ok, got it" (or something) button at the bottom of the card in our typical style.  Even if there's fancy logic to not show this card again the next time, people want a way to get the instructions out of their face in the current moment.  The X at upper right is something that many people simply don't see or understand as a close function.  Can't tell you how many times we've seen screen shots of people using H who have never closed the get started card.

**Comment by dwhly** [comment]
Also, would be great to see how this would be styled on the current H sidebar, separate from eLife, if it's something that will completely replace our current get started card.

**Comment by dawachan** [comment]
sure, i'll mock something up! thanks for the feedback @dwhly

**Comment by dawachan** [comment]
Here are the 2 variations for eLife and Hypothesis. The difference between the 2 versions is eLife have requested to hide the 'Reply/Share' and 'Groups' blocks. 

Updated as per feedback @dwhly, (although I felt that the 'Ok, got it' button looked better centre aligned in this context, since it isn't a traditional login/dialog box and there is only one primary action to take, I feel the design looked more balanced with centered alignment of this button, imho -
 although I understand the wish to standardize alignment.

Made the section headers sentence case to match what we currently have now in prod.

![getting started - elife](https://user-images.githubusercontent.com/5212631/30478657-d82d7bc4-9a09-11e7-8545-d2c471697fd6.png)
![getting started - hypothesis](https://user-images.githubusercontent.com/5212631/30478677-e7f3c64e-9a09-11e7-8c44-9c347dbf9e20.png)

I've added the 'Ok, got it' button to both versions, but it's possible that since the # steps is smaller for eLife, they would prefer to hide this - I'll double check with them. 

Below, the 'Ok, got it' button is shown center aligned.

![getting started - elife2](https://user-images.githubusercontent.com/5212631/30478692-f56b71fa-9a09-11e7-9f18-1ed02dec149c.png)
![getting started - hypothesis2](https://user-images.githubusercontent.com/5212631/30478711-0464f1f4-9a0a-11e7-9d8c-c78a5cba23fc.png)


**Display Rules:**

The 'Getting Started' box persists on a page until these conditions are met:

- A user manually dismisses it by clicking/tapping the 'x' or 'Ok, got it' which results in the 'Getting Started' box hidden globally.

- Once the user makes an annotation on a given page, the box is automatically hidden within the page scope. If annotations exist that are made by others, the box persists globally regardless of whether annotations made by others exist until the user manually dismisses it.

**Comment by dawachan** [comment]
@robertknight has reviewed and provide feedback re: grammar - have taken on board in final version and will send to eLife now for final sign-off. Rob also confirmed that all configurations proposed + logic around display rules are doable.

**Comment by dawachan** [comment]
Based on confirmation from Giuliano received today the final rules for the Getting Started panel should be implemented as follows:

**1. Display Rules:**

The 'Getting Started' box persists on a page until these conditions are met:

A user manually dismisses it by clicking/tapping the 'x' or 'Ok, got it' which results in the 'Getting Started' box hidden globally.

Once the user makes an annotation on any page/article, the box is automatically hidden globally.

(We should determine whether this means globally within a domain and/or cross domain) 

_Proposal 1:_

If a user signs up for eLife, begins annotating and then creates/logs into an H account for the first time, the 'Getting Started' panel won't display as the user has already added an annotation to the client, and since they have already 'got started' we don't need to display the box.

_Proposal 2:_

The instructions and features we are exposing for Hypothesis are slightly different for eLife - we display additional items e.g Share/Reply and Group blocks so we should display the 'Getting Started' screen again if it is unique to a particular domain.

I think it is a balance between keeping the user informed and annoying them by showing the information too many times. I think for now I'm leaning towards Proposal 2, but it's certainly something we could user test. As long as it goes away once the user makes their first annotation within a given domain.

**2. Blocks to show/hide:**

For e-Life, only the 'Start Annotating' block will display, the other 2 blocks: Reply/Share, Groups and the 'Ok got it' button are to be hidden.

**3. Alignment of 'Ok, got it' button:**

There were 2 different proposals for aligning the 'Ok, got it' button outlined earlier (one centered, one right aligned). Let's right align this for now.

**Comment by ajpeddakotla** [comment]
So @sheetaluk 2 changes that need to be made (to summarize this card): 

1. The universal change to the getting started card
2. The eLife specific changes to new getting started card 
- blue buttons instead of gray
- remove share and groups text

**Comment by dawachan** [comment]
I'd like to add that there is a current H version of 'Getting Started' where we talk about accessing the profile (as it is represented currently) and the creating a private group, and there is a future H version which will need to be rolled out when we push the new groups work out and revise the login control. Please find attached below:

![getting started hypothesis - current](https://user-images.githubusercontent.com/5212631/31545213-5ea135ca-b016-11e7-9b94-aa05b815f5a0.png)
![getting started hypothesis - future](https://user-images.githubusercontent.com/5212631/31545214-5ec3a89e-b016-11e7-98ec-308b259601e9.png)

eLife is the same:

![getting started - elife](https://user-images.githubusercontent.com/5212631/31545299-a288f80e-b016-11e7-819e-6325f83b681e.png)

I feel it's important to mention the various permutations and that they might change over time or on a per publisher basis, because it affects how configurable of a template vs hard coded we make this component. The accent colours for the annotation icon and the + note button etc will need to match the accent colour of the publisher brand.

I can do a detailed font/design spec if needed, but at a high level: 

* Section titles/headers: 16
* Body copy: 14
* Ok, got it copy: 15
* add note button copy: 14

I owe you the cursor used in the annotation mockup, and annotate icon @sheetaluk cheers.

**Comment by ajpeddakotla** [comment]
@dawariley @sheetaluk @robertknight given the time crunch we are under, we will not be making these changes to Hypothesis. We will only be implementing these changes for eLife. We can revisit these changes for Hypothesis when we have more space on the roadmap.
