### ISSUE TITLE
enable double opt in for communication during H. account sign up

### ISSUE THREAD

**Issue by xolotl** [hypothesis/product-backlog#354]
Hypothesis uses Mailchimp to send information about our organization to a large list of email addresses, most of which are on the list because they are attached to Hypothesis accounts. Mailchimp has indicated that Hypothesis is in danger of having its service suspended because of high rates of reports of "unsolicited email" from our recipients.

Hypothesis would like to continue to email organizational information to as many of our account holders as possible.

To address this issue, we propose a three step solution which matches widespread account and email practices:
1. Include a double opt in process in the Hypothesis account creation flow.
2. Email all existing emails on our list, not yet opted in, to opt in if they wish to receive organizational information from Hypothesis.
3. In the future, only send organizational information to email addresses that have opted in.

A detailed description of the issue and proposed solutions:
https://docs.google.com/document/d/1DXvAa1fgCTvgocQVI-_92l01gfiADM_9rWgTwgldYGA/edit

**Comment by klemay** [comment]
Closing in favor of: https://github.com/hypothesis/product-backlog/issues/431
