### ISSUE TITLE
H not activating on a specific page

### ISSUE THREAD

**Issue by jeremydean** [hypothesis/product-backlog#364]
### Steps to reproduce
1. Go to this site:

http://utc.iath.virginia.edu/uncletom/uthp.html

2. Try to activate h via extension or via proxy.

### Expected behaviour
Nothing happens.

### Actual behaviour
H sidebar should appear, I should be able to select text and see annotate/highlight button.

### Browser/system information
Updated Chrome quite and via proxy.

### Additional details

There's something going on with frames here so may have something to do with that work.

**Comment by klemay** [comment]
@jeremydean  - I was looking through related issues and came across this one. I'm able to activate the h chrome extension and make annotations (see: https://hyp.is/HZAdwgLHEeiyRuPB8CI25A/utc.iath.virginia.edu/uncletom/uthp.html)

It looks like they rebuilt the page without frames. Should we close this issue?
