### ISSUE TITLE
Knowledge transfer

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#365]
Given that @chdorner is leaving, we'll need to make sure we scope out the work for the following projects: 
1. [x] Via rewrite: https://github.com/hypothesis/product-backlog/issues/307
2. [ ] Groups backend work - David isn't here, and won't be back until after Christof leaves. So we'll need to scope out the work on the backend here. 
3. [x] Site reliability/scaling work - Knowledge transfer

**Comment by judell** [comment]
Suggestion: When these transfers occur, try (if appropriate/helpful) to capture narrated screen recordings along with written notes.

**Comment by ajpeddakotla** [comment]
Google Doc where we can ask questions: https://docs.google.com/document/d/1u4GFoT3MAzAmZWc2RVIhZfc3Vj8MDdqxj4U2lELr9Yk/edit#
