### ISSUE TITLE
Upgrade PDF.js in Via and the browser extension

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#366]
We are currently shipping PDF.js [v1.1.215](https://github.com/mozilla/pdf.js/releases/tag/v1.1.215) (June 2015) with the browser extension and v1.1.24 (~ March 2015) with Via. This means that we are missing out on 2+ years worth of PDF compatibility improvements, bug fixes and performance improvements.

I did try upgrading PDF.js not long ago but ran into issues anchoring existing annotations described in https://github.com/hypothesis/browser-extension/issues/12 , which need to be investigated and resolved.

**Comment by robertknight** [comment]
https://hypothesis.zendesk.com/agent/tickets/1495

**Comment by felliott** [comment]
Around the beginning of July 2018, pdf.js removed the `PDFViewerApplication.documentFingerprint` property the client uses to get the document identifier.  See https://github.com/mozilla/pdf.js/commit/e522b2d87e8eb3d4eb8a391a098a0f6f157e8c12

**Comment by robertknight** [comment]
Thanks for the notice @felliott.

**Comment by gavento** [comment]
As of 12-2018, the PDFJS version bundled in Firefox 64.0 (on Ubuntu 18.04 64bit) is `PDF.js: 2.0.936`.

(The PDFJS versions in Via and the Chrome browser extension are still 1.1.24 and 1.1.215 respectively).

The API changes seem to be substantial in volume, but hopefully not in depth (see the [diff of api.js](https://github.com/mozilla/pdf.js/compare/v1.10.100...master#diff-0ecad279ed2252e3eb47a4d96ec1463c) in the tab Files Changed). Unfortunately, there is no comprehensive overview of the changes to 2.0 (or even among the 1.x minor revisions), only [examples update](https://github.com/mozilla/pdf.js/issues/9528).

**Comment by gavento** [comment]
There are few more issues across the Hypothesis project related to the PDF.js update:
https://github.com/hypothesis/via/issues/81
https://github.com/hypothesis/browser-extension/issues/12
https://github.com/hypothesis/client/issues/259
https://github.com/hypothesis/pdf.js-hypothes.is/issues/14

**Comment by gavento** [comment]
@robertknight I would be curious in your opinion on what is the biggest blocker in upgrading PDF.js: Is it the anchoring issues between PDF.js versions (e.g. hypothesis/browser-extension#12) or technical issues with recent PDF.js API changes / incompatibilities?

**Comment by robertknight** [comment]
Hi @gavento - making sure that annotations that anchored with older versions of PDF.js still anchor after we update the copy in the browser extension and Via is the main concern. The Hypothesis client's "fuzzy anchoring" algorithm is not sufficiently robust to some of the typical changes in text output between older and newer PDF.js versions. For example, changes in where spaces appear in the text layer.

PDF.js API changes haven't posed a major issue.

**Comment by JamesPJ** [comment]
I was trying to upgrade the PDF.js to 2.x version. But, I'm facing issue with the frame syncing. The `addFrame` function is never getting called, due to this `Redux store` is having empty `frame` state. I can see the `addFrame` is attached to`bridge.onConnect(addFrame);`. I'm having difficulty in understanding this portion of implementation. Can anyone explain when the `Redux store` should update with frame data and on what condition we are triggering the `postMessage` to the `frame-sync`.

**Comment by robertknight** [comment]
Hello @JamesPJ -

PDF.js is not part of the client. Are you trying to use a newer version of PDF.js in the browser extension, Via or with a different tool?

The Hypothesis client already supports recent versions of PDF.js, at least the version shipped with the stable release of Firefox (2.1.97). You shouldn't need to make any code changes to the client to use it with that version.

If you are trying to build your own version of the client for whatever reason, I would suggest to start with getting the simplest configuration working, which is the client's development server at http://localhost:3000.

**Comment by JamesPJ** [comment]
@robertknight Thank you for the quick response. Yes, I was trying the new PDF.js version with the browser extension base by combining the features of client. Let me check whether client alone works for me.

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/via/issues/81
