### ISSUE TITLE
Extend groups backend to include public and open groups

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#369]
### Background
We have a backend model that we created for publisher groups detailed here: https://github.com/hypothesis/product-backlog/issues/39#issuecomment-262810123. In this work, we'll extend the model to create two new group structures: 

**Public groups:** A group which allows for all annotations to be read by everyone, but only written by Hypothesis group members that have been added by group admins. 

**Open groups:** A group created which allows for annotations to be read by everyone, and written by any Hypothesis user.

**Comment by seanh** [comment]
I'm gonna close this, we want to change how we work to work in terms of user stories not in "Implement the backend, then implement the frontend" sort of terms like we did in the past/
