### ISSUE TITLE
Verify that annotations made in public and open groups are visible user's profile and search pages (activity pages)

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#371]
### Background
Annotations made in Public and Open groups should be viewable on a user's search and profile page. We will need to design out what this looks like and @dawariley will add the designs to this ticket. 

### Users will have the ability to view: 

- [ ] All annotations made within the group
- [ ] All members that have been added to the group
- [ ] Group information (creation date, who controls the group, etc) 

**Arti to add more spec to this**

**Comment by gobengo** [comment]
@ajpeddakotla something I think it makes sense to do in while checking existing pages to make sure they work well with the new group types: On all 'group search' pages, there is an "Invite new Members" section in the lower right, that lets you copypasta a link that others can use to join the group.

But for 3/4 group types where JoinableBy is falsy, this link will result in a 404 for users who aren't already a member.

**Comment by seanh** [comment]
I'm gonna close this. I've created a [separate issue for activity pages for open groups](https://github.com/hypothesis/product-backlog/issues/422). For restricted groups (formerly called "public groups"), there are problems with activity pages that will need to be solved before activity pages will work for restricted / public groups, see https://github.com/hypothesis/product-backlog/issues/424
