### ISSUE TITLE
As a publisher, I’d like to designate a group as authoritative over my domain or by page

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#372]
### Background
Currently we don't offer a way to designate a group as authoritative over a publisher's domain unless the publisher decides to implement a restrictive publisher group that excludes the ability for non-publisher group members to annotate. 

**Publishers would like to designate a group as authoritative by:** 
- [ ] Domain
- [ ] Page
- [ ] The authoritative group will show first in the list of active domains
- [ ] The publisher can use an publisher-specific icon to mark publisher group

Question: 
Is this a parameter on the embed script, or will this be stored in the database somewhere? @gobengo this is something that we have to determine. We'll need to understand the caveats to each approach.

**Comment by gobengo** [comment]
I'm going to try to implement this first such that publishers can provide this information in their web page, and the h client will render it based on that. So the source of truth is the customer's page. There will not be a h database record for this info.

Is there an existing pattern for how a customer developer might provide this sort of metadata on their page? I'd recommend something in HTML very similar to [ogp](http://ogp.me/)
```
<meta property="h:icon" content="https://hypothes.is/assets/images/favicons/favicon-32x32.png" />
<meta property="h:group" content="https://hypothes.is/groups/VmBb83L7/bengo-group" />
```

UPDATE: yes I found the existing pattern of passing configuration options to the client. I'll be using that instead, not meta tags.

We start a registry of properties that web page editors can add to their pages. The registry will start out with

* `icon` - icon of logical Domain that this page belongs to
    * if this isn't present, we can fall back to favicon (link[rel=icon]). Customers only have to add this if they want an image different than their favicon
* `group` - relationship between a page and the groups that should be featured in the client when viewing the page

**Comment by seanh** [comment]
@ajpeddakotla Can we close this issue? The way Dawa and I split this one up:

* At first, publisher open groups appear at the top of the groups menu: https://github.com/hypothesis/product-backlog/issues/417
* Later (separate user story) groups are grouped under the publisher's name in the groups menu (and the publisher's groups still appear tat the top): https://github.com/hypothesis/product-backlog/issues/418
* Later, publisher icons are added: https://github.com/hypothesis/product-backlog/issues/419

I think those iterations will achieve what this github issue was wanting to achieve? In that case, **can we close this issue?**

**Comment by ajpeddakotla** [comment]
Closing this one as it has been covered here: #448
