### ISSUE TITLE
Finalize configuration options exposed for new "clean" look

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#377]
https://github.com/hypothesis/client/pull/555 implements a new set of configuration options for the client that enables a new "clean" look for the client:

![](https://user-images.githubusercontent.com/2458/32611823-8b2c9366-c55e-11e7-9f46-629ccbb81dd5.png)

That PR implements a configuration option per toolbar feature, which allows many combinations that don't currently make sense. We can get feedback on the new theme before finalising the configuration API, but we _do_ need to polish/confirm the final config API before we commit to publicly supporting it.

**Comment by robertknight** [comment]
My personal preference would be to expose the _minimum_ number of configuration options. Why? For two reasons:

1. It reduces the matrix of configuration options that have to play nicely with each other.
2. We get direct feedback from users when they want something we don't yet support.

In this case we initially could boil it down to a single "theme" setting which is either "clean" or "classic".

Based on my discussions with people working on EPUB etc. I also have a suggestion as to how we might support "arbitrary" ways of publishers handling the sidebar if they have more elaborate needs. Rather than supporting everything ourselves in the client, we could instead provide them with a way to "mount" the sidebar inside a container element that they control and provide them with access to the necessary hooks/data to do what our sidebar currently does. This in particular would help cases where the publisher already has some kind of sidebar and want to integrate the client into that, rather than having it be a separate thing.

**Comment by seanh** [comment]
@robertknight This looks like a dup of https://github.com/hypothesis/product-backlog/issues/380 (and I think it's done)
