### ISSUE TITLE
Finalize and document new sidebar UI customization options

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#380]
We recently implement a batch of new sidebar UI customization options in order to enable publishers to configure a client with a "cleaner" look, specifically with eLife in mind:

<img src="https://user-images.githubusercontent.com/2458/32885925-f228a64c-cab6-11e7-878c-9b593e667a97.png" width="400">

The new options currently implemented are:

**disableToolbarCloseBtn** _bool_. - Disables the "X" button to close the sidebar in the screenshot above.
**disableToolbarMinimizeBtn** _bool_. - Removes the ">" button in the normal Hypothesis look that "minimizes" the sidebar down to the toolbar.
**disableToolbarNewNoteBtn** _bool_. - Removes the "New note" button in the toolbar
**disableBucketBar** _bool_. - Removes the buckets indicating annotation positions in the document from the toolbar.
**enableExperimentalNewNoteButton** _bool_. - Adds a button labeled "New note" to the notes tab.
**enableCleanOnboardingTheme** _bool_. - Enables the new version of the sidebar tutorial shown to new users.
**enableSidebarDropShadow** _bool_. - Enables a drop shadow on the sidebar's outer frame, designed to make it possible to distinguish the edge of the sidebar when both the sidebar and the host page have the same color (white in the case of eLife)
**theme** _"clean" | "classic"_. - "classic" is the default Hypothesis look. "clean" is a bunch of UI tweaks which give the sidebar a flatter look, as shown in the screenshot above.

Before we can sign of eLife as "done", we need to:

1. **Review how we expose the new possibilities as config options**. Right now we expose a bunch of individual tweaks and not all of them work together. For example, the minimize button & bucket bar in the toolbar aren't styled to match the rest of the sidebar if using the "clean" theme. A couple of config options ("enableExperimentalNewNoteButton" and "enableCleanOnboardingTheme") are explicitly "temporary" settings because we wanted to enable eLife to test the changes without committing to applying them to the standard Hypothesis interface.
2. **Finalize the naming of the config options**
3. **Document the new config options**

**Comment by robertknight** [comment]
Recapping a discussion between Sheetal, Arti, Sean H and myself yesterday:

For the initial release, we are going to bundle the following into a single `theme` option:

- The options to remove individual toolbar buttons
- The option to remove the bucket bar
- The new "New note" button
- The new onboarding look
- The cosmetic changes to the sidebar and drop shadow

The main colors and fonts used in the sidebar, along with the partner logo and label will continue to be separately configurable.

This does _not_ preclude us from adding more flexibility in future, but as a starting point it gives us a manageable test matrix and makes life simpler for publishers by giving them a much simpler means to get a configuration that works together.

As we work with more publishers / consumers of the client we will get a better understanding of where they have a genuine need for differentiation from other publishers and the client's default look and feel. We can then evolve the configuration accordingly.

My expectation is that changes to both the default look and the "clean" look will also continue to happen in future as we a) incorporate some of the changes made for eLife into the default look (eg. new onboarding card) in some capacity, b) people get experience using the clean/minimalist look out in the field and inevitably come to us with change requests.

**Comment by seanh** [comment]
@sheetaluk This is done right? This issue can be closed?

**Comment by robertknight** [comment]
The options have been finalised but not yet documented, so that's one last thing to do.
