### ISSUE TITLE
Team user research survey

### ISSUE THREAD

**Issue by segdeha** [hypothesis/product-backlog#381]

**Comment by dawachan** [comment]
Completed.

Team Survey findings here:
https://drive.google.com/open?id=1ISoi1Vl19z7jI_UcmCtrAmVJmpAp_bFPqTY9JO2LWes

Survey:
https://drive.google.com/open?id=1eigahdGGVODh0H5ZakV5_s1Vw4IA2cQp1GgeI7d1ErM

Anonymised answers:
https://drive.google.com/open?id=1HvpPU2BhQVNVH0bba_Qz6-BCWEHLcvOGlutsSRm62rc
