### ISSUE TITLE
Remove old Elasticsearch indexes

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#387]
When we [do a search engine reindex](https://github.com/hypothesis/playbook/blob/master/docs/running-tasks-on-qa-and-prod.md) it creates a new index and changes over to it (zero-downtime reindexing) but it looks like it doesn't delete the old indexes. This will be wasting some storage space.

Task: figure out whether we're deleting old search indexes in production or not (probably not) and if not set up a way to delete them.

See: https://hypothes-is.slack.com/archives/C2N6HPG2G/p1511527582000551

**Comment by dhwthompson** [comment]
From a quick initial poke around, it looks like we’re *not* deleting old search indexes in production automatically. There are currently two old ones hanging around, wasting 2–3 GB of storage each out of the 40GB we appear to have allocated for our search cluster.

**Comment by robertknight** [comment]
This was implemented for future reindexing operations by https://github.com/hypothesis/h/pull/5122. I also cleaned out the existing old indexes from the ES1 cluster.

Note that if a reindex _fails_ for any reason after the new index has been created, both current and new (incomplete) indexes will still exist.
