### ISSUE TITLE
Display annotation count in group selection menu

### ISSUE THREAD

**Issue by papatistos** [hypothesis/product-backlog#392]
### Problem you are trying to address with this feature

**This is more a UX improvement that a feature**

Lets assume you have a document that has annotations in a group in which you are a member. To keep things simple, let's also assume that the document has no public annotations.

If you open a document with the chrome extension installed (but currently not active), the chrome extension icon will show a blue rectangle with the annotation count like this:
![image](https://user-images.githubusercontent.com/3662750/33521140-d0da2130-d7c9-11e7-8a2a-efc52ba63f8e.png)
A natural reaction to that annotation count would now be to activate the sidebar by clicking on the extension icon. If you do that, something confusing happens: the annotation count disappears (and the hypothesis icon turns dark):
![image](https://user-images.githubusercontent.com/3662750/33521170-d5304510-d7ca-11e7-926b-d2458bdbf95b.png)
Even more confusing: if you expand the sidebar, there are absolutely no annotations:
![image](https://user-images.githubusercontent.com/3662750/33521182-1c7f0da2-d7cb-11e7-9b9f-599cfb96dd49.png)
As far as I can see, the reason for this is that the annotations are "hidden" in a group and they will (of course) only appear when you select that group. 

But, assuming that I haven't yet given up at this point (which, I'd assume, most users would have), which group should I look into in order to find those annotations? Hypothesis give absolutely no hint.

### Your solution
The annotation count on the hypothesis icon is a great feature, so removing it is obviously not an option. I also think it is good that it shows the total annotation count, across all groups. So limiting it to public annotations or a specific group is also not an option.

So a first step to avoid confusion would be to display the annotation count also when the extension is active. This would signal to the user that these annotations are really there, even if you can't see them at the moment and chances are that the user will understand that in order to find them s/he has to switch to a different group.

To facilitate this, I suggest to add a blue rectangle with the annotation count to every group in the group selection dropdown menu that holds annotations. Like this, for example: 

![image](https://user-images.githubusercontent.com/3662750/33521260-8fb3310c-d7cd-11e7-8777-f2fc2514bd0c.png)

**Comment by dhwthompson** [comment]
Hi @tophee; thanks for the detailed feature request.

We’ve actually got an issue open for this very problem: #260. As far as I can tell, our proposed fix is exactly the fix you’ve suggested. As such, I’m going to close this issue as a duplicate, and you’re very welcome to follow along with the progress on #260.

If I’ve missed something and there’s more to this than we’ve already got covered, feel free to reopen this or to file a separate issue for anything that remains.

Thanks again.
