### ISSUE TITLE
Setup routine removal of old Graphite databases

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#396]
On [2017-12-08](https://docs.google.com/document/d/1NDTlVxqvyJiDfoSsku0VjijVrILqtzMZYc70tp6vFWg/edit#heading=h.585d998hhxlg) our production database backup failed due to the server on which the backup task runs running out of disk space. Disk space on the "mon" server was exhausted due to a proliferation of [Whisper databases](http://graphite.readthedocs.io/en/latest/whisper.html) from EC2 instances associated with old h deployments which no longer exist.

There is currently no mechanism to automatically remove Whisper databases associated with no-longer-existent EC2 instances, so eventually these will just multiply and consume available disk space on whatever machine they live.

More details: https://docs.google.com/document/d/1NDTlVxqvyJiDfoSsku0VjijVrILqtzMZYc70tp6vFWg/edit#heading=h.585d998hhxlg
Slack discussion: https://hypothes-is.slack.com/archives/C074BUPEG/p1512691224000032

**Comment by dhwthompson** [comment]
Here‘s [a script I put together](https://gist.github.com/fatbusinessman/3c3c832774035b961e4b0b6f7216b524) to remove Whisper directories that haven’t had any files modified in the last *n* days. It might be a useful basis for something we run regularly.

**Comment by robertknight** [comment]
We don't use Graphite any more.
