### ISSUE TITLE
Setup Grafana dashboard for lms app

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#398]
This was split out of <https://github.com/hypothesis/product-backlog/issues/384>. Setup a Grafana dashboard for the lms app, the same as the one we have for the lti app: <https://mon.hypothes.is/grafana/dashboard/db/lti>.

It looks like we have these dashboards for the production apps only, not the qa ones.

The app should already be reporting data to Graphite, so I think only setting up the dashboard in Grafana should be needed.

**Comment by robertknight** [comment]
Initial dashboard is here: https://mon.hypothes.is/grafana/dashboard/db/lms

I created this as follows:

1. Go to https://mon.hypothes.is and login to Grafana
2. Selected an existing app dashboard (I chose “LTI”) and made a copy via {Gear icon} => Save As... => "LMS"
3. Edited the `$instance` template var in the new LMS dashboard via {Gear} => Templating and changed the reference to “lti-env” to “lms-env”
4. Saved the dashboard using the disk icon in Grafana

As far as I can ascertain, our existing dashboards are not persisted in a textual/JSON format in a repo anywhere.

**Comment by robertknight** [comment]
Update: I also found that the data sources for the "Request rate" and "Response time" panels had to be edited directly to replace hard-coded references to "lti" with "lms". Notes on Slack here: https://hypothes-is.slack.com/archives/C4K6M7P5E/p1513771698000056

The basic metrics now all appear to be there.
