### ISSUE TITLE
_Should_ you run the Ansible bootstrap playbook manually? If so, how? On bastion? What am I doing?

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#400]
Need more information here @seanh @robertknight

**Comment by robertknight** [comment]
I had a brief stab at this at the end of December and learned a little but not a lot before breaking for the holidays. My notes are at https://hypothes-is.slack.com/archives/C074BUPEG/p1516718414000801

I leave figure the rest out as an exercise for the reader 😛

**Comment by robertknight** [comment]
See also this documentation in the playbook: https://github.com/hypothesis/playbook/blob/master/docs/setting-up-ansible.md

It was written a couple of years ago so parts may be out of date, but this is probably still a useful reference.
