### ISSUE TITLE
Set up database backups for the lms app. 

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#403]
From @seanh's notes: It doesn't have any! Except what RDS provides out of the box. (The lti app also never had any.)

**Comment by robertknight** [comment]
As explained at https://github.com/hypothesis/playbook/blob/master/docs/backups.md we have two types of PG backup:

1. 30 days worth of RDS snapshots. These backup the entire DB _instance_ [according to the docs](http://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_WorkingWithAutomatedBackups.html), so that would include the lms QA & prod DBs and whatever new DBs we add in future.
2. Logical backups taken with `pg_dump`. These are configured by https://github.com/hypothesis/playbook/blob/master/secret/conf/postgres-s3-backup_env . pg_dump only dumps a single database, currently the "h" DB. In order to change this to include the lms DB we'll have to adjust the backup process to handle multiple DBs.

**Comment by robertknight** [comment]
A thought that came up from a hangouts chat. Using RDS's tools AFAIK we can currently only restore the entire DB instance from a previous point, not individual DBs or tables. _However_, if we can restore a DB instance snapshot to a separate RDS instance then we can always get a logical backup by first restoring the snapshot to a new RDS instance, then dumping the table/DB of interest and finally restoring that DB/table to the existing RDS instance.

If all this is possible then setting up a separate logical backup might be unnecessary.

**Comment by segdeha** [comment]
Logical backups of the `lms` DB are still necessary at some point, I think. But from a risk management perspective, we can probably put it off if we're mitigating risk to `h` using the procedure above.

**Comment by robertknight** [comment]
We have RDS' automated backups of the lms DB. I'm going to close this for now until we have a clear need for logical backups for other reasons.
