### ISSUE TITLE
Groups - Prework

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#412]
Let's read over and familiarize ourselves with this project before Dawa's design call on Thursday 
I'm adding some links here for more reading/info. The docs are in order from high level -> deep dive: 

Groups Problem Statement: https://docs.google.com/document/d/1bgPTrlHvlCDGhUVqRLfWbRcO9Gtaiidlf3JLwKhwwp8/edit#
Triage of groups work: https://docs.google.com/document/d/1B1mEyZMAM7--bV-HPyIKRTnRnROVWADaB999ELCxirQ/edit
The Triage doc has all the links to more technical documentation and design documentation. 

@ajpeddakotla Pasting below original feature spec sheets and documents I found - not sure how much of this is current.. assuming it all is, but we might want to update the MVP doc: 

https://docs.google.com/document/d/1tsyUGDfLLaQsa4Pmc-loHRcYCIe4Q56meery6Be6CoA/edit#heading=h.ge43xo9poyis if we're going to limit the scope for the minimum shippable product.

MVP - Public and Open Groups FSS:
https://docs.google.com/document/d/1tsyUGDfLLaQsa4Pmc-loHRcYCIe4Q56meery6Be6CoA/edit#heading=h.ge43xo9poyis

Short- term Hypothesis Groups solution:

https://docs.google.com/document/d/1z71q5FYofor8kSNcKBN2QJK6QJfS2KafD_OOQwEXHZo/edit

--
Dawa's List:

Group Admin Demo video:
https://drive.google.com/open?id=1RK3ZR3bgh9zRWom0mNxa_gghbckUr7QH

Working Design Specs: https://docs.google.com/presentation/u/1/d/1ESiIotb91xJnUj9v6M2R2qW0o7akT1MbwsIMPjab6Ho/edit#slide=id.g1ee5cfaab5_0_15

Early post-hire Design Thinking:
https://docs.google.com/presentation/d/1gUJ-kOHipJ6FcoDfqFAAKfjyrSSyt8VuvCrgHmDnPWg/edit#slide=id.g20739fc6bc_0_93

Very Early pre-hire Design Thinking:
https://docs.google.com/presentation/d/1Hc19p69wHhIILq9u9aVImO3SvY-IpE947TeJ_ldLETI/edit#slide=id.g1ee5cfaab5_0_6

Group Control Scenarios:
https://docs.google.com/spreadsheets/u/1/d/1t0s2z_m-u3kLNqjgigTzpjvZ9Nha2TUuHZA2Hv9YoG4/edit#gid=0

Groups User Flow End-to-end:
https://hypothes-is.slack.com/files/U073V8GCT/F78LFN48Z/groups_user_flow_end-to-end

Group Controls - Sorting and Display rules:
https://hypothes-is.slack.com/files/U073V8GCT/F705M7QDB/group_control_notes_-_sort_ordering

Groups Demo - walkthough:
https://hypothes-is.slack.com/files/U5V7KQUEA/F7NMDD7HA/groups_v1_-_23.10.17.pdf

Invision protoype:
https://projects.invisionapp.com/share/XPDTS1M9S#/screens/256922267

Early doc I put together as I was trying to make sense of the user needs:
https://docs.google.com/document/d/1Lm4JjJ2Y0VB_8Zvx5OLzOXnit2scUATAsei9u6jxKvk/edit

**Comment by dawachan** [comment]
Sorry @ajpeddakotla had to convert from a note -> issue to be able to add more characters!

**Comment by dhwthompson** [comment]
Since this was background reading for a meeting that's now happened, along with the subsequent work to tease out the different use cases, I'm happy calling this complete.
