### ISSUE TITLE
Full support for MathJAX

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#414]
### Problem you are trying to address with this feature
Currently, users must escape out $ for LaTeX commands (as noted in [this support ticket](https://hypothesis.zendesk.com/agent/tickets/1915)). Additionally, there are certain LaTeX math mode commands, which are not recognized (like "\iff", or "\implies", but also "\begin{align} .. \end{align}" etc.

### Your solution
Implement MathJAX; potentially enable a "Math mode" so commands like $ don't need to be escaped out

**Comment by robertknight** [comment]
Some of the limitations of the KaTeX-based math rendering can be resolved simply by updating KaTeX to a newer version, so we should evaluate as we get specific feedback about certain math features.

Whatever we do with math rendering in future, it is important not to regress loading/rendering performance for the majority of users not making use of the feature in their annotations.

**Comment by robertknight** [comment]
KaTeX has been updated. `\iff` and `\implies` are now supported. See release notes at https://github.com/KaTeX/KaTeX/blob/master/CHANGELOG.md for versions after 0.7.0 up to 0.10.0 (inclusive) for full details.

Can you paste the full details of the original support ticket here @klemay?

**Comment by robertknight** [comment]
Supporting two different LaTeX rendering engines is a maintenance overhead I would really like to avoid. As long as KaTeX is being regularly updated and it covers the substantial majority of our users needs, I'm inclined to close this issue.

**Comment by klemay** [comment]
The ticket was long and convoluted. The full text is below, but here's a TL;DR at the top: 

- Users have to use `$$` instead of `$` when typing mathematical expressions. This user found it cumbersome, since he and others at his institution are primarily writing math expressions.
- The same user also found KaTeX lacking support for things like `\iff` and `\implies` (now supported) and things like `\begin{align}` and `\end{align}`.  

We might decide that KaTeX is developing at a rate that we're comfortable not pursuing MathJAX and close this ticket. I'd leave that up to @dwhly and @ajpeddakotla. 

Personally I'd advocate for closing this ticket & removing from backlog because:
- We've already deemed this "low priority" in the backlog
- I agree with @robertknight that maintaining 2 different LaTeX rendering engines isn't ideal
- Given the engineering team's recent work to automate dependency updates, we will get KaTeX updates faster than we previously used to

--- 

Full text of original ticket: 

> My institution enabled the built in LaTeX support for Hypothesis. The problem is it doesn't recognize the $ command for math mode. They told me to use \( \) but this is very annoying. The command is not easily typable, is different for the beginning and end, and requires double the amount of characters. No sane person would use this notation when writing out a long mathematical proof.
> 
> There is a reason almost *everybody* uses the $ command when writing LaTeX.

Robert responded:

> Hypothesis has two ways of embedding LaTeX, inline in the middle of a sentence using \( and \) and as a block using $$. I'm guessing a single "$" was not used for inline LaTeX because people who are not trying to use LaTeX (remember that Hypothesis is a general purpose annotation tool) may have been too likely to trigger it inadvertently, but I will have to ask around the organization to confirm.

Then the user said:

> I was indeed talking about the single $ symbol, which is the normal way of writing in LaTeX math mode. Of course if people want to write the actual dollar sign they would need to escape it. But how often does one want to write a dollar sign compared to writing in math mode? I would say way less often. Also the $ symbol is the industry standard syntax, with the $ for inline math mode and $$ for block math mode. I mean there is nothing wrong with leaving the other syntax as option. At least you should implement the $ syntax as an option which one can turn off/on if one wants to.

Dan responded: 

> Our challenge is that Hypothesis annotations are not LaTeX documents. As Robert observes, they are general purpose documents, which support LaTeX math notation as a helpful convenience but not as a primary operating context. The frequence of use of $ as a dollar sign as opposed to a trigger for LaTeX math notation is much higher in the overall population of all documents.

Then we heard from the user:

> I'm worried that you don't even mention the possibility to implement an option for the LaTeX $ syntax.
> 
> In the environment I'm in, nobody has ever wanted to write a dollar sign. Maybe there are other environments, where this is different, fine.
For us though this is a problem. We need to write a lot of LaTeX code. And the syntax is immensely influencing it. It's not like there is something that you might sometime need to consider or so. No, it's like every time you start and stop writing LaTeX code that you have to deal with it. And if you have to deal with a problem that is really hindering you like 1000 times a day, you want to naturally try to take a look at it and get rid of it, right?
> 
> At least now you've seen the perspective of one customer, which is unhappy with the current LaTeX syntax.
> Why not built it in as option?

And the user followed up: 

> Follow up idea: A setting like "enable math mode" which enables a full MathJax implementation and also the *standard* syntax (which is the dollar sign (single and double) in the Hypothesis settings.
> Then the implementations who need to write math can enable this setting so their users can type math.
> Also the identical setting would enable a full MathJax implementation which supports all LaTeX math mode commands. In the current implementation on Hypothesis there are certain LaTeX math mode commands, which are not recognized (like "\iff", or "\implies", but also "\begin{align} .. \end{align}" etc.). If you use only one of them the whole post breaks and doesn't display any math.
> Though to my knowledge MathJax supports all of them, because the implementation used at math.stackexchange.com handles them well.

Then internally, Dan noted:

> There seem to be two issues:
> 
> 1- Invoking via $ instead of $$. So, here I have to say that I'm seriously surprised this seems to be a big deal. This is the first I've ever heard about it. I'm not sure why it's a major inconvenience. Would be curious to hear from other LaTeX users on this one.
> 
> 2- Support for full MathJax ... this is probably a bigger deal. Currently we use a library called KaTex (Khan academies' version, much lighter weight), which has a more minimal set of MathML functions. Though apparently the support for broader math functions has been increasing. We've been waiting for heavy math users to use us enough that we'd hear complaints to implement MathJax (which we actually used to support).
> 
> I'd probably note this with appreciation now and add as a feature request just so we track.

**Comment by dwhly** [comment]
> Supporting two different LaTeX rendering engines is a maintenance overhead I would really like to avoid. As long as KaTeX is being regularly updated and it covers the substantial majority of our users needs, I'm inclined to close this issue.

Agree.  When full math becomes big deal for us, then we'll address.  For now, the simplicity of sticking w/ KaTex is a real win.  MathJAX is very large (or at least it was), and much slower (or at least it was) and thus there was a not insignificant burden to maintain the prior implementation that we had.  Things could be changing but that bears investigation.

**Comment by robertknight** [comment]
OK. I'm going to close this specific issue for supporting MathJax as something we're not currently planning to implement.

Regarding the other issues in the user's ticket, changing the way math-mode is invoked and support for specific LaTeX commands, we can discuss those in separate issues.
