### ISSUE TITLE
Groups menu display and sort order rules

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#423]
This needs to be written up as a clear and concise user story (or perhaps multiple stories) with clear acceptance criteria, but for now: there is a [google doc about sort ordering and display rules for groups in the groups menu](https://docs.google.com/document/d/1-7y_7rJmcHX5etGPpcBq33DCcveeuZ6sx1LvBVJvu64/edit) and this is just a placeholder card for that it needs to be turned into a user story or stories so it can be prioritized and (at the appropriate time) implemented.

**Comment by ajpeddakotla** [comment]
There are other cards that already reference sort order, so I'm closing this one out.
