### ISSUE TITLE
As Hypothesis I want to be able to contact our user base via in-app messaging.

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#430]
Acceptance criteria:

**Done when:**

- [ ]  There is a documented procedure for showing an in-app message.
- [ ] The button is implemented according to the design specs as outlined below in terms of button style (background colour,  positioning).
- [ ] The message contains an icon (such as the speech bubble icon in the
mockup below).
- [ ] The message links to a web page, such as a Google doc or a blog
post.
- [ ] Once the user has clicked on the link the message disappears and is not shown
to that user anymore
- [ ] The message can be dismissed by the user without following the link (e.g.
by clicking a "close" or "dismiss" button on the message)
- [ ] The display of the button (visible or hidden) can be configured on/off on a per publisher basis. 

**Out of Scope:**

- The branding of the button is themeable according to a publishers styling. (TBD/future phase)
- The messaging and whether it is live (published or not) is configurable via an admin interface. (TBD/future phase)

**Details:**

The breakdown of in-app messaging taken from the [launch proposal document](https://docs.google.com/document/d/1lg7W3obnXA94YgLOZmwMy2ZoOq3j6_8g1JM4CcdesjE/edit)
To include a button inside the client to be displayed for the duration of the survey results collection. 

![takeasurvey_btn](https://user-images.githubusercontent.com/5212631/35156478-d7e82614-fd28-11e7-92a8-45f9e6162074.png)

**Button features:**

Users should be able to dismiss the button by clicking on the ‘x’. This will mean it is not displayed in the sidebar again.
Once the user has clicked the button to take the survey and the Google from launches, the button will be hidden.

**Button style and positioning:**

- The button is anchored to the bottom of the browser window in the sidebar as a sticky button.
- Sidebar distance from right margin: 33px
- Web.hypothesis inset distance from right margin: 43px
- Grey background: #626262 (same colour as post button).
- onRollover: #3A3A3A (same rollover state as post button).
- Button text: “Take our survey”

**Placement of button inside the sidebar:**

![placement_lg](https://user-images.githubusercontent.com/5212631/35156680-7a67509a-fd29-11e7-959e-485b77779e25.png)

![sidebar_classictheme](https://user-images.githubusercontent.com/5212631/35156779-c5fed58c-fd29-11e7-807e-71e9af8b8958.png)

![sidebar_cleantheme](https://user-images.githubusercontent.com/5212631/35156786-cb8cf9fc-fd29-11e7-909d-564bdb73c53e.png)

**Comment by ajpeddakotla** [comment]
We're not going to be implementing this anytime soon, so I'm closing this.
