### ISSUE TITLE
Use H in different languages

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#438]
## Feature Request Form
Request from user to offer Hypothesis in other languages (in this case, FR-CA) [came in via Zendesk
](https://hypothesis.zendesk.com/agent/tickets/1992) today. Logging this here in case similar requests come in the future; if that's the case we may revisit this.

**Comment by lpmarceau** [comment]
See Issue https://github.com/hypothesis/product-backlog/issues/324

**Comment by klemay** [comment]
^ closing in favor of #324
