### ISSUE TITLE
option to set default tags

### ISSUE THREAD

**Issue by katrinleinweber** [hypothesis/product-backlog#442]
### Problem you are trying to address with this feature

Some conference websites offer one page/URL per presentation, session or panel, on which one can conveniently capture notes with hypothes.is. Usually, there is an official tag for the conference.

### Your solution

Upgrade tag elements that have been set with a `pin` button or long-press action. Activating this function would store the tag(s) in some kind of cache, and each next annotation or page note starts out with the same tag(s). Until one deactivates this function again.

### Add tags - did you add labels? 
Can't do that. Probably, only collaborators in this repo can.

**Comment by robertknight** [comment]
Did the person asking about this say what they ultimately wanted to do with the tags?

If they are trying to find all the annotations associated with a particular conference, and if all the documents are on a particular domain or URL prefix (eg. https://organizer.org/conference-name/year) then perhaps being able to search on that basis would also solve the problem?

**Comment by katrinleinweber** [comment]
Well, I'm asking ;-)

> […] ultimately wanted to do with the tags?

The same as with all tags, I guess. Allowing easy aggregating of annotations regardless of domain.

Your hint about searching for the domain solves the problem for now though, thanks :-)

**Comment by robertknight** [comment]
> Well, I'm asking ;-)

Ah, sorry about that. I wasn't thinking and mixed you up with someone who works at Hypothesis!

**Comment by katrinleinweber** [comment]
No problem :-) With FLOSS projects, everyone is a co-worker.

**Comment by katrinleinweber** [comment]
No problem :-) With FLOSS projects, everyone is be a co-worker.
