### ISSUE TITLE
usability/UX suggestions

### ISSUE THREAD

**Issue by malcook** [hypothesis/product-backlog#446]
A few suggestions:

Reinforce conception that a **highlight** is simply an **annotation** without any attached text!  Many things flow from this.

Use color to distinguish annotation from highlight.

Make the side-bar less intrusive.

Display it less!

Make the side-bar background (optionally?) be semi-transparent when you display it at all.

On click raise/lower of annotation sidebar is annoying to me.   Too distracting!

Instead, provide single annotation display, not the whole sidebar.

Make single annotation display what happens on click.

Make single annotation display be semi-transparent.   Let user adjust where it pops up.

Provide option to display SAD on hover.

In general, provide option to be fully keyboard driven - remove requirement to use mouse.    Allow to work with current text selection regardless of how established (ie shift arrow keys extend selection) - provide keyboard shortcuts for everything (i.e. meta-a: edit-annotation-at-selection; meta-h: toggle-highlight-selection).

Reduce # steps to create new annotation!  e.g.:  meta-a (or mouse-drag-release) pop-up a single annotation box (not the whole toolbar), type text, hit a few tabs (be default keeping tags from last annotation entered), hit enter, and it all GOES AWAY.  No clicks!  Just keyboard.  And fewer mode changes!  

If you must keep the sidebar:  it appears I have to click away to dismiss the sidebar.  Escape does not dismiss it either and arguably should.  

Thanks!

**Comment by klemay** [comment]
Hi there,

Thanks for reaching out - feature requests and UX/UI suggestions from the community are always welcome. Some of these are already outlined in existing issues, so I'm going to link to them here. For the others, I'm going to create discrete cards and will link back here. Once that's done I'll close this issue, but you'll be able to follow your requests via their individual cards.

**Comment by klemay** [comment]
## Sidebar
### Your requests
- Make the side-bar less intrusive.
- Display it less!
- Make the side-bar background (optionally?) be semi-transparent when you display it at all. (combining with "Make single annotation display be semi-transparent. Let user adjust where it pops up.")
- On click raise/lower of annotation sidebar is annoying to me. Too distracting!
- If you must keep the sidebar: it appears I have to click away to dismiss the sidebar. Escape does not dismiss it either and arguably should.
### Existing issues
- [Don't cover the page with your sidebar #94](https://github.com/hypothesis/product-backlog/issues/94): discussion of making sidebar less intrusive and providing options to users
- [Improve sidebar behaviour when making a new annotation #189](https://github.com/hypothesis/product-backlog/issues/189): discussion of sidebar behavior when making annotations

## Annotations vs highlights
### Your requests
- Reinforce conception that a highlight is simply an annotation without any attached text! Many things flow from this.
- Use color to distinguish annotation from highlight.
### Existing issues
- [Highlight in multiple colours #198](https://github.com/hypothesis/product-backlog/issues/198): ongoing discussion of providing color options for annotations/highlights
- [Make private highlights less confusing #190](https://github.com/hypothesis/product-backlog/issues/190): ongoing discussion of highlights vs. annotations and how that can be confusing for users

## Keyboard controls and workflow
### Your requests
- In general, provide option to be fully keyboard driven - remove requirement to use mouse. Allow to work with current text selection regardless of how established (ie shift arrow keys extend selection) - provide keyboard shortcuts for everything (i.e. meta-a: edit-annotation-at-selection; meta-h: toggle-highlight-selection).
- Reduce # steps to create new annotation! e.g.: meta-a (or mouse-drag-release) pop-up a single annotation box (not the whole toolbar), type text, hit a few tabs (be default keeping tags from last annotation entered), hit enter, and it all GOES AWAY. No clicks! Just keyboard. And fewer mode changes!
### Existing issues
- [Create annotations/highlights via context menu #7](https://github.com/hypothesis/product-backlog/issues/7): suggestion for simplifying workflow
- [Remove requirement to use mouse #447](https://github.com/hypothesis/product-backlog/issues/447): a newly created issue thanks to your suggestion! 

## Single Annotation Display
### Your requests
- Make single annotation display what happens on click.
- Provide option to display SAD on hover.
### Notes
- We already have a way of viewing just one annotation. If you click on a highlighted portion of text, the sidebar will open, showing only that annotation.
