### ISSUE TITLE
confirm Tweets before posting

### ISSUE THREAD

**Issue by xolotl** [hypothesis/product-backlog#465]
### Steps to reproduce
1. Share an annotation using the H. "Share" button.
2. Choose to share to Twitter.
3. On first tweet confirmation view, realize one wants to post from a different Twitter account.
4. Log out of the first Twitter account and log in to another.
5. The tweet is sent without another chance to modify its contents!!!

### Expected behaviour
Users should ALWAYS get the opportunity to modify the content of social shares before they are posted, regardless of other steps in the workflow.

### Actual behaviour
Covered in steps to reproduce.

### Browser/system information
Chrome Version 64.0.3282.140 (Official Build) (64-bit), Mac OS 10.13.3.

**Comment by robertknight** [comment]
I confirmed that X/Twitter requires confirmation before tweeting after using the share link in the client. We can only control the first place we link to though on Twitter / X though, we're not in control of what happens after that.
