### ISSUE TITLE
Migrate h to Python 3

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#467]
Python 2 is gradually starting to reach end of life [1] and various libraries are starting to drop support for it. We are not under any immediate pressure to finish a migration but our codebase is mostly compatible [2] and AFAIK we no longer have any dependencies that are Python 2 only. Additionally Python 3 provides various functional and performance improvements across the language, runtime and standard library.

On that basis, I'd propose that we start running tests against Python 3 and incrementally fix remaining issues, with a view to transitioning the production environment over some time in the next few months.

A rough plan of action would be:

1. Make Travis run unit tests against Python 3, ignoring existing failures.
1. Incrementally fix remaining compat issues
1. Get our functional tests running against Python 3
1. Do some testing of the app itself locally to make sure all the core functionality works
1. Change the Docker build to use Python 3
1. Test on QA
1. Deploy to prod
1. Profit!

[1] See https://github.com/Pylons/pyramid/issues/2903
[2] I got all the unit + functional tests passing locally with a diff of ~250 lines over master at 66f83ba23.

**Comment by ajpeddakotla** [comment]
Note - add documentation for devs/external users on the Python 3 requirement.

**Comment by lyzadanger** [comment]
Closing in favor of https://github.com/hypothesis/h/issues/5384
