### ISSUE TITLE
Several client UX issues related to the inline nature of the annotation editor

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#476]
This is just a mega-issue to collect together in one place a list of UX issues to do with creating and editing annotations to consider.

I think there's actually several closely related issues with creating annotations in Hypothesis right now. I don't think any of these are necessarily problems with **the adder** per se, rather they're problems with the whole UX flow of creating annotations, for example I think the **annotation editor** in the sidebar is implicated in many of these. Here's just some off the top of my head but I think there are more.

In my opinion these issues all have to do with the fact that creating and editing annotations happens **in line** within the sidebar while all the other functions of the sidebar remain active, rather than being a modal experience as I think posting in most other web apps is.

1. Select some text, click **Annotate**, maybe start typing your annotation, then realise that you're not in the group you want to annotate in. At this point you're stuck: you can only save the annotation into the group you're in (it can either be shared or **Only Me** within that group but it must be within that group).

   This actually is not true - there's a workaround that we added that if you change the focused group in the groups menu, then the in-progress annotation moves with you into the new group. You _can_ actually move an annotation between groups, as long as it's an unsaved annotation that you're newly creating. But this seems counterintuitive and undiscoverable to me - I doubt that many users know they can do this. Also, this behaviour is at odds with what happens when you try do so the same thing while **editing** a previously saved annotation, the inconsistency is likely confusing and unexpected.
  
2. Select some text, click **Annotate**, maybe start typing your annotation, then realise that you're not in the group you want to annotate in. Since you're someone who knows about this hidden Hypothesis feature you change the group in the groups menu, making sure to do so **without** saving your annotation first, because you know that **unsaved** annotations will move with you to the new group. But when you go to the new group you see many annotations from other people, and your in progress annotation is lost!

   After changing group while creating an annotation the sidebar does not scroll to the in-progress annotation within the new group. If the new group contains a lot of annotations you can easily lose sight of your in-progress one.

3. Select some text, click **Annotate**, maybe start typing your annotation, then realise that you don't have permission to annotate in the group that you're in. This is a stronger version of (1), and is a new problem that only appears once we have restricted groups.

4. Select some text, click **Annotate**, maybe start typing your annotation, then realise that you're not logged in. Currently we actually prevent users from creating a new annotation while not logged in, but we prevent in what I think everyone agrees is a horrible and broken way that doesn't help users achieve what they're trying to do (sign up or log in and then continue creating their annotation).

   Attempting to create a new annotation when you haven't signed up for a Hypothesis account yet is a stronger version of (4) (and the UX for this experience is massively worse)

5. Select some text, click **Annotate**, maybe start typing your annotation, then move the scrollbar within the sidebar. Your in-progress annotation can go off screen and out of view completely, and it can become quite difficult to find it again, especially if there are a lot of annotations, even new realtime annotations are coming in, or if you change to a different group (your annotation remains in progress and unsaved in the other group).

   There's no indication that you have unsaved work in progress, or of where your in-progress annotation is. You can just lose it.
   
   In some situations (e.g. realtime annotations coming in and pushing yours down) you don't even have to move the scrollbar yourself - the app will move your in-progress work off screen for you! Accidentally hitting keys like Page Up, Page Down, Home or End while typing will also jump your work off scree suddenly too. Creating a second annotation while the first one is still in progress (see below) will also automatically scroll and lose the first one too.

   If you navigate to a different page (e.g. by clicking a link) when in this situation you will just lose your in progress work without warning. (Many things in the client are buttons that you _can_ safely use without losing work, other things that often look the same are links that will navigate the page and lose your work.)

6. Select some text, click **Annotate**, maybe start typing your annotation ... At this point there's nothing to stop users from selecting some more text (either the same text or some different text) and then clicking **Annotate** again.

   What happens if you do this is inconsistent and confusing. If you hadn't yet typed any text into the first annotation then the second time you click **Annotate** it deletes the first empty annotation and replaces it with a second empty annotation. Two empty annotations look almost exactly alike, so it's likely that the user doesn't realise what has happened and instead thinks the second click of **Annotate** didn't work.
    
    If you _had_ already typed some text into the first annotation then it leaves the first annotation in-progress and creates and scrolls to a second, new in-progress annotation. This likely scrolls the first annotation off screen and there's no indication that the first annotation is still in-progress or where it is or how to get back to it - it's likely lost to the user.
    
    This second behaviour is also what happens if you create a new annotation while in-progress **editing** a previously saved annotation.

7. Select some text, click **Annotate**, type some text into the annotation, don't save it yet. Select some text again, click **Annotate** again, creating a second annotation so that you now have two in-progress annotations unsaved. Don't type any text into the second annotation. Change the group in the groups menu. The first unsaved annotation gets left behind (still unsaved) in the previous group, whereas the second annotation comes with you to the new group, though if there are already annotations in the new group it miay be scrolled off screen. At this point the user may well have lost track of both annotations, in different ways!

8. There's no way to see all my private annotations, and only my private annotations, together in one place without other people's annotations and my shared annotations mixed in.

9. Annotation isn't discoverable. A new user looking at Hypothesis for the first time sees a new page note button but no annotate button. You have to select some text in the browser to see the annotate button. Unlikely to be discovered by users.

10. Select some text, click **Annotate**, type some text into the annotation, realise that the text you've selected isn't quite right. You're stuck: there's no way to change the selected text of an annotation.

**Comment by dawachan** [comment]
Thanks for collating these issues @seanh. It's a massive undertaking and agree that it needs to be a separate albeit related effort to Restricted groups. I would like to sync with @ajpeddakotla when she is back in with respect to the prioritisation of fixing some of the more pressing UX issues with respect to annotation behaviour vs. the groups work we are currently tasked with.

**Comment by seanh** [comment]
I'm gonna close this card as it's just a record of a whole lot of related issues and not really a card that we would do / implement ever. Smaller cards should probably be created for specific things when the time comes. The closed card is always still here to refer to
