### ISSUE TITLE
Improve access to 'All My Annotations' from the sidebar

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#478]
**Justification:**

At the moment, the only way for users to view all their annotations is to click the profile icon within the sidebar to expand it, and then click their username to go to web view and see all their annotations.

A tool tip appears 'View all your annotations' on rollover.

![screen shot 2018-02-19 at 14 26 11](https://user-images.githubusercontent.com/5212631/36382457-da84fd96-1580-11e8-8185-cdc1f091f8b8.png)

It is suggested (@heatherstaines) that we incorporate a more intuitive and obvious way to be able 'View all annotations'.

**Solution:**

TBD

**Comment by ajpeddakotla** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/110
