### ISSUE TITLE
Rapid Iterative Testing for Open Groups

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#480]
Done When: 
- [ ] Write testing script
- [ ] Dependent on integration timelines, book testing sessions

**Comment by dawachan** [comment]
Have put together a list of follow up questions for publishers:
https://docs.google.com/document/d/1QtJPKkkbdKPOGFDKOKvvoJm0a4y3aYPyZiKw9lUgtEk/edit

These cover requirements around: group type, path scoping and admin/mgmt - have asked product team to add to the doc with additional questions.

Have followed up with CUP and am waiting for feedback.

**Comment by ajpeddakotla** [comment]
Closing this as no longer needed.
