### ISSUE TITLE
Migrate `GET /groups` property `urls` to `links`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#486]
The developer of the new `GET /api/groups` endpoint (ahem, yours truly) managed to not notice that `annotation` objects are returned by the API with a `links` object, and named the analogous property `urls` on `GET /api/groups`. Whoops. This should be rectified—groups should have a `links` property, not a `urls` property—but needs to be coordinated with a client release as it is breaking.

Also a good opportunity to excise the legacy and cumbersome `url` property from this response.

This could possibly be accomplished by:

## Step 1 (Removing `url`)

*  [x] Client code is checked to make sure that there are no references to the `url` property on `group` objects returned by the API at `GET /api/groups`. If there _are_ references to `url`, these should be changed to `urls['group']` and merged before proceeding.
* [x] Update generated API documentation for `/api/groups` to remove the `url` property from the docs
* [x] Update `h.presenters.group_json` to remove `url` from the returned model
* [x] Update tests

## Step 2 (adding `links`)

This is an interim step before _removing_ `urls` outright.

* [x] Update `h.presenters.group_json` to return a `links` property that is identical, for now, to `urls`
* [x] You may opt to change `links['group']` to `links['read']` to better match the annotation links reponse
* [x] Update tests

(Don't update docs just yet)

## Step 3 (convert client to use `links`)

Once the above is merged:

* [x] Vet the client code for all references to `urls['group']` and change it to `links['group']` (or `links['read']` if you chose that naming)
* [x] PR/merge these changes

## Step 4 (remove `urls` from response)

* [x] Update `h.presenters.group_json` to remove `urls` (return `links` only)
* [x] Update generated API docs for `GET /api/groups` to _add_ `links` and _remove_ `urls`
* [x] Update tests

**Comment by sheetaluk** [comment]
Blocked to begin by https://github.com/hypothesis/h/pull/4871
