### ISSUE TITLE
Open group activity pages styling/ux design changes

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#490]
As a user I would like to have pretty activity pages that are easy to navigate and obtain information about an open group. This is styling related to https://github.com/hypothesis/product-backlog/issues/422.
https://user-images.githubusercontent.com/5212631/36032068-b22e6c9e-0da4-11e8-9ee0-ab3e2335a7a3.png
https://user-images.githubusercontent.com/5212631/36032071-b248b7fc-0da4-11e8-886a-1f78f745272c.png
Note: this does not include the logo or authority -that will be in another PR.

**Comment by hmstepanek** [comment]
@dawariley I made a new issue for the styling for open groups that we've been working on. I think the mocks are a little out of date/have changed slightly from when you first made them (based on our back and forth about the styling). I'm not sure if it's necessary to upload new ones but just wanted to let you know I attached them and feel free to modify them/remove them as you see fit.

**Comment by ajpeddakotla** [comment]
Closing this as it is completed.
