### ISSUE TITLE
Activity pages for restricted groups

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#495]
### User Story: 
As a Hypothesis user I want to be able to see all the annotations that are made in a restricted group so that I can view all the annotations made within that group in one view. 

### Acceptance Criteria: 
Activity pages should show
- [x] # of public annotations made in that group
- [x]  Name of the group admins (so that H users know who created and controls that group)
- [x]  Share link for group (so that H users can share the group), but users will not be able to join the group using the share link. 
- [x] Restricted Groups won't appear in the groups dropdown (for non-members)
- [ ] ^ Write tests for that
- [x] Restricted groups should have their own groups landing page 
- [x] Restricted groups pages are visible to logged out users.
- [x] Keep the leave link in the sidebar for restricted groups. (group members should be able to leave the group if they no longer want to be a member of the group). 
- [x] Show tags used (As currently exists)
- [x] Show group members to the public (as currently exists for private groups)
- [x] In Dawa's mockup below 'Authors' is now 'Contributors'(not anymore. They are always going to called Members irrespective of group type)

**Comment by dawachan** [comment]
Earlier mock I did for Restricted Group activity page:

![36210599-bcab1924-1196-11e8-8706-7aa27740941a](https://user-images.githubusercontent.com/5212631/36740184-9e038054-1bd9-11e8-9755-e7bd7c1f184c.png)

Note Authors is now Contributors, will update.

**Comment by hmstepanek** [comment]
See comment: https://github.com/hypothesis/product-backlog/issues/424#issuecomment-367539827

**Comment by ajpeddakotla** [comment]
@dawariley re: Authors vs. Contributors. 

Those two terms are different from what our current schema uses, so I would like to understand the rationale for the change in wording. Also, I think this is something that might need further discussion in how we're presenting groups/membership/users holistically. 

Currently for the restricted group I see: 
<img width="396" alt="screen shot 2018-03-02 at 1 24 54 pm" src="https://user-images.githubusercontent.com/7463523/36917818-7570a608-1e1d-11e8-86c6-4382c621bc72.png">

Can we just keep the same structure we have now for private groups, and instead just mark the moderators/creators in the same way we do in private groups? For instance in the current H Reading group, I can see that judell created the group and the rest of the members of the group too. 
<img width="218" alt="screen shot 2018-03-02 at 1 25 25 pm" src="https://user-images.githubusercontent.com/7463523/36917882-a955a874-1e1d-11e8-99db-5f8359f6bdf2.png">

What do you think about this approach @dawariley?

**Comment by hmstepanek** [comment]
Personally, I agree with Arti here. I would think restricted groups would also have members, however, we do need some way of distinguishing to the user the difference between the groups and this is one very effective way of doing that.

**Comment by dawachan** [comment]
Thanks @ajpeddakotla I'm going to respond Monday!

**Comment by ajpeddakotla** [comment]
Reminder to take contributors v. member discussion offline. - @sheetaluk is blocked on this until we figure this out.

**Comment by dawachan** [comment]
As part of my 1:1 with @dwhly we discussed renaming members -> contributors for restricted groups activity pages. Based on product needs, it was decided that we should leave the list of users as 'members' as the working term for now until we can get feedback from our users. I hope this unblocks with you @sheetaluk and I hope @ajpeddakotla you're onboard with this too!?

**Comment by sheetaluk** [comment]
Opened new cards for:
1. User leaving restricted group from the activity page view
https://github.com/hypothesis/product-backlog/issues/530
2. Refactor activity pages template and view files into manageable components
https://github.com/hypothesis/product-backlog/issues/531

**Comment by seanh** [comment]
@sheetaluk Can we close this card now?

**Comment by ajpeddakotla** [comment]
Closing as issue is completed.
