### ISSUE TITLE
Add create_restricted_group() service method

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#499]
Part of https://github.com/hypothesis/product-backlog/issues/496

Add a new `create_restricted_group()` method and tests to [GroupService](https://github.com/hypothesis/h/blob/master/h/services/group.py). This will allow restricted groups to be created by developers in a Python shell, and then we can see what needs to be done for them in the API, activity pages and client.

**Comment by ajpeddakotla** [comment]
Closing as it is completed.
