### ISSUE TITLE
Write up of QDR ATI Workshop

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#506]
Write up of 2-day attendance at QDR:

https://docs.google.com/document/d/1P9F0-SCBk9u4dpSE8DEozzJofpEGbm0SW4DbRUQPMlU/edit#

Learnings:

* Use cases for scholarly annotation
* Feature requests for annotation clients
* Pain points with H and annotation tools
* Feedback and use cases on groups in scholarly annotations for authors + researchers

**Comment by ajpeddakotla** [comment]
closing this as it has been completed.
