### ISSUE TITLE
Add ability to delete groups (for H admins only)

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#507]
Feel free to obliterate this if it is a dupe of something tracked elsewhere.

We're getting to a point with groups development that I think we need some way to delete open and restricted groups—only from the admin interface initially. This will avoid us from heaping up tons and tons of test groups or mistaken groups that are hard to get rid of. I seem to recall hearing that deleting groups was non-trivial, but I hesitate to add the ability to add groups in the UI without a way to remove them, too. Ultimately this will have a meaningful user story driving it because users need to be able to delete groups in the long term.

There are some established patterns for removing entities (with confirm modals, e.g.) that could be used to build the admin interface for this. I think the first step is to identify the challenges inherent in removing groups and see what it would take to overcome them.

Updated: acceptance for this could look like:

**Please keep in mind this is a first-draft tool mostly for development/testing purposes**

* [x] Add a `Delete Group` column to the current table of results on the `list groups` admin panel (_Edit: This was added as a button to the group edit/read page instead_)
* [x] When `Delete Group` is clicked on, a confirmation modal similar to that shown for admin-user-delete should be displayed
* [x] If the modal is agreed to, the group should be deleted from the database and the admin user should be put back on the list-groups page (the deleted group should not show up anymore)
* [x] Group deletion should also include deletion of annotations within that group
* [x] Group deletion should also include removing member relationships from that group
* [x] If the modal is dismissed, nothing should happen—the admin user should see the list of groups again with no changes to it

**Note**: At time of authoring these acceptance criteria, organization modeling is just entering reality—it is possible that the existence of `organization` entities may add additional need here.

**Comment by robertknight** [comment]
> I seem to recall hearing that deleting groups was non-trivial

We already do delete groups when deleting user accounts in `h.services.delete_user`. There are some potential complications with the way annotations are soft-deleted which means that a synchronous deletion of groups would temporarily leave soft-deleted annotations in the DB referencing a `groupid` that no longer exists. I don't think that will be a major issue.

**Comment by lyzadanger** [comment]
> We already do delete groups when deleting user accounts in h.services.delete_user. 

Can I presume that there are some cascading DB constraints that will delete annotations in the group if the group is deleted, in general ? That is, will something as simple as `self.request.db.delete(group)` (from `h.services.delete_user`) be sufficient to kick of whatever "soft-deletion" happens?

i.e. "Is it really that simple for _basic_ group deletion"?

**Comment by robertknight** [comment]
> Can I presume that there are some cascading DB constraints that will delete annotations in the group if the group is deleted, in general ?

Annotations don't have a DB-level FK relation with groups, which is I think mostly a historical artefact, so a little bit of extra logic is needed to handle the deletion. But if you look at `h.services.delete_user` you can see that it isn't very complicated - just fetching annotations in that group, looping over them and making a couple of calls to other code.

**Comment by lyzadanger** [comment]
>  But if you look at h.services.delete_user you can see that it isn't very complicated - just fetching annotations in that group, looping over them and making a couple of calls to other code.

Oh, yeah, duh, now I see that!

Do I need to explicitly remove group-user relationships or (as I would expect) they'll automatically get wiped?

**Comment by robertknight** [comment]
> Do I need to explicitly remove group-user relationships or (as I would expect) they'll automatically get wiped?

Inspecting the generated schema, it looks like there isn't presently a cascading deletion on the `user_group` relationship:

```
 ~/h/r/h > docker run -it --link postgres:postgres --rm postgres sh -c 'exec psql -h "$POSTGRES_PORT_5432_TCP_ADDR" -p "$POSTGRES_PORT_5432_TCP_PORT" -U postgres '
psql (9.6.1)
Type "help" for help.

postgres=# \d "group"
                                      Table "public.group"
    Column    |            Type             |                     Modifiers                      
--------------+-----------------------------+----------------------------------------------------
 created      | timestamp without time zone | not null default now()
 updated      | timestamp without time zone | not null default now()
 id           | integer                     | not null default nextval('group_id_seq'::regclass)
 pubid        | text                        | not null
 authority    | text                        | not null
 name         | text                        | not null
 creator_id   | integer                     | 
 description  | text                        | 
 joinable_by  | group_joinable_by           | 
 readable_by  | group_readable_by           | 
 writeable_by | group_writeable_by          | 
Indexes:
    "pk__group" PRIMARY KEY, btree (id)
    "uq__group__pubid" UNIQUE CONSTRAINT, btree (pubid)
    "ix__group_name" btree (name)
    "ix__group_readable_by" btree (readable_by)
Foreign-key constraints:
    "fk__group__creator_id__user" FOREIGN KEY (creator_id) REFERENCES "user"(id)
Referenced by:
    TABLE "groupscope" CONSTRAINT "fk__groupscope__group_id__group" FOREIGN KEY (group_id) REFERENCES "group"(id) ON DELETE CASCADE
    TABLE "user_group" CONSTRAINT "fk__user_group__group_id__group" FOREIGN KEY (group_id) REFERENCES "group"(id)

postgres=# 
```

(BTW. The table names "user" and "group" have to be quoted in psql because they have special meanings otherwise. This isn't needed for other tables).

On that basis, I think you will either need to add this cascade (which can be done with a migration, I think we have some past examples) or (probably easier to start with) manually remove the relations in code first. Please do check my guesswork though!

**Comment by lyzadanger** [comment]
Several pieces of this are in flight if anyone wishes to pick this up.

* [This branch](https://github.com/hypothesis/h/tree/admin-delete-groups-view) defines a view controller and a template for the delete-a-group interface following the established modal-confirm pattern from the delete-a-user admin tool
* [This branch](https://github.com/hypothesis/h/tree/delete-groups-service) adds a `delete-group` service and some rudimentary tests for it.

What needs to happen next:

* I'm not convinced the tests are good enough on the `delete-group` service; specifically, I'd like to be able to verify that `user_group` relationships are deleted when the `group` is deleted
* Things need to be hooked up: the view controller needs to be connected to the `delete-group` service once that's ironed out.
