### ISSUE TITLE
Search - Adding 'my' open and restricted groups to Group: facet

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#510]
**As a USER I want to be able to find annotations and groups that I am associated with.**

note: This card is part of a bigger EPIC story for improving the discoverability of open and restricted groups covered by: #470 

**Changes Required to accommodate new groups:**

1. A user clicks the search field at the top of an activity/user page in web view, the text giving an overview of the search facets is modified from: "show annotations you are a member of" (current string) to: "show annotations associated with a group."

<img src="https://user-images.githubusercontent.com/5212631/36260158-7676b982-1258-11e8-9352-d268ecbf5bd3.png">

2. The user enters`group:` in the search field and a list of the groups I am associated with appears below (currently only private groups display). This list will be extended to include Open and Restricted groups.

![screen shot 2018-03-08 at 15 09 51](https://user-images.githubusercontent.com/5212631/37158250-d821d1a4-22e2-11e8-9949-cb01fbeeeb8b.png)

Note: This view should keep parity with the 'My Groups' control in web view. #473 

Pending review by @dwhly and @ajpeddakotla

**Outstanding Questions apply across both:**

* Should we show the organisation name? *(recommendation: since exposing and clustering by org. is a key concept in the main group control, it will help users if we keep consistency here too.)*
* Should we include the role? *(recommendation: having role is helpful because it shows the user at a glance what their relationship is to a particular group.)*

*Mock showing org name included below:*
![screen shot 2018-03-08 at 15 13 27](https://user-images.githubusercontent.com/5212631/37158438-4dc1e958-22e3-11e8-8bfb-74299a3901de.png)

AC:

- [ ] The text string describing the group: facet inside the search field expanded state is changed to: 'group: show annotations associated with a group.'
- [ ]  Groups that users are already are a member of (private) or have been assigned to or created (restricted or open groups) will show up when the user types `group:` in the search field as per the mockup above.
- [ ]  The user role (group creator/contributor) is exposed (tbd)

**Comment by ajpeddakotla** [comment]
@dawariley @hmstepanek - Dawa, Dan, Andrew, and I met and we discussed the use of labels to mark group members. 

The use of the `creator` label is great as it let's the user know that these are groups that they've created. 

But the use of other labels to identify group members is a seperate story, and something we need to discuss further. So let's implement the `creator` group label for now. 

Let me know if there are any questions.

**Comment by ajpeddakotla** [comment]
Closing as this has been completed.
