### ISSUE TITLE
Converting groups from one type to another

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#512]
### User Story: 
As a Group Owner/creator I want to be able to convert a group from one type to another after it has been created, and make sure all the annotations follow the read logic of that chose group, so that I can change who can see and make annotations in my group. 

_e.g 
Open -> Restricted
Restricted -> Private_

***To discuss:***
Limiting permissions is potentially easier to manage from a user perspective. The danger we have with opening up previously restricted groups is that users privacy might be violated if annotations are suddenly world readable so this type of group type conversion will need to be exercised with caution (we could implement special messaging or an alert within the admin UI to warn users about the consequences of changing type). 

_e.g
Restricted -> Open
Private -> Open_

**Justifications:**
The need to expose annotations and allow contribution/collaboration around annotations via groups varies throughout the pre-print -> peer review -> submission -> re-submission life cycle. Our users need to have control of who can see annotations and who can contribute. we should afford users with control over the restrictions/ openness around group permissions in order to be able to support these needs.

Presently the only way to change permissions of a group would be to delete and create a group from scratch.

**Comment by dawachan** [comment]
Needs some 'design thinking' re: UX and privacy issues around exposing annotations previously created in 'private' or 'restricted' contexts and how we should handle this/messaging for end users/admin users.

**Comment by ajpeddakotla** [comment]
Closing this as we're going to build it for the admin panel first. Will write up a new ticket for that.
