### ISSUE TITLE
Restricted groups show twice in groups menu if you are a member of the group

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#514]
If you are a member of a restricted group (for example if you are the creator of the group, since the creator of a restricted group is automatically added as a member) then the restricted group appears twice in your groups menu in the client.

It appears once near the top of the menu with the other open and restricted groups, above the **Public** group. Then, since you're a member of the group, it appears again further down with the private groups.

Note: my guess is that **the API** is probably returning the restricted group to the client twice, so this should probably be fixed by fixing the API (and no client changes). If my guess is right.

@sheetaluk Since your `sheetaluk` account is the creator of the restricted group on <https://biopub.hypothes.is/>, can you add a screenshot of the big to this card for me please?

**Comment by sheetaluk** [comment]
![image](https://user-images.githubusercontent.com/502186/37039087-9a906928-2124-11e8-87e3-cde000763b7b.png)
Pointing out what may already be obvious - doesn't happen when a user is logged out.

**Comment by lyzadanger** [comment]
This is related to #509

**Comment by sheetaluk** [comment]
@lyzadanger might be obvious, I'm just noting that this happens for both restricted and open groups
