### ISSUE TITLE
Add `delete-group` Service

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#525]
This is part of #507 

We need a new `h.service` along the lines of `h.services.delete_user` for deleting groups. The delete method in this service needs to be cognizant of the delete requirements mentioned in #507 ; that includes:

* Removing any and all members from the group
* Deleting all annotations within the group
* Deleting the group itself (last)

This service is initially intended to be used for admin deletion of groups _only_ and should not be considered "production-worthy" in terms of deleting actively-used groups with a bunch of members. It's mostly, at this point, a tool to be able to remove test and dev-site groups.

**Comment by lyzadanger** [comment]
Work-in-progress branch: https://github.com/hypothesis/h/tree/delete-groups-service

**Comment by ajpeddakotla** [comment]
Closing as this has been completed.
