### ISSUE TITLE
Design Spike: Improvements to existing Groups Control Menu

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#532]
As a USER I need an easy way to perform user actions associated with a group:

- Delete a Group (if creator)
- Leave a Group (if member)
- View Activity
- Invite/Share

### User requests
- https://hypothesis.zendesk.com/agent/tickets/2546 (wants to delete group)
- https://hypothesis.zendesk.com/agent/tickets/2831 (wants to delete group)

### Justification ###

In the current groups control, a user is able to view activity and leave (or delete) a group. In order to be able to leave a group or 'invite' users to join or to share a group they need to go to the Activity page first.  Users also report issues of missing the target and clicking through to the groups activity 
page.

**AC**

- [ ] onHover/onPress a larger target (grey circle) is shown to show greater affordance. (1 below)
- [ ] Clicking on the downward arrow inside the groups menu expands the group actions panel. (1 below)
- [ ] Clicking off the group actions panel closes it.
- [ ] Inside the expanded panel, onRollover a group action - the text is bold and #BF363F. (2.1 below)
- [ ] Display the list of actions associated with the group type and available to the authenticated user (e.g creator vs. non creator) as contained in the specs below 2.2 -> 2.6.
- [ ] Clicking on a group action performs the action spec'd out below in 2.2 -> 2.6.

note: ~~Annotation Counts~~  are not part of the implementation for this card.

note: for Share/Join group action - for now this redirects to activity page where the link is shown, but I would like to propose a short cut against this menu option to share direct from the menu.

**Outstanding Questions:**

1. Should a creator be allowed to leave a group? Presently we support this but as a user I would be confused in terms of who will have creator (edit/delete) permissions if I leave a group.
2. As a user with admin permissions on an Open or Restricted group - do we show delete or edit options in the menu?

![screen shot 2018-04-16 at 11 12 25](https://user-images.githubusercontent.com/5212631/38803463-3a2950b4-4167-11e8-8c98-d9b7566edc3e.png)

![screen shot 2018-04-16 at 11 14 06](https://user-images.githubusercontent.com/5212631/38803526-6e06362c-4167-11e8-865a-97625510eefb.png)

### Proposal ###
The proposed design 'rolls up' the associated actions into an expandable menu and includes shortcuts e.g leaving a group and sharing/inviting members directly from within the control itself. 

Depending on the group type and user permissions - the actions displayed in the menu will vary.

**1. Interim group control**

_Arrow right aligned_
![interim dropdown target cta - consistent arrows medium copy](https://user-images.githubusercontent.com/5212631/39428266-a906d278-4c7e-11e8-8ed3-5ad1cf377816.png)

_Arrow right aligned with read-only badge_
![interim dropdown target cta - consistent arrows medium with read only badge](https://user-images.githubusercontent.com/5212631/39471275-402ff3ee-4d3a-11e8-9f83-3fa4fbf3253e.png)

**2. Target group control**
![final dropdown target cta - medium with read only badge](https://user-images.githubusercontent.com/5212631/39471401-f1d4c764-4d3a-11e8-8229-e36c92968175.png)

_Revised Carat Specs_
![carat specs](https://user-images.githubusercontent.com/5212631/39471282-47d9e154-4d3a-11e8-9284-984a193540ea.png)

**_Carat colour_**
New Carat colour: **#4C4C4C** to pass WCAG requirements.

**_Tap target_**
Tap target area around Carat (including carat): **44px**.
![screen shot 2018-05-01 at 17 18 30](https://user-images.githubusercontent.com/5212631/39481613-f78aefac-4d63-11e8-9dcc-a4204d20ed31.png)

**_Carat onHover state_**
onMouseover or onTap (mobile) within the 44px radius of the carat -  display a grey circle to users around the carat: #DEDEDE with a diameter of 30px.
![screen shot 2018-05-01 at 16 59 38](https://user-images.githubusercontent.com/5212631/39481464-747f7f42-4d63-11e8-8236-abec79957bc4.png)

**2. Expanded Menu States**

_2.1 Initial state and on rollover_

![menu states](https://user-images.githubusercontent.com/5212631/38806518-6c6cbda4-4171-11e8-86cd-eb44996e1b83.png)

_2.2 Private Group Expanded Menu - creator_

![menu states - private group - creator](https://user-images.githubusercontent.com/5212631/38806566-94c2ad18-4171-11e8-9fc4-11c924be1942.png)

_2.3 Private Group Expanded Menu - non creator_

![menu states - private group - non creator](https://user-images.githubusercontent.com/5212631/38806573-9a1188d4-4171-11e8-819a-1bca23078c2d.png)

_2.4 Hypothesis Public Group Expanded Menu_

![menu states - hypothesis](https://user-images.githubusercontent.com/5212631/38806622-b828190a-4171-11e8-9659-9b9aeb5d3781.png)

_2.5 Open Public Group Expanded Menu_

![menu states -open group](https://user-images.githubusercontent.com/5212631/38806750-3a518a92-4172-11e8-9f1d-9640585909a7.png)

_2.6 Restricted Group Expanded Menu_

![menu states - restricted group](https://user-images.githubusercontent.com/5212631/38806758-3f13e62e-4172-11e8-9511-dfcb8217ecc7.png)

**Comment by klemay** [comment]
I enjoyed seeing this in the Demo today! I have a few questions from a support/accessibility perspective:

- Does the color of the arrow vs background of menu meet [WCAG standards for contrast](https://webaim.org/resources/contrastchecker/)? If you provide a hex code for the color of the arrow I'd be happy to check this myself.
- Glad to see you've considered the size of the target area, and I know the team brought up a question about this during demo. There isn't a clear consensus re: what makes a touch target big enough to be "accessible" but I usually refer to [Google's Web Fundamentals](https://developers.google.com/web/fundamentals/accessibility/accessible-styles).

There are also some considerations that are specific to screenreader / keyboard-only users:
- How will this arrow + dropdown affect the tab order of the groups control? I.e., will a screenreader user be forced to listen to the "View group," "Invite," "Edit," etc for each and every group they see in their drop down? Or can they focus on the arrow and have the screenreader say something like "expand for group options", with the option to skip?
- Do you have preference for what that screenreader prompt should say? I think "Drop-down: group options. Press enter to expand" would be my first instinct.
- Will this arrow be able to take keyboard focus + accept keyboard commands?

**Comment by dawachan** [comment]
Thanks for raising these issues @klemay. Addressing the accessibility concerns individually:

**_Arrow size and padding_**
I'll add it to the specs that the minimum tap area around the design elements in the new groups control should be 44px x 44px as recommended by the HIG - https://developer.apple.com/ios/human-interface-guidelines/visual-design/adaptivity-and-layout/.  Although as you mentioned, there isn't a clear consensus, Google recommends 48px x 48px: https://developers.google.com/web/fundamentals/accessibility/accessible-styles. 

In the design I did, I was proposing to show a rollover state on mouseover for web, could also have the colour change on tap as well. In the attached, the inner circle around the arrow is the visible affordance, and the outer circle is the actual tap area required. 

![interim dropdown target cta - medium with read only badge - darker](https://user-images.githubusercontent.com/5212631/39472509-cef1b3c2-4d41-11e8-911a-2fd51fc97f78.png)

**Comment by dawachan** [comment]
**_Arrow colour_**

I will increase the colour of the arrow to be a darker shade, and inline with the selected group state. This will be slightly darker than the arrow we have in production currently. See above mock for suggested revised colour: #585858

With respect to meeting the WCAG standards for contrast - there are several areas with the current H client that don't meet the standards, so fixing these will need to be a separate effort, but agreed that the colours of the new groups control and be darkened to provide greater contrast. 

**_Icons in top bar_** don't pass the foreground to background contrast standards:

![icon in top bar](https://user-images.githubusercontent.com/5212631/39472673-bba715ea-4d42-11e8-9d63-b84f162235b4.png)


**_UI text_** in certain places doesn't pass e.g View group activity and invite others. Hopefully the expanded group control will replace this soon!

![view group activity text](https://user-images.githubusercontent.com/5212631/39472680-c564dc98-4d42-11e8-8d5b-929671c9b78e.png)

I'm going to open a separate design spike to look at colour contrast for accessibility standards, and will put together a findings report. #627

**Comment by dawachan** [comment]
**_With regards to screenreader and keyboard-only users:_**

I agree that we should be considering screenreader/keyboard-only users. I'm going to do some research re: best interaction patterns for visually impaired users and get back to you with regards to the suggestions you made. 

My question would be in terms of supporting the prompts,keyboard focus and accept commands is whether this is going to be part of the v1 groups work. It definitely adds to the implementation time so I'm wondering if we are going to prioritise this work now.  Retrospectively, what will we need to do to bring the H client in-line with screenreaders/keyboard only interactions? I'm going to create a separate card for these issues #628  with respect to groups control and wait for them to be prioritised.

**Comment by klemay** [comment]
Regarding when to prioritize keyboard focus / screenreader prompts: I would say this can wait until after our the accessibility review of the current product. This is taking place this month, and I will share back the consultant's findings.

**Comment by ajpeddakotla** [comment]
| Business Viability | User Engagement | Building Community | Level of Effort |
|---|---|---|---|
| 1 | 3 | 1 | 1 |

**Comment by klemay** [comment]
3 separate issues:

- UX affordances to improve in menu
- Annotation count for group
- Anything else to track?

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/product-backlog/issues/828
