### ISSUE TITLE
Spike to investigate Elasticsearch timeouts

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#536]
We still seem to be having frequent Elasticsearch timeouts, as can be seen for example in Grafana:

![screenshot from 2018-03-19 12-14-28](https://user-images.githubusercontent.com/22498/37595073-46805924-2b6f-11e8-9439-fc0ab3350b36.png)

And in Sentry:

![screenshot from 2018-03-19 12-15-23](https://user-images.githubusercontent.com/22498/37595081-50cbb874-2b6f-11e8-82f8-47b1da1f73fa.png)

One problem that these timeouts cause us is that they're a major contribution to us hitting our Sentry rate-limiting quota, harming our ability to understand what errors are happening in production.

They're also likely causing slowness and crashing or broken behaviour for users.

Aim of the spike is to answer these questions:

* How often are Elasticsearch timeouts happening?
* What effect do these timeouts have on users?
* What's causing these timeouts?
* What can we do to fix these timeouts?

If the fix is easy then we might just go ahead and apply it right away.

See also:

* [Previous investigation of this issue](https://github.com/hypothesis/h/issues/4734) (unclear to me what the outcome was)

**Comment by hmstepanek** [comment]
Since we upgraded elastic search and we query more efficiently we are no longer seeing elastic search timeouts on this scale. Every once and a while we do see one occasionally but it's quite rare so I'm going to close this issue.
