### ISSUE TITLE
Spike to do an analysis of our traffic (requests and responses)

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#537]
Outcome of this spike is a short written report on how well we're currently serving the traffic that we're getting, especially during our daily peak traffic. For example:

* How are our response times? Are we fast? How often are we giving unacceptably slow responses?
* How are out error rates? Are we robust? How often are we giving error responses, for what reasons, and how is this affecting users?
* How well is auto scaling working? Does h auto scale up smoothly as traffic increases for the day, without giving users a lot of slowness and errors? Or is auto scaling happening too slowly and giving degraded performance while it scales up?

If problems are found then optionally suggest solutions to them (or make another spike card for investigating solutions).

See also:

* [Spike to investigate Elasticsearch timeouts](https://github.com/hypothesis/product-backlog/issues/536)

**Comment by hmstepanek** [comment]
I'm closing this as I have completed a performance investigation into h and lms and added issues to the performance board based on my findings.
