### ISSUE TITLE
Spike to get on top of our Sentry crash reports

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#538]
I don't think we've been on top of our Sentry crash reports for a while - crash reports are coming in but are being ignored, we don't have a clear idea of how crashy or not we are and whether there's any bugs in need of fixing, we've been hitting Sentry's rate limiting.

This spike is to answer questions such as:

* How many crashes are happening? Are we robust or are we crashy? Particularly in h I think, but in our other projects as well.
* How is this affecting user experience?
* Open issues for any bugs found, so we can get them fixed
* Are we still hitting Sentry rate limiting? (And if so what can we do to stop hitting it?)

Generally I'd like to get on top of our Sentry crash reporting so that we're not hitting rate limits and so that we don't have a lot of unresolved issues in Sentry, and are in a situation where we're keeping on top of Sentry and are noticing and resolving issues as they come in.

See also:

* [Spike to investigate Elasticsearch timeouts](https://github.com/hypothesis/product-backlog/issues/536)
* [Spike to do an analysis of our traffic (requests and responses)](https://github.com/hypothesis/product-backlog/issues/537)

**Comment by lyzadanger** [comment]
We're getting much more on top of this and are down to a limited number of known/open Sentry issues.
