### ISSUE TITLE
Our Business Metrics Grafana dashboard is broken

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#540]
Our Business Metrics Grafana dashboard at <https://mon.hypothes.is/grafana/dashboard/db/business-metrics> is broken - it isn't receiving any data.

This is a dashboard that gives us graphs of the number of annotations created (total, daily, monthly) and of the number of active users.

I'm not sure how long it has been broken for and it kind of looks like no one is using it.

Did we move to getting these business metrics from somewhere else instead (Metabase)? If so, can we just delete this Grafana dashboard?

**Comment by seanh** [comment]
Looks like it's still in use so we'll need to fix it: https://hypothes-is.slack.com/archives/C03QZM0K4/p1521465540000503

**Comment by ajpeddakotla** [comment]
TBD: talk about if this overlaps w/ metabase.

**Comment by ajpeddakotla** [comment]
@seanh just talked about this in our commercial call. Since we use Metabase for our business metrics (annotations created (total, daily, monthly) and of the number of active users), and Metabase queries the database directly, I think we can eliminate the Business Metrics Grafana dashboard.

**Comment by seanh** [comment]
I've backed up and deleted the dashboard
