### ISSUE TITLE
Improve our logging setup

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#544]
Logs are useful for example in diagnosing incidents while and after they're happening.

Our logging set up for our application servers isn't very good. It's just what Elastic Beanstalk provides by default - you can download the log files, but not in a very convenient format. I think we can just upgrade this to a better AWS logging service - [Amazon CloudWatch Logs](https://docs.aws.amazon.com/AmazonCloudWatch/latest/logs/WhatIsCloudWatchLogs.html).

We also have other logs besides ones from the application servers. I believe our static servers log to Papertrail, for example. Our other managed services (RDS, Elasticsearch, CloudAMQP, Mandrill...) all probably have logs of their own too.

But I think the main thing we'd like is better access to our application servers logs.

**Comment by robertknight** [comment]
Work on CloudWatch logs is happening in https://github.com/hypothesis/deployment/pull/29

**Comment by robertknight** [comment]
CloudWatch logs are now enabled for all Python web services, with the initial exception of via. This provides centralized access and searching of current and historical stdout/stderr logs from the Docker container, nginx access and error logs, plus a few other files.

Let's see whether this meets our needs in practice. If not, we can look into other options.
