### ISSUE TITLE
Hypothesis application performance review (New Relic)

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#546]
I think it'd be good to look through New Relic and get an idea of how well our application is currently performing, and whether there are any obvious performance bottlenecks or inefficiencies. Identify any issues and make github issues for them.

See also:

* [Spike to do an analysis of our traffic (requests and responses)](https://github.com/hypothesis/product-backlog/issues/537)
* [Spike to investigate Elasticsearch timeouts](https://github.com/hypothesis/product-backlog/issues/536)

**Comment by hmstepanek** [comment]
Obvious performance bottlenecks: python and using jinja to generate html files.-every single transaction has 75% of it's slowdown in python. Also reducing # of queries to db/es per transaction.

**Comment by hmstepanek** [comment]
I started doing this a couple weeks ago and filed a bunch of issues that are now at the top of the ops backlog. I think part of this is another LF to teach how to use NR to identify these issues. I'm going to add that to the LF channel.
