### ISSUE TITLE
Add organizations

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#549]
- [x] Create an organization table.
- [x] Add the organization model.
- [x] Create organization in group table.
- [x] Add a nullable organization id to the group model.
- [x] Allow logo=None in validate logo. <-This is a bug fix.
- [x] Allow svg to have xmlns in validate logo. <-This is a bug fix.
- [x] Create a default hypothesis organization similar to the `__world__` group only for organizations (in db init and db migration).
- [x] Add organization service.
- [x] Add organization to group service.
- [x] Add list organization service.
- ~~Create CLI command for creating organization.~~
- [x] Migrate all groups to be under that default group and make sure creating a group always adds the group under the default organization if one is not specified. 
- [x] Add organization into admin page.
- [x] Change organization id so it is no longer nullable.
- [x] Add organization to group admin page.
- [x] Migrate certain groups to be under a different organization (such as biopub). <--This will be the original story that started this mess.

**Comment by lyzadanger** [comment]
Done! Woot!
