### ISSUE TITLE
Accessibility improvements for web.hypothes.is (from Nate's website backlog)

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#551]
- [x] Move Bookmarklet out of modal [webhypothesis #20](https://github.com/hypothesis/webhypothesis/issues/20)
- [x] Change font-weight on blog [webhypothesis #19](https://github.com/hypothesis/webhypothesis/issues/19)

**Comment by klemay** [comment]
Solution proposed and approved for [webhypothesis #20](https://github.com/hypothesis/webhypothesis/issues/20)

**Comment by klemay** [comment]
Submitted PR for font-weight: https://github.com/hypothesis/webhypothesis/pull/21

Update: Nate feels changing `font-weight` would mean a significant redesign, so this PR is closed and this web backlog item is on hold.

**Comment by xolotl** [comment]
[Website team agrees on 17 Apr 2018](https://docs.google.com/document/d/1S-MBbjqAWrnlcZtt4yIhL0S6u4UrbB0vhAIwJw7WWkM/edit#heading=h.s8k5wfaqwoef) that @klemay will spend a short time (eg, 1hr) investigating and possibly proposing easy changes to address this issue.
