### ISSUE TITLE
Add command for making an organization

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#554]
Enable creating an organization via bin\hypothesis

**Comment by robertknight** [comment]
I've started work on CRUD views for managing organizations in https://github.com/hypothesis/h/pull/4928. We may decide that we don't need a CLI command any more.

See also https://github.com/hypothesis/product-backlog/issues/522

**Comment by hmstepanek** [comment]
Ok. I already have the code implemented in a branch I just didn’t turn it into a or yet.

**Comment by lyzadanger** [comment]
As of https://github.com/hypothesis/h/pull/4928 we have CRUD in the browser, so I'm going to close this for now (I don't think there is an immediate need for a CLI command).
