### ISSUE TITLE
GDPR - Ask users to opt-in to our privacy policy

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#560]
### Justification

In order to meet new GDPR requirements, we need to provide users with a link to the privacy policy on the sign up form and include a way to actively opt-in to our privacy policy. 

**A/C**

- [ ] The revised sign up form contains an explicit opt-in to privacy policy checkbox - **unchecked by default**.
- [ ] The revised sign up form contains an explicit opt-in to product and research communications checkbox - **checked by default**. covered in #431 
- [ ] Link to privacy and cookies policy in the acceptance language. e.g. "I have read and agree to the privacy and cookies policy."
- [ ] Copy linking to terms of service and community guidelines is appended to the opt-in to privacy policy checkbox string above( note: no tracking of opt-in to terms or community guidelines is needed - purely informational.)
- [ ] Sign up to Hypothesis is prevented if users do not accept the privacy policy and a tooltip is displayed with the text "Acceptance of the privacy policy is required." which points to the checkbox.

### Mock up
![sign up - revised language - final ammended](https://user-images.githubusercontent.com/5212631/39358576-753356be-4a0e-11e8-9bd1-3ebfe5976fe5.png)

**Tooltip when the form is submitted with an incomplete field.**

![screen shot 2018-04-12 at 14 21 12](https://user-images.githubusercontent.com/5212631/38680043-4004acd4-3e5d-11e8-8023-4dc6da6dfbaa.png)

_Notes from @ajpeddakotla_ 

- This doesn't cover users that have already signed in. It only covers users that will be creating new accounts. 
- If users don't agree to our policy, they won't be able to create accounts. 
- We need to make sure everything we're linking to is fully available/accessible on our website.

Note: this card is closely related to the opt-in for marketing permissions signup: https://github.com/hypothesis/product-backlog/issues/431

Implementation issue can be found here: https://github.com/hypothesis/product-backlog/issues/591

**Comment by dawachan** [comment]
Quick question about the Twitter solution outlined above. When I spoke with @segdeha, I understood that an implicit opt-in, e.g. 'by clicking sign up you're opting in' wouldn't be enough for GDPR and that we require users to take an explicit opt-in action. e.g a checkbox. I noticed in the text above it says: "We also need users to actively opt-in to our terms of service/privacy policy." I'll add a checkbox!

**Comment by dawachan** [comment]
![current sign up form](https://user-images.githubusercontent.com/5212631/38311028-fc4c40bc-3815-11e8-94e4-568c35ea22f9.png)

**Comment by dawachan** [comment]
**Proposed Revised Design**

_Consent fields above CTA_

![revised sign up form](https://user-images.githubusercontent.com/5212631/38313602-565439f6-381c-11e8-9c07-dcc1fc5c7dbb.png)

_Consent fields below CTA_

![sign up with acceptance underneath copy](https://user-images.githubusercontent.com/5212631/38368506-63bc6f5c-38dd-11e8-90b6-6504ce5970b7.png)

**Note:** 

Working language for explicit opt-in: "I have read and agree to the terms of service and privacy & cookies notice." This was inspired by a Medium article I read on how to design GDRP compliance consent https://medium.com/@sagarag/how-to-design-gdpr-compliant-consent-b5d6cf28d0c5.

I've also added the opt-in to be contacted by Hypothesis as we currently cannot contact our users without their consent. This could also come in handy re: future changes to the law and needing to keep users informed etc. Suggested language: "We may contact you for marketing, product and research purposes unless you click to opt out." Working language.

Question: Are we required to also serve our users a 'cookies' notice?.

**Comment by dawachan** [comment]
note: Proposed form will have to change, as I'm going to have to solve age content and weave this to the sign up form/flow: https://github.com/hypothesis/product-backlog/issues/561.

If we can at least agree on the explicit consent box copy/positioning and 'By signing up.. copy' that would be great - need final copy/legalese to use.

**Comment by segdeha** [comment]
To confirm, yes, we need users to take an explicit action to opt-in to our PP and ToS. A checkbox like the one @dawariley proposes fits that purpose.

**Comment by rallos** [comment]
I spoke with Andrew this afternoon and I will be researching ways Twitter is using a binding contract rather than a Consent means to gather information.  Let me have until Friday afternoon to get you some information.  But this research shouldn't change what you have created thus far.

**Comment by rallos** [comment]
I did some research on the Opt-In consent under GDPR for marketing by electronic mail.  It looks like we can avoid this by using an exception in the rule that allows us to market to them as long as we (1) attain their email during sign up, (2) provide our own products/services in the marketing, and (3) allow for opt-out (unsubscribe) in our email marketing.  Thus, it's recommended to remove the second empty checkbox  "opt-in" consent for marketing as shown in your UX design, as if we elect to use "opt-in" method, then we would need to track then consent to receive email marking in a separate table and manage it.

**Comment by dawachan** [comment]
hi reem, thanks for the update! it will definitely make the process simpler for users if there is only one checkbox for opt-in. my only concern is that we might need to track opt-in for comms separately because I believe we're intending to allow users the option to opt out or unsubscribe from comms in any emails we send out. only having one field for GDPR might make this tricky.. that said, we could remove the second checkbox and only keep a record of unsubscribed users to look up against if and when they elect to opt out or unsubscribe otherwise we assume everyone that signed up is opt-in by default. 

moving forwards the intention is to contact our existing users and have them opt-in to being contacted for comms purposes, so we might be able to roll this effort into GDPR opt-in, and use the same data model for both new sign ups and existing users. i think it would be worth flagging this with the dev team now, as it also seems like an implementation question (@segdeha - can we run this by the developers) as we don't want to dig ourselves into a hole by adding/removing a checkbox.. not saying this will happen but it's worth thinking through the implications!

@rallos can you advise on obtaining GDPR consent from existing users and what the rules/timelines are around this. thanks!

**Comment by segdeha** [comment]
@xolotl It sounds like an affirmative opt-in for update emails may not be strictly necessary from a GDPR standpoint, but is it something that we need to do to be in good standing with our email provider?

**Comment by dawachan** [comment]
I've revised the form as per feedback in the product sync, left both checkboxes in for now, pending further input and final copy.

![sign up - revised language](https://user-images.githubusercontent.com/5212631/38495366-3ba0c754-3bf1-11e8-881b-c81e25688c3f.png)

**Comment by ajpeddakotla** [comment]
Need to ensure that we: 
1. Change the language in our policy as directed here: https://github.com/hypothesis/product-backlog/issues/561#issuecomment-379343664 by @rallos, so that we don't have to ask for explicit consent from minors. 
2. That the opt-in checkbox blocks the user from creating the account if they do not check it.

**Comment by dawachan** [comment]
I'm updating the description for this card with what the latest specs. Previous background description from @ajpeddakotla below:

### Background
Per GDPR requirements, we need to provide users the link to the privacy policy at the time when they create an account. We also need users to actively opt-in to our terms of service/privacy policy. 

### Issues that need to be addressed: 
- [ ] Design what the UI/UX will look like. Here's an example of what Twitter's sign up screen looks like for reference. 
![twitter sample sign up](https://user-images.githubusercontent.com/7463523/37917207-6c6debc8-30e3-11e8-82c3-7e654cd42009.png)
- [ ] This doesn't cover users that have already signed in. It only covers users that will be creating new accounts. 
- [ ] If users don't agree to our policy, they won't be able to create accounts. 
- [ ] We need to make sure everything we're linking to is fully available/accessible on our website

Note: this card is closely related to the opt-in for marketing permissions signup: https://github.com/hypothesis/product-backlog/issues/431

**Comment by ajpeddakotla** [comment]
Closing this as we've broken this card down into 2 parts: 
#590 and #431

**Comment by dawachan** [comment]
Updated the copy against the second checkbox based on feedback from @dwhly to say: "I agree to receive occasional communication for product and research purposes."

**Comment by dawachan** [comment]
Attached the revised opt-in to comms copy from @dwhly to: #431
