### ISSUE TITLE
Implement encryption-at-rest for Elasticsearch

### ISSUE THREAD

**Issue by segdeha** [hypothesis/product-backlog#562]
This is the [Epic](https://github.com/hypothesis/product-backlog/labels/Epic) card for implementing Elasticsearch encryption-at-rest. We should add a checklist here of all the sub-cards that this breaks down into, but for now they all have the [Upgrade Elasticsearch label](https://github.com/hypothesis/product-backlog/labels/Encrypt%20Elasticsearch).

Implement encryption-at-rest for our Elasticsearch cluster. This requires migrating h to a new Elasticsearch cluster that is running a much newer version of Elasticsearch (must be version 5.1+, but we will probably jump directly to the latest version 6.2) and that has Elasticsearch's encryption-at-rest feature enabled.

 - @seanh 2018-04-24

**Comment by seanh** [comment]
@segdeha Just out of interest, what does the `STORY` prefix at the beginning of an issue title mean?

**Comment by robertknight** [comment]
I changed the label name from "Encrypt Elasticsearch" to "Upgrade Elasticsearch" because really, that is what 99% of the work is about.

**Comment by ajpeddakotla** [comment]
Closing this card as this task has been completed.
