### ISSUE TITLE
GDPR - Logging - Track and Document

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#563]
### Background
Per GDPR requirements, we need to document all the logging we do for our application. 

### Issues to be addressed
- [ ] Analyze and document how we currently log information. (Needs to be completed as part of initial GDPR requirements). 
- [ ] Future work: Reduce the surface area of our logging, particularly where it's not done to cover a vital business need (this will likely be a seperate card, and not part of GDPR requirements). (We can hold off on this for now).

**Comment by robertknight** [comment]
Assigned to me for elaboration/refinement.

**Comment by segdeha** [comment]
To add a little context, the outcome of this work is intended to be that we can describe in our privacy policy what data provide about our users to third parties and for what purpose.

> We share X with Y to do Z.

For example:

> We share information including IP addresses with Google Analytics to improve the quality of our user interface.

**Comment by ajpeddakotla** [comment]
Please enter in your findings in this document: https://docs.google.com/document/d/1m-_H6MDUIO3jM1O9D8a9M0O8rioV9dEqKwLCrb7mg3Q/edit, and not in the github issue.

**Comment by robertknight** [comment]
I have filled in the document above with details about services we use and what data we share with each of them. Please review it and close this issue once you have done so.

**Comment by ajpeddakotla** [comment]
Closing as this is completed.
