### ISSUE TITLE
annotation made on https://thinkprogress.org/electoral-college-trump-top-lawyers-8a8b6e0ca916#.k8oz7vfhg points instead to https://thinkprogress.org/

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#57]
### Steps to reproduce
1. Annotate https://thinkprogress.org/electoral-college-trump-top-lawyers-8a8b6e0ca916#.k8oz7vfhg

### Expected behaviour
The uri: field of the resulting annotation should be that URL 

### Actual behaviour
Instead it is https://thinkprogress.org/

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/client/issues/142
