### ISSUE TITLE
WEBSITE GDPR : Implement Cookies Affirmative Consent Dialogue Box

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#574]
### Background
In order to meet new GDPR regulations and increase transparency with our users with regards to data storage the proposal, a visible cookie banner will be displayed on the home page of http://web.hypothes.is. 

Final design and copy is TBD, below is a proposal featuring explicit acceptance i.e. 'I ACCEPT' button.

![100 width - grey i accept](https://user-images.githubusercontent.com/5212631/39044900-5ff0041c-4489-11e8-899d-a02747ff9776.png)

A/C

- [ ] The homepage of web.hypothes.is features a banner displayed at the bottom of the page.
- [ ] The banner is sticky to the bottom of the browser which will ensure it is above the fold on smaller devices or monitors.
- [ ] Suggested copy: "In order to improve your experience, we are using cookies to track usage.  <Learn more>"
- [ ] <Learn more> links to a plain english description of the cookies policy or the cookies section of the privacy policy. TBD.
- [ ] CTA "I Accept' which onClick dismisses the banner.
- [ ] Acceptance of the notice removes the notice permanently. The banner will persist until the notice is dismissed.

**Comment by robertknight** [comment]
The original article which the Cookies-GDPR.pdf article is a printout of: https://www.itgovernance.eu/blog/en/how-the-gdpr-affects-cookie-policies/

**Comment by dawachan** [comment]
I've audited several sites/apps re: their cookie policies to capture how they message cookie acceptance to their users. All were by 'contract' not explicit consent, apart from the 'snake oil' businesses that specialise in selling 3rd party cookie cutter (literally) solutions and consultancy services. https://docs.google.com/document/d/1DeVK3F3MvrsN-lC8zq_eyUPstOpHiWGhJa9iGrUKyPY/edit?usp=drive_web&ouid=101089125405921231050

**Comment by dwhly** [comment]
I'll just say that if there is any way we can avoid having to force people to dismiss notices about cookies, that would be a gift indeed.  The notion that people who actively manage their privacy can't ever dismiss the notice because the mechanism for registering whether it's been dismissed uses the very technology that they have elected to prevent is one of god's abominations.

**Comment by dawachan** [comment]
Design proposals for contractual and explicit cookie consent below. Will update the description when we reach consensus.

**Contractual Consent** - n.b. suggested text is placeholder

_100% - white_
![100 width - white](https://user-images.githubusercontent.com/5212631/38747865-31eddfde-3f44-11e8-910a-09608d848503.png)

_100% - grey_
![100 width - light grey](https://user-images.githubusercontent.com/5212631/38747874-377fccb4-3f44-11e8-9d46-9cfcdf183081.png)

_100% - dark_
![100 width - dark](https://user-images.githubusercontent.com/5212631/38747878-3be6625e-3f44-11e8-9ebe-ee12939114ec.png)

_50% - white_
![50 width - white](https://user-images.githubusercontent.com/5212631/38747895-47099034-3f44-11e8-8777-82ea84bcaf61.png)

_50% - grey_
![50 width - grey](https://user-images.githubusercontent.com/5212631/38747900-4e63aa04-3f44-11e8-8b9a-8b3094788cf6.png)

_50% - dark_
![50 width - dark](https://user-images.githubusercontent.com/5212631/38747904-51e0f326-3f44-11e8-8a58-b55d63c7b1fb.png)

_30% - white_
![30 width - white](https://user-images.githubusercontent.com/5212631/38747911-55d5572e-3f44-11e8-8566-f3b68d200738.png)

_30% - grey_
![30 width - grey](https://user-images.githubusercontent.com/5212631/38747920-5d78f7c4-3f44-11e8-8a00-628fe08756ab.png)

_30% - dark_
![30 width - dark](https://user-images.githubusercontent.com/5212631/38747924-629d5b96-3f44-11e8-907e-e3fe6804fb03.png)


**Explicit consent** - n.b. suggested text is placeholder, explicit consent mechanism can be ported to one of the above designs and vice versa.

_Toast - white_
![toast - white](https://user-images.githubusercontent.com/5212631/38747930-6825f3ac-3f44-11e8-9fe9-a227e52705e0.png)


_Toast - grey_
![toast - grey](https://user-images.githubusercontent.com/5212631/38747942-6d7c84b0-3f44-11e8-8c4e-7761aadaacf6.png)


_Toast - dark_
![toast - dark](https://user-images.githubusercontent.com/5212631/38747949-7152abaa-3f44-11e8-8407-1682f54d7e3b.png)

**Comment by dawachan** [comment]
_**ARCHIVE of earlier description. Please follow current description for this card above.**_ 

### Background
We need to enable a cookie dialogue box if you we have cookies enabled on the website (before the end user sign-in or register) that capture information about the users used for analytics, advertising, surveys and chat tools. 

### Items to be addressed: 
- [ ] Identify if we have 1st and/or 3rd party cookies enabled. Consent is required before you gather this information from the user and before they create an account (or sign in).

Example designs below: 
![tracking2](https://user-images.githubusercontent.com/7463523/38374503-6bf48ab6-38b9-11e8-9bb8-8a9a899fa094.png)
![tracking 2](https://user-images.githubusercontent.com/7463523/38374506-6da40d82-38b9-11e8-9e53-5fba7896ab4a.png)

More info available here:
[Cookies-GDPR.pdf](https://github.com/hypothesis/product-backlog/files/1880579/Cookies-GDPR.pdf)

**Comment by ajpeddakotla** [comment]
Closing as this is no longer relevant.
