### ISSUE TITLE
Group creator does not get added to group member list in activity page view (restricted groups) 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#578]
### Problem: 

When creating a new group, I added a group creator and three other group members to the restricted group. 
I then went the activity page expecting the see 4 members for the group. I only saw three: 
<img width="234" alt="screen shot 2018-04-09 at 3 08 53 pm" src="https://user-images.githubusercontent.com/7463523/38520639-ecf2ad94-3c08-11e8-91ac-8e38edbdff8d.png">

I then went back and added the group creator as a group member in the admin panel, and `linda_vanasupa` (the group creator) now appears as a group member. 
<img width="1194" alt="screen shot 2018-04-09 at 3 16 29 pm" src="https://user-images.githubusercontent.com/7463523/38520676-0d44820c-3c09-11e8-9354-fd3cbe1b9a31.png">
<img width="231" alt="screen shot 2018-04-09 at 3 09 00 pm" src="https://user-images.githubusercontent.com/7463523/38520680-0fe6ddd4-3c09-11e8-991c-eb59463d08cb.png">

### Expected Behavior
When group creators are added to the group, they are automatically added to the member list. Anyone that is creating a group will have to add the group creator username twice - once as the group creator, and once as a group member. 

As a user creating a group, I expect that the group creator will automatically be added to the group member list. 

*** Note: this is a blocker for the public release of the group creation page.

**Comment by seanh** [comment]
> *** Note: this is a blocker for the public release of the group creation page.

Public release? (This page is intended for internal use only, and is already live on production for internal use.)

> As a user creating a group, I expect that the group creator will automatically be added to the group member list.

To clarify: only Hypothesis admins can create open and restricted groups, not general users. So:

> As a **Hypothesis admin** creating an **open or restricted group**, I expect that the group creator will automatically be added to the group member list so that I don't have to manually add the creator as a member.

**Comment by seanh** [comment]
One thing we should watch out for by the way - if the creator is automatically added as a member, then what if the user _does_ enter the creator twice in the form? Once as the creator and once as a member. Make sure the code doesn't add the user to the member list twice or crash.

**Comment by seanh** [comment]
Might also be interesting to consider whether this admin form should allow the creator to be _removed_ from the member list, when editing an open or restricted group?
