### ISSUE TITLE
Restricted group is not appearing on a publisher site's path, when scoped to origin 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#579]
### Problem/steps to reproduce: 

1. I created a restricted group here: https://hypothes.is/admin/groups/adrYe36E, and scoped it to http://murmurations-journal.org 
2. Murumurations (the journal) wants the group to show up here: http://murmurations-journal.org/index.php/murmurations/$$$call$$$/api/file/file-api/download-file?fileId=64&revision=1&submissionId=19&stageId=3

The group shows up on the murmurations-journal.org site, but not on the specific site requested by the publisher. 

### Expected behavior
Currently scoping only allows for scoping to an origin. So when I scope to a particular origin, I expect to see the open/restricted group show up everywhere on that site.

**Comment by robertknight** [comment]
It looks like this is a problem with our logic for extracting document URIs from PDFs.

1. The groups service calls `store.searchUris()` to get the list of URLs for the main frame and then uses the first `http:` or `https:` URL to fetch groups.
2. The `searchUris` function looks at the `metadata.links` property of each frame.
3. In the dump of app state below taken from [this article link](http://murmurations-journal.org/index.php/murmurations/$$$call$$$/api/file/file-api/download-file?fileId=64&revision=1&submissionId=19&stageId=3) you can see that the second URL in the `link` array is relative (`/index.php/...`), when it should be absolute. This affects both searching for annotations and searching for groups.

<img width="1067" alt="screenshot 2018-04-10 16 44 44" src="https://user-images.githubusercontent.com/2458/38567679-ba20741a-3cde-11e8-9a4d-1224b7936a0f.png">

**Comment by robertknight** [comment]
When the journal generates the URL for the PDF viewer's iframe, they generate a relative URL for the `file` query string parameter. Until we get this fixed, they could work around the issue by passing an absolute URL.

http://murmurations-journal.org/plugins/generic/docCentricWorkflow/pdf.js/viewer/web/viewer.html?file=%2Findex.php%2Fmurmurations%2F%24%24%24call%24%24%24%2Fapi%2Ffile%2Ffile-api%2Fdownload-file%3FfileId%3D64%26revision%3D1%26submissionId%3D19%26stageId%3D3%26docCentricWorkflowComponent%3DviewConversion
