### ISSUE TITLE
Error messages overlap on Sign up form

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#581]
When multiple errors are detected in the sign up form, they are displayed on top of each other making it impossible to read them.

**Steps to reproduce:**

1. Go to: https://hypothes.is/signup
2. Enter a really short username e.g 'd'
3. You will get 2 errors: "Must be 3 characters or more" and "This username is already taken."
4. They are displayed on top of each other.

**Suggested fix:**

Concatenate the error messages e.g. "This username is already taken and must be 3 characters or more."

![screen shot 2018-04-12 at 14 09 20](https://user-images.githubusercontent.com/5212631/38679354-6d8bf182-3e5b-11e8-8e55-a58c96a16f79.png)

**Comment by klemay** [comment]
In this case, "This username is already taken" is not a valid error message, right? We shouldn't have any users with username "d" because we don't allow for it. 

We might also want to rewrite the logic of "This username is already taken" so it only shows up when appropriate.

**Comment by sheetaluk** [comment]
We decided to show just one failing constraint at a time because:
(1) Showing them all can take up too much space
(2) Some of the combinations don't make sense. Eg: This username is already taken and must be 3 characters or more.
