### ISSUE TITLE
Spike: Research how to switch over from ES 1.5 to ES > 5.1

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#588]
Research how to switch over es version with little to no downtime.

**Comment by hmstepanek** [comment]
Possibly using a read only feature flag during switch

**Comment by hmstepanek** [comment]
>  Snapshot And Restore
You can store snapshots of individual indices or an entire cluster in a remote repository like a shared file system, S3, or HDFS. These snapshots are great for backups because they can be restored relatively quickly. However, snapshots can only be restored to versions of Elasticsearch that can read the indices:

>A snapshot of an index created in 5.x can be restored to 6.x.
A snapshot of an index created in 2.x can be restored to 5.x.
A snapshot of an index created in 1.x can be restored to 2.x.
Conversely, snapshots of indices created in 1.x cannot be restored to 5.x or 6.x, and snapshots of indices created in 2.x cannot be restored to 6.x.
https://www.elastic.co/guide/en/elasticsearch/reference/current/modules-snapshots.html

We might consider upgrading to 2, then tackling upgrading from 2 to 5.

**Comment by hmstepanek** [comment]
>To upgrade an Elasticsearch 1.x cluster, you have two options:

> 1) Perform a full cluster restart upgrade to Elasticsearch 2.4.x and reindex or delete the 1.x indices. Then, perform a full cluster restart upgrade to 5.6 and reindex or delete the 2.x indices. Finally, perform a rolling upgrade to 6.x. For more information about upgrading from 1.x to 2.4, see Upgrading Elasticsearch in the Elasticsearch 2.4 Reference. For more information about upgrading from 2.4 to 5.6, see Upgrading Elasticsearch in the Elasticsearch 5.6 Reference.

> 2) Create a new 6.x cluster and reindex from remote to import indices directly from the 1.x cluster.

2 seems like what we want to do but this, as I understand it, requires having 2 es clusters running at once.

**Comment by hmstepanek** [comment]
We are already using index aliasing to point to the old node while the new one is updating, so we will just use the same aliasing in the new cluster as the old one with same indexes etc. 
https://www.elastic.co/guide/en/elasticsearch/guide/current/index-aliases.html

The docs say it is faster to reindex than to pull from a db so we may find that we want to do that instead as it could take days to create the indexes on the new cluster. There are settings in es where you can essentially disable searching from the indexes while you are reindexing etc that will massively speed up re-indexing performance so we will prob want to take advantage of those. https://www.elastic.co/guide/en/elasticsearch/reference/master/tune-for-indexing-speed.html

You can update/re-index incrementally which is something they recommend in the docs as well, this enables us to do a massive re-index then an incremental final re-index (possibly several) to account for any new data that may have been added since we initially re-indexed. I'm still not convinced that a couple annotations might not get lost but we can always result to a read-only tag while we're doing that final re-index if it's really a concern (also this is the technique we are using now and that appears to be working so far). And of course we can double check before the final switch to the new cluster to verify we aren't missing a bunch. I'm also thinking the final switch should happen when we get the least traffic (aka 12:00 am PST).
https://www.elastic.co/guide/en/elasticsearch/guide/current/reindex.html

Our current re-indexing commands/config/etc are here:
https://github.com/hypothesis/h/tree/master/h/search

**Comment by hmstepanek** [comment]
Breaking Changes that will Affect H:
Elasticsearch Reference: 6.2 (current)
Elasticsearch Reference: 6.1
Elasticsearch Reference: 6.0
Elasticsearch Reference: 5.6
Elasticsearch Reference: 5.5
Elasticsearch Reference: 5.4
Elasticsearch Reference: 5.3
Elasticsearch Reference: 5.2
Elasticsearch Reference: 5.1
Elasticsearch Reference: 5.0
Elasticsearch Reference: 2.4
Elasticsearch Reference: 2.3
Elasticsearch Reference: 2.2
Elasticsearch Reference: 2.1
Elasticsearch Reference: 2.0
Elasticsearch Reference: 1.7
Elasticsearch Reference: 1.6-

**Comment by segdeha** [comment]
@hmstepanek Will the migration require spinning up additional instances compared to what we currently use? I.e. we should be aware of whether we need to make another request to increase any limits imposed by AWS on the number of instances in advance. Thanks!

**Comment by hmstepanek** [comment]
- [ ] use https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html to create 6.2 es docker image
- [ ] spike to research breaking changes (reading about it in the docs possibly using the migration plugin)
- [ ] make h use write to both elastic search versions
- [ ] make h only read from one version based on a feature flag
- [ ] improve functional test coverage of search
         - what is our coverage now (click around in the client make sure we cover all those cases)
         - fill in the gaps 
- [ ] make a new cluster in amazon running es 6.2 and use the new reindex scripts
- [ ] make new scripts in h/search for re-indexing and configuring the es 6.2 (rename old functions to _old)
- [ ] come up with production queries to compare with feature flag off vs on
- [ ] have monitoring metric plan in place for the switch
- [ ] es cleanup tasks
- [ ] verify bouncer's query works/have a transition plan
- [ ] make backup of old es cluster before we take it down

**Comment by hmstepanek** [comment]
@segdeha I wouldn't say any more instances but it will require spinning up a whole second es cluster and running those in parallel for a while which won't be cheap.

**Comment by robertknight** [comment]
> The docs say it is faster to reindex than to pull from a db so we may find that we want to do that instead as it could take days to create the indexes on the new cluster. 

Can you clarify what you mean by "reindex" here? The existing commands in h for "reindexing" do build a complete new index from the DB. This takes about two hours at the moment, and the process hasn't been massively optimised AFAIK. I know this because we reindexed the data not long ago to add a new field.

> use https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html to create 6.2 es docker image

Do you mean "use the current ES Docker images from  https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html for local development / CI"? In production we're using Amazon ES and I presume we would continue to do so?

**Comment by hmstepanek** [comment]
I understand your confusion cause reindex is a bit of a vague term. It basically just means creating a new index. You can do that from an existing outdated index or from data in the db. I had a chat with Sean and we currently do it from the db and it takes a couple hours so I think this is a non issue. We can just use that same method without any significant issues with performance. Also yes to your comment about the docker image only being used in dev and yes we will be spinning up a new cluster on amazon with the new es version (not using docker in prod).
