### ISSUE TITLE
LMS Student Users should be automatically provisioned, authenticated

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#593]
### Problem
Currently, students using Canvas have to manually create their own account in Hypothesis in order to complete their assigned annotation homework. This creates a clunky, and less than desirable user experience. The goal of this work is to create as painless of a sign on experience for students as possible. 

### User Story

I am a student who is a user of my institution's Hypothesis-compatible LMS. When I open a course assignment that uses Hypothesis, I want to be able to start working on my annotation homework right away without having to take any action to create an account or log in.

### Acceptance Criteria: 

- [x] The first time a student launches a Hypothesis LMS assignment, a user account is created for them and they are automatically logged in and can start creating annotations.
- [x] Any subsequent time a student launches the _same_ Hypothesis LMS assignment, they are automatically logged in with the user account already created for them.
- [x] Any subsequent time a student launches _another_ Hypothesis LMS assignment within the same course, they are automatically logged in with the user account already created for them.
- [x] Any subsequent time a student launches a Hypothesis assignment for _a different course_ within the same institution, they are automatically logged in with the user account already created for them.

### Additional Info: 
- This card was previously scoped out by Sean, and may contain some useful information for the research/scoping purposes. https://github.com/hypothesis/product-backlog/issues/342

**Comment by seanh** [comment]
@lyzadanger Can we close this now?
