### ISSUE TITLE
LMS Instructor Users should be automatically provisioned, authenticated

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#594]
### Problem: 
The process of creating a Hypothesis course assignment within an LMS is awkward and tedious. At present, teachers must:

1. Establish a Hypothesis account manually.
2. Create a private group for their course if one doesn't already exist.
3. Add every student of the course to the private group. This requires the instructor to obtain email addresses for all course students.
4. (Finally), create the assignment.

This is self-evidently cumbersome. This user story is concerned with #1 above.

### User Story

I am an instructor using an LMS system for my courses. When I create an assignment using Hypothesis in one of my courses, I want an account to be automatically created for me (if one doesn't exist). When I launch (view) any of my Hypothesis course assignments, I want to be automatically logged in so I can start annotating or reviewing annotations immediately.

### Acceptance Criteria: 

- [x] When an instructor creates a Hypothesis assignment in their LMS, an account should be created for them if one does not exist.
- [x] When an instructor launches a Hypothesis assignment in their LMS, it should be verified that they have a Hypothesis account, and one should be created if not. The instructor user should be automatically logged into their account.

### Discussion

Student user accounts are created/authenticated when a student _launches_ a Hypothesis LMS assignment, while an instructor's account needs to be created (if not extant) during assignment-creation time. The reason for this is so that the instructor user may be set as the creator of the private group that gets created for the course.

The existence of an instructor's account is verified whenever a Hypothesis LMS assignment is launched for a few reasons, the most easily-explainable one is that there could be more than one instructor per course and this makes sure they get accounts, too.

### Additional Info: 
This card was previously scoped out by Sean, and may contain some useful information for the research/scoping purposes. #342

**Comment by seanh** [comment]
@lyzadanger Can we close this now?
