### ISSUE TITLE
Make ES 6.2 Docker file/image for Developer Env

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#598]
Use https://www.elastic.co/guide/en/elasticsearch/reference/current/docker.html to create a 6.2 es docker image. We currently use the https://www.elastic.co/guide/en/elasticsearch/plugins/current/analysis-icu.html so we'll need to make sure that exists in the new image. Below are the command that were used to build the image that we use now:
```
ADD file:e5a3d20748c5d3dd5fa11542dfa4ef8b72a0bb78ce09f6dae30eff5d045c67aa in /
CMD ["/bin/bash"]
RUN apt-get update && apt-get install -y --no-install-recommends   ca-certificates   curl   wget  && rm -rf /var/lib/apt/lists/*
RUN apt-get update && apt-get install -y unzip && rm -rf /var/lib/apt/lists/*
RUN echo 'deb http://httpredir.debian.org/debian jessie-backports main' > /etc/apt/sources.list.d/jessie-backports.list
ENV LANG=C.UTF-8
{   echo '#!/bin/bash';   echo 'set -e';   echo;   echo 'dirname "$(dirname "$(readlink -f "$(which javac || which java)")")"';  } > /usr/local/bin/docker-java-home  && chmod +x /usr/local/bin/docker-java-home
ENV JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64/jre
ENV JAVA_VERSION=8u72
ENV JAVA_DEBIAN_VERSION=8u72-b15-1~bpo8+1
ENV CA_CERTIFICATES_JAVA_VERSION=20140324
RUN set -x  && apt-get update  && apt-get install -y   openjdk-8-jre-headless="$JAVA_DEBIAN_VERSION"   ca-certificates-java="$CA_CERTIFICATES_JAVA_VERSION"  && rm -rf /var/lib/apt/lists/*  && [ "$JAVA_HOME" = "$(docker-java-home)" ]
RUN /var/lib/dpkg/info/ca-certificates-java.postinst configure
RUN gpg --keyserver ha.pool.sks-keyservers.net --recv-keys <key>
arch="$(dpkg --print-architecture)"  && set -x  && curl -o /usr/local/bin/gosu -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch"  && curl -o /usr/local/bin/gosu.asc -fSL "https://github.com/tianon/gosu/releases/download/1.3/gosu-$arch.asc"  && gpg --verify /usr/local/bin/gosu.asc  && rm /usr/local/bin/gosu.asc  && chmod +x /usr/local/bin/gosu
RUN apt-key adv --keyserver ha.pool.sks-keyservers.net --recv-keys <key>
ENV ELASTICSEARCH_MAJOR=1.6
ENV ELASTICSEARCH_VERSION=1.6.2
ENV ELASTICSEARCH_REPO_BASE=http://packages.elasticsearch.org/elasticsearch/1.6/debian
RUN echo "deb $ELASTICSEARCH_REPO_BASE stable main" > /etc/apt/sources.list.d/elasticsearch.list
RUN set -x  && apt-get update  && apt-get install -y --no-install-recommends elasticsearch=$ELASTICSEARCH_VERSION  && rm -rf /var/lib/apt/lists/*
ENV PATH=/usr/share/elasticsearch/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
RUN set -ex  && for path in   /usr/share/elasticsearch/data   /usr/share/elasticsearch/logs   /usr/share/elasticsearch/config   /usr/share/elasticsearch/config/scripts  ; do   mkdir -p "$path";   chown -R elasticsearch:elasticsearch "$path";  done
COPY dir:33dd1c3731770e94d42b26287546da3520074086c8b1bdc784ed8089c8c8cc9b in /usr/share/elasticsearch/config
VOLUME [/usr/share/elasticsearch/data]
COPY file:d25889029dd34582c7a8998596b9d115f83a2c1d054e446733c2cbabdc4fe8bd in /
ENTRYPOINT &{["/docker-entrypoint.sh"]}
EXPOSE 9200/tcp 9300/tcp
CMD ["elasticsearch"]
RUN plugin install elasticsearch/elasticsearch-analysis-icu/2.6.0
```
Disclaimer: the above was abstracted from the image and not the Dockerfile that built the image so it's not perfect. Also this was based on a linux base image as oposed to a pre-fab es image that we will be using for 6.2 so we prob don't need to do nearly as many commands as we did before. We should pretty much just need to build our indexes/es cluster on top of the es base image and that's it.

Note our reindexing/configuration scripts are in h/search and reindexing/remapping can be done via the hypothesis search command.

**Comment by seanh** [comment]
@hmstepanek Lets get a dockerized Elasticsearch 6.2 actually integrated into the h dev env, so that if I followed the [dev install docs](http://h.readthedocs.io/en/latest/developing/install/) I would end up with _two_ Elasticsearch's running locally, 1.5 and 6.2, even if h doesn't use the 6.2 one (either to read or to write) yet.

**Comment by seanh** [comment]
By the way, can we turn on Elasticsearch encryption-at-rest in dev envs too? Just for maximum [dev/prod parity](https://12factor.net/dev-prod-parity)

**Comment by hmstepanek** [comment]
Hmmm... I’m not sure about turning on encryption since the encryption is provided via amazon and not es but I can look into it briefly. I got an image is es6.2 working yesterday. I’m not sure where to put the dockerfile-do you think h/search is an appropriate place?

**Comment by hmstepanek** [comment]
It looks like if we want to encrypt the data in the docker image we can use the x-pack plugin. Some of the official es images come with it but it is licensed software (aka it costs $) so I would advise against it. I don't think the encryption is something that requires us to do any mods to h so I think this shouldn't strictly be necessary. If it turns out that I'm wrong about that we can always revisit this.

**Comment by lyzadanger** [comment]
Are there other tasks left on this issue?
