### ISSUE TITLE
Spike to research breaking changes between ES1.5->ES6.2

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#599]
**Outcome of this spike:** A list of breaking changes from Elasticsearch 1.5 to 6.2 that we should be aware of because they might affect h or bouncer (e.g. they are breaking changes to Elasticsearch features that h or bouncer use).

Research by means of reading about it in the docs and possibly using the migration plugin (see below) breaking changes relevant to us upgrading from 1.5 to 6.2. Note this card is intended to be strictly research and not implementation. Once we have the docker image done (separate card) we will be able to test locally and identify any gaps. Breaking changes we are interested in include both configuration/reindexing/mapping options as well as search query changes.

See also:

* [Elasticsearch migration plugin](https://github.com/elastic/elasticsearch-migration) that will tell us our health of moving from 1.5 to 2 and 2 to 5
* Our reindexing/configuration scripts in [h/search](https://github.com/hypothesis/h/tree/master/h/search)
* Reindexing/remapping can be done via [the `./bin/hypothesis search` command](https://github.com/hypothesis/h/blob/master/h/cli/commands/search.py)
* [List of breaking changes in the Es docs here](https://www.elastic.co/guide/en/elasticsearch/reference/index.html). Click on the version then breaking changes.

## Breaking Changes that will Affect H:

* Elasticsearch Reference: 6.2 
  - None
* Elasticsearch Reference: 6.1
  - None
* Elasticsearch Reference: 6.0
  - Open/Close index API don’t return an error by default when a provided wildcard expression doesn’t match any closed/open index. This is something to watch out for in the tests.
  - The index parameter in the delete index API no longer accepts alias names. This is relevant when we re-index the cluster and try to delete the old index- we need to make sure we refer to the index via it's actual name and not it's aliased name. (At least that's my interpretation here.) 
   - Analyze api needs to define parameters in request body.
   - There is a list of deprecated query changes-most of them have already been mentioned/will have no effect: https://www.elastic.co/guide/en/elasticsearch/reference/6.0/breaking_60_search_changes.html#_changes_to_queries.
* Elasticsearch Reference: 5.6
  - None
* Elasticsearch Reference: 5.5
   - Elasticsearch attempts to set the kernel parameter vm.max_map_count during installation. - Nothing we need to do here just thought this was somewhat relevant to a discussion Sean and I had on the docker container PR.
* Elasticsearch Reference: 5.4
  - Default settings are no longer supported (aka how we currently set the host and index instead of always using the env vars).
    ```
    settings.setdefault('es.host', 'http://localhost:9200')
    settings.setdefault('es.index', 'hypothesis')
    ```
   - To check if an index exists via a get request you must add: ?allow_no_indices=false as a non existant index with no longer 404 without it. The only place with might be relevant is in monitoring tools and startup of make dev.
* Elasticsearch Reference: 5.3
  - Changes to logging config path and no longer permits lenient boolean values (AFAIK these won't impact us).
* Elasticsearch Reference: 5.2
  - None
* Elasticsearch Reference: 5.1
  - This isn't unique to this particular version but here's a good list of things to check for in our index alias names: https://www.elastic.co/guide/en/elasticsearch/reference/5.1/breaking-changes-5.1.html#_alias_names_are_validated_against_most_of_the_rules_for_index_names.
* Elasticsearch Reference: 5.0
  - The fields parameter has been replaced by stored_fields
  - See the deprecated queries section many of these are very relevant to our current usage: https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_search_changes.html#_deprecated_queries_removed. 
  - type: string has been deprecated in favor of text (see https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html)
  - index now accepts bool values instead of analyzed/not_analyzed/no.
  - There have been max field nesting limits imposed (not that I think we are close to hitting these but just something to be aware of) https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_field_mapping_limits.
  - The _parent field is no longer indexed. See https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_field_mapping_limits.
  - When taking a snapshot, closing or deleting an index will now cause the close/delete to fail instead of the snapshot.
  - There have been changes made to the stats response which may affect grafana monitoring; https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_mapping_changes.html#_field_mapping_limits, https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_rest_api_changes.html#_removed_literal_mem_literal_section_from_literal__cluster_stats_literal_response & https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_rest_api_changes.html#_revised_node_roles_aggregate_returned_by_literal__cluster_stats_literal.
  - suggest stats was added to search stats.
  - Indexing a document with op_type=create without specifying an ID is not supported.
  - There are retries on search failures now.
  - The get API will issue a refresh if the requested document has been changed since the last refresh but the change hasn’t been refreshed yet. This can have performance implications if read modify updates happen a lot. See https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_document_api_changes.html#_get_api.
  - bulk and update api's use _source instead of fields.
  - Plugins that define custom settings must register all of their settings during plugin loading using the SettingsModule#registerSettings(Setting) method.
  - Not that I think we have these but something to check for; Elasticsearch will now fail any request that contains unrecognized query string parameters.
  - Previously, JSON documents were allowed with unquoted field names, which isn’t strictly JSON and broke some Elasticsearch clients. This is no longer allowed (there is a temporary workaround but it is deprecated in 6.0).
  - The filters and char_filters parameters have been renamed filter and char_filter. The token_filters parameter has been removed. Use filter instead.
  - The JVM now dies on fatal errors-I assume amazon will take care of respawning the instance for us but we should check to make sure. See https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_packaging.html#_dying_on_fatal_errors.
  - AWS plugins have split into 2. (https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_plugins.html#_cloud_aws_plugin_changes)
  - 

    > Only a subset of index files were open with mmap on Elasticsearch 2.x. As of Elasticsearch 5.0, all index files will be open with mmap on 64-bit systems. While this may increase the amount of virtual memory used by Elasticsearch, there is nothing to worry about since this is only address space consumption and the actual memory usage of Elasticsearch will stay similar to what it was in 2.x. See http://blog.thetaphi.de/2012/07/use-lucenes-mmapdirectory-on-64bit.html for more information.
  - There may be some performance hits when aggregating over numeric fields; https://www.elastic.co/guide/en/elasticsearch/reference/5.0/breaking_50_aggregations_changes.html#_significant_terms_on_numeric_fields. 
  - size: 0 is not valid for terms. It looks like in the code we currently allow it to be 0<= so we'll need to change that to 0<.
* Elasticsearch Reference: 2.4
  - None
* Elasticsearch Reference: 2.3
  - > Indexing a document with 100 nested fields actually indexes 101 documents as each nested document is indexed as a separate document. To safeguard against ill-defined mappings the number of nested fields that can be defined per index has been limited to 50. This default limit can be changed with the index setting index.mapping.nested_fields.limit. Note that the limit is only checked when new indices are created or mappings are updated. It will thus only affect existing pre-2.3 indices if their mapping is changed.
* Elasticsearch Reference: 2.2
  - None
* Elasticsearch Reference: 2.1
  - detect_noop option from false to true. This means that Elasticsearch will ignore updates that don’t change source unless you explicitly set "detect_noop": false. 
  - queue_size in nodes info/stats was sometimes shown as "1k" instead of 1000. Now it always shows as 1000-this may impact our monitoring tools like grafana.
* Elasticsearch Reference: 2.0
  - delete_by_query has been moved to a plugin. It looks like the only place we currently use it is in tests/functional/conftest.py. If we need to keep it we will need to install it in the docker image and amazon's cluster as a plugin.
  - facets have been deprecated in favor of aggregations: it looks like we don't actually use these in es and have our own version sitting outside of es in python. I wonder if we could speed up performance by actually using these as part of es? We do use aggs already so maybe we are ok here.
  - Fields with the same name, in the same index, in different types, must have the same mapping. I'm not sure what this means yet...
  - All metadata (aka _* fields) are returned by default. The only thing this would probably affect is the tests.
  - If using custom routing, routing is required when deleting things from multiple shards as it no longer broadcasts. I don't think this will impact us as I don't see that we have custom routing in place but I'm not 100% sure.
  - The document body can no longer be wrapped in a type (I don't see that we are doing this in the code but again not 100% sure.
  - There have been significant changes to filtering (too complex to delve into here). See https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_query_dsl_changes.html for details. The example is super helpful and explains most of it but needless to say our filter configs will need changes.
  - There may be some caching/performance impacts of the filter changes: 

     > The terms filter lookup mechanism no longer caches the values of the document containing the terms. It relies on the filesystem cache instead. If the lookup index is not too large, it is recommended to replicate it to all nodes by setting index.auto_expand_replicas: 0-all in order to remove the network overhead as well.

  - Time zone date format changes: the value +1:00 must now be written as +01:00.
  - It's unclear whether this is going to be a problem (from the limited cases I've looked at it looks like we reference them in the correct way)but...a field can no longer be referenced using its short name. Instead, the full path to the field is required. So if we have nested fields like below we have to refer to source as target.source.
     ```
     'properties': {
        'target': {
            'properties': {
                'source': {    # 1
                    'type': 'string',
                    'index_analyzer': 'uri',
                    'search_analyzer': 'uri',
                    'copy_to': ['uri'],
                },
           },
      },
     }
     ```
  - The default value for the require_field_match option has changed from false to true, meaning that the highlighters will, by default, only take the fields that were queried into account.
  - The mapping for the parent type can be added at the same time as the mapping for the child type, but cannot be added before the child type. This is relevant to replies. I'm not sure I fully understand what this means but here's a link to the docs: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_parent_child_changes.html.
  - There are changes to the analyze api: https://www.elastic.co/guide/en/elasticsearch/reference/2.0/breaking_20_index_api_changes.html.

* Elasticsearch Reference: 1.7:
  - None
* Elasticsearch Reference: 1.6:
  - None

**Comment by hmstepanek** [comment]
This may come in useful: https://github.com/hypothesis/h/pull/4923.

**Comment by seanh** [comment]
@hmstepanek I've edited the issue description for clarity

**Comment by hmstepanek** [comment]
Potentially relevant work done here: https://github.com/hypothesis/h/pull/4923.

**Comment by robertknight** [comment]
I ran the v1 => v2 Elasticsearch migration plugin that @hmstepanek linked to in the original issue on our local cluster. Note that I have a bunch of indexes, so the error reports are duplicated for each. Generated report:

[elasticsearch migration checker v1.19.pdf](https://github.com/hypothesis/product-backlog/files/1987681/elasticsearch.migration.checker.v1.19.pdf)

**Comment by ajpeddakotla** [comment]
Closing as spike has been completed, and work has started.
