### ISSUE TITLE
enable cors for api writes as well as reads

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#60]
### Problem you are trying to address with this feature

I'm working with Mike Caulfield on a project that uses H to help analyze and critique fake news. As part of it, we needed a tool that annotates a page with the result of a Facebook API query. 

Example:

![image](https://cloud.githubusercontent.com/assets/46509/20677091/ce92b956-b546-11e6-9998-f784a76d11fd.png)

Here a bookmarklet has queried FB for this InfoWars page, found 50K FB shares for it, and created a page note with that info.

The problem: We evidently support CORS for API reads but not writes. So to make this work I had to create a CORS proxy and relay the bookmarklet's POST request through that.

### Your solution

Do we intend to disallow CORS for H API writes? If not it would be great to allow it and simplify the creation of tools like this one.

**Comment by judell** [comment]
Is it just a matter of adding @cors_json_view decorators?

For example, this seems to work:

![image](https://user-images.githubusercontent.com/46509/27361967-bea8864e-55df-11e7-9097-854874a096b9.png)

/cc @nickstenning, @chdorner, @dthompson

**Comment by robertknight** [comment]
CORS headers are set on all API requests, including those for writing to the API. One issue that may have caused confusion is that until today, CORS headers were _not_ set if the request _failed_ with a 4xx or 5xx error.

```sh
# The main request
$> curl -i -X POST 'https://hypothes.is/api/annotations' -H 'Authorization: Bearer $DEVELOPER_TOKEN' -d'{"uri": "https://robertknight.me.uk", "text": "API test"}'
HTTP/2 200 
... other headers elided ...
access-control-allow-origin: *


{ ... successful JSON response ...  }

# The CORS preflight request which the browser sends first
$> curl -i -X OPTIONS -H 'Access-Control-Request-Method: POST' -H 'Origin: https://www.google.com' 'https://hypothes.is/api/annotations'
HTTP/2 200 
... other headers elided ...
access-control-allow-origin: https://www.google.com
access-control-allow-methods: HEAD, GET, PATCH, PUT, POST, OPTIONS, DELETE
access-control-max-age: 86400
access-control-allow-headers: Authorization, Content-Type, X-Client-Id
```

**Comment by judell** [comment]
> CORS headers were not set if the request failed with a 4xx or 5xx error.

That was indeed the confusion. Thanks for resolving this!
