### ISSUE TITLE
Make h write everything to two Elasticsearch clusters at once

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#600]
Change h so that it always writes all updates to **two** Elasticsearch clusters:

1. The existing Elasticsearch 1.5 cluster
2. A new Elasticsearch 6.2 cluster with encryption-at-rest enabled

All updates should always be written to both Elasticsearch clusters, so that they're always in sync.

Note that h will continue to read everything from the old 1.5 cluster only. It will only write to, and never read from, the new 6.2 cluster. [Getting it to read from 6.2 as well is a separate card](https://github.com/hypothesis/product-backlog/issues/601).

Both production and development environments should be writing to two cluster simultaneously.

If this is implemented before we have the new 6.2 cluster available in production, then we can put the code behind a **feature flag** so we can still ship it.

Edit: This is dependent on:

* https://github.com/hypothesis/product-backlog/issues/631
* https://github.com/hypothesis/product-backlog/issues/632

**Comment by seanh** [comment]
@hmstepanek I rewrote the description on this one

**Comment by robertknight** [comment]
This is implemented on master, but I think we ought to actually get this working in production before we close it.

**Comment by robertknight** [comment]
The `index_es6` flag is now enabled in production. If there are any issues I'll file separate tickets.
