### ISSUE TITLE
Use Elasticsearch 6 cluster to handle searches

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#601]
Once indexing into ES 6 is complete and the search code is ready to run against ES 6, implement a feature flag that causes searches to use the new ES cluster.

- [x] Add a feature flag to h that, when enabled, causes all Elasticsearch reads to read from the ES cluster
- [x] Make our existing search tests run with and without this feature flag
- [x] Enable this feature flag in production for staff
- [x] Test that it works as expected for staff in production
- [x] Enable this feature flag for all users

**Comment by seanh** [comment]
@hmstepanek I edited the title and desc on this one

**Comment by seanh** [comment]
We may want to do this in separate steps? For example, one feature flag to send all badge requests to the new cluster? Another for normal search API requests? Just so we can move the traffic over to the new cluster bit by bit. But it might be easier just to switch it all at once.

**Comment by robertknight** [comment]
I personally don't think there is enough risk to justify needing to implement a bunch of separate feature flags for different features that use search.

This feature flag is added as part of https://github.com/hypothesis/h/pull/5176

**Comment by robertknight** [comment]
This is now done. See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1532621303000295.
