### ISSUE TITLE
What is our current integrated test coverage of search?

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#602]
**Outcome of this spike**: A list of all the search-related test cases that we don't currently have integrated test coverage of.

We want to be able to change h to use Elasticsearch 6.2 instead of 1.5, and we'd like to be able to upgrade to 6.2 and run the h tests and, if the tests all pass, have some confidence that everything works correctly with 6.2.

This requires us to have some integrated tests of our search features, where by "integrated" I mean that they call the real Elasticsearch not a mock one.

What is our integrated test coverage of our search features now?

Click around in the client and on activity pages. What different kinds of search requests get sent? Is there a test for each?

See also:

* [Improve integrated test coverage of search features](https://github.com/hypothesis/product-backlog/issues/603) (to be done after this spike)

**Comment by seanh** [comment]
@hmstepanek I've clarified the issue description

**Comment by hmstepanek** [comment]
These may come in useful: hypothesis/h#4923 & https://github.com/hypothesis/h/pull/4941.
