### ISSUE TITLE
Improve integrated test coverage of search features

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#603]
Based on the gaps in test coverage that were identified in https://github.com/hypothesis/product-backlog/issues/602 implement integrated tests that cover those gaps.

**Comment by hmstepanek** [comment]
These may come in useful: hypothesis/h#4923 & hypothesis/h#4941.

**Comment by seanh** [comment]
Closing this as I've broken it up into multiple cards: <https://github.com/hypothesis/product-backlog/issues/640>, <https://github.com/hypothesis/product-backlog/issues/639>, <https://github.com/hypothesis/product-backlog/issues/641>, <https://github.com/hypothesis/product-backlog/issues/642>
