### ISSUE TITLE
Create Elasticsearch 6.2 cluster in Amazon

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#604]
Set up a new Amazon-managed Elasticsearch cluster

- [x] Configure security group for ES cluster (so we can use the recently added [VPC support](https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-vpc.html)) and give h access to it (PR pending, but has been run locally: https://github.com/hypothesis/playbook/pull/170)
- [x] Create an Amazon KMS key for use with the new cluster (see https://github.com/hypothesis/product-backlog/issues/617) (_Cluster created using the default key for Amazon ES_)
- [x] Create a new Amazon Elasticsearch cluster running ES 6.2 with the "Encryption at rest" option enabled. The cluster should have the same capacity as the existing one, although we may want to use fewer nodes initially to reduce costs until we are ready to go live (_Created as [hypothesis-es6](https://us-west-1.console.aws.amazon.com/es/home?region=us-west-1#domain:resource=hypothesis-es6;action=dashboard)_)
- [x] Provide the {h, bouncer}-{prod, qa} EB app environments with the location of the new ES domain via an `ELASTICSEARCH_URL` configuration variable

**Comment by robertknight** [comment]
This is now done and {h, bouncer}-{prod, qa} apps have access to the new cluster via the `ELASTICSEARCH_URL` env var.
