### ISSUE TITLE
Implement reindexing command for ES 6

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#605]
Implement a CLI command for indexing all existing annotations into the new Elasticsearch cluster. There should be a mechanism (eg. different command name or flag) to reindex into the new cluster without affecting the existing ES 1.x cluster.

**Comment by hmstepanek** [comment]
This may be useful: https://github.com/hypothesis/h/pull/4923.

**Comment by seanh** [comment]
To be clear, I think this refers to getting the `./bin/hypothesis search` commands working with Elasticsearch 6.2?

Since we're going to be running both 1.5 and 6.2 simultaneously, at least for a time, I wonder if the `./bin/hypothesis search` commands will need a command-line option (or something) for selecting whether to work on the old or new Elasticsearch cluster?

**Comment by hmstepanek** [comment]
I think we should change the previous commands to <command>old and let the old commands become the new commands for es6.2 and run both es versions at the same time as we will need that for the other cards.

**Comment by lyzadanger** [comment]
I believe that, since the CLI `search` module bootstraps the application, we may be able to use the same feature flags here as in the app code, so there may not be much work to do in `h.cli.commands.search` assuming the underlying indexing API remains constant.

**Comment by lyzadanger** [comment]
I'm fairly certain this is a subset of #600 — so I'm going to close if that's OK.

**Comment by hmstepanek** [comment]
@lyzadanger I’m confused why this was closed as writing indexing scripts/configuring the cluster and writing to two different es clusters are very different things in my mind. Maybe you discussed something yesterday that makes these two things the same?

**Comment by hmstepanek** [comment]
According to the little research I’ve done in the changes from our existing version to 5.0 there are changes in the indexing code particularly in the filters which would require changes to the search scripts.
