### ISSUE TITLE
How will the Elasticsearch 6.2 migration affect bouncer? Make a migration plan for bouncer

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#609]
Bouncer communicates with Elasticsearch directly. We should make sure it is no longer reliant on the Elasticsearch 1 cluster, either by making it communicate with the new cluster or by making it no longer query Elasticsearch directly.

**Comment by robertknight** [comment]
Closed by https://github.com/hypothesis/bouncer/pull/135
