### ISSUE TITLE
Move production h/LTI RDS DB to encrypted storage

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#614]
(_Edited by @robertknight on 2018-05-14_)

Encrypt our production Postgres DB by using the backup-encrypt-restore process described at https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/Overview.Encryption.html#Overview.Encryption.Enabling. This process will make the production h/LTI apps unavailable for about an hour, though we should advertise a longer timescale to users in case we run into issues.

In more detail, the steps involved are:

1. Put the existing h and LTI apps into maintenance mode [1]
2. Create a snapshot of the existing hop-prod-db RDS instance (~1 minute)
3. Create an encrypted copy of the snapshot using the chosen encryption key (~15 minutes)
4. Restore the encrypted copy of the snapshot into a new RDS instance, sharing the same subnets, security groups and other settings as the existing instance. (~20 minutes)
5. Update the configuration for the h-qa, h-prod, lti-qa and lti-prod EB environments to use the new RDS instance
6. Relaunch the h-qa, h-prod, lti-qa and lti-prod instances
7. Disable maintenance mode for the h/LTI apps

[1] "Maintenance mode" being some kind of unavailable status which is clearly indicated to visitors to the h website / Chrome extension / Via.

Once everything is up and working on the new instance, we can remove the old RDS instance. This is tracked separately in https://github.com/hypothesis/product-backlog/issues/619

If we run into any problems snapshotting, encrypting or restoring the snapshot to a new instance, we can re-launch the h/LTI apps with their configuration unchanged and they will continue to use the old RDS instance.

----

- [x] Existing DB snapshotted, encrypted using the chosen key and restored to a new instance
- [x] New instance has same security groups, subnets and other settings as existing instance
- [x] New instance has same automated daily snapshotting settings as existing instance (time, retention period)
- [x] h and LTI prod/QA instances configured to use the new RDS instance

**Comment by robertknight** [comment]
I went through this procedure yesterday for our current RDS instance to get an idea of how long it takes:

1. Snapshotting the existing RDS instance took 1-2 minutes
2. Creating an encrypted copy of the snapshot took ~15 minutes
3. Creating a new RDS instance from the encrypted snapshot, using the same settings as the existing RDS instance (eg. enabling multi-AZ deployment), took ~20 minutes

That puts a lower bound of ~40 minutes to do the data migration.
