### ISSUE TITLE
Add the ability to read from either the old or the new db in h

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#616]
Add the ability to read from either the not encrypted or the new encrypted db in h.

**Comment by robertknight** [comment]
As explained in https://github.com/hypothesis/product-backlog/issues/615#issuecomment-386275116 I don't think we should try to support reading from two different databases at once in the app. Instead we can just change the configuration to point from the unencrypted to the encrypted RDS instance.

**Comment by robertknight** [comment]
I'm closing this card for now because, unless I hear objections, I'm going to assume we'll do what we outlined in my comment above which does not involve code changes to h.
