### ISSUE TITLE
Decide which KMS keys to use for Elasticsearch and Postgres

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#617]
Make an encryption key/keys for db and es. These can either be custom or generated through amazon. Amazon uses AWS KMS (https://docs.aws.amazon.com/kms/latest/developerguide/overview.html) to manage it's keys. From the docs:

> You can manage keys used for Amazon RDS encrypted instances using the AWS Key Management Service (AWS KMS) in the IAM console. If you want full control over a key, then you must create a customer-managed key. You cannot delete, revoke, or rotate default keys provisioned by AWS KMS.

> You can view audit logs of every action taken with a customer-managed key by using AWS CloudTrail.

> Important

> If you disable the key for an encrypted DB instance, you cannot read from or write to that DB instance. When Amazon RDS encounters a DB instance encrypted by a key that Amazon RDS doesn't have access to, Amazon RDS puts the DB instance into a terminal state. In this state, the DB instance is no longer available and the current state of the database can't be recovered. To restore the DB instance, you must re-enable access to the encryption key for Amazon RDS, and then restore the DB instance from a backup.

**Comment by robertknight** [comment]
KMS provides a default key for each Amazon service that you use it with. We could simply stick with using that key. As the documentation that Hannah linked to above notes, that limits of the things that we can do with the key. I'm not certain whether any of those limitations are really going to matter yet.

**Comment by robertknight** [comment]
For now I've just used the KMS default key for the ES 6.2 cluster.

**Comment by seanh** [comment]
@robertknight I wonder if we can move this to completed / close this?

**Comment by robertknight** [comment]
I would like to do a little more research on this to check that I'm not missing anything important here. I want to be sure that using the default key is an appropriate choice for us at the moment. It appears that [changing the key](https://aws.amazon.com/premiumsupport/knowledge-center/update-encryption-key-rds/) is a relatively laborious operation that involves re-creating the RDS instance / ES cluster.

**Comment by robertknight** [comment]
Related resource - Amazon's advice on how to use KMS: https://d1.awsstatic.com/whitepapers/aws-kms-best-practices.pdf . See pages 8-9 for a discussion of the difference between AWS-managed keys and customer-managed keys.

**Comment by robertknight** [comment]
I can't see a strong reason for us needing the additional control that comes with customer-manged keys in KMS at present. On that basis I'm going to recommend that we stick with AWS-managed keys (aka. "the box-ticking option" according to one KMS presentation I saw from Amazon) until we have a clear reason to do otherwise.
