### ISSUE TITLE
Delete the old DB and the backups

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#619]
Remove the old RDS instance and the unencrypted logical backups

- [x] Old RDS instance removed
- [x] Snapshots of old RDS instance removed, except for the final manual snapshot that has been encrypted and used to launch the new RDS instance
- [x] Unencrypted logical RDS backups removed from S3 or transferred to encrypted storage

**Comment by robertknight** [comment]
The old DB instance has deleted. Old backups in S3 / RDS will gradually expire over the next 30 days. We can expedite this if necessary.
