### ISSUE TITLE
Find out what needs to be encrypted at rest for GDPR

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#622]
Spike to investigate what needs to be encrypted at rest for GDPR.

We received [a card titled "implement encryption at-rest"](https://github.com/hypothesis/product-backlog/issues/559) but it doesn't yet specify _what_ needs to be encrypted at rest. It looks like we've already decided that Elasticsearch and PostgreSQL need to be encrypted at rest. But is there anything else?

Outcome of this spike: a list of all the things that we need to encrypt at rest.

The list so far:

- [ ] Elasticsearch: https://github.com/hypothesis/product-backlog/issues/562
- [ ] PostgreSQL: https://github.com/hypothesis/product-backlog/issues/621

**Comment by seanh** [comment]
Assigning this to @robertknight who may even already know the answer. Worth pinging @segdeha too.

**Comment by segdeha** [comment]
From my perspective, let's focus on Es + RDS for 25 May. Those are the biggies (and possibly the only places where we need to do this work). We can investigate any nooks and crannies after that date.

**Comment by seanh** [comment]
Ok. I wonder if we can just close this issue then?
