### ISSUE TITLE
Block YouTube and other problem sites from Via

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#626]
We had an incident last week in which VIa started having serious problems:

* All app server CPUs pegged at 100%
* Auto scaling not happening
* Unable to deploy due to new app servers failing EB's health check
* Via responding very slowly, or not at all

The problem appeared to be caused by someone watching YouTube through Via. This guess is based on nothing more than we saw a lot of youtube.com in the access logs, and video sites are known to cause high CPU usage on Via.

We blocked `https://hypothes.is/https://youtube.com/*` using a page redirect in CloudFlare, and Via recovered soon after.

This was just a temporary solution - we probably don't want to use CloudFlare to protect Via from YouTube in this way long term. Apart from anything else, we have only a limited number of page redirects in CloudFlare.

We should implement a better way to block YouTube and other problem sites from Via:

* Block them in Via's nginx config?
* Block them in the Via Python code itself?
* Configurable blocklist via an env var? Or just hard-coded?

I think the desired user experience should be:

1. User visits https://via.hypothes.is/
2. User pastes in a blocked URL
3. Instead of proxying the page, https://via.hypothes.is/ reloads again with an error message along the lines of "Sorry, you can't annotate youtube.com" and the text field empty for pasting in another URL

**Comment by seanh** [comment]
Initial list of sites to block (please add more):

* YouTube
* Vimeo

**Comment by judell** [comment]
> This was just a temporary solution

But a most helpful one, thank you for it.

**Comment by robertknight** [comment]
To be clear, the problem is not the YouTube _website_ itself but the fact that we are proxying large video files through Via. If there is a way that we can avoid proxying just that content, that would be better.
