### ISSUE TITLE
Design Spike: Perform Colour Contrast and Accessibility Audit of H Client

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#627]
### Background ###

Several issues exist with the current H client with respect to colour contrast ratios between foreground and background not meeting current WCAG standards. A couple of these are highlighted with reference to the redesign of the Groups control menu: https://github.com/hypothesis/product-backlog/issues/532.

It is suggested that a complete audit for colour contrast and accessibility be performed against the H client to find out which areas need to be fixed.

### Examples of items not currently meeting WCAG standards ###

**_Icons in top bar_** don't pass the foreground to background contrast standards:

![icon in top bar](https://user-images.githubusercontent.com/5212631/39472673-bba715ea-4d42-11e8-9d63-b84f162235b4.png)

**_UI text_** in certain places doesn't pass e.g View group activity and invite others:

![view group activity text](https://user-images.githubusercontent.com/5212631/39472680-c564dc98-4d42-11e8-8d5b-929671c9b78e.png)

**Comment by ajpeddakotla** [comment]
Closing this as we'll have more information when the accessibility audit has been completed.
