### ISSUE TITLE
Optimising the Group Control for screen readers and keyboard inputs controls

### ISSUE THREAD

**Issue by dawachan** [hypothesis/product-backlog#628]
### Background ###

As part of a wider effort to address Accessibility for visually impaired users - this card looks at what we need to do in order to improve the accessibility of the revised groups control and expanded menu options #532.

### Issues that need to be solved ### 
(copied from #532 @klemay)

There are also some considerations that are specific to screenreader / keyboard-only users:

- How will this arrow + dropdown affect the tab order of the groups control? I.e., will a screenreader user be forced to listen to the "View group," "Invite," "Edit," etc for each and every group they see in their drop down? Or can they focus on the arrow and have the screenreader say something like "expand for group options", with the option to skip?
- Do you have preference for what that screenreader prompt should say? I think "Drop-down: group options. Press enter to expand" would be my first instinct.
- Will this arrow be able to take keyboard focus + accept keyboard commands?

**Comment by ajpeddakotla** [comment]
closing this in favor of #753
