### ISSUE TITLE
Make `h` app able to initialize/configure the index of newer ES version

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#632]
This is dependent on https://github.com/hypothesis/product-backlog/issues/631

Once a connection can be established in the `h` app to the newer ES instance, the instance’s index needs to be configured—the “search needs to be initialized.”

This is handled in `h.search.config.init`

## Background and Notes

The initialization functionality needs to be made compatible with the new version of ES while also still supporting (for now) the legacy version.

In your local development environment, `init` is run every time you start up your env using `make dev` as part of the `h.cli.commands.init` step.

In deployed environments, `init` is run manually by shelling in and executing it (via the CLI, I _think?_)

Initialization current accomplishes two main things:

* Making sure the “analysis-icu” plugin is installed on the ES instance.
* Configuring the ES index—primarily, this involves defining the `annotation` type

A large part of this work is reworking the `annotation` “type” such that it is compatible with newer ES.

See https://github.com/hypothesis/h/pull/4923 for some possible starting points on that.

**Comment by seanh** [comment]
Closing in favour of https://github.com/hypothesis/product-backlog/issues/648
