### ISSUE TITLE
Install `elasticsearch1` alongside `elasticsearch` on `h` so that we can use two versions of `elasticsearch` simultaneously

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#633]
As I read the docs on `elasticsearch`, our python library for Elasticsearch, I am seeing a need for us to be able to use two versions of the package at the same time. Their docs read in part:

> The library is compatible with all Elasticsearch versions since 0.90.x but you have to use a matching major version

To support this, they release separate, numbered packages for legacy versions.

Let's go ahead and:

* install `elasticsearch1`, which _should be_ a drop-in replacement for `elasticsearch` at the version we're using it
* replace `elasticsearch` dependencies in the app with `elasticsearch1`
* upgrade `elasticsearch` to latest so it's available for development against the new ES

I spiked on this yesterday and ran into some issues with some poorly-mocked tests, but you might not run into that depending on how you approach the dependency replacement. Fixing bad tests is always good, though!

**Comment by robertknight** [comment]
@hmstepanek has implemented the elasticsearch v1 => elasticsearch1 migration and added the newer elasticsearch v6 to our dependencies, so I'm going to close this.
