### ISSUE TITLE
Sharing Restricted and Open groups via URL so they will show up on any page

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#635]
### Problem we're trying to solve: 
Publishers, communities, and other users want to be able to share restricted and open groups with others, so that they can see the annotations that have been made in those groups. 

We currently have an implementation of publisher and restricted groups where they can only appear on a page if they are scoped to a page. This restriction is necessary to declare groups as "authoritative" or the page, and show up as the first group users see when they launch H. 

We need to move to model that allows restricted and open groups to show up on any page, but only if someone has a link to that group, or if they are a member of that group (or both). 

While this won't address any of the questions we need to answer around discoverability, it will allow us to relive the pain point of the current restriction so we can have unscoped open and restricted groups. 

### User Story
As a member of a group, I want to see that group available to me on all web pages—not just those that match my group’s scope—so that I am able to annotate within that group anywhere on the web.

### Acceptance Criteria
- [ ] Hypothesis team members should be able to create restricted and open groups that have scopes so that those groups can be "authoritative" over those domains. 
- [ ] Hypothesis team members should be able to create restricted and open groups that do not have scopes - groups that are unscoped - so that those groups can appear anywhere on the web, for members of those groups. 
- [ ] Hypothesis team members should be able to create restricted and open groups that have scopes, but are still able to appear anywhere on the web. That is, the scoping doesn't restrict groups from appearing on other websites for group members, and for users who have links to view annotations made within that group on other, nonscoped sites. 
- [ ] This should work on a group by group basis. All current restricted and open groups shouldn't be affected by these changes, unless group owners explicitly request such group behavior.

**Comment by sheetaluk** [comment]
Problem:
QDR wants the ability to annotate across different webpages but within the same group. They want this group to be sharable with anybody, without having to ask them to join this group. They also want to restrict write access to just group members.

What they seem to be describing is what we are calling restricted groups minus the scoping requirement.

We have 3 parts to this problem:
(1) generate sharable links to a group, both restricted and private
(2) show annotations in the client for a given restricted or private group.
(3) control membership of these new unscoped restricted groups. First phase will be done manually through H support.

Implementation: 

h:
Remove the scope requirement for restricted groups.
We have to make sure that unstopped restricted groups do not appear in the group list of non-members in the client or in their activity pages.

bouncer:
In bouncer, add group’s pubid to the query string(see `bouncer/views.py def goto_url`) to show annotations for that particular group in the via_url and the extension_url url strings.
Possibly validate the existence of a group with a given pubid like we do with annotations?

client:
Read the group’s pubid in the url to see for which group we have to fetch annotations(see `sidebar/components/sidebar-content.js def loadAnnotations`).

Even though we only want to do this for restricted groups, it is possible that the url contains the pubid of a private group.
In this case, we have to see if the user is signed in AND the user belongs to the group, focus that group and load annotations for that group.
If the user is signed in BUT is not a member of the group, prompt them to join the group.
If the user is not signed in, prompt them to sign in.

Questions:
Which group will we focus on while loading annotations for the a group?
What will the UI to generate the bouncer link look like? QDR mentioned they were happy creating links manually, but if we want this feature to be used by other H users, that might not be enough.

See: https://docs.google.com/document/d/19Ev7TPWOhfYh2ePC9utejXxWwpY4P7vwemybqJB_D6Y/edit?usp=sharing

**Comment by lyzadanger** [comment]
> Hypothesis team members should be able to create restricted and open groups that do not have scopes - groups that are unscoped - so that those groups can appear anywhere on the web, for members of those groups.

Open groups do not have members, so this is not possible as written.

**Comment by lyzadanger** [comment]
> Hypothesis team members should be able to create restricted and open groups that have scopes so that those groups can be "authoritative" over those domains.

Can you help me understand how this is different from what is currently possible?

**Comment by lyzadanger** [comment]
> Hypothesis team members should be able to create restricted and open groups that have scopes, but are still able to appear anywhere on the web. That is, the scoping doesn't restrict groups from appearing on other websites for group members

The above sounds like the same thing as 

> Hypothesis team members should be able to create restricted and open groups that do not have scopes - groups that are unscoped - so that those groups can appear anywhere on the web, for members of those groups.

Can you help me understand the difference?

**Comment by lyzadanger** [comment]
> This should work on a group by group basis. All current restricted and open groups shouldn't be affected by these changes, unless group owners explicitly request such group behavior.

Cool. This captures what @klemay brought up and sounds like a reasonable approach.

**Comment by klemay** [comment]
> > Hypothesis team members should be able to create restricted and open groups that have scopes so that those groups can be "authoritative" over those domains.
> 
> Can you help me understand how this is different from what is currently possible?

I think this is stated as a requirement to reiterate that current functionality shouldn't go away (so it's not different from what's currently possible)

**Comment by klemay** [comment]
Hah, Tried to cancel a comment I was typing and accidentally closed the issue. I am SO sorry about that. Moving it back to Near Term on the roadmap

**Comment by ajpeddakotla** [comment]
Closing in favor of the epic work described here: https://github.com/hypothesis/product-backlog/issues/866
