### ISSUE TITLE
Integrated tests for existing search indexing code

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#640]
Write integrated tests for the `h.search.index::index()` function and the code that it calls (includes at least features implemented in [h/search/config.py](https://github.com/hypothesis/h/blob/master/h/search/config.py), in `AnnotationSearchIndexPresenter` and `DocumentSearchIndexPresenter` as well as the `index()` function itself).

These tests have already been begun https://github.com/hypothesis/h/blob/master/tests/h/search/index_test.py

**Comment by robertknight** [comment]
This is now done
