### ISSUE TITLE
Add required ELASTICSEARCH_URL config setting

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#646]
Add a new Elasticsearch URL config setting. This should be named:

* `ELASTICSEARCH_URL` when used an environment variable
* `es.url` when used in `conf/*.ini` files and in `request.registry.settings` (e.g. `request.registry.settings["es.url"]`)

This card is just for adding the config setting and making it required (h should crash on startup if the setting is missing), but nothing will actually be using the setting yet.

**Note**: We're **not** going to touch the existing `ELASTICSEARCH_HOST` / `es.host` setting. Lets just leave that setting untouched and then when we no longer support Elasticsearch 1 we'll just delete it.

## Done when

- [x] The URL for the new Elasticsearch 6.2 config setting can be configured using a `ELASTICSEARCH_URL` environment variable or an `es.url` setting in the `ini` file.

- [x] If no Elasticsearch URL is present then h crashes on startup, with a helpful error message that this URL needs to be set

- [x] The Elasticsearch URL defaults to http://localhost:9201 in development environments. This should be done by putting `es.url: http://localhost:9201` in `conf/development-app.ini` and `conf/development-websocket.ini`.

- [x] There is no default Elasticsearch URL in production environments. In production the `ELASTICSEARCH_URL` env var must be set in the environment or h will crash on startup.

- [x] `ELASTICSEARCH_URL` has been set to an appropriate value in our QA and production environments

## See also

* h (specifically, the code in [`config.py`](https://github.com/hypothesis/h/blob/master/h/config.py)) doesn't yet have the concept of a required config setting. This should be added. The old lti app, which has very similar config code to h, [does have required settings](https://github.com/hypothesis/lti/blob/0cf85fdfff4e4fa92d03a1ee5d2aaea430f9cdfb/lti/config/settings.py#L20-L25)

* Some Slack discussion of this setting, starting [here](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1525341625000218)

* [Config in the Twelve-Factor App](https://12factor.net/config)

## Implementation notes

* Config settings are currently defined in `h/config.py` but the code (`EnvSetting`, `SettingError`, etc) comes from `h/settings.py`. It would be nice to gather all config settings code together in a single `h/config` **directory**. See how [this was done in the lti app](https://github.com/hypothesis/lti/tree/master/lti/config).

* All config settings and their default values, whether they're required or not, etc should be defined in one place in the code. Currently that place is `config.py`. If we refactor along the lines of the lti app it would be `config/__init__.py`. Either way, some config settings and default values are currently defined in other places in the code, e.g. [in search](https://github.com/hypothesis/h/blob/ca306257f65df43fb8161681c185d4d475f0d2bc/h/search/__init__.py#L18-L19). These should be moved into one place.

* There are three places where values for config settings can be set in h: 1: Default values can be hard-coded in the Python code. 2: Default values can go in the `conf/*.ini` files. 3: Per-instance config setting values can go in environment variables. See [this comment about how config settings should work in h](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1525343855000385?thread_ts=1525342830.000169&cid=C1MA4E9B9):

  > - Config setting has sensible default value across all deploys (dev and prod) = hardcoded default in `h/config.py`
  > 
  > - Config setting has sensible default in dev envs only = default in `conf/development-app.ini`. For some settings it may be necessary to add the default in `conf/development-websocket.ini` as well.
  > 
  > - Config setting has sensible default in prod deploys = default in `conf/app.ini` (and if necessary also in `conf/websocket.ini`)
  > 
  > - So a config setting can have a single default value (hard-coded in `h/config.py`) or it can have different default values for production and development environments or a default for dev envs but no default for production envs etc (in these cases put the defaults in the `conf/*.ini` files). And of course a config setting with no defaults at all is also possible.

  Also some comments about how our config settings work (under **Details**) [in the playbook docs](https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md#the-app-must-read-all-config-settings-from-environment-variables)

* The default value for the old `ELASTICSEARCH_HOST` config setting seems to be duplicated in multiple places. It's [set in `h/search/__init__.py`](https://github.com/hypothesis/h/blob/ca306257f65df43fb8161681c185d4d475f0d2bc/h/search/__init__.py#L18), it's [in `conf/development-app.ini`](https://github.com/hypothesis/h/blob/ca306257f65df43fb8161681c185d4d475f0d2bc/conf/development-app.ini#L7), and it looks like it's also in `Makefile` (at least the port is) and `docker-compose.yml`. Don't copy this. The default setting should be in one place only.

* The code in `settings.py` and `config.py` currently doesn't have the concept of a default value either. This was also [done in the lti app](https://github.com/hypothesis/lti/blob/0cf85fdfff4e4fa92d03a1ee5d2aaea430f9cdfb/lti/config/settings.py#L14) so could be copied from there.

* `elasticsearch.url` would be a better name for the config setting in `*.ini` files and in `request.registry.settings` (rather than `es.url`), given that its environment variable is `ELASTICSEARCH_URL`. But there are already multiple other config settings using the `es.` prefix like this, and we'd have to change them all.

**Comment by seanh** [comment]
I've added a [separate card for config code refactoring](https://github.com/hypothesis/product-backlog/issues/647) that could be done before this card.

**Comment by hmstepanek** [comment]
I'm confused about the need to add a default in the .ini files and then make a required env var setting in the h/config.py. Don't those contradict each other? If we make it required you'll see a warning when running make dev. It's possible I'm miss-understanding; is the intention to not default it in the app.ini and make it required for prod env's but not for dev env's? I guess that makes sense but I'm not a huge fan of seeing warnings in dev either. It seems like you would simply want it to override the setting via the env var when it's present, otherwise use the default in the .ini file in which case the env var is not required (I believe this is the current behavior). Perhaps certain env vars may be required in all envs (dev/qa/prod) in which case specifying them as so makes sense but I don't think the es.url is one of those settings.

**Comment by hmstepanek** [comment]
This also makes me wonder whether we should do something similar with the es settings for the client and put them in the .ini files and config.py files instead of defaulting them in client.py. Also just an FYI, you can inherit settings from one .ini to another so that's also an option rather than duplicating them.

**Comment by seanh** [comment]
> I'm confused about the need to add a default in the .ini files and then make a required env var setting in the h/config.py. Don't those contradict each other?

I think those would contradict each other yes. But my intention was that the production ini would _not_ contain any default value. (The development ini files would contain a default, though.)

> the intention to not default it in the app.ini and make it required for prod env's but not for dev env's?

The intention was to make it a required config setting that has a default value in dev envs (so dev envs will just work, you will not see any warnings) but no default value in production envs. It's required in both dev and production envs, but the difference is that it has a default value in dev envs (so you don't actually have to set the env var in dev, because the defaults from the ini files will be used) but no default in prod (so in prod you do have to set the env var). So in dev envs it will just work, but in production envs it will crash on startup if no env var is set.

My reasoning is:

* `es.url` is definitely required. The app can't work without it. So whenever it's not set (no env var and nothing in ini file), whatever type of environment this is (dev or prod), h should refuse to start up.

* There's no sensible default value for `es.url` in production envs. For example in our production env `es.url` is some long internal AWS URL. In Elsevier's env it will be something else. I would rather have h refuse to start up, and inform the user that they need to set an `ELASTICSEARCH_URL` env var, rather than silently use a default value like `localhost:9201` and then crash when it tries to connect to that (because in a production env, most likely there isn't an Es on `localhost:9201`).

* There _is_ a sensible default value for `es.url` in dev envs. It's always going to be `localhost:9201` in dev envs. So for dev envs we may as well save devs the trouble and just put a default value in the `ini` files. Of course if someone has a dev setup that requires a different URL they can set that by setting an `ELASTICSEARCH_URL` env var which will override the ini file.

Does that make sense?

**Comment by seanh** [comment]
I think there may be some confusion about **has a default value** vs **is a required setting**. I think these are two orthogonal settings. All 8 possible combinations are valid!

| Has a default  | Is required |
| -------------- | ----------- |
| Yes            | Yes         |
| Yes            | No          |
| No             | Yes         |
| No             | No          |

For example lets say that `es.url` is both required and has a default in dev envs. So you don't actually have to set an `ELASTICSEARCH_URL` environment variable in a dev env, because it will just use the default from the `ini` file. But if you, say, edited your `conf/development-app.ini` file and deleted `us.url` from it, _then_ h would crash on startup in a dev env (if no `ELASTICSEARCH_URL` was set). Or if you were in a production env, where `app.ini` doesn't contain any `es.url` to begin with, that would crash too if no `ELASTICSEARCH_URL` was set.

**Comment by hmstepanek** [comment]
Ok yes that makes sense. Thanks!
