### ISSUE TITLE
Refactor h config code

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#647]
Refactor h's config code to work more like [the config code in the old lti app](https://github.com/hypothesis/lti/tree/master/lti/config):

* All config and settings-related code together in one directory
* Any default values for config settings are defined in the same place where the config setting is defined
* It's possible to define required config settings and h crashes on startup with a helpful error message if one of these is missing

## Steps

Each one of these steps could be its own pull request, some of them could be multiple pull requests:

- [ ] Move `h/config.py` to `h/config/__init__.py` and move `h/settings.py` to `h/config/settings.py`.
- [x] Add a `required=False` keyword argument to `EnvSetting`. Change any existing required settings should use this.
- [x] Add a `default=None` keyword argument to `EnvSetting`. Change any existing settings that have default values that can be hardcoded in Python should use this.
- [ ] Move any config settings or default values that're being defined elsewhere in the code into `h/config/__init__.py`. For example [these search settings](https://github.com/hypothesis/h/blob/ca306257f65df43fb8161681c185d4d475f0d2bc/h/search/__init__.py#L18-L19).

## Implementation notes

* There are three places where values for config settings can be set in h: 1: Default values can be hard-coded in the Python code. 2: Default values can go in the `conf/*.ini` files. 3: Per-instance config setting values can go in environment variables. See [this comment about how config settings should work in h](https://hypothes-is.slack.com/archives/C1MA4E9B9/p1525343855000385?thread_ts=1525342830.000169&cid=C1MA4E9B9):

  > - Config setting has sensible default value across all deploys (dev and prod) = hardcoded default in `h/config.py`
  > 
  > - Config setting has sensible default in dev envs only = default in `conf/development-app.ini`. For some settings it may be necessary to add the default in `conf/development-websocket.ini` as well.
  > 
  > - Config setting has sensible default in prod deploys = default in `conf/app.ini` (and if necessary also in `conf/websocket.ini`)
  > 
  > - So a config setting can have a single default value (hard-coded in `h/config.py`) or it can have different default values for production and development environments or a default for dev envs but no default for production envs etc (in these cases put the defaults in the `conf/*.ini` files). And of course a config setting with no defaults at all is also possible.

  Also some comments about how our config settings work (under **Details**) [in the playbook docs](https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md#the-app-must-read-all-config-settings-from-environment-variables)

**Comment by robertknight** [comment]
We've done all the work we are going to do on this for now. Specifically we did provide a way to mark env vars as mandatory and provide defaults for them. We didn't do the other tasks. If others think this is still worthwhile I think we should make that a separate issue.
