### ISSUE TITLE
Implement IP masking for Google Analytics

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#653]
As indicated by Nate in our [GDPR logging doc](https://docs.google.com/document/d/1m-_H6MDUIO3jM1O9D8a9M0O8rioV9dEqKwLCrb7mg3Q/edit), if H. anonymizes IP addresses collected by GA, then H's use of GA will not include any PII and thus will not require active user opt in.

Info on masking IP addresses here: https://support.google.com/analytics/answer/2905384?hl=en

- [x] Apply changes to GA instances used by web.hypothes.is (@xolotl)
- [x] Apply changes to GA for app
- [x] Explore how to make h app compliant for anonymous viewers

**Comment by klemay** [comment]
For non-website GA instances:
- How many instances of GA do we have aside from the website (i.e., one each for sidebar and app? are they both in the same instance?)
- Do we use gtag.js or ga.js (that will determine what the code snippet looks like)
- Is it easier on the team for me to point someone toward the code snippet, or to get access to GA and implement myself?

@xolotl perhaps after you implement for website, you could let me know what the process was like (i.e., is it really as simple as C&P-ing a bit of code or did you have to create addtl variables / rewrite anything)?

**Comment by xolotl** [comment]
@klemay @segdeha long story short, I've done this on the H. website, but it looks like we don't need to do this for the H. application/client/etc because:
* H users opt in to H's new privacy policy on account creation.
* GA is not the only service that collects IPs in the H. application (eg, New Relic).
* The new H. privacy policy makes it clear that the H. application employs various tracking services (eg, GA, New Relic, yada yada).

The reason we need to do it on the website is so we do not set tracking cookies for website visitors, who have not necessarily opted in to anything. If we don't track personal info on the website, then we don't have to have an annoying popup cookie opt in notice and mechanism not to set cookies until opt in. The website changes are [outlined in the issue for that project](https://github.com/hypothesis/webhypothesis/issues/41).

Let's continue the convo here if needed. When we are resolved, this issue can be closed.

**Comment by dwhly** [comment]
It's the use of the app embedding GA (or New Relic) when used by those who have *not* logged in and therefore have not agreed to our privacy policy that we should consider. Including on our own website, blog etc.

**Comment by xolotl** [comment]
Sorry, yes, @dwhly makes a good point. On pages where the Hypothesis sidebar loads on the H. website, an additional GA cookie is set (by GA service related to UA-26026798-5, which is named "Client" in GA). The cookie set by the website's GA (UA-26026798-8) is already configured to deidentify IPs. I don't see any evidence of New Relic or other services setting cookies, so deidentifying IPs in the Client GA should ensure that all GA cookies for anonymous website users do not track personal information.

**Comment by xolotl** [comment]
IIUC, we are looking at a few "environments" where anonymous users interact with H and we are attempting to ensure there are no cookies set that track personal information so we don't have to deploy cookie notices and opt in mechanisms.

1. The H. website (web.hypothes.is)
1. The H client/sidebar deployed in the H. website
1. Activity pages/etc that can be browsed anonymously (eg, https://hypothes.is/users/nateangell)
1. Proxys/redirections like via and bouncer.

For 1 (website), the steps taken to remove New Relic and deidentify GA address the goal (with the outstanding issue of cookies set by embedded media in both the website and annotations to be discussed/solved elsewhere).

For 2 (client), the goal can be addressed if the same steps are taken to deidentify GA (UA-26026798-5). No New Relic or other cookies appear to be set by the client for anonymous users.

For 3 (activity pages), the goal would need to be addressed by deidentifying GA (UA-26026798-1), and figuring out if the "XSRF-TOKEN" (New Relic?) and "session" cookie values track personal information (eg, IP addresses) and figuring out ways to either disable them for anonymous users, or deidentify them. I do not have the right knowledge to take on this task.

For 4 (proxies/redirects):  I do not have the right knowledge even to adequately explore/describe the issues.

**Comment by xolotl** [comment]
client GA IPs anonymized via https://github.com/hypothesis/client/pull/736

**Comment by xolotl** [comment]
activity pages/search GA anonymized via https://github.com/hypothesis/h/pull/5047

**Comment by xolotl** [comment]
Decisions made about this set of tasks in the GDPR slack channel: https://hypothes-is.slack.com/archives/C9CKK4UBU/p1527197341000451

**Comment by klemay** [comment]
Nate, thanks so much for your work on this while I was out. Closing this issue.
