### ISSUE TITLE
Support searching by tag with Es 6

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#665]
* Fill out [`TestTagsMatcher`](https://github.com/hypothesis/h/blob/8571df6891bd406fd11bede70c0b05aa8d0eb1a9/tests/h/search/query_test.py#L108-L114)
* Make the tests run against both the Es 1 and the Es 6 versions of our search code
* Make the tests pass against Es 6

**Comment by robertknight** [comment]
Superseded by https://github.com/hypothesis/product-backlog/issues/601. We are now using the same code, with one exception, for handling searches against ES 1 and ES 6. Therefore we don't really need an issue for each field to be aggregated or searched by.
