### ISSUE TITLE
Support searching for replies with Es 6

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#666]
Support searching for replies with Es 6: the `separate_replies` argument and the `reply_ids` in the returned search result should work the same as in Es 1.

* Fill out [`TestRepliesMatcher`](https://github.com/hypothesis/h/blob/8571df6891bd406fd11bede70c0b05aa8d0eb1a9/tests/h/search/query_test.py#L117-L125)
* Make both the `TestRepliesMatcher` and the [`TestSearch` and `TestSearchWithSeparateReplies`](https://github.com/hypothesis/h/blob/master/tests/h/search/core_test.py) tests run against both the Es 1 and the Es 6 versions of our search code
* Make the tests pass

**Comment by robertknight** [comment]
Superseded by https://github.com/hypothesis/product-backlog/issues/601. We are now using the same code, with one exception, for handling searches against ES 1 and ES 6. Therefore we don't really need an issue for each field to be aggregated or searched by.
