### ISSUE TITLE
Only show publisher groups above "Public" when on pages within their scope

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#691]
### Problem you are trying to address with this feature

Currently, if you are a member, scoped groups show at the top of your group list wherever you are.  

### Your solution

Only show groups above others like the H "Public" group if you're on a page they're scoped to.

**Comment by ajpeddakotla** [comment]
| Business Viability | User Engagement | Building Community | Level of Effort |
|---|---|---|---|
| 2 | 2 | 2 | 3 |

**Comment by klemay** [comment]
I created a restricted group scoped to https://www.katelynlemay.com and I am the sole member. The group is in the Hypothesis organization. It only shows in my groups control on the scope origin. I moved it to a different organization and saw no change in this behavior. Is this happening just for 3rd party groups, or am I missing something?

**Comment by klemay** [comment]
No longer relevant - I wasn't able to reproduce, and we've since made improvements to the way publisher groups are displayed
