### ISSUE TITLE
Add "User Agent" to objects created using the API

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#696]
### Problem you are trying to address with this feature

Right now annotations, groups and (shortly?) users are able to be created / provisioned using the API.  However, Hypothesis has little to no visibility to the programs / processes that are creating these things.  As we expand the utility of our API, we will have an increasingly larger number of external applications making use of it.  But right now we cannot characterize that ecosystem, and we don't know when new apps or services show up.

### Your solution

If we include a User Agent string (required? optional?) for each of these three objects we provide a path for applications to self-report.  While not a guarantee (as we all know) this is a voluntary bit of information which we could gather statistics on and use to better understand our ecosystem.

It might also potentially be useful internally.  For instance if we know that an annotation was created using version XXX of our chrome extension vs version YYY etc. etc.

**Comment by judell** [comment]
Where in our current monitoring/logging systems can one find stats on API calls? If that info is unavailable, or inconvenient to get,  one could learn a lot from (a sample of) raw http access logs. I'd be curious to see such logs for the h backend, for via, and for bouncer.

**Comment by segdeha** [comment]
I don't believe we're tracking everything at a fine-grained level at the moment, but New Relic would probably be the place to collect this information, if we aren't already. Do you agree, @hmstepanek?

**Comment by hmstepanek** [comment]
Yes. You could add a metric in for that and have NR track it.

**Comment by judell** [comment]
> I don't believe we're tracking everything at a fine-grained level at the moment

Do we not have webserver access logs?

**Comment by hmstepanek** [comment]
I’m not sure-if we do I think they’d be on aws so you could check there.

**Comment by judell** [comment]
I can't, actually, no access, that's why I'm asking.

**Comment by robertknight** [comment]
> Right now annotations, groups and (shortly?) users are able to be created / provisioned using the API. However, Hypothesis has little to no visibility to the programs / processes that are creating these things. As we expand the utility of our API, we will have an increasingly larger number of external applications making use of it. But right now we cannot characterize that ecosystem, and we don't know when new apps or services show up.

API clients identify themselves via the OAuth client ID when they acquire an access token. The proper way to track usage by different clients would be to record somewhere annotation creation by client etc. I suggest we revisit this when we have a more concrete idea of the report etc. that we want to generate.
