### ISSUE TITLE
Change cursor on hover over a highlight

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#703]
### Problem you are trying to address with this feature

People have noted that when you're hovering over a highlight the cursor currently doesn't change to indicate that it's clickable.  It should.

### Your solution

Change to a pointing cursor vs a selecting cursor.

**Comment by dwhly** [comment]
Is this possibly a bug / regression?  Can't recall.

**Comment by ajpeddakotla** [comment]
Not a bug/regression IMO/from my historical understanding. Putting this in the product backlog.
