### ISSUE TITLE
Bucket bar numbers should open sidebar when clicked.

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#704]
### Steps to reproduce
1. Click on bucket bar number

### Expected behaviour
Sidebar should open, scoped to the annotations that are indicated by the number.

### Actual behaviour
Nothing happens

### Additional details
This is a regression.  Used to work this way.

**Comment by klemay** [comment]
Including a gif to help explain - clicking on the numbers in the sidebar will scroll the page to the annotation/highlight, but it will not open the sidebar:

![screencast-web hypothes is-2018 07 17-11-32-08](https://user-images.githubusercontent.com/12087705/42828041-ce57e318-89b5-11e8-8298-c0422d9f0a4c.gif)

(I tried this on [one of our blog posts](https://web.hypothes.is/blog/gdpr/))

**Comment by ajpeddakotla** [comment]
Given that we've had another issue that's come up that's higher priority, we're going to put this in the backlog and review prioritization again during the next sprint planning meeting.

**Comment by dwhly** [comment]
@robertknight Can you verify that this is fixed?  It's still failing for me.

**Comment by robertknight** [comment]
Hi @dwhly - The issue was fixed in the embedded client but I forgot to release the browser extension. I'll take care of that now.

**Comment by robertknight** [comment]
This is now done.
