### ISSUE TITLE
Hide or otherwise "Handle" email-related setting(s) for users with no email address

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#706]
On the `h` account settings page, the "Email me when someone replies to one of my annotations" setting makes no sense for users without emails.

Note that users without email addresses—third-party users only—should not be able to access this page, but we should still clean up after recent changes by hiding or otherwise handling this setting for folks with no email.

**Comment by sheetaluk** [comment]
![image](https://user-images.githubusercontent.com/502186/42824865-bf2604ee-89ae-11e8-9fed-cb7663f6abfe.png)
