### ISSUE TITLE
EPIC: Badge API improvements

### ISSUE THREAD

**Issue by segdeha** [hypothesis/product-backlog#717]
Some work has been done to improve this endpoint already (https://github.com/hypothesis/h/pull/5113), but there is more that could be done to make the expensive part of this call cheaper, such as a bloom filter.

**Comment by ajpeddakotla** [comment]
Note badge endpoint issue summary outlined here: https://docs.google.com/document/d/1TqNduRkkjfIVK98QKrWGpJW3eWmPx2ns4XSrHJfBSdE/edit?usp=drive_web&ouid=116413705235587132219

**Comment by hmstepanek** [comment]
Ran across this rather impressive stat while looking into rate limiting:
Badge uses ~ 7/12 gunicorn workers per host so it accounts for more than half of our total aws host cost. @dwhly

**Comment by lyzadanger** [comment]
This work has been broken down into constituent parts, e.g.

https://github.com/hypothesis/product-backlog/issues/926
