### ISSUE TITLE
Enable social login

### ISSUE THREAD

**Issue by LeetCodes** [hypothesis/product-backlog#723]
---
name: 🚀 Feature Request
about: ORCID API integration when editing profile 

---

## Feature Request Description

**Current behavior**
When adding an ORCID to profile it doesn't follow their [brand guidelines](https://orcid.org/trademark-and-id-display-guidelines)

**My Suggestions**
Integrating with their [API](https://orcid.org/organizations/integrators/API)
* authentication you're the owner of the provided iD
* eliminates the need for fetching it yourself or memorizing it due to platforms not integrating

**Comment by klemay** [comment]
See also: https://github.com/hypothesis/h/issues/2286

**Comment by ajpeddakotla** [comment]
Closing this as it's a dupe with #234
