### ISSUE TITLE
Plan how future Elasticsearch upgrades will be executed

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#732]
The process of upgrading h from Elasticsearch 1 to Elasticsearch 6.x has been extremely protracted.

I think it would be wise to reflect on the process and figure out what we should do differently in future, as well as making some notes on a strategy for future upgrades should we need to.

----

Some misc initial thoughts:

- We lacked a test suite which actually tested our search code against Elasticsearch. Much of the time was spent creating this.
- Attempting to redesign part of the code at the same time as upgrading a major dependency is a bad idea, especially without fully appreciating _why_ the code is factored the way it is and all of the minor complexities that it handles.
- Although reading/writing against two clusters at the same time was a reasonable choice in this instance, we could make future upgrades much easier if we avoided needing to do that.

**Comment by segdeha** [comment]
I agree that doing the upgrade in steps (i.e. not trying also to do the DSL stuff at the same time) has kept things simpler. Would completing the DSL work make it simpler to upgrade in the future?

**Comment by robertknight** [comment]
> Would completing the DSL work make it simpler to upgrade in the future?

I don't think so. Certainly it is of much less relevance than other issues.

**Comment by robertknight** [comment]
Based on my experiences of the Elasticsearch 1.x to 6.x upgrade in h, these are my current thoughts on how future upgrades can be done much more efficiently:

- Avoid a "write to multiple clusters at once" approach for future upgrades if possible. This took a lot of effort to implement and I'm certain there will be easier paths in future, especially since we are starting from a current version of Elasticsearch.

- To the extent possible, change one thing at a time. A significant cause of delay in the ES 1.x => ES 6.x migration was trying to redesign the internal h APIs for search and indexing at the same time as upgrading the server version and writing to multiple clusters at once.

- Related to the above; decouple client library and server upgrades if possible. The REST API which the Python Elasticsearch client uses to communicate with the server is very stable. There were not that many breaking changes going from ES 1.x to 6.x which actually affected us. For future ES upgrades the changes will likely be much smaller. Despite what the Python elasticsearch package's documentation advises, it seems very likely that it should be possible to upgrade the client library and server version separately. That is, upgrade the ES server, _then_ the client library in separate steps, or the other way around. It may be necessary to introduce runtime server version checks in a small number of places.

- Consider using Amazon Elasticsearch's in-place upgrade feature. See https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-version-migration.html for details. It isn't entirely clear from the docs whether / how long a cluster is expected to be unavailable during an upgrade. A separate cluster could be created for experimentation before the production migration is done to answer questions like this.

Based on the above, a possible upgrade path in future from the current to a particular target ES version therefore might look like this:

1. Read the release notes for the major ES versions from the current (exclusive) to target ES versions (inclusive) for details of any breaking changes which might affect h.

2. Test out the current h code with a newer ES server version locally. Create a Docker container with the new ES server version and configure h to use it as the ES server. Run the automated tests, perform some basic manual testing and find out what changes affect us. It is possible that everything will _just work_.

3. Make any changes needed to h to support the current and target ES versions concurrently. By this I mean only having a single ES connection, but supporting that being the current or target ES version. For the ES 1.5 => 6 upgrade we found that it was possible to resolve several compatibility issues by rewriting queries in a way that were compatible with _both_ versions without any explicit version checks. As part of this, consider setting up an additional Travis or Jenkins build which uses the target ES version - much like we have Python 2 + Python 3 builds to handle the Python transition.

4. Make sure any monitoring we have other than Amazon Elasticsearch's own monitoring can handle the target ES version. For example the grafana ES metrics plugin.

5. Once the deployed version of h is known to be compatible with the newer ES version, use Amazon Elasticsearch's in-place upgrade feature to upgrade the server to a newer release.

6. If not already done so in earlier steps, upgrade the Elasticsearch client library used by h to correspond to the target server version.
