### ISSUE TITLE
LMS app should generate deterministic usernames for user provisioning

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#733]
Part of https://github.com/hypothesis/product-backlog/issues/712

The LMS app needs to generate an `h` username that is (outside of the black box) deterministic and reusable on subsequent launch requests. This is needed because so many of the `h` services depend on `username` (or `userid`, which includes `username`) as the unique identifier.

**Comment by seanh** [comment]
Apologies but I opened a dup of this card here https://github.com/hypothesis/product-backlog/issues/737 which I've already linked to from elsewhere, so gonna close this one
