### ISSUE TITLE
LMS app should generate unique identity during user provisioning

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#734]
This is part of https://github.com/hypothesis/product-backlog/issues/712

The LMS app needs to generate a valid and deterministic identity (tuple of `provider`, `provider_unique_id`) during the user provisioning and LTI app launch cycle. During user provisioning this identity should be sent along with the user-create request.

**Comment by seanh** [comment]
Apologies but I opened a dup of this card here https://github.com/hypothesis/product-backlog/issues/736 which I've already linked to from elsewhere, so gonna close this one
