### ISSUE TITLE
Implement a faster, easier and more effective way to test LTI launches

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#739]
Part of https://github.com/hypothesis/product-backlog/issues/712

**Comment by robertknight** [comment]
Can this be closed now that [hypothesis/potemkin](https://github.com/hypothesis/potemkin) is a thing?

**Comment by seanh** [comment]
Yeah, I'd say we can close this now. We'll add to Potemkin bit by bit now (and can create cards for those bits if we want) but this card is finished
