### ISSUE TITLE
Provide a more efficient way to page through or sync large collections of annotations

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#744]
The search API currently supports iterating through collections of results using `offset` and `limit` parameters. When the collection is large (eg. all annotations in "Public"), this gets very inefficient as `offset` gets large.

Elasticsearch 6 by default limits the sum of result offset and result set size [to 10,000](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html#search-request-from-size). The end result is that queries with a larger `offset` fail. We could just raise the limit, but that wouldn't fix the fundamental problem that `offset` is an inefficient way to either page through all results or page through results starting from some previous point (eg. as one might do when synchronizing annotations from H to some other place).

**Use cases**

1. Paging through all annotations from a large collection in order to compute metrics
2. Incrementally synchronizing annotations from H to another database, eg. by allowing users to query for annotations created or updated since a previous sync operation.

**Related issues**

https://github.com/hypothesis/h/issues/5191 (API issue from a user trying to sync annotations)
https://github.com/hypothesis/h/issues/5208 (Same underlying issue, but manifested in activity pages)

**Implementation notes**

For the API, we could provide a `start_after` parameter that displays results starting from a given value by whatever field we are sorting by. This would map well to the [search after](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-search-after.html) facility in Elasticsearch which one recommended option for iterating over large collections of results. The `offset` parameter could then be validated and capped at some reasonable number (1000?).

In the context of paging through activity pages results (https://github.com/hypothesis/h/issues/5208) we'll need a different solution, that could involve UI changes.

**Comment by hmstepanek** [comment]
Sentry error:https://sentry.io/hypothesis/h/issues/98916594/

**Comment by hmstepanek** [comment]
According to the docs the official way to do this is through the scroll api:https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-scroll.html This would mean passing a token between the client and the server and potentially having to deal with expired tokens on the server. You can of course do this in more unofficial ways for example by specifying a range of dates; https://www.elastic.co/guide/en/elasticsearch/reference/current/query-dsl-range-query.html. The potential problem with this approach is the requester will not know how many annotations are between x-date and y-date. They may end up with an unexpectedly large number or 0 so the range query becomes inefficient and potentially hazardous as there may be too many annotations to return within the range.

**Comment by hmstepanek** [comment]
https://www.elastic.co/guide/en/elasticsearch/reference/master/search-request-search-after.html <- this one sounds like what we want. Spoke with Rob this AM and this what I will be implementing.

**Comment by robertknight** [comment]
This is now implemented via the [`search_after` parameter](https://h.readthedocs.io/en/latest/api-reference/#operation/search).
