### ISSUE TITLE
Make `group`-`organization` relationship NULLable

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#752]
Summary: We need to alter the current data model involving groups-organizations to support needed functionality for third-party private groups for LMS, but potentially other partner uses as well.

----

Our current modeling of `organization` and its relationship to `group`s is brittle and it has become an actual problem (versus a complexity) when it comes to supporting third-party private groups (for LMS and beyond).

Right now:

* `organization` is a _required_ (non-nullable) relation on `group` records
* both `group` and `organization` have an authority field

All groups must belong to an organization—this is enforced on the DB level.

In our _services_ layer, we enforce a match between `group.authority` and `organization.authority`.  This starts becoming more complex because it means that at least one `organization` must exist for every `authority` and that the services need to know which `organization` to slot a given group into.

We routed around this complexity (sort of) for first-party private groups by making sure a `Hypothesis` default organization exists wherever the app is running, assigned to the `hypothes.is` authority. We have an `Organization.default` class method that will return that “default” organization. If a group-create service (for any type of group) is invoked without passing an explicit `organization`, the new group is chucked into this default organization. Net result is that first-party private groups all get put into the default, “Hypothesis” organization. The relationship between private groups and the “Hypothesis” organization is contextually meaningless; that relation exists solely because it’s a non-nullable relationship. There is no coherent or semantic “meaning” for a private group being in the “Hypothesis” organization.

This breaks down further with third-party private groups. The create-private-group service will attempt to put the new group into the default—Hypothesis—organization. As I mentioned above, there is a validation check here to make sure that the group and organization authorities match, _which they won’t because the default organization is firmly attached to the Hypothesis authority_.

The only “workaround” possible in the current setup is to have a default organization available for _every_ authority and to use that organization to put the authority’s private groups into. That means that the service has to know which “default” organization to use, meaning extension of the model or services classes to juggle this. This becomes a deeper and deeper data tangle. It smells.

There are two ways I believe this could be alleviated:

1. Make the `group` -> `organization` relationship nullable. This would be the fullest and most meaningful way to solve this problem set, as the relationships between private groups and their containing organization(s) don’t mean anything.

2. Remove the `authority` field from `organization` for now. It’s non-normalized that `authority` exists in both places. In this approach, all private groups would be chucked into the default organization (which would no longer be tied down to a single authority). 

----

After discussion with the engineering team, it has been decided that we're going to try for approach 1—making the `organization` relationship on `group` NULLable. This is high-priority as it is on the critical path for LMS work.

**Comment by dwhly** [comment]
Lyza!  Huge gratitude.  

I'll note that we had flagged up this earlier in other discussions.  Namely that there are some groups that will "belong" to H, but many more that won't.  We noted the distinction of being part of our organization vs running on our service.  Taking steps to remove this as the default paradigm in a sensible way is a big step forward.  

Thank you!

**Comment by lyzadanger** [comment]
@dwhly 

 > I'll note that we had flagged up this earlier in other discussions

Yep! I have long thought something was going to need to shift a bit. Yay!

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/h/pull/5223
