### ISSUE TITLE
Cannot type in Annotation card or select a group

### ISSUE THREAD

**Issue by heatherstaines** [hypothesis/product-backlog#760]
### Steps to reproduce
1. I'm annotating in Chrome (Version 68.0.3440.106) on https://www.smithsonianmag.com/smart-news/fishy-origins-of-human-hair-180969688/#tEiIi7bqL4bsV5C3.99 Trying to make a mock up for eLife on how they can use annotation in Marketing
2. If I launch the client, I cannot switch from the public layer to my private group. When I try to activate the group scope the client closes.
3. If I select text, the sidebar opens, but I cannot type in the annotation card (client closes) nor can I change from public to another group).

### Expected behaviour
Tell us what should happen.
I should be able to select my private group and annotate in it or select text to make an annotation and then select the group.

### Actual behaviour
Tell us what happens instead.
Sidebar closes.

### Browser/system information
Tell us which browser, browser version, and operating system you were using when
you encountered this issue.
Chrome Version 68.0.3440.106

### Additional details
Article: https://www.smithsonianmag.com/smart-news/fishy-origins-of-human-hair-180969688/#tEiIi7bqL4bsV5C3.99
I believe I have reported this issue before on another site, but cannot put my finger on it. This is a project for eLife, so I really need to be able to annotate on this article.

### Add tags - did you add labels? 
If this a customer requested feature, make sure to add that label.

**Comment by klemay** [comment]
@heatherstaines I took a look and this appears to be related to ad technology on the Smithsonian website. When I access the site with an ad blocker enabled, it works just fine. If I don't use an ad blocker, I run into the same problem you do, and the browser console shows a bunch of errors related to ads on the page.

We have an existing issue [here](https://github.com/hypothesis/product-backlog/issues/695), where we'll be looking into the ways in which ad technology interferes with Hypothesis, so I have added this as an example of sites to look into and will close this issue.

In the meantime, a workaround would be to install an ad blocker (I use Ad Blocker Pro) and enable that while annotating this site.
