### ISSUE TITLE
Upgrade `support` to Ubuntu 18.04

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#762]
All our static servers run Ubuntu 14.04, which is [supported until April 2019](https://www.ubuntu.com/about/release-cycle). At some point between now and April 2019 we need to upgrade all our servers (`bastion-1`, `bastion-2`, `management`, `support` and `mon`) to 18.04. This card is to upgrade `support` (which runs <https://jenkins.hypothes.is/>) to 14.04 and use it as a test-run for the process we'll use to upgrade the others later.

If we do this right we can get quite a few birds with one stone. I'd like us to:

- [ ] Do the upgrade by provisoning a new VM from scratch (rather than upgrading the new VM in place) and installing Jenkins and its requirements on it from scratch (attaching Jenkins's `/data` volume to the new server). This will verify that we can re-build the critical Jenkins server from scratch in case of a catastrophe, and document how.

  We can also probably follow the process of creating a new VM from scratch and attaching the volume to it the next time we need to upgrade Ubuntu, instead of upgrading it in-place. This means we can keep using 18.04 for as long as possible, not necessarily needing to upgrade it when the next LTS comes out, as we're not going to end up with a giant upgrade to do - we're going to recreate from scratch.

- [ ] Name the new server "jenkins" rather than "support".

  Since we're gonna be bringing up the new server without taking down the existing `support` server first, we won't be able to name the new server `support` anyway. It'll be nice to have a server named `jenkins` that runs only Jenkins anyway, so lets take the opportunity to do that.

  Also see note below about taking down or not taking down `support` afterwards.

- [ ] Choose an EC2 `t3.large` instance. This should be both faster and cheaper than our current `t2.large`.

- [ ] Install the latest LTS release of Jenkins (2.183.1, expected soon) instead of the weekly release line.

  <del>We can fix a problem with our existing Jenkins - being on the weekly release line instead of the LTS - while provisioning the new one.</del> (The existing Jenkins [has been moved over to the LTS](https://github.com/hypothesis/product-backlog/issues/850) now. We should still make sure to use the LTS when setting up a new Jenkins though.)
  
  [Jenkins's download page](https://jenkins.io/download/) describes the LTS vs weekly release lines. We want to be on the LTS release line Ubuntu/Debian package. Specifically, [this apt repo](https://pkg.jenkins.io/debian-stable/). _Or_ maybe we want to use the Generic Java Package (.war) version? I've heard that with .war installs you can upgrade Jenkins from the Jenkins UI. Either way though, we want to be on the LTS.

- [ ] Need to go through everything about the `support` server in the playbook and make sure we've set up everything necessary on it.

  For example it needs to be set up to send emails. `unattended-upgrades` needs to be set up. Etc.
  
- [ ] Install Java 8 properly.

  Java 8 is currently installed on support using an unofficial and unreliable-looking webupd8 blog PPA. This was because Java 8 is difficult to install on Ubuntu 14.04. Hopefully there's a better, more official way to install Java 8 on 18.04. Research needed.
  
- [ ] Install nginx properly.

  Nginx is also installed on `support` using a not entirely official-looking third-party PPA. This should be easy: surely we can just use the nginx from the standard Ubuntu repos?
  
- [ ] Thoroughly document the process.

  A problem with Jenkins currently is that we have no disaster-recovery plan. We don't know how we'd re-create Jenkins from scratch if it was lost. Going through the process of re-creating it from scratch in order to upgrade it to 18.04 is a chance to create that disaster-recovery documentation.
  
  We should create full step-by-step guide similar to the one for [Deploying a new app for the very first time](https://github.com/hypothesis/playbook/blob/master/docs/deploying-a-new-app.md).
  
  This will also greatly improve the team's understanding of Jenkins and of our static servers generally.

- [ ] Everything needs to be done via the playbook.

- [ ] Backups.

  Make sure we have regular (e.g. hourly or daily) automatic backups or snapshots of some kind of the Jenkins server and its storage volumes, which we can use to recover it quickly if we need to.

  We should also test and document this fast-recovery process.

- [ ] Set up monitoring.

  It'd be useful to have resource usage monitoring so that we know whether our `support` server is resource-constrained and could benefit from a size increase, or is over-provisioned. Maybe the monitoring that EC2 provides by default will be enough. Or maybe we should turn on CloudWatch for it. Etc.
  
- [ ] Set up alerting.

  We want to get PagerDuty alerts if Jenkins goes down.

- [ ] Take down the old `support` server afterwards?

  Once the new Jenkins is up and running if there's no longer anything on `support` then we should delete it. _Is_ there anything on `support`, other than Jenkins, though? It may have some other stuff on it, e.g. maybe Slack bots?, in which case we should leave it in place but probably shrink it down to the smallest instance size.

- [ ] I'd like us to also take this as an opportunity to try out [Jenkins Blue Ocean](https://jenkins.io/doc/book/blueocean/). It looks like it can be installed alongside the classic UI.

**Comment by robertknight** [comment]
Assigned to me for the moment to review Sean's notes above and see if we can break this work into smaller steps.

**Comment by lyzadanger** [comment]
This specific work is part and parcel of other scoped operations tasks.
