### ISSUE TITLE
extension fails at altantic.com: unexpected anonymous AMD define

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#764]
Reported on Twitter: https://twitter.com/prof_gabriele/status/1032430653860708352

Example: https://www.theatlantic.com/politics/archive/2018/08/what-trumps-supporters-think-of-corruption/568147/

Error:

```
system.src.js:4300 Uncaught TypeError: Unexpected anonymous AMD define.
    at a.reduceRegister_ (system.src.js:4300)
    at a.pushRegister_ (system.src.js:2766)
    at a (system.src.js:4273)
    at FragmentAnchor.js:3
    at Object.6 (FragmentAnchor.js:11)
    at o (_prelude.js:1)
    at _prelude.js:1
    at Object.39../range (types.coffee:1)
    at o (_prelude.js:1)
    at _prelude.js:1
```

**Comment by klemay** [comment]
There's an existing issue for this - https://github.com/hypothesis/product-backlog/issues/695

Thank you for the additional info! 

For some reason, using Via and/or an ad blocker will allow users to annotate.
