### ISSUE TITLE
Lozenge truncated in IE 11

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#77]
Typed asdf, lozenge became a:

![image](https://cloud.githubusercontent.com/assets/46509/20976357/252a3fca-bc57-11e6-9288-84d4ffcce947.png)

Cannot delete the a lozenge shown above

Similar for user page:

![image](https://cloud.githubusercontent.com/assets/46509/20976850/a9e59902-bc58-11e6-912f-4a3c242971c5.png)

**Comment by lyzadanger** [comment]
@klemay Recommend closing as we no longer support IE11.
