### ISSUE TITLE
Establish relationship between toggle and sidebar

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#772]
Part of https://github.com/hypothesis/product-backlog/issues/753; related to https://github.com/hypothesis/product-backlog/issues/771. 

In addition to telling screenreaders whether the sidebar is currently open or closed, the toggle button should 

Requirements:

- [ ] Add an accessibility feature to make it readable to screen readers to the toggle `button`, such that `ID` is the ID of the annotation panel.

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 3 | 1 | 2 |

**Comment by ajpeddakotla** [comment]
Closed in favor of #1085
