### ISSUE TITLE
Add ARIA markup to tab panels

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#776]
Part of https://github.com/hypothesis/product-backlog/issues/753.

This refers to the "Annotations," "Page Notes," and "Orphans" tabs in the client sidebar. 

For an example, see: http://accessibility.athena-ict.com/aria/examples/tabpanel2.shtml

## Requirements:
- [ ] Add `role=”tablist”` to the tab `<ul>` and `role=”tab”` to individual `<li>`s. 
- [ ] On the tab content divs, add `role=”tabpanel”` and `aria-labeledby=id` 
- [ ] Set `aria-selected=”true”` for selected tabs, and `aria-hidden=”true”` for hidden tab panels

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 2 | 1 | 3 |

**Comment by ajpeddakotla** [comment]
Closed in favor of #1085
