### ISSUE TITLE
Add  aria-haspopup attribute to items with pop-up menus

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#777]
Part of https://github.com/hypothesis/product-backlog/issues/753.

Indicate that an element has an interactive pop up element using the `aria-haspopup`.

The value of `aria-haspop` should match the role (menu, listbox, tree, grid or dialog). Add `ariaexpanded` attribute to indicate the state of the content. 

More info here: https://labs.levelaccess.com/index.php/ARIA_Haspopup_property

Items in the client that have interactive pop-ups:
- Scope selector
- Sort button
- Share button
- User icon
- Share button (on annotation cards)
- Arrow next to the "Post" button

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 2 | 1 | 3 |

**Comment by ajpeddakotla** [comment]
Closed in favor of #1085
