### ISSUE TITLE
Add aria lables to share button in client menu

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#780]
The `a` element needs `aria-label="Share this page"`

(NB: ideally this would be a button rather than a `<link>` because displaying the Bouncer link is not a linking action, but adding this `aria-label` will at least allow the screenreader to announce what the share icon does.

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 2 | 1 | 3 |
