### ISSUE TITLE
Add aria-labels to annotation tags

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#781]
When a user is reading an annotation using a screenreader, the tags are presented as "links" and it's not obvious that they are meant to be tags associated with the annotation. This could be confusing to non-visual users. 

One option would be to add the word "Tags" before the `<ul>` containing the tags. 

This issue would require us to have a semantic relationship between tags and the annotation cards.

**Comment by ajpeddakotla** [comment]
| User Engagement | Building Community | Level of Effort |
|---|---|---|
| 3 | 1 | 3 |
