### ISSUE TITLE
Update Via to establish "LMS_MODE" or similar

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#790]
Update via environment settings such that an "LMS MODE" or similar may be supported and config may be injected into via documents that indicate that the client should use `postMessage` to obtain a grantToken.

This description needs to be fleshed out, but for now, here is some preliminary prototype work @seanh did: https://github.com/hypothesis/via/pull/135

**Comment by seanh** [comment]
Pasting in a comment from Slack that seems highly relevent here:

> The whole auto provisioning feature is only supposed to be turned on for _some_LMS's! Auto provisioning is currently turned on or off on a per "application instance" (per installation of our LMS app in an LMS) basis using a feature flag in the LMS app.
> 
> But now not all of the user provisioning code is gonna live in the LMS app anymore. Some of it is gonna live in the client and/or in Via. And the provisioning needs to be used or not used depending on whether the feature is activated for the application instance that the LMS app is currently talking to.
> 
> **This may argue in favour of using a Via sub-path or query param to activate the feature in Via** (as opposed to using an envvar) (and Via then activates the feature in the client): because the LMS app is the only place that currently knows when the provisioning feature should and should not be used, and the LMS app can simply vary what Via URL it uses.
