### ISSUE TITLE
Update client to allow login from grantToken via postMessage for LMS

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#791]
The gist here is that the client should be able to use some config value to alert itself that it should look for a `grantToken` in a parent iFrame, and it should request it via `postMessage`. (This description should be expanded).

@seanh did a spike prototype here: https://github.com/hypothesis/client/pull/764

This work is closely tied with https://github.com/hypothesis/product-backlog/issues/790

**Comment by seanh** [comment]
Also closely tied with https://github.com/hypothesis/product-backlog/issues/792
