### ISSUE TITLE
Update LMS app to respond to grantToken Requests

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#792]
The LMS app should appropriately listen for `postMessage` communication the client and return a generated grantToken as needed for user authentication in the client. (This description should be expanded if possible).

See @seanh 's prototype work on this feature here:

https://github.com/hypothesis/lms/pull/196

**Comment by seanh** [comment]
I guess this one is pretty intertwingled with the corresponding client issue for the other end of this postMessage request and response: https://github.com/hypothesis/product-backlog/issues/791
