### ISSUE TITLE
Hypothesis not working on some ecommerce sites built with Magento2

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#795]
[Reported by a user via Zendesk](https://hypothesis.zendesk.com/agent/tickets/3010). 

The user provided these two examples:
- https://www.bulgari.cn/en-cn/
- https://www.hpshopping.in/

I cannot get Hypothesis to activate over these sites in Chrome, Firefox, or Safari. When I activate the extension or Bookmarklet, nothing happens. 

Both sites throw the same console error when I try to launch Hypothesis:

<img width="621" alt="screen shot 2018-09-07 at 10 48 39 am" src="https://user-images.githubusercontent.com/12087705/45225907-9c765880-b28b-11e8-87cb-efbceea3b070.png">

If I try to visit these sites using Via, the site will load, and the annotation layer will not. 

The user who reported this issue mentioned that both sites are built with Magento2, but I'm not sure if that is in fact the cause of the conflict from this error message. If we decide to investigate this, we'll want to find some other sites built using the framework to test this out.

**Comment by robertknight** [comment]
> https://www.bulgari.cn/en-cn/

Hypothesis now works on this site.

> https://www.hpshopping.in/

This site is no longer accessible.
