### ISSUE TITLE
Annotate 1:1 with another user

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#800]
### Problem you are trying to address with this feature

Users in many contexts are asking for the ability to annotate only to another single user, as opposed to within a group or the general public.  

- Teachers want to respond privately via annotation on a student's work.
- Researchers want to be able to annotate a private note to the author of a paper (same user story as above).
- Teachers want to respond privately to a students annotation.
- Users want to respond to an annotation but only to the annotations author (same user story as above).
- Users want to privately annotate to another user who is neither the author of a document, nor the author of an existing annotation.  (essentially like a private @mention).

These modes would be valuable in a wide range of situations from the open web, to dedicated teaching and peer review contexts.

They would fundamentally expand on the three major modes of annotation we support now (personal, group, and public) adding a powerful fourth category (1:1).

### Your solution

Establish a "Post" paradigm that would let users specify another user, or the author of a document specifically (if that author's username is made available to the client).

**Comment by dwhly** [comment]
Requested: https://hypothesis.zendesk.com/agent/tickets/3052

**Comment by klemay** [comment]
We have an issue open for this, and it's been prioritized in our backlog: https://github.com/hypothesis/product-backlog/issues/466. 

I initially proposed a slightly different solution, but we probably don't need 2 issues. I'll edit my original one and close this in favor of the 1st one, which is already on the roadmap.

**Comment by jeremydean** [comment]
@klemay i don't think we should lose your suggested solution. I think there are merits and draw backs to both. The answer will come upon further research/investigation.

**Comment by dwhly** [comment]
@klemay I hadn't realized you already had one open for this.  Apologies, I've read it-- but wonder if your original idea is still present there.  Would like to understand what you had proposed.

**Comment by klemay** [comment]
@dwhly @jeremydean point taken!

My original idea was batch creation of sub-groups within groups. So if I crested a group for English 101 with my 20 students, with the click of a button I could create a 1:1 group for each student who has joined English 101. Similar to what Jon suggested via email the other day. 

This is a much less elegant solution than simply being able to annotate 1:1 in a group, as it would clutter the groups control significantly, especially for those teaching multiple classes.
