### ISSUE TITLE
In Deform, buttons do not support custom attributes needed for WCAG compliance

### ISSUE THREAD

**Issue by dwolfe** [hypothesis/product-backlog#801]
The Deform library defines its button class in `form.py` (no other element is defined here), and does not allow for the addition of custom attributes, ex. `aria-label`, which is necessary for full WCAG compliance. (Whether or not we need to be fully WCAG compliant is another discussion, just raising the issue of extending the button component here.)

Two possible solutions: 1) for the `aria-label` attribute specifically, we could modify the relevant Jinja template to duplicate the `title` attribute as an `aria-label`, but that would affect every button created with Deform, and there may be cases in which the `title` and the `aria-label` shouldn't be the same. 2) We could extend/subclass the button class.

*Open Questions:*
• Are there similar issues with other components in Deform, besides buttons?
• Should we replace Deform? If so, with what?

**Comment by dwolfe** [comment]
@ajpeddakotla If this is still relevant, could you open a new issue for it? Thanks!

**Comment by ajpeddakotla** [comment]
@dwolfe  could you turn off notifications for this repo rather than closing issues? Let’s not create more work when it’s not needed.

**Comment by ajpeddakotla** [comment]
Closed in favor of #1085
