### ISSUE TITLE
Grafana broken after unexpected upgrade

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#805]
Yesterday I fixed a problem where login to our Grafana dashboard at https://mon.hypothes.is broke because the OAuth client used for Google SSO got deleted. After a new OAuth client had been provisioned and an updated Grafana config file had been deployed by ansible, we noticed that:

- Grafana looks somewhat different than before. It is now on version 5.2.2. I think we were running an older version for some time before that. This major update was unexpected.
- Our dashboards are broken. I don't know how hard it will be to adapt them to whatever API breakage has happened.

A conjecture I have is that Ansible upgraded Grafana for the first time in aeons when it deployed the updated config file, but this is yet to be verified.

**Comment by seanh** [comment]
If Ansible's `configure` playbook did this there may be logs of it in Jenkins.

If fixing the dashboards doesn't look easy I think downgrading Grafana may be fairly easy.

**Comment by robertknight** [comment]
Duplicate of https://github.com/hypothesis/private-issues/issues/16. Now fixed.
