### ISSUE TITLE
Fix non-performant database queries on activity pages

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#812]
See these incident reports for details: https://docs.google.com/document/d/1gwcLAUbogRJ95tTW0tbxSonDim7itolqUVnLow-USyw/edit.

https://docs.google.com/document/d/1gefQl1KBHFc4WMrt1vsWBrKYqRxc5bfU9AFbIbecyRw/edit

**Comment by judell** [comment]
<s>What are some example of non-performant queries?</s> Never mind, found the incident report.

**Comment by robertknight** [comment]
Based on the details in the incident report and Hannah's comments in Slack, it looks like it is this count which is computed in an expensive and unnecessarily exact way:

<img width="1101" alt="screenshot 2018-09-26 10 40 24" src="https://user-images.githubusercontent.com/2458/46072021-38073480-c179-11e8-9c25-97a88bbe1e11.png">

https://github.com/hypothesis/h/blob/a2ed4eaf27dceaf47870ae4d60afd2fd89790360/h/views/activity.py#L159

@hmstepanek - New Relic also shows that a large number of requests are being made to fetch user data. Perhaps worth pre-fetching user info?

**Comment by robertknight** [comment]
The expensive queries for fetching user and group counts on `/groups/{id}` and `/users/{id}` pages have now been resolved by the PRs linked above so I'm going to close this.
