### ISSUE TITLE
Add cron job to clean support server

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#820]
Make a cron job to cleanup the support server:
 1. Remove docker images from beyond 1 week
 1. Remove docker volumes from beyond 1 week
 1. Remove docker containers from beyond 1 week
 1. Remove docker networks from beyond 1 week
 1. Remove jenkins workspace runs from beyond 1 week

**Comment by dmfine** [comment]
These are some relevant commands:
> docker ps --filter status=dead --filter status=exited -aq   | xargs docker rm -v
> docker volume ls -qf dangling=true | xargs -r docker volume rm

**Comment by dmfine** [comment]
Rather than a cron to clean up, might we make the build clean up after itself better? It's something to look into. I'd consider making the cleaner a jenkins build job instead of a cron, it's already right there...
