### ISSUE TITLE
Debug elastic load balancer problems

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#824]
We've been having problems over time with our load balancer overloading our instances causing them to restart. Here is one such incident:
https://hypothes-is.slack.com/archives/C0LUWQQJJ/p1538706245000200

It's unclear why this is happening. Is it a configuration we have or is it a problem with amazon's load balancer?

Possible solutions may include filing a support ticket with aws.

**Comment by dmfine** [comment]
Is this still an issue @hmstepanek

**Comment by hmstepanek** [comment]
AFAIK yes. It's intermittent. I can't say I've seen the issue recently but we haven't done anything to fix it/looked into it since this was filed. You should be able to see it by looking at the aws stats page or the NR h-prod dashboard. Both of those keep track of how long an instance stayed up/was in use.
