### ISSUE TITLE
Be able to rename a PDF 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#825]
### Problem: 
PDF names are sometimes unreadable, and currently unchangeable. 

### Feature Request:  
Be able to change a PDF name, likely on activity pages, so that users have a better understanding of what they have annotated. 

User posted this as an example: 

<img width="463" alt="screen shot 2018-10-08 at 10 45 30 am" src="https://user-images.githubusercontent.com/7463523/46619281-5826e400-cae7-11e8-8e2e-de2090b4d567.png">

https://hypothesis.zendesk.com/agent/tickets/3177

**Comment by dwhly** [comment]
Related to: https://github.com/hypothesis/product-backlog/issues/127

Close this one?  Rename the other one?

**Comment by ajpeddakotla** [comment]
Yep. Closing this one in favor of #127.
