### ISSUE TITLE
indicate the group creator on the group page

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#83]
### Problem you are trying to address with this feature

Although I created https://hypothes.is/groups/wqvn7Lar/hypothesis-reading, the page https://hypothes.is/groups/wqvn7Lar/hypothesis-reading doesn't indicate that judell is the creator. As judell I can edit the group page, as jonudell I can't, but there's no way to know which of my identities has that power without trying to edit the page as each of them.

### Your solution

On a page like https://hypothes.is/groups/wqvn7Lar/hypothesis-reading, indicate who created the group.

**Comment by klemay** [comment]
As we start to think about moderation and abuse prevention, "who created this group?" will be a helpful bit of information to surface.

**Comment by hmstepanek** [comment]
@judell @ajpeddakotla Can we close this now as we have a creator label in the list of members on a groups activity page now?
![image](https://user-images.githubusercontent.com/30059933/39073469-bb39b11a-44a2-11e8-8c9e-e254ac9e8c5e.png)
