### ISSUE TITLE
Jumping to last page of activity page silently fails

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#832]
It used to be (before we put a limit on offset for searching), that you could crash activity pages by jumping to the last page. Because there is a limit for offset now, jumping to the last page on activity pages silently fails. It appears to work but it doesn't return the old annotations because of the limit. It only goes back to 10k annotations in the past. 

For example: https://hypothes.is/search?page=2832 (the last page of all annotations) reports no annotations are older than Sep 2018.

Activity pages still use offset for pagination which is incorrect. We need to look into elasticsearch pagination techniques and use one of them on activity pages in place of the existing implementation.

**Comment by judell** [comment]
What's the repro for this? 

I can do https://hypothes.is/search?q=the and then https://hypothes.is/search?q=the&page=1751 with no apparent problem.

**Comment by hmstepanek** [comment]
Hmmm...you're right! I can't reproduce this anymore. Perhaps we fixed it at some point in the last couple months. Ok I'm gonna close this then.

**Comment by hmstepanek** [comment]
I have re-opened this under a slightly different title. I did some digging in the code and in fact this has not been fixed. Same problem-just a different symptom.
