### ISSUE TITLE
Fix issue with list_groups performance

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#835]
h/services/list_groups.py:_scoped_groups is running a slow seq scan query.
![image](https://user-images.githubusercontent.com/30059933/46848514-22138980-cd9f-11e8-81a4-af69b005afb6.png)

See [NR](https://rpm.newrelic.com/accounts/1385283/applications/22688631/datastores?tw%5Bend%5D=1539299314&tw%5Bstart%5D=1539239486#/overview/Postgres/trace/?id=94dc6c8d-cd59-11e8-8940-0242ac110008_0_2165&metric=Datastore%2Fstatement%2FPostgres%2Fgroupscope%2Fselect) for details.

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/h/issues/5608 (the slowness was in the user-select query, BTW, less so in the group-scope query).
