### ISSUE TITLE
Remove ability to leave groups from client in LMS context

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#841]
_Extracted from 
https://github.com/hypothesis/product-backlog/issues/789#issuecomment-429840443_:

In the context of an LMS assignment when account auto-provisioning is enabled, it is possible for the user to leave the group associated with the course that the assignment is in using the "X" button in the groups dropdown menu.

If the user leaves all groups this will leave the client in an invalid state where the groups menu can appear but is empty, and annotations are displayed despite there being no active group.

If the user reloads the page they get auto-joined to the appropriate group again, so clicking this button is not fatal.

Some possible solutions:

- Allow the user to leave groups except for the one associated with the current assignment. This will allow the user to leave groups for courses that are no longer active.
- Allow the user to leave groups except for the last one. This way there is always at least one group active.
- Don't allow the user to leave groups at all in this context

**Comment by lyzadanger** [comment]
Given that we're taking actions on behalf of users vis-a-vis groups in the LMS context, I feel that the clearest approach here might be disallowing the user from leaving any groups for now. That is, the LMS authority is granted the ability to decide when a user joins these groups, and I think it's consistent that this would extend to the user _leaving_ groups, as well. I anticipate a future requirement in which admins/instructors (or even an automated process) would need to remove certain users from course groups (e.g. if a user drops a course), extending the oversight into group membership for the LMS authority.

I fear that a mixing of "you can leave this group but not that one" along with automatically re-joining users to course groups could lead to confusion.

Say a student in a given LMS instance is registered for two courses that use Hypothesis. The student launches an assignment in course A and is automatically joined to course A's course group. The student then launches an assignment in course B and is auto-joined to that course group. So: student is currently working on an assignment within course B's group but can also see that they are a member of course A's group.

Two of the scenarios above allow the user to leave course A's group at this point:

* Allowing the student to leave course groups for all but the currently-active course group, or
* Allowing the student to leave all course groups except for the last one

But then the student goes back to an assignment in course A and is re-auto-joined to course A's group. That seems pretty confusing!

Also, third-party users cannot currently create private groups through the client/web service, so these course groups—for the immediate future—are the _only_ groups that these students will see.

Lots of words aside: I'd vote for the simplest approach—don't allow students to leave course groups. For now. We can always change our minds in the future!

**Comment by lyzadanger** [comment]
Important: This issue may no longer be valid if we opt to disable the groups menu in the LMS context.

**Comment by hmstepanek** [comment]
Sounds like this has been resolved and we are going to disable the groups drop down. https://github.com/hypothesis/lms/issues/294#issuecomment-431487038. In light of that I'm going to go ahead and start working on disabling the groups drop down which will also solve this issue.

**Comment by lyzadanger** [comment]
This ticket is still valid, but is not presently actionable.

**Comment by lyzadanger** [comment]
Closing because I believe that https://github.com/hypothesis/product-backlog/issues/868 renders this particular issue no longer valid, but reopen as necessary!
