### ISSUE TITLE
Enable rate limiting per user per end point

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#849]
When a script runs on H is can take down the server thus rate limiting needs to enabled on a per IP address/auth token.

Nginx has the ability to do this: https://www.nginx.com/blog/rate-limiting-nginx/

**Comment by robertknight** [comment]
> Nginx has the ability to do this: https://www.nginx.com/blog/rate-limiting-nginx/

If we can do the rate limiting at the nginx level and thereby prevent the request even hitting the app that seems like a good idea.

**Comment by hmstepanek** [comment]
We will need something better than just a blanket rate limit for all transactions as things like badge can handle > 16k requests/min but the create annotation endpoint can handle much less. You can use NR's transaction [table](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions)  as a reference to figure out what the rate limits should be. 

It looks like there was a little mini incident just before the main incident where the create annotation's endpoint spiked to a throughput of 40 requests/min. We should prob limit this somewhere around 25 requests/min since this mini-incident still resulted in update db times of > 1s. The typical rate is ~11 rpm. (Just to give some idea of what the limit should be for this particular endpoint.)

**Comment by robertknight** [comment]
Status update: There is an [approved PR open](https://github.com/hypothesis/h/pull/5423) which implements rate limiting and metrics/alerts have been configured in Cloudwatch. Hannah is planning to deploy this when she gets back on Friday.

**Comment by dwhly** [comment]
> metrics/alerts have been configured in Cloudwatch.

Thank you (per my other question).

**Comment by hmstepanek** [comment]
Fixed by https://github.com/hypothesis/h/pull/5432.
