### ISSUE TITLE
When particular config present, client should filter out other groups

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#852]
Part of https://github.com/hypothesis/product-backlog/issues/680

There's a dependency between this issue and https://github.com/hypothesis/lms/issues/301

In the presence of a particular config option identifying a specific "focused" group (from the LMS app), the client should filter out the groups from the API response that are _not_ that group and only display/provide access to the focused group.

(Don't forget error handling if the config-defined focused group isn't in the API response for some reason).

**Comment by robertknight** [comment]
This has been deployed in client release v1.98.0.
