### ISSUE TITLE
Create a link to share a group 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#855]
Part of https://github.com/hypothesis/product-backlog/issues/866

### Problem
Currently, there is no way for users to create links to share a group with other users. 

### User Story
As a user, I’d like to be able to create a link to view annotations for a document made by a specific, group, even if I am not a member of that group.

### Acceptance Criteria
- [ ] Users should be able to use group identifiers to create a specialized link that will share the annotations made within a group, on a specific page, with other users. 
- [ ] Amend current share link in the sidebar to include groups, when present.
- [ ] Add clipboard button to this share link on sidebar (consistency of implementation w/ activity pages). 
To view the share link, users have to click on the share icon at the top of the header
<img width="438" alt="screen shot 2018-10-30 at 9 54 47 am" src="https://user-images.githubusercontent.com/7463523/47727207-fbbc6d80-dc29-11e8-97d5-888c96bba23c.png">

They are then shown the share link 
<img width="426" alt="screen shot 2018-10-30 at 10 21 47 am" src="https://user-images.githubusercontent.com/7463523/47729197-bb5eee80-dc2d-11e8-9894-dedb046de0ed.png">

**Comment by dwhly** [comment]
One note:

![screen_shot_2018-10-30_at_8_04_18_am](https://user-images.githubusercontent.com/1413074/47730441-6320f000-dc1f-11e8-8fce-0511e03a627a.png)

The share link UI is missing the copy button that we have in the direct link below, we might want to take this oppy to harmonize.

Happy to create a separate issue if that's preferable. @dwolfe ^

Also, a note that we have a report that the copy to clipboard is broken in mobile (chrome?) apparently.

**Comment by ajpeddakotla** [comment]
closing as it is being tracked in #1030
