### ISSUE TITLE
Slow api/annotations:create endpoint

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#860]
The create annotation endpoint has a lot of slow requests. This appears to be due to some loops around document uri's. We should investigate why there are these loops and ways to reduce them and thus the number of requests made to the db.
![image](https://user-images.githubusercontent.com/30059933/56978858-5416ee00-6b2d-11e9-9f18-8afb3b0a2202.png)
[detailed trace in NewRelic](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions?tw%5Bend%5D=1556642508&tw%5Bstart%5D=1556037708#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e616e6e6f746174696f6e733a637265617465222c22225d&app_trace_id=70a5823e-6699-11e9-93d3-0242ac11000f_24144_29749&tab-detail_70a5823e-6699-11e9-93d3-0242ac11000f_24144_29749=database_queries)

Here's a graph of the percentage of requests that experience requests to this endpoint slower than .5s: 
![image](https://user-images.githubusercontent.com/30059933/56979972-ffc13d80-6b2f-11e9-9a4f-0e81202d0c24.png)

Due to this percentage, and the fact that this endpoint is one of our main features, this needs to be addressed ASAP. Over the course of a 7 day period ~5% of requests are > .5 s.

**Comment by robertknight** [comment]
Can you add links to the New Relic dashboard where you got this screenshot from?

**Comment by hmstepanek** [comment]
Transaction traces are located at the bottom of this [page](https://rpm.newrelic.com/accounts/1385283/applications/22688631/transactions?tw%5Bend%5D=1540968112&tw%5Bstart%5D=1540881712#id=5b225765625472616e73616374696f6e2f46756e6374696f6e2f682e76696577732e6170692e616e6e6f746174696f6e733a637265617465222c22225d&sort_by=throughput). If you expand one of those traces and look at the Database queries tab you can click on the individual query to see the details that are screen shotted in this issue.
