### ISSUE TITLE
[Feature request] Annotation moderation

### ISSUE THREAD

**Issue by ArtFlag** [hypothesis/product-backlog#862]
First of all, thanks for your hard work, Hypothesis is a really nice tool. I have a feature request for you:

As a group creator, I would like to be able to moderate the annotations:
- delete annotations
- mark annotation as resolved
- edit annotations

I'm using Hypothesis as a feedback tool, and the ability to delete annotations when the feedback has been resolved would be great.

**Comment by klemay** [comment]
Closing in favor of: https://github.com/hypothesis/product-backlog/issues/409
