### ISSUE TITLE
Allow direct-link sharing to annotations within a group context

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#866]
Informed by https://github.com/hypothesis/product-backlog/issues/844

This epic tracks these high-level user stories, as informed by requirements in https://github.com/hypothesis/product-backlog/issues/844 and its related issues, translated into implementation "chunks."

### User Stories

If I’m viewing a group’s annotations on a page, I want to also be able to grab a link such that I can direct others to the same experience I’m seeing.

I want to be able to follow a link shared with me to see annotations within any specific group, even if I am not a member of that group.

-----

At a high level, implementation of this includes:

* Making technical changes so that world-readable groups may be "available" outside of their scopes and that restricted groups configured as such show up for their members web-wide (https://github.com/hypothesis/product-backlog/issues/865)
* Implementing the core link functionality (a.k.a. "QDR work") so that visiting certain-formatted links displays a document's annotations within the context of a specific world-readable group (https://github.com/hypothesis/product-backlog/issues/864)
* Making sure that links to annotations in _private_ groups work and flow smoothly for users: (https://github.com/hypothesis/product-backlog/issues/867)
* ~~Creating a tool to create these share links for any type of group~~ (https://github.com/hypothesis/product-backlog/issues/855) (no longer part of this phase)
* ~~Improving groups-control UX~~ (tracked in https://github.com/hypothesis/product-backlog/issues/848 )

**Comment by lyzadanger** [comment]
Yay!

**Comment by adam3smith** [comment]
This is amazing! Is this already live (if not, roughly when can we expect it to be)? Any documentation (which can be super-rough; I'll work through it) I could find?

**Comment by robertknight** [comment]
Hi @adam3smith - It is live in the embedded version of the client with one notable issue, that the sidebar doesn't open automatically yet if you direct-link to a group, as well as some rough edges that we'll be polishing over the next few weeks. To use it, create a link of the form https://hyp.is/go?url={url}&group={group_id}. We also still need to ship the updated browser extension. That should happen in a day or two.

**Comment by robertknight** [comment]
Hi @adam3smith - It is live in the embedded version of the client with one notable issue, that the sidebar doesn't open automatically yet if you direct-link to a group, as well as some rough edges that we'll be polishing over the next few weeks. To use it, create a link of the form https://hyp.is/go?url={url}&group={group_id}. We also still need to ship the updated browser extension. That should happen in a day or two.

**Comment by adam3smith** [comment]
Perfect, got it to work in the embedded version (we use `#annotations:group:<groupid>` ).
