### ISSUE TITLE
Perfect the flow for viewing direct-linked private group context annotations

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#867]
Part of https://github.com/hypothesis/product-backlog/issues/866

Inspired by: https://github.com/hypothesis/product-backlog/issues/748

This issue is intended to track UX, privacy or functional problems that arise from allowing direct links to annotations within the context of a _private_ group.

it is placeholder-y for the time being, but a known piece of https://github.com/hypothesis/product-backlog/issues/866

**Comment by robertknight** [comment]
See also notes on private groups in https://github.com/hypothesis/product-backlog/issues/990

**Comment by robertknight** [comment]
The description here was a little vague but from my recollection, https://github.com/hypothesis/client/pull/1084 was the main issue that we needed to address. On that basis, I'm going to close this.
