### ISSUE TITLE
Disable the groups drop down menu when thirdparty and only one group

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#868]
If it is a third-party service and there is only one group to be displayed in the groups drop down, do not display the group drop down menu. This has the following advantages:
 1. It doesn't waste the user's time by clicking on a drop down only to see no other option.
 1. It removes the ability of a user to leave a group that they shouldn't be able to leave.
 1. Third-party services don't have multiple groups and they don't yet have the ability to make private groups so this has no impact on pre-existing third-party accounts. 
 1. The direction we will take to enable creation of private groups/multiple groups for third-party services is unknown at this time but if there are at some point multiple groups/options to display, the group drop down will once again be displayed so this is a low risk logical change.

**Comment by lyzadanger** [comment]
Related to https://github.com/hypothesis/product-backlog/issues/841

**Comment by robertknight** [comment]
This is done.
