### ISSUE TITLE
Long URLs (strings?) cause annotation card controls to misalign

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#877]
### Steps to reproduce
1. Make an annotation with a long URL embedded, like the reply here: https://hyp.is/RjbBWOeSEeije7sb74asRA/web.hypothes.is/help/how-do-i-navigate-to-the-search-and-profile-pages/
2. Reply to it

### Expected behaviour
Controls on reply should be properly laid out

### Actual behaviour
Controls (and timestamp) are shifted to the right.

### Browser/system information
Chrome 

### Additional details

![screen shot 2018-11-13 at 3 43 00 pm](https://user-images.githubusercontent.com/1413074/48451149-ec770d00-e75d-11e8-95bd-b5fba9c3dc63.png)

**Comment by klemay** [comment]
Hey @dwhly I think this may be fixed - can you confirm? the link to the annotation in your original description no longer exists, so I re-created to try and reproduce. Looks like it's working properly now:

<img width="410" alt="Screen Shot 2020-11-09 at 11 15 10 AM" src="https://user-images.githubusercontent.com/12087705/98566544-de8cf180-227c-11eb-880f-04ef886dbdbb.png">
