### ISSUE TITLE
Consolidate Nginx's

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#884]
# Problem: 
Currently aws elastic beanstalk's instances are wrapped in nginx and we also have nginx inside our application's docker container. We don't need two nginx's. See [aws nginx docs](https://docs.aws.amazon.com/elasticbeanstalk/latest/dg/java-se-nginx.html) for details.

Our current setup of running nginx in the same docker container as our application is less than ideal in several ways:
1. We serve static files from our python application instead of nginx.
2. We do not have a separate nginx container.
3. A request has to go through 2 nginx layers to reach our web server.

# Proposed Solution:
Since amazon's nginx isn't going away, we should apply the docker nginx's config to aws' nginx and remove nginx from our application's docker container. 

# Problematic Areas:
We still need a solution for local development to test out our nginx configurations though:
The recommended setup for a python application using gunicorn, and nginx is so have a separate container for nginx.  For local development this means we need to add an nginx container to docker-compose. The nginx container however, needs to be able to talk to localhost since our current dev env runs gunicorn locally as opposed to inside a docker container and this is not possible on all operating systems with docker. 
 > The host networking driver only works on Linux hosts, and is not supported on Docker Desktop for Mac, Docker Desktop for Windows, or Docker EE for Windows Server.

Currently the way our repo's are setup we need to add amazon's config to .ebextensions which is in a separate repo from h (deploy) which means we need to run nginx in h but depend on the config file in the deploy repo. It might make more sense to have a separate docker-compose in the deploy repo for dev and run nginx from there and point it at the application when needing to test nginx. Of course pointing it at the application is still problematic.

See https://hypothes-is.slack.com/archives/C4K6M7P5E/p1543509032046800 for a list of changes.
This depends on https://github.com/hypothesis/product-backlog/issues/890 and https://github.com/hypothesis/product-backlog/issues/889.

**Comment by robertknight** [comment]
So aside from having one less proxy server in the request-response chain, this would presumably mean moving the nginx config out of the "h" repo and into the "deployment" repo?

That may make sense anyway as it means that we could have stuff in the nginx config which is specific to our QA/prod environment without worrying about trying to make it reusable for other people deploying the Docker image. We already do have hypothes.is specific stuff in `conf/nginx.conf` which is irrelevant for other parties running h.

**Comment by robertknight** [comment]
This would also enable us to fix an issue where the nginx access logs in CloudWatch show the load balancer IPs instead of the original request IPs as reported by the `X-Forwarded-For` or `CF-Connecting-IP` headers.

**Comment by hmstepanek** [comment]
And this would enable us to actually identify an ip to block from the access logs.-All good things.

**Comment by seanh** [comment]
What's the problem with serving static assets from the Pyramid app? Presumably they are (or at least should be) cached in nginx and even in Cloudflare, so only the first request for each static asset should actually get to the Pyramid app? Or are all static assets request hitting the Pyramid app currently?

**Comment by seanh** [comment]
I've opened a separate issue for the nginx in dev thing. Possible workaround for the macOS host networking problem? https://github.com/hypothesis/product-backlog/issues/1047

**Comment by seanh** [comment]
I think the serving static files thing is also a separate issue?

Agree that the two nginx's in production definitely seems wrong. Definitely seems like we should be doing it in AWS's documented way

**Comment by hmstepanek** [comment]
Presumably they would be cached at the cloudflare level yes. In dev however, since we don’t run nginx these requests all go straight to the pyramid app. In general I don’t think this is really a performance problem in production so much as a what’s the correct architecture and a separation of concerns. Yes our current architecture works but it doesn’t necessarily follow best practices. Consider lms for example: we have a client and a web server however, currently we serve these two different services as if they were one service from the web server. It works but architecturally speaking they are two separate services and typically nginx would be where the static client would be served from, not the web server.
