### ISSUE TITLE
Version our API; Release 1.0

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#888]
The h api is not versioned today. This gives us no way of deprecating features and endpoints which in the long run results in a lot of technical debt.

For example (I'm sure there are many more non search related things) there are several search specific things that would prob be worth deprecating at some point in the future:
- url or uri (we only need one of these)
- tags
- offset

**Comment by lyzadanger** [comment]
I realize that instead of co-opting this issue, I should create a new one so that my authorship is more clear. Thanks for planting the stake, @hmstepanek !
