### ISSUE TITLE
Set timeout on postgress queries so metabase doesn't fall over

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#892]
We've had to kill long running (days) queries by hand. My conservative guess is that queries running longer than 30 seconds are doing something wrong. Let's find out what the baseline is and set the timeout to like 2 or 3 standard deviations from that.
https://dba.stackexchange.com/questions/164419/is-it-possible-to-limit-timeout-on-postgres-server

**Comment by hmstepanek** [comment]
Note that our rds snapshot backups run queries longer than 30s-so we'll have to take those into account with this setting.

**Comment by dmfine** [comment]
This is probably no longer needed since moving to the read replica
