### ISSUE TITLE
Improve docker containers for H

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#893]
Currently, the `make dev` command is used for development which runs gunicorn locally inside tox. It would be nice if we could develop inside the same environment we deploy (docker). Currently there are `make docker` and `make run-docker` commands that allow you to build and run the full docker container locally but the `make docker` command which builds the docker image does not use the local version of the files but rather uses git HEAD. This means you have to commit your changes before testing local changes using docker which make development using docker slow.
 
Make a new make command(s) for using docker locally for development that pulls from the local files rather than git HEAD. This is one of the first steps we need to take if we would like to move to using docker to develop new code in dev. (We will probably need to make a new command because I suspect the old command is used by our ci for actually building the deploying to qa and prod.)

Ultimately using docker in dev would drastically simplify H setup/install and also remove the need to use tox to setup a python environment.

**Comment by lyzadanger** [comment]
> the make dev target should load app code from a local working directory instead of master. 

Hi @dmfine — I'm a little perplexed by this as `make dev` _does_ work with the local source, irrespective of branch/`master`.

**Comment by hmstepanek** [comment]
@dmfine I've made some edits to the description so it's more clear. I think you were confusing `make dev` with `make run-docker`. @lyzadanger does it make more sense now?

**Comment by lyzadanger** [comment]
@hmstepanek Definitely more sense! Thanks!
