### ISSUE TITLE
Change our current metabase to talk to a read-only snapshot

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#894]
Currently metabase runs queries against our production database. This caused an incident last week. See [incident report](https://docs.google.com/document/d/1HKsFqMVgQaugbkUINWaWG43k0UYSkUu1o0lxGHqflAE/edit#). This poses multiple issues:
 1. A user of metabase can run write queries and could potentially wipe the entire prod database (not that anyone would but we all make mistakes). 
 1. Occasionally queries that take too long because they are so non-performant can be run via metabase that affect quality of service for our customers.

One important note is metabase is nice for debug and certainly for incident mitigation as we saw in the incident linked above so I would recommend keeping a version of metabase running on prod around for that purpose but for what the programs team uses metabase for day-to-day, that version should be running agains the latest snapshot in readonly mode.

**Comment by robertknight** [comment]
> that version should be running agains the latest snapshot in readonly mode.

RDS has support for setting up and managing [read replicas](https://aws.amazon.com/rds/details/read-replicas/). Would this be an easier option than creating a DB instance that uses a snapshot? It would also enable queries against the latest data which may sometimes be useful.

**Comment by hmstepanek** [comment]
^ That sounds reasonable as long as it doesn't run any queries on the master db and disallows writing. It sounds like it acts like it's own db instance on a network of db instances so as long as the query routes directly to the readonly instance and doesn't send anything to master it sounds like it would work. Also we would want to disable this ability (not sure if this is the default or special but it sounds like it's not necessarily readonly or can be made not to be):
 > Because the Amazon RDS for MySQL engine also allows you to perform table-wide actions like adding indexes or new columns to read replicas, you can use its replica-promotion capability to minimize the impact of these actions.

**Comment by hmstepanek** [comment]
In general I'm pro whichever is simpler.

**Comment by judell** [comment]
I've written a whole lot of queries, and would sure love a way to share code across them. It'd be great to be able to put shared logic into SQL functions, which I think implies a writable DB instance. But maybe there's another way?

**Comment by hmstepanek** [comment]
Yeah I guess I'm ok with writing as long as it doesn't affect the master/prod database. Alternatively you can have the sql functions already in there. Do you make a lot of new sql functions or are they just the same ones that you re-use a lot?

**Comment by judell** [comment]
> Do you make a lot of new sql functions or are they just the same ones that you re-use a lot?

I haven't made any yet because there's been no opportunity to do so. Ideally I could make them in an exploratory/iterative way.

**Comment by dmfine** [comment]
I created a read replica on t2.medium instance. Added it as an option in metabase (unclear if we have to change all our "questions" by hand or if there's an automated way to do that)

**Comment by dmfine** [comment]
Some metabase queries fail with "ERROR: canceling statement due to conflict with recovery Detail: User query might have needed to see row versions that must be removed." So I'm following the parameter settings here: https://stackoverflow.com/questions/14592436/postgresql-error-canceling-statement-due-to-conflict-with-recovery

**Comment by robertknight** [comment]
Hello @dmfine and @hmstepanek - What's the status of this? Can we close this ticket or is there more to do?

> So I'm following the parameter settings here:

Which parameter settings? `max_standby_streaming_delay`?

**Comment by dmfine** [comment]
We're using it in metabase now :)
for historical record I went with the following parameters:
max_standby_archive_delay = 900s
max_standby_streaming_delay = 900s

**Comment by xolotl** [comment]
@dmfine if it's automatic, how often does the read db replicate?
