### ISSUE TITLE
update Metabase to 0.31.2 (or latest)

### ISSUE THREAD

**Issue by xolotl** [hypothesis/product-backlog#910]
"Metabase 0.31.2 is available. You're running 0.24.2"

In order to continue our evaluation of Metabase as a possible solution for [H. data reporting needs](https://docs.google.com/document/d/1FBwIokymCAy8WQylaslSPEWIUzaWTJUTlK4JSAbCnu8/edit?usp=sharing), we'd like to upgrade it to the latest version. Maybe it's as simple as hitting the update button in the admin panel, but I leave it to the prod team to know what's best.

![cursor_and_updates_ _settings_ _admin_ _metabase](https://user-images.githubusercontent.com/997548/50866478-f59be900-135e-11e9-8d26-7271ed7b0101.png)

**Comment by ajpeddakotla** [comment]
Closing this in favor of original issue: https://github.com/hypothesis/private-issues/issues/11
