### ISSUE TITLE
PDF support broken in FF 64 and above

### ISSUE THREAD

**Issue by dwhly** [hypothesis/product-backlog#915]
### Problem you are trying to address with this feature

In current FireFox, using PDFjs 2.0.936, existing Hypothesis annotations will not anchor, and new annotations cannot be made.  This is using the H bookmarklet within FF 64 or above.

This is the sample PDF that is failing for me: https://arxiv.org/pdf/1805.09695v6.pdf

As recently as FF 63.0.3, using PDFjs 2.0.775, everything was working satisfactorily.

Unless I'm wrong about this, it means any users of the H bookmarklet in FF (an important population) cannot see or contribute additional annotations to any PDF.

### Your solution

We need to support the newest version of PDFjs, and potentially (but separately) think about upgrading the PDFjs version we're pinning in Chrome.

**Comment by dwhly** [comment]
To elaborate:

New annotations cannot be made because the adder exhibits an odd flickering behavior.  The "Annotate" target in the adder is (kind of) visible but not clickable.

**Comment by dwhly** [comment]
Related: https://github.com/hypothesis/product-backlog/issues/914

**Comment by robertknight** [comment]
Testing this locally, I see the following error when attempting to make an annotation:

```
TypeError: PDFViewerApplication.pdfViewer.getPageTextContent is not a function[Learn More] 2 pdf.coffee:1
	getPageTextContent pdf.coffee:1
	n pdf.coffee:1
	getPageOffset pdf.coffee:1
	describe pdf.coffee:1
	n guest.coffee:1
	map (index):286
	createAnnotation guest.coffee:1
	onAnnotate guest.coffee:1
	r adder.js:159
	e adder.js:165
```

It looks like the `getPageTextContent` method was removed in https://github.com/mozilla/pdf.js/commit/e293c12afcf3a9a55669b6bf095d657e7780ba16. The bottom of the diff for that commit shows an alternative implementation using other APIs.

More broadly, I'm not clear on whether `getPageTextContent` was considered a public API or not. [This PR](https://github.com/mozilla/pdf.js/pull/9369) has some related discussion about exactly what constitutes the public API of PDF.js. One thing that is mentioned in the comments is that the primary public API is defined in [api.js](https://github.com/mozilla/pdf.js/blob/master/src/display/api.js).

Going forwards, I think it would be a good idea to consider:

- Auditing our use of PDF.js APIs, to determine whether we are relying on anything that is considered a private API, and replacing these uses with public APIs. This may involve some discussion with upstream.
- Creating a thin abstraction layer around the PDF.js functionality we use where we can isolate the logic for dealing with different PDF.js versions and also see in one place what PDF.js APIs we are using. We could potentially create automated tests which verify that this works as expected against the current released version of PDF.js so we don't run into surprises when a new Firefox version is released or a user tries to load Hypothesis into a new PDF.js version.

**Comment by judell** [comment]
> We could potentially create automated tests

+1 

I suspect that headless Chrome + https://github.com/GoogleChrome/puppeteer can make that testing both easier and more reliable than the last time around when we used Selenium.

**Comment by robertknight** [comment]
This issue has been fixed in our master branch, but we'll leave deployment until first thing next week, just in case there is a problem.
