### ISSUE TITLE
Update readthedocs GitHub integration for `h`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#921]
Our `readthedocs` integration (which builds our documentation at https://h.readthedocs.io) is flaky or possibly dead at present for the `h` repo. Current integration is via a service on GitHub. Services are deprecated and GH urges use of webhooks or GH apps instead.

I had to manually build the docs (at https://readthedocs.org) to get a recent doc change to build and show up.

**Comment by robertknight** [comment]
This has been done. I've changed the configuration for the client and h repos to use webhooks to trigger Read the Docs rebuilds instead of GitHub services as per https://docs.readthedocs.io/en/latest/webhooks.html
