### ISSUE TITLE
HoneyBadger filter endpoint

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#926]
The simple triage solution - endpoint returns True if there have ever been any annotations to a given document, else false. Since vast majority of requests to badge, this will keep unnecessary traffic from traversing the H stack. The client will need to be extended to query the badger endpoint first, and only query H if it returns "True". Additional optimization possible if sidebar follows this behavior, not submitting a query to H unless this endpoint returns True. 

Considerations:
Fail open. If error or if response takes more than 100ms just query H like we do today. It's possible that will unleash an unmanageable amount of traffic on H if honeybadger goes down, in which case the service would be slow until the H cluster has a chance to scale. 

This implementation will just be a bloom filter. Future implementations may want to use a document store to cache realtime count stats. 
The client

**Comment by ajpeddakotla** [comment]
@dmfine is this a 1st step to the work we outlined in Brighton for the badge endpoint?

**Comment by robertknight** [comment]
I believe this has been superseded, at least for near-term work, but three other issues that came out of a discussion yesterday. See https://github.com/hypothesis/product-backlog/issues/953#issuecomment-465223390. If so we should either close it, or at least remove it from the current sprint for the time being.

Please let me know if I've got this wrong @dmfine.
