### ISSUE TITLE
Spike: Research LMS entry points to apps

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#933]
Part of #932 

As a pre-requisite to designing the UX and flow of the student and teacher LMS activity views, we need to collect information about potential "entry points" into applications across LMSes. Are we constrained to working within an application launch or are there other points of entry for students, teachers?

**Comment by klemay** [comment]
Done! See: https://docs.google.com/presentation/d/1QYM7InlOE-ZDOhK5Mvr1TfM3RTCqLP1dK1wy-eP9zB0/edit (requires Hypothesis GSuite login)
