### ISSUE TITLE
Community Groups: Implement updated Featured/My groups UI in client

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#938]
Part of #865 
Depends on #937 
Depends on #939

Once we're able to [retrieve and filter the correct set of groups behind a feature flag](https://github.com/hypothesis/product-backlog/issues/937), we need to render those groups in the groups selector.

This is going to require teasing apart https://github.com/hypothesis/client/pull/830 to glean markup and behavior logic.

Note: This does not yet include the addition of the "Currently Viewing" (by URL) group; that'll come subsequently.

**Comment by ajpeddakotla** [comment]
After talking to @hmstepanek there are some lingering questions around what to do for three specific items: 

1. Where to put the "view groups activity" 
2. What to do with leave groups
3. What to show users in a logged out state. 

For the first 2, there are three options. Out of these I think option#1 is the best - it works on both mobile/other devices, it gives us more room to put additional group functionality in if needed, and requires only one more click from a user to access the menu. 

Option#1 - Implement a drop down style menu that would show users additional groups capabilities (shown in very crude drawing below)
![20190225_124745](https://user-images.githubusercontent.com/7463523/53361323-1dd6ab80-38fd-11e9-9cd0-0c8941a8139b.jpg)

Option#2 - Implement icons on right hand side of group name that users can click to go to group activity page
![20190225_124750](https://user-images.githubusercontent.com/7463523/53361333-262ee680-38fd-11e9-8a7d-1e0e7688935f.jpg)

Option#3 - leave as is. We already know users don't like where groups activity page link is, so we should work to change it. 


For point#3 - Hannah's already implemented this in her PR which I think is sufficient and follows current flow of when a user is logged out. 
<img width="679" alt="screen shot 2019-02-25 at 1 00 01 pm" src="https://user-images.githubusercontent.com/7463523/53361408-4b235980-38fd-11e9-819a-91ee252bb401.png">

**Comment by robertknight** [comment]
@hmstepanek - Where does the "Public" group show up for logged-out users if there are no featured groups? I noticed it wasn't visible in the WIP PR in the menu.

**Comment by hmstepanek** [comment]
I'd expect Public to show up in the My Groups list. In this screen capture I wouldn't expect it to show up cause this page has an Open Group so the Public group is filtered out in that case. That being said, the template logic was wrong in my PR and I've updated it so that when the user is logged out it still loops through the groups list.
![image](https://user-images.githubusercontent.com/30059933/53370287-34333600-3902-11e9-80d3-55588fc86948.png)
I'm not sure I quite like the look of this tho. It's probably worth having a conversation about this too. If there is a group in the My Groups should we still show this message or maybe we should just re-word the message?

**Comment by hmstepanek** [comment]
This also might be a good time to revisit whether the Public group should be part of My Groups cause it would eliminate the complexity above.

**Comment by ajpeddakotla** [comment]
I think: 
1. Public should be a part of My Groups - cause that will follow the user around wherever they go. 
and 
2. Users that are logged out will see the Public group, and whatever scoped world-readable groups are available to them (which is the current flow). If there aren't featured groups available to users, they'll still see the public group. I don't think they need to see a message.

**Comment by hmstepanek** [comment]
> 2\. Users that are logged out will see the Public group, and whatever scoped world-readable groups are available to them (which is the current flow). If there aren't featured groups available to users, they'll still see the public group.

The pre-existing logic is setup to *not* show the Public group if there are other scoped world-readable groups. I assume this was to prevent people from annotating in the Public group on pages that had a scoped group. I just want to clarify-it sounds like we want to change this behavior to always show the public group under My Groups regardless of what other groups there are-is that correct? I think it makes sense to make this switch since the featured group will still show up and be first in the list so it's harder to confuse the two.

**Comment by lyzadanger** [comment]
Had an in-depth discussion with @hmstepanek this morning. I’d like to propose that the current problem we’re solving, _immediately_, is defining what set of groups are presented to the user and how those groups are organized in the group-select menu. Once we have that sorted, we’ll circle back and address how the _actions_ (e.g. view activity, leave group) can be represented. Breaking it down in this way will help prevent this from becoming too monolithic in scale in one step. To put folks at ease, _all of these things will be addressed_ before this is launched to the public, we just need to break it down a little as we implement here, especially without a dedicated designer/UX expert on staff.

It’s important that we consider all possible states of user and context vis-a-vis groups in the client group-select logically. Some of this was done in earlier UX work, but some states were not accounted for, most specifically certain states for users who are not logged in.

To wit, I spent some time today working on sketches for group-selector states representing non-logged in users and discussed same with Hannah.

The general tenets are:

1. If there is no action possible in the group-select menu, do not render as a menu; show the applied group only. This case applies when there is only one possible group in the given context and we’ve got an anonymous user. This is consistent to what we’re already doing in the client today. There’s no purpose in rendering a menu as there isn’t anything to do inside of it.
2. The “My Groups” notion does not apply semantically/metaphorically to anonymous users. This sub-heading does not get rendered in any of the currently-defined states for anonymous users.
3. The “Public” group is hidden if there is one or more in-scope open or restricted group in the current context (this is current behavior)
4. The notion of “Currently Viewing” is being nailed down here…happy to take input on state 6 below, especially.

I’ve identified seven (7) states pertaining to groups as concerns anonymous users and have created low-res sketches of these. _Remember_: this exercise is concerned with which groups show up, and where, but does not include other actions that can be taken on those groups, yet.

### States (Sketches Explained)

1. Public group is the only available group in the current context: Do what we do now; don’t render a drop-down.
2. Context has exactly one open/restricted group associated with it: Do what we do now; don’t render a drop-down (Public group is hidden in these contexts, currently).
3. Context has multiple open/restricted groups: Render a drop-down. Applicable open/restricted groups are listed under FEATURED GROUPS. Again, currently logic hides Public group in these cases.
4. User is following a direct link to an annotation in the Public group and there are no other applicable groups in the context: Same as State 1 (do not render drop-down)
5. User is following a direct link to an annotation in an in-scope restricted or open group and there are no other applicable groups (Public is hidden): Same as State 2 (no drop-down)
6. User is following a direct link to an annotation in an in-scope restricted or open group and there are other restricted or open groups that apply: Same as State 3, with the annotation’s group pre-selected. Note: It could be argued that the relevant group should be listed under CURRENTLY VIEWING. I went with FEATURED GROUPS because the group in question would normally be visible here, even if the user were not following a link…but I’m kinda starting to sway back toward CURRENTLY VIEWING…
7. Direct link to annotation in Public group when there are other open or restricted groups available (Public group would not usually be visible in this context): Public group, as the currently-focused group, goes under CURRENTLY VIEWING; other groups remain under FEATURED GROUPS

![image](https://user-images.githubusercontent.com/439947/53440104-c3f3e580-39d1-11e9-8a90-775eb6a48856.png)

![image](https://user-images.githubusercontent.com/439947/53440110-c9e9c680-39d1-11e9-95ca-1e670a58e807.png)

Next step...making sure all logged-in states are accounted for...

**Comment by seanh** [comment]
@lyzadanger One thing I'm wondering about your sketches, what would non-logged-in state 7 (when there is the public group and two featured groups) look like if the public group was _not_ the currently selected group? Presumably _Public_ would not belong under _Currently Viewing_ in that case. So does it move under _Featured Groups_?

**Comment by hmstepanek** [comment]
@seanh I don't think that case exists cause when you are logged out you won't see the public group when there are other groups unless you specifically request to see it.

**Comment by robertknight** [comment]
The first iteration of this is done. I'm currently working on re-introducing groups actions (leaving a group, going to the activity page) to the menu in a way that avoids the UX problems of the current one.
