### ISSUE TITLE
Engineer should review exposure of metabase queries to external parties

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#942]
There's been some discussion of exposing some views into Metabase data for outside users. As I understand it, Metabase has support for this in a way that my prevent sensitive data from being viewed, but we should have a dev look at what this entails to make sure we are not inappropriately sharing any sensitive data.

**Comment by dmfine** [comment]
To date, there is only one question shared, with eLife, but the goal is to develop a standard dashboard to share with each partner. We will not share without review. You can always see everything that’s sharable in here: 
https://metabase.hypothes.is/admin/settings/public_sharing

**Comment by lyzadanger** [comment]
Thanks! Appreciate the auditing.
