### ISSUE TITLE
Possible ad code conflict with LA Times

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#944]
This was first [reported](https://www.latimes.com/opinion/op-ed/la-oe-goldberg-trigger-warnings-20140520-column.html) by an instructor using our LMS app in Blackboard. When launching an assignment created using [this LA times article](https://www.latimes.com/opinion/op-ed/la-oe-goldberg-trigger-warnings-20140520-column.html), it takes a very long time to load (and sometimes will time out). Turns out, the conflict is not limited to the LMS environment.

The LA Times website has quite a lot of ads and scripts running, and even if you don't try to activate Hypothesis the browser console will throw multiple errors:

<img width="1645" alt="screen shot 2019-01-30 at 3 00 07 pm" src="https://user-images.githubusercontent.com/12087705/52008943-c2e99a00-249f-11e9-97f4-ea84b3e45cce.png">

## Using Via
Go to via.hypothes.is/https://www.latimes.com/opinion/op-ed/la-oe-goldberg-trigger-warnings-20140520-column.html

It will take a long time, but the article will load with Hypothesis enabled. It seems to take longer in Chrome than in Firefox or Safari

## If you're using the Chrome extension
Go to https://www.latimes.com/opinion/op-ed/la-oe-goldberg-trigger-warnings-20140520-column.html and activate the extension.

The Hypothesis sidebar won't load at all

## If you're using the Bookmarklet
In Firefox, it won't load at all. In Safari, it will take a long time but the sidebar will eventually load. 

Not proposing we do anything about this right away; just documenting this so we can track it.

**Comment by mkdir-washington-edu** [comment]
Possibly the same issue: https://github.com/hypothesis/support/issues/122

**Comment by klemay** [comment]
Closing in favor of https://github.com/hypothesis/support/issues/122
