### ISSUE TITLE
annotations can fail to anchor, yet not be reported as orphans

### ISSUE THREAD

**Issue by judell** [hypothesis/product-backlog#954]
Consider http://jonudell.net/h/Rhetoric_and_Crisis.pdf, where the client reports one orphan. (That one, by the way, is an example of the known problem that selections can't cross page boundaries.) 

When I ran the new anchoring test, https://github.com/judell/h_puppeteer/, it reported four orphans. I figured that was a problem with the test, but apparently it's a legit issue with the client.

There are two annotations on that document that target the phrase "networks are not human". They are:

A: 0x3BbHriEeaMYPclP4fEBA

```
				{ "type": "TextPositionSelector", "end": 23088, "start": 23066 },
				{
					"exact": "networks are not human",
					"prefix": "ns among elements. Furthermore, ",
					"type": "TextQuoteSelector",
					"suffix": "-or at least they are not merely"
				}
```

B: -afq4IDeEea20kO4RMsmFw

```
				{ "type": "TextPositionSelector", "end": 23088, "start": 23064 },
				{
					"exact": ", networks are not human",
					"prefix": "ions among elements. Furthermore",
					"type": "TextQuoteSelector",
					"suffix": "-or at least they are not merely"
				}
```

A anchors. B does not, but neither is it reported as an orphan. It's just sort of hanging around in limbo. If you click on the highlighted phrase "networks are not human" you'll only find A, if you search for the phrase, you'll find both, but of course you'd never think to do that. 

The other missing orphans:

- JEeXXoBZEeawhx-THRaiCA

- gEyOdoRxEea9wK8ixCQPow

- 4qkWwoAPEeadyud9XjPFMA

There is no difference between PDF.js 1 and 2 with respect to this observation

Another example: HfgcQrq1EeeHH1-Kxe_v7g in http://cdn.nmc.org/media/2017-nmc-horizon-report-he-EN.pdf. 

```
		"selector": [{
			"type": "TextPositionSelector",
			"end": 77986,
			"start": 77969
		}, {
			"exact": " free of charge. ",
			"prefix": "s into higher education courses,",
			"type": "TextQuoteSelector",
			"suffix": "Their blended program leverages "
		}],
	"text": "Fantastic... how long will this last?\n",
```

Search the document for "free of charge" and you will find two other annotations on highlights that contain the phrase. But you will not find HfgcQrq1EeeHH1-Kxe_v7g, unless you search the sidebar for "fantastic".

**Comment by judell** [comment]
Update: I've found more examples of this syndrome. So far, all are cases where the target of the annotation that goes missing, in the way described here, overlaps the targets of other annotations that do behave as expected.

**Comment by judell** [comment]
Here's a short screencast illustrating how this can look to users: http://jonudell.net/h/user-visible-manifestation-of-unreported-orphans.mp4.

I finally understand why these unreported orphans sometimes appear to be missing and sometimes appear to be not a problem at all. In the screencast, the unreported orphans just happen to show up in the sidebar in a way that makes you think they're anchored even though they're not. They are not click accessible from the document, but you don't notice that. In other cases, though, unreported orphans will be offscreen and so you won't be able to get to them by clicking on the highlight they should have anchored to, you can only get to them by scrolling or searching the sidebar, so they are effectively lost to you in a heavily-annotated doc.

These unreported orphans all seem to overlap annotations that do anchor properly, so I suspect and hope it'll be a straightforward fix.

I am pretty sure that this has been going on forever. I know I've seen the behavior in the screencast for as long as I can remember, and never did get to the bottom of it, but I think we may have now.

**Comment by robertknight** [comment]
> I am pretty sure that this has been going on forever. I know I've seen the behavior in the screencast for as long as I can remember, and never did get to the bottom of it, but I think we may have now.

Highlighting is currently implemented (and has been since forever) by wrapping DOM nodes with spans that apply highlighting and are used to detect clicks. A fundamental issue with this approach is that the process of creating a highlight modifies the DOM and that can end up interfering with the process of creating highlights for other, overlapping annotations.

Unless there is something new that I've missed here, this bug has existed forever. There was one earlier attempt at fixing it. See discussion in https://github.com/hypothesis/h/issues/3278 and https://github.com/hypothesis/h/pull/3313.

We can take another look at this, it will need to be scheduled accordingly and I expect it will take a few days of dev time at least to explore options.

**Comment by judell** [comment]
Thanks @robertknight.

**Comment by robertknight** [comment]
I'm taking this card back off the current sprint. If someone wishes to discuss it sooner than the next sprint planning, please ping me.

**Comment by judell** [comment]
Okay. I had forgotten that for Science in the Classroom the fix was evidently to sort annotations by largest to smallest target. That's been seemingly working for them for several years now, at least I haven't heard any complaints. Of course that isn't the Hypothesis client doing the anchoring, it's a much simpler piece of code which does anchoring in a completely serial fashion. That said, the absence of complaints is not evidence that everything is correct. Silent failures are easy to miss, which is why this has gone on so long.

What's new here, at least to me, with respect to the Hypothesis client, is that these anchoring failures are not reported as orphans by the client. But we do now have a way to measure how frequently that occurs, and we can find annotations with overlapping targets to focus the tests. So I will now gather data, from both the PDF and HTML domains, so we can better characterize the severity of the problem.

**Comment by judell** [comment]
An example from the HTML domain: at https://www.nytimes.com/2018/12/08/opinion/college-gpa-career-success.html there are 8 annotations that anchor to the last paragraph, but 3 that orphan. Unlike the PDF examples I've found, where the orphans are not reported as such by the client, these 3 are reported as orphans.

However the test also finds a fourth and unreported orphan: https://jsoneditoronline.org/?url=https://hypothes.is/api/annotations/vMUgMBPUEemCRFtt9j4ayg

**Comment by dwhly** [comment]
This is an excellent page to test this issue on: https://hybridpedagogy.org/decoding-digital-pedagogy-pt-1-beyond-the-lms/

**Comment by ajpeddakotla** [comment]
#1079 (this is a test)

**Comment by robertknight** [comment]
> There are two annotations on that document that target the phrase "networks are not human". They are:

The issue doesn't occur at present with these two annotations any more:

<img width="600" alt="networks-not-human" src="https://user-images.githubusercontent.com/2458/97565752-2048ad00-19de-11eb-827a-6d3d1b8028ef.png">

Note the stronger highlight for the phrase "networks are not human". If you click on either of them, you'll see both annotations in the sidebar. I tested in Safari 14 and Chrome 88. There is currently one orphan in the Public group for the document http://jonudell.net/h/Rhetoric_and_Crisis.pdf. The issue for that annotation is that it spans multiple pages.

> Another example: HfgcQrq1EeeHH1-Kxe_v7g in http://cdn.nmc.org/media/2017-nmc-horizon-report-he-EN.pdf.

This URL no longer exists. I did find a copy via Google at https://www.sconul.ac.uk/sites/default/files/documents/2017-nmc-horizon-report-he-EN.pdf though by searching for the quoted phrase "Their blended program leverages".

The annotation HfgcQrq1EeeHH1-Kxe_v7g did anchor in the document, but it anchored to the wrong text:

<img width="890" alt="wrong-text-anchor" src="https://user-images.githubusercontent.com/2458/97572888-ddd49f80-19e0-11eb-8ff8-62f71eecbfce.png">

The blue highlight in the page is the anchored part of the document associated with the annotation in the bottom of the sidebar in this screenshot.

**Comment by robertknight** [comment]
> An example from the HTML domain: at https://www.nytimes.com/2018/12/08/opinion/college-gpa-career-success.html there are 8 annotations that anchor to the last paragraph, but 3 that orphan. 

This article is unfortunately now behind a subscription-wall.

> This is an excellent page to test this issue on: https://hybridpedagogy.org/decoding-digital-pedagogy-pt-1-beyond-the-lms/

This page has a spectacular number of orphans, but the same that I looked at appeared valid - the quoted text did not appear on the page.

<img width="517" alt="lots-of-orphans" src="https://user-images.githubusercontent.com/2458/97573541-d792f300-19e1-11eb-88e9-35ab355e5b2b.png">

To be a useful bug report we need an example of a document where this currently happens.

**Comment by robertknight** [comment]
@judell - Do you want to try re-running your tool and see if you can find an example of this problem that occurs with the current client in a document that is publicly accessible?

My suspicion of what may have happened here historically is that the result of wrapping the anchored text of one annotation with highlights may have invalidated the anchored ranges associated with another annotation. I have no reason to believe that can't still occur, but I know that we did change some of the related code as part of recent cleanup in ways that may have made it less likely to occur.

**Comment by judell** [comment]
> The issue doesn't occur at present with these two annotations any more.

Indeed it does not. That's encouraging!

I could rerun the tool but it's slow, clumsy, and only covers a small
universe of documents. It would sure be nice to have telemetry that can
capture a much wider and clearer view of anchoring outcomes.
