### ISSUE TITLE
Handling long claimant_uri's

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#955]
https://sentry.io/hypothesis/h/issues/864120830/?referrer=slack

When annotating `https://watermark.silverchair.com/document?token=crazy long token` the claimant_uri is too large because of `crazy long token`. There are two issues here: What to do about these particular urls perhaps drop the token but also what to do with other claimant_uri's that are too long to fit in the db.

**Comment by robertknight** [comment]
A limit on the length of document URIs is now imposed by h - https://github.com/hypothesis/h/pull/8595. There is still more work to do to handle this gracefully in the client.
