### ISSUE TITLE
lti launches takes a long time

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#958]
The response time is a direct result of the api calls to h. In one case it took >2s to respond from add_member and >1s to respond to groups.update. Interestingly these endpoints in h show that they had a max response time of only .4s and .6s respectively. This indicates that the bulk of the request time was spent in network/routing time (outside of h and lms).

![image](https://user-images.githubusercontent.com/30059933/52806642-6315f600-303e-11e9-833f-a29158bc47af.png)
![image](https://user-images.githubusercontent.com/30059933/52806653-68734080-303e-11e9-90d0-cc11502baaf3.png)
![image](https://user-images.githubusercontent.com/30059933/52810066-9492bf80-3046-11e9-9f09-86bcac69415f.png)
![image](https://user-images.githubusercontent.com/30059933/52810189-d7ed2e00-3046-11e9-88d6-f72ec90234b2.png)

**Comment by robertknight** [comment]
Since this issue was filed a collection of APIs for bulk operations were introduced to amortize the overhead of API calls from the lms to h.
