### ISSUE TITLE
lms reports page takes min 4.5s to complete

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#959]
The lms reports page is a growing table and the db query for it takes at min >4s to complete. This means that gunicorn work is occupied for 4.5s and unable to full fill other requests. If there are a lot of these at peak traffic this can impact our customers. 

This table and view need to be removed and we need to turn them into a metabase query. 
![image](https://user-images.githubusercontent.com/30059933/52807387-2ba84900-3040-11e9-8977-dfcd961438b3.png)

**Comment by robertknight** [comment]
The lms reports have been replaced/rewritten several times since this issue was filed.
