### ISSUE TITLE
Move all of our static server and QA and production app server logs to a Papertrail

### ISSUE THREAD

**Issue by seanh** [hypothesis/product-backlog#968]
## See Also

* [Improve log file storage and access for our apps](https://github.com/hypothesis/product-backlog/issues/847), the issue from when we moved from Elastic Beanstalk Logs to CloudWatch Logs (our current solution). This move didn't solve the problem. CloudWatch Logs is too unusable and has too poor a feature set to be useful for most developers to do their jobs effectively.

* [Slack thread](https://hypothes-is.slack.com/archives/C4K6M7P5E/p1550662725222300) that prompted me to create this issue

## Problem

1. Static server and app server logs are not all in one place.

   Our static servers currently send their logs to <https://papertrailapp.com/>. Our app server logs used to go to Papertrail once upon a time but this stopped a long time ago (possibly when we moved the app servers to Elastic Beanstalk) and app server logs are now available in both Elastic Beanstalk logs and AWS CloudWatch Logs but not in Papertrail.

   This means that it's difficult to browse, search or watch logs from our "whole system" (static servers and app servers) at once because they live in two different systems with completely different UI's and feature sets.

2. Even though all our app server logs are in one place in CloudWatch Logs, it doesn't allow you to view all the logs from all app servers at once. You can't even view all the logs from a single app at once. The best you can do is view all logs from one "log group" of a single app. "Log groups" are groupings of logs along technical lines (application stdout, nginx access log, etc.) You don't want to view one log group at a time. When observing and debugging you want the full context of viewing everything at once, and _then_ narrowing down as you focus in on the issue. Otherwise you will miss things, and the logs will simply not be effective for debugging or observing.

   Also having to browse to one particular log group for one particular app doesn't give developers a quick way to observe our system and see what's going on right now by "going to the logs". There is no "the logs". There are hundreds of different log groups and you can only laboriously browse to and view one of them at a time.

3. We don't have any place to send events that aren't bugs (so shouldn't be sent to Sentry) but that we nonetheless want to keep track of. We could send them to CloudWatch Logs, but no one will ever see them there, because it's so terrible and difficult to access, search, or alert from that no one ever uses it.

   For example when adding new validation code to the LMS app, we don't want to send validation errors to Sentry because they aren't crashes. But we do want to send validation errors somewhere, because if our validation code is sending back validation errors to users all the time that would be a problem and we'd need to know about it.

   Another example: when rewriting the OAuth support for the LMS app, we want to log when a user authorizes successfully and when the user or Canvas refuses authorization. Again, these aren't bugs, and don't belong in Sentry. But if the new system is causing too many of our users to fail to get through authorization then we would want to know that.

   A logging system that's easy to access and has good saved searches and alerts features would be a good fit.

4. Our app server logs are not easy for developers to observe or search through.

   The CloudWatch Logs UI and feature set is terrible. Let's say that a developer notices that Via is currently really slow. Looking at Via's traffic logs to ask whether someone is streaming a lot of YouTube or something would be the first and most obvious thing to do and could lead to a quick resolution (blocking YouTube). But this isn't what developers will do, at least not right away, because accessing this info from the logs is a PITA. Much more likely developers will ignore the problem for some time and hope it'll go away or someone else will deal with it. Accessing Via's CloudWatch logs involves:

   1. Logging in to AWS.

      You always have to re-login to AWS. It auto logs you out every day because it's very security conscious because the AWS dashboard has all sorts of powerful functionality beyond log reading (such as taking down our entire system etc).AWS login is slow and a pain in the butt, requiring of Account ID / Alias, an IAM User Name, a password, and a 2FA code every time, and the login page doesn't work with password managers.

   2. Now use the world's biggest and most complicated dashboard ever to navigate to the CloudWatch sub-dashboard, and then to the logs sub-sub-dashboard within that.

   3. You'll now be presented with a massive list of "Log Groups", only partially shown in the screenshot below, and you have to known which log group is gonna contain the logs that you need. 

      ![screenshot from 2019-02-21 10-40-30](https://user-images.githubusercontent.com/22498/53163105-48ef9100-35c5-11e9-8f54-5777d13f23ba.png)

   4. Logs from multiple log groups, or from all of them, may be relevant to what you're trying to debug, but you can only view one at a time. You don't want to make this choice of which log group to view now, but you have to.

   5. Via's logs appear to be completely missing from CloudWatch Logs (?!!) so you can't use them to debug Via issues at all. You will have to go to Elastic Beanstalk Logs, which is even worse. So let's pretend we were trying to debug an LMS app issue instead...

   6. Pick the `/aws/elasticbeanstalk/lms-prod/var/log/eb-docker/containers/eb-current-app/stdouterr.log` log group (we'll say for the sake of argument that this is the log group you need and that somehow you know that)

   7. Clicking on this log group, or any log group, now shows you a second massive list of all the app servers (again shown only partially below), current and past, to choose from. You're supposed to choose the specific app server you want to see the logs of.

      ![screenshot from 2019-02-21 10-44-43](https://user-images.githubusercontent.com/22498/53163371-d29f5e80-35c5-11e9-8142-c77b4b4ae7ef.png)

   8. You almost never want to see the logs from just one app server. You want to see them all at once. There's no obvious way to see them all at once in CloudWatch Logs. Fortunately there _is_ a hidden way though: click the <samp>Search Log Group</samp> button and you'll see all of the log messages (that're within this log group, anyway) from all app servers (belonging to this one app, anyway). Finally, we now actually see some log messages! It's only a subset of the log messages that're likely relevant, but that's the best CloudWatch can do.

   9. Log messages are presented _oldest_ messages at the top, newest ones at the bottom, but the newest ones aren't loaded at first. So the newest messages, which are almost always what you want to see, are still not on screen. To get to them you have to scroll to the bottom of the page, wait for it to load more newer messages, scroll again, wait for it to load again, scroll, wait, scroll, wait ... This is a horribly broken and upside down implementation of the  "infinite scroll" design pattern, in which the most important stuff that you want to see first is at the bottom not the top and you have to do a really slow and laborious amount of scrolling to get to it.

   10. From here, functionality for searching and filtering, saved searches, bookmarks, alerts, etc etc are all very limited.

## Solution

Papertrail provides a really nice and usable UI for logs that is quick to access and has a great feature set. Quick and easy login; The front page of the app is a searchable real-time tail of _all_ our logs in one place; Saved searches and bookmarks; Sane timezone support; Keyboard shortcuts; Etc etc

We already have a Papertrail account and already send our static server logs to Papertrail.

Let's just send our app server logs to Papertrail as well. This will be a massive improvement to our developer UX when dealing with production issues. It'll massively improve observability of our apps. Encourage the team to observe our apps more, and be more proactive about debugging production issues. When deploying new features, we'll be more likely to add logging messages to them and then observe their behaviour in production. More issues will be spotted before they become big problems. For our users system performance and incident response times will improve.

Other log management apps, including Sumo and Loggly, have been suggested and those can be investigated too, if one of them is better than Papertrail we should go with it instead, but I'll stress that **simplicity** and **developer friendliness** is of highest importance here: We don't need another New Relic, Grafana or Google Analytics (another massive confusing dashboard that no one uses and no one understands) (except Hannah who actually does use New Relic a lot), we need something really simple and easy to use that also has powerful filtering and saved searches and alerting etc.

**Comment by dmfine** [comment]
It looks like the easiest way will be to have a lambda job forward cloudwatch logs to PT
https://github.com/apiaryio/cloudwatch-to-papertrail

The alternative would be to change H logging config to add a second handler (which, we probably want fewer references to 3rd party services in the codebase)

Or, we could make H log to file and use a tool papertrail provides to tail and forward that file. That should be okay as long as we rotate the log somehow

More Docs for reference:
https://help.papertrailapp.com/kb/hosting-services/aws-elastic-beanstalk/
https://help.papertrailapp.com/kb/hosting-services/amazon-cloudwatch/

**Comment by dmfine** [comment]
Looks like the best way forward is adding a syslog handler to the log config of each application. Bouncer does not have a config file so it will be a separate challenge. https://help.papertrailapp.com/kb/configuration/configuring-centralized-logging-from-python-apps/#send-events-using-pythons-sysloghandler
