### ISSUE TITLE
Various Metabase Issues: Pulses don't appear, timeouts, crashes

### ISSUE THREAD

**Issue by dmfine** [hypothesis/product-backlog#971]
Issue for tracking all Metabase issues currently affecting us.

1. Pulses sometimes don't appear
2. Metabase has needed rebooting
3. Some long running queries timeout

**Comment by dmfine** [comment]
1. Pulses
Have been discussing with metabase developers. It could be related to issues #2 or #3, for example if the queries for that pulse timeout on a particular day. Troubleshooting is hindered by the fact that metabase doesn't log activity related to pulses. I'm told that feature will be included in the next minor release however. Since upgrading the instance RAM to address issue #2 the pulses have been consistent, but I'm not confident they will continue to be. One thing to try next could be splitting pulses with multiple questions into individual ones, so that we still get most stats in the case that one fails. Hopefully that won't be necessary

**Comment by dmfine** [comment]
2. Metabase rebooting
On Thursday last metabase was unresponsive. I was able to ssh, but the console was running so slowly that it was barely usable. I did manage to run commands to confirm it was out of memory. It ran on a t2.micro instance, which is maybe not enough for a dockerized java app. I upgraded to a t2.small with twice the RAM for $8/mo extra. Since then it has not needed rebooting. I'm hopeful.

**Comment by dmfine** [comment]
3. Long running timeouts
I observed certain queries consistently timing out at precisely 60 seconds. Metabase developers say that it no longer has hard timeouts and suggested some places for me to look. I changed some RDS settings to no avail. Then they suggested looking at the ELB, and sure enough there was a 60s timeout set on it. More testing is needed, but that's certainly one place where it would have been timing out.

**Comment by dmfine** [comment]
Still getting Java OOM. Increasing to t3.medium with 4gb RAM. The query no longer crashes...

**Comment by hmstepanek** [comment]
https://hypothes-is.slack.com/archives/C074BUPEG/p1552520109000100

**Comment by ajpeddakotla** [comment]
closing this as issues have been resolved
