### ISSUE TITLE
Exploring moving groups heading and activity page link 

### ISSUE THREAD

**Issue by ajpeddakotla** [hypothesis/product-backlog#973]
**** This is exploratory work that will live behind a feature flag ****** 

Exploring moving groups heading and activity page link 

•  Move current group title to annotation set header
•  Change group selector control to a descriptive button
•  “Go to group” functionality = link on group title
•   Remove "leave group" button
<img width="252" alt="Screen Shot 2019-03-13 at 2 21 11 PM" src="https://user-images.githubusercontent.com/7463523/54310101-96956300-459f-11e9-98ec-40061b14b7ba.png">
<img width="255" alt="Screen Shot 2019-03-13 at 2 22 12 PM" src="https://user-images.githubusercontent.com/7463523/54310108-99905380-459f-11e9-8e8f-5ca41833d01d.png">

**Comment by robertknight** [comment]
After some discussion, we're planning to explore an alternate design where the actions are presented in the groups menu, but in a different way: https://github.com/hypothesis/product-backlog/issues/974

**Comment by lyzadanger** [comment]
Closing, not out of disregard, but because we are implementing the functionality referenced in this issue in #974.
