### ISSUE TITLE
Community Groups: Re-introduce group actions to UI

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#974]
Part of https://github.com/hypothesis/product-backlog/issues/848
Part of https://github.com/hypothesis/product-backlog/issues/865

Implement a new design for the groups menu which re-introduces actions for going to a group's activity page, copying a link for the group and leaving the group.

We plan to use the same dropdown menu style both across the client and also in new LMS activity views. The task for implementing the base menu component is https://github.com/hypothesis/product-backlog/issues/1010, which this issue depends on. There are separate issues for converting existing menus in the client to the new style.

**Remaining subtasks**

- [x] Review design details (font sizes, spacing etc.)
- [x] Turn on the feature flag for everyone
- [x] Create a separate follow-up issue for the "Copy invite link" button

**Mocks**

![7f28a897-049e-481b-b91b-5dffcad63b63](https://user-images.githubusercontent.com/2458/57143378-a6b70b00-6db6-11e9-8267-647137ca39c8.png)

Recent design discussion: https://hypothes-is.slack.com/archives/C07NXBDNW/p1556182586025400 and https://hypothes-is.slack.com/archives/C07NXBDNW/p1556641888063100

**Comment by robertknight** [comment]
This is now done, except for:

- Design details such as font sizing, spacing etc. should be reviewed
- The feature flag to turn on the menus needs to be enabled for everyone
- The "Copy invite link" item is not currently present in the menu. This is a new feature so I think we should pull it out into a separate task

**Comment by robertknight** [comment]
This is shipped.
