### ISSUE TITLE
Spike: Investigate what's causing 502 errors

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#977]
This is edited from a broader issue description. To figure out what we want to do about application 502 errors, we first want to do some digging: in what situations do they arise in the first place? This is a spike to figure out just that, and then we can subsequently decide what to do (logging, fixing, metrics...etc.).

**Comment by seanh** [comment]
@lyzadanger Which app is having 502 errors? Shall we move this to that app's repo? Or just close this? Certainly doesn't seem like it should have the Operations label

**Comment by lyzadanger** [comment]
Boy, this is a terribly-written issue. Sorry. I have no recollection of even what I was thinking. I'm closing this. If we see 502 errors from something, somewhere, sometime, we can open a reasonably-written issue about it.
