### ISSUE TITLE
Track down current SLA's

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#978]
Track down our current SLA's. This is step one in a larger goal of connecting our SLA's to our monitoring infrastructure.

**Comment by hmstepanek** [comment]
Current SLA's: https://docs.google.com/document/d/1OFKXMq5n86hhd4gr6tzU9ezyFdVMhXi5NenkUtdHXjE/edit

**Comment by hmstepanek** [comment]
![image](https://user-images.githubusercontent.com/30059933/54933715-6b354100-4eda-11e9-992f-353e64a4da39.png)

![image](https://user-images.githubusercontent.com/30059933/54933646-4b9e1880-4eda-11e9-9664-0514845f2ff8.png)

![image](https://user-images.githubusercontent.com/30059933/54933603-30cba400-4eda-11e9-9005-4c30288793fa.png)

**Comment by hmstepanek** [comment]
https://stackoverflow.com/c/hypothesis/questions/177/178#178

**Comment by lyzadanger** [comment]
Thanks!
