### ISSUE TITLE
Provide more information on signup confirmation page

### ISSUE THREAD

**Issue by klemay** [hypothesis/product-backlog#984]
Our signup flow has changed since I opened https://github.com/hypothesis/product-backlog/issues/654, so I'm closing that in favor of this issue.

Now, when someone creates an account, they remain at https://hypothes.is/signup, and they see this:

<img width="529" alt="Screen Shot 2019-03-28 at 10 40 02 AM" src="https://user-images.githubusercontent.com/12087705/55166797-27df0a80-5146-11e9-95a1-9a3d41a05da9.png">
 
The email doesn't send immediately (it took ~5 minutes when I tried it with a new account just now), so @dwhly has suggested adding more info to this page:

- How long it will take for the user to receive the email
- What to do if they don't receive the email
- A way to contact support from the page

_Note to devs: this is something I could pick up in a sprint, as it's pretty simple_

**Comment by dwhly** [comment]
@klemay the fact that an email takes 5 minutes is a real problem.  Can we create an issue for this / a spike to investigate our average turnaround times for activation emails & standard deviation?  What is the longest time it takes, what is the shortest time when working well, etc. If mailchimp/mandrill is not reliable then perhaps we need to investigate options. We should prioritize that spike. 

Also, looks like for some/many folks it's not getting through at all.  We should also get stats on how many accounts are created that are never activated as a percentage of overall total.  Would be great if that stat could be part of our monthly customer support snapshot.

**Comment by klemay** [comment]
@dwhly I agree. Created https://github.com/hypothesis/product-backlog/issues/988 (now in the To Review column of Product backlog) and https://github.com/hypothesis/support/issues/62 (will be picked up as I prepare the March support summary in a few days).

**Comment by lyzadanger** [comment]
Fixed by https://github.com/hypothesis/h/pull/5628
