### ISSUE TITLE
Handle legal/illegal linking to a group

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#990]
Possible legal/illegal states of requesting a group:

Restricted Groups:
1. The group is a restricted group, the user is not a member, the group is not scoped to the page, the group scope is enforced. The api request gives us back the group and the client would have to be responsible for filtering out the group since it should not be visible to the user.

1. The group is a restricted group, the user is not a member, the group is not scoped to the page, the group scope is not enforced. The group should be visible to the user.

1. The group is a restricted group, the user is not a member, the group is scoped to the page, the group scope is enforced or not enforced. The group should be visible to the user.

1. The group is a restricted group, the user is a member, the group is scoped or out of scope, the group scope is enforced or not enforced. The group should be visible to the user.

Private groups:
1. The group is a private group, the user is not a member. The api returns a 404 in this case and the group should not be visible to the user. 

1. The group is a private group, the user is a member. The group should be visible to the user.

Open Groups:
1. The group is an open group, the group is not scoped to the page, the group scope is enforced. The api request gives us back the group and the client would have to be responsible for filtering out the group since it should not be visible to the user. 

1. The group is an open group, the group is not scoped to the page, the group scope is not enforced. The group should be visible to the user.

1. The group is an open group, the group is scoped to the page, the group scope is enforced or unenforced. The group should be visible to the user.
Partial fix for https://github.com/hypothesis/product-backlog/issues/975.

**Comment by robertknight** [comment]
A related issue I ran into this morning is simply what happens if the group doesn't exist.

**Comment by robertknight** [comment]
> The group is an open group, the group is not scoped to the page, the group scope is enforced. The api request gives us back the group and the client would have to be responsible for filtering out the group since it should not be visible to the user.

If the group is not scoped to the current page, then the API won't return it, since the user won't be a member.

Having said that, none of the code that is currently written in the groups service cares about whether the group is "restricted" or "open", so it should work if we do support membership of open groups in future, for example to support giving people additional roles within that group.

**Comment by hmstepanek** [comment]
Completed by https://github.com/hypothesis/client/pull/1064.
