### ISSUE TITLE
Document `/go?group={id}` query param in bouncer

### ISSUE THREAD

**Issue by hmstepanek** [hypothesis/product-backlog#991]
Add documentation for new fragment: #annotations/groups/GROUP_ID.
Partial fix for https://github.com/hypothesis/product-backlog/issues/975.

**Comment by robertknight** [comment]
Discussed on a call today. The #annotations fragment syntax is not considered a public API, but the bouncer URL syntax is. We should update any documentation for the bouncer URL syntax but don't need to document the fragment syntax as public API.
