### ISSUE TITLE
Spike: Investigate and Document issue with developer controller in `h`

### ISSUE THREAD

**Issue by lyzadanger** [hypothesis/product-backlog#996]
We're seeing reports of the developer controller (used by the "Developer" page of account settings) taking upwards of 20 seconds (!) to do its job.

We need to investigate and write up an incident report. If the root cause is straightforward, this task should also include fixing the problem.

**Comment by seanh** [comment]
Completed: https://docs.google.com/document/d/1CFPykb5U5_CZTri7g-KhDTn7Dy_SBe_KvDTXwhMFBrE/

One follow-up issue was opened: https://github.com/hypothesis/h/issues/5608
