### ISSUE TITLE
Make sure that new groups list menu is accessible

### ISSUE THREAD

**Issue by robertknight** [hypothesis/product-backlog#998]
As part of the community groups menu we are re-designing the groups menu in the client to separate groups into categories depending on why they are showing up and also fixing some long-standing UX issues.

I think this would be a good time to make sure we start on the right foot wrt. accessibility for new UI. Specifically, we need to make sure:

- Keyboard navigation works
- The menu is presented appropriately to assistive technologies

As the new groups menu is implemented with Preact, this may be a good time to set up https://github.com/evcohen/eslint-plugin-jsx-a11y to check for a11y issues on an ongoing basis.

- [x] Use appropriate semantic elements and/or add ARIA roles to menu toggle button and menu items
- [x] Implement keyboard navigation within menus
- [x] Resolve issue with space activating menu item but not closing menu
- [x] ~~Look into issue where VoiceOver reports that submenus contain more actions than they actually do (nice to do, but not essential)~~ (_This was deferred as we had more urgent work to do on the Speed Grader integration in the LMS_)

**Comment by robertknight** [comment]
The new menu is currently implemented behind a feature flag this morning. I have tested basic keyboard navigation and presentation in VoiceOver on macOS. I haven't tested other screen readers. I found two issues that I want to look into before closing this:

- [ ] There is a quirk where VoiceOver announces that collapsed submenus have three items in them, but otherwise its descriptions of menu items are accurate.
- [x] Basic keyboard navigation works, except that pressing Space to select a menu item does not close the menu, whereas clicking the menu item does.

**Comment by lyzadanger** [comment]
> There is a quirk where VoiceOver announces that collapsed submenus have three items in them, but otherwise its descriptions of menu items are accurate.

My gut opinion on this one: if the fix is relatively obvious and involves using, say, more semantic hints or otherwise making markup just...better...that seems fine to me. But if it requires cleverness and hackery, or isn't easy to figure out, my 2c would be to not pursue a remedy.

**Comment by ajpeddakotla** [comment]
@robertknight do we have an answer to @lyzadanger comment above? It seems like resolving this may time some time, and if that's the case, maybe we can de-prioritize this for now?

**Comment by robertknight** [comment]
I've deleted the remaining TODO for the moment, as a minor issue that we may revisit another time.
